### ISSUE TITLE
Return button brings up Privacy modal on page editor

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail#6814] opened 2021-02-16 10:47 UTC
### Issue Summary

On the page editor, if you are in a single line text field (e.g. title) and you press the Enter button on your keyboard, Wagtail brings up the page privacy modal. 

### Steps to Reproduce

1. Open any page
2. Go to the title field and press Enter button on your keyboard

I feel like this is confusing behaviour. I think the enter button here should do nothing.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: 2.12
* Browser version: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36

**Comment by zerolab** [comment] 2021-02-16 11:54
Thanks @phildexter , this is a duplicate of #6592

**Closed** 2021-02-16 11:58 UTC
Labels: type:Bug
