### ISSUE TITLE
Missing migration in release 6.0.0 and 6.0.1

### ISSUE THREAD

**Issue by ayurchenko-versa** [wagtail/wagtail#11690] opened 2024-02-23 13:33 UTC
### Issue Summary
There is one missing migration with name [0092_alter_collectionviewrestriction_password_and_more.py](https://github.com/wagtail/wagtail/blob/main/wagtail/migrations/0092_alter_collectionviewrestriction_password_and_more.py). It was added in #11572 but it is still not released.

### Steps to Reproduce

1. Install wagtail==6.0.0 or 6.0.1
2. run `python manage.py makemigrations --dry-run`

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details
N/A

### Working on this
Python/Django skills required

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment] 2024-02-23 13:46
Hi @ayurchenko-versa,
Thanks for the report - however, the PR #11546 that made this migration necessary is not part of Wagtail 6.0.x, as far as I can see?
The merge into main (for 6.1) happened here: https://github.com/wagtail/wagtail/commit/67f3af875c06062784ffd816af91f2ea2fe7a4ac#diff-39ff7e0e4a224c53e2ed244c6234b85654a1aa065ea36b039923058da07dfc8d

and the stable/6.0.x branch still has the old version of the labels: https://github.com/wagtail/wagtail/blob/stable/6.0.x/wagtail/models/view_restrictions.py#L20-L25

**Comment by gasman** [comment] 2024-02-23 13:51
Have also tried running `python manage.py makemigrations --dry-run` on a fresh wagtail==6.0.1 installation in a clean virtualenv - this reports no changes.

Closing as unable to replicate.

**Closed by gasman** 2024-02-23 13:51 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed

**Comment by ayurchenko-versa** [comment] 2024-02-23 14:43
@gasman thanks for your answer. However, I see that this migration file is still missing. If you go [here](https://github.com/wagtail/wagtail/tree/v6.0.1/wagtail/migrations) you can see it. Also, I did upgrade on my server to wagtail 6.0.1 and I still see this:
```
root@acf79e57f462:/app# poetry show --tree | grep wagtail
wagtail 6.0.1 A Django content management system.

root@acf79e57f462:/app# django-admin makemigrations --dry-run
2024-02-23 06:41:56-20-apps:21-select completed for session
2024-02-23 06:41:56-20-apps:25-select completed for User
Migrations for 'wagtailcore':
  /usr/local/lib/python3.12/site-packages/wagtail/migrations/0092_query_searchpromotion_querydailyhits.py
    - Create model Query
    - Create model SearchPromotion
    - Create model QueryDailyHits
```

**Comment by gasman** [comment] 2024-02-23 14:49
`0092_alter_collectionviewrestriction_password_and_more` is not part of Wagtail 6.0, because the corresponding model change is not in 6.0 either.

`0092_query_searchpromotion_querydailyhits` is a different issue, and that's caused by you having a reference to the models from `wagtail.contrib.searchpromotions` without that app being included in INSTALLED_APPS.

**Comment by ayurchenko-versa** [comment] 2024-02-23 16:17
It works. Thanks. But to be 100% correct it should be `wagtail.contrib.search_promotions'

**Comment by rikva** [comment] 2024-03-01 10:54
FYI, this affected me as well and I found the solution (adding `wagtail.contrib.search_promotions` to `INSTALLED_APPS`) by looking through the github issues.

Maybe a good idea to add this piece of information to the upgrading docs?

**Comment by lb-** [comment] 2024-03-01 12:15
We've had a few people encounter this same issue. 

We do actually reference the requirement for this module in the documentation where we have a code example for setting up a search page. 

https://docs.wagtail.org/en/latest/topics/search/searching.html#promoted-search-results

We could make it clearer though.

**Comment by gasman** [comment] 2024-03-01 12:55
Thanks for the suggestion @rikva! Have opened a PR with a proposed update to the 6.0 release notes: https://github.com/wagtail/wagtail/pull/11712
