### ISSUE TITLE
Error in Setting up the Wagtail codebase

### ISSUE THREAD

**Issue by gitkaarma** [wagtail/wagtail#8099] opened 2022-03-09 22:34 UTC
### Issue Summary

While setting up a local copy of the Wagtail git repository, running the command `$ pip install -e .[testing,docs] -U` generates the following error: - 
```
ERROR: Cannot install myst_parser and wagtail because these package versions have conflicting dependencies.

The conflict is caused by:
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 2.0.1 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 2.0.0 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 1.1.0 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 1.0.0 depends on attrs<21 and >=19

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Steps to Reproduce

1. Clone a copy of the Wagtail codebase using the following commands: - 
```
$ git clone https://github.com/wagtail/wagtail.git
$ cd wagtail
```
2. With your preferred virtualenv activated, install the Wagtail package in development mode with the included testing and documentation dependencies:
`$ pip install -e .[testing,docs] -U`

3. The error will pop up. 

There is something wrong with documentation dependencies.  
`$ pip install -e .[testing] -U` works absolutely fine. 

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version: 3.10
* Django version: 4.0.3
* Wagtail version: 2.17a0
* Operating System: Windows/ Mac

**Comment by gasman** [comment] 2022-03-09 22:41
I'm guessing this was triggered by #8084... ping @lb- @thibaudcolas

**Comment by lb-** [comment] 2022-03-09 22:56
I have been able to reproduce this issue.

It looks like `jinjalint` has not been [updated since 2018](https://pypi.org/project/jinjalint/#history), so I cannot see an easy way to just update jinjalint.

I might have to take another look at this later.

```
ERROR: Cannot install markdown-it-py==1.1.0, myst_parser and wagtail because these package versions have conflicting dependencies.

The conflict is caused by:
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 1.1.0 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 2.0.1 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 2.0.0 depends on attrs<22 and >=19
    jinjalint 0.5 depends on attrs==17.2.0
    markdown-it-py 1.0.0 depends on attrs<21 and >=19

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by lb-** [comment] 2022-03-09 22:57
I have not tested it but curlylint says it supports jinja templates https://pypi.org/project/curlylint/ (it is a fork of jinjalint).

**Comment by thibaudcolas** [comment] 2022-03-10 06:44
Arh, the pain! I’ll work on a PR and assign to you @lb- for review.

**Closed** 2022-03-11 15:21 UTC
Labels: type:Bug, Documentation

**Comment by thibaudcolas** [comment] 2022-03-11 17:05
@gitkaarma should be all resolved, sorry about that! Please let us know if you encounter further issues like this.
