### ISSUE TITLE
Page.copy() should copy Parental Many to Many fields

### ISSUE THREAD

**Issue by ChristophTr** [wagtail/wagtail#4931] opened 2018-11-29 14:08 UTC
### Issue Summary

Looking at the relevant code in `Page.copy`, unfortunately it doesn't look like we're doing anything to deal with those fields when copying revisions. `exclude_fields_in_copy` does not work on Parental M2M relations also, due to this limitation.

### Steps to Reproduce

1. Open the wagtail bakery demo (admin) and edit the first 'Bread' page by adding some ingredients (as it is a parental many to many field: `ingredients = ParentalManyToManyField('BreadIngredient', blank=True)`.
2. Save changes to that page with ingredients added
3. Go back to page listing under 'breads' and copy the page
4. Open the copied page (in the page editor)
5. Creating a copy of that instance using the Page.copy() does not offer a way to not copying those relations in the revision file (ingredients field), none are selected. 

We have discussed this issue in the support slack channel with @gasman and found this to be a possible bug.

*updated*

**Comment by lb-** [comment] 2019-02-20 05:38
@ChristophTr  - thanks for the issue submit

I am having trouble reproducing this scenario, I am using Wagtail Bakery

On the file [`bakerydemo/breads/models.py`](https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/breads/models.py#L123), in the `BreadPage` model - adding (~ line 125) the following `exclude_fields_in_copy = ['bread_type', 'ingredients']`.

When copying a bread page, it appears to remove the `bread_type` field on copy as expected, but it **does not** copy the ingredients.

However, If i remove that line, it will still **not** copy the ingredients.

Can you confirm that the issue is that `ParentalManyToManyField` are **never** copied, or that you have found that they are **always** copied, irrespective of what is put into `exclude_fields_in_copy`.

Currently the `exclude_fields_in_copy` will not work for `ParentalManyToManyField`s, but I am not sure if the issue is with copying those fields in general or if the wagtail bakery demo is set up differently.

**Comment by lb-** [comment] 2019-02-23 10:49
After some more digging, I have updated the issue summary/steps to reproduce.

There are two issues;
1. Parental Many to Many fields are not copied as expected (this issue)
2. ALL child relation fields AND Parental Many to Many fields do not honour the usage of `exclude_fields_in_copy` on the page's model - new issue to be created

In regards to this issue:

Page model copy method intentionally ignores `many_to_many` fields and comments advise that those fields are covered when child objects are copied.

https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L1062-L1065

However, the section that copies child objects uses the function `get_all_child_relations` which will not retrieve the parental m2m relations, we also need to add the usage of `get_all_child_m2m_relations`.

https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L1101-L1116

https://github.com/wagtail/django-modelcluster#introspection


Rough unit test below (which fails in current master)

```
   # wagtail/core/tests/test_page_model.py L705
    def test_copy_page_copies_parental_relations(self):
        christmas_event = EventPage.objects.get(url_path='/home/events/christmas/')
        summer_category = EventCategory.objects.create(name='Summer')
        holiday_category = EventCategory.objects.create(name='Holidays')

        # add parental many to many relations

        christmas_event.categories = (summer_category, holiday_category)
        christmas_event.save()

        # Copy it
        new_christmas_event = christmas_event.copy(
            update_attrs={'title': "New christmas event", 'slug': 'new-christmas-event'}
        )

        ## check that parental many to many are copied
        self.assertEqual(
            christmas_event.categories.count(),
            2,
            "Child objects (parental many to many) defined on the superclass were removed from the original page"
        )

        self.assertEqual(
            new_christmas_event.categories.count(),
            2,
            "Child objects (parental many to many) weren't copied"
        )
```

**Comment by lb-** [comment] 2019-02-23 11:15
See also original discovery as part of #4827

**Comment by lb-** [comment] 2019-02-28 22:06
Fixed in #5108

**Closed by lb-** 2019-02-28 22:06 UTC
Labels: type:Bug
