### ISSUE TITLE
streamfield auto select

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#10466] opened 2023-05-23 09:58 UTC
When I'm using a streamfield for and only have one block in it and click on the + symbol then I should not have to select the one item that my streamfield is offering. It should autoselect that one item. Currently you have to click and then click the block you want even if there is only one block type.

**Comment by laymonage** [comment] 2023-05-23 10:40
Thanks for the report, closing this issue as I believe this is a duplicate of #3998.

**Closed by laymonage** 2023-05-23 10:40 UTC
Labels: type:Enhancement
