### ISSUE TITLE
The left side of the Algolia InstantSearch results panel is cut off when viewing in portrait mode on mobile phone

### ISSUE THREAD

**Issue by andrewchung** [wagtail/wagtail#9893] opened 2023-01-08 16:57 UTC
The left side of the Algolia InstantSearch results panel is cut off when viewing in portrait mode on mobile phone (see attached).

Mobile browser is Chrome.  Is there a way to modify the CSS in the theme to adjust for this?  Thanks!
 
![Screenshot_20230108-114125_Chrome](https://user-images.githubusercontent.com/590100/211208987-46adea48-ec39-4685-84c0-67b813c69731.jpg)

**Comment by lb-** [comment] 2023-01-15 04:29
Flagging as a good first issue - fixing some styling in the docs.

@SyedImtiyaz-1 - not sure if you wanted to give this one a go.

The file needing changing is this one I think https://github.com/wagtail/wagtail/blob/main/docs/_static/css/docsearch.overrides.css

Please note that there is some nuance here as there is an overflow scroll styling class that gets toggled when the search popover opens/closes. This is so that the left table of contents can scroll nicely but also ensures that on larger devices (desktop width) the popover can overflow to the right.

See here for more context

* https://github.com/wagtail/wagtail/blob/main/docs/_static/css/docsearch.overrides.css#L22
* JS for body lock class https://github.com/wagtail/wagtail/blob/main/docs/_templates/layout.html#L74
* CSS in Sphinx theme that does the overflow for the left column https://github.com/wagtail/sphinx_wagtail_theme/blob/main/sass/_component_toc.scss#L95
* Related issue with scrollbars https://github.com/wagtail/sphinx_wagtail_theme/issues/204

**Comment by SyedImtiyaz-1** [comment] 2023-01-15 05:25
@lb- I'm started working on this issue. I'll raise a PR. when the issue got fixed or it get solved. You can assign me this one without any hesitation.

**Comment by Aym-n** [comment] 2023-01-18 19:53
Made a pull request for this issue #9912 
Please Check it and let me know if there are any  problems

**Comment by TensaCoder** [comment] 2023-02-05 18:30
Hi @lb- , Is this issue assigned or closed by any chance?
I would like to work on it, please do let me know if I can start working on it.
Thanks.

**Comment by gasman** [comment] 2023-02-05 18:38
@TensaCoder Please see the comments above - @Aym-n has created a pull request for this already.

**Comment by MashiatK** [comment] 2023-02-08 17:12
I want to work on this. If the issue is open, please assign it to me.

**Closed** 2023-02-16 09:48 UTC
Labels: Documentation, good first issue
