### ISSUE TITLE
Editing pages on mobile devices

### ISSUE THREAD

**Issue by inyoka** [wagtail/wagtail#5610] opened 2019-10-08 17:16 UTC
### Problem...

The only time I have an issue using Wagtail is when I am editing content from a mobile phone.  The "Drop Up" menu for want of a better word covers the last item on the editable page, making it impossible to edit (at least on my iPhone Plus).

In the image below, you can see where it says "Save Draft", is actually covering the text entry field for the body, and it is impossible to scroll down any further.

### Possible solution...

I would like the menu with "Publish, Save Draft, Submit for moderation etc" to be at the bottom of the page, rather than floating on the bottom.  This would allow users to reach the last element on the page for editing.

### Alternatives that make this non-essential ...
One solution is to rotate the phone to landscape, however in the era of mobile first development this is annoying, and isn't a very elegant solution.

![image](https://user-images.githubusercontent.com/6580673/66416963-ed103600-e9f6-11e9-959a-ee3caa2e75ad.png)

**Comment by thibaudcolas** [comment] 2020-03-03 13:35
Closing as duplicate of #4641.

**Closed by thibaudcolas** 2020-03-03 13:35 UTC
Labels: component:Frontend, type:Bug
