### ISSUE TITLE
Potentially wrong "check" method in "AbstractRendition" class

### ISSUE THREAD

**Issue by pierremanceaux** [wagtail/wagtail#3272] opened 2017-01-11 15:33 UTC
I make it short: I got some help from an experienced Django developer for an issue I got using custom image rendition. I won't be able to technically follow this thread since I'm much more frontend and new to Django.

### Issue Summary

Custom image rendition model breaks since updating Wagtail from 1.7 to 1.8.

### Steps to Reproduce

Here is our custom model:
```python
class SEORendition(Rendition):
    class Meta:
        proxy = True

    @property
    def alt(self):
        return self.image.alt_tag

    @property
    def attrs_dict(self):
        """
        A dict of the src, width, height, and alt attributes for an <img> tag.
        """
        return OrderedDict([
            ('src', self.url),
            ('width', self.width),
            ('height', self.height),
            ('alt', self.alt),
            ('title', self.image.title),
        ])
```

And here is the check that seems to fail, according the dev I have been talking to:
From https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailimages/models.py#L542
```
    @classmethod
    def check(cls, **kwargs):
        errors = super(AbstractRendition, cls).check(**kwargs)
        if not cls._meta.abstract:
            if not any(
                set(constraint) == set(['image', 'filter_spec', 'focal_point_key'])
                for constraint in cls._meta.unique_together
            ):
                errors.append(
                    checks.Error(
                        "Custom rendition model %r has an invalid unique_together setting" % cls,
                        hint="Custom rendition models must include the constraint "
                        "('image', 'filter_spec', 'focal_point_key') in their unique_together definition.",
                        obj=cls,
                        id='wagtailimages.E001',
                    )
                )

        return errors
```

According him, the check condition should be:
```python
if not cls._meta.abstract and not cls._meta.proxy:
    ...
```

Temporary workaround:
```python
class SEORendition(Rendition):
    class Meta:
        proxy = True

    @property
    def alt(self):
        return self.image.alt_tag

    @property
    def attrs_dict(self):
        """
        A dict of the src, width, height, and alt attributes for an <img> tag.
        """
        return OrderedDict([
            ('src', self.url),
            ('width', self.width),
            ('height', self.height),
            ('alt', self.alt),
            ('title', self.image.title),
        ])

    # Because we have a proxy model their check in the rendition class is invalid
    @classmethod
    def check(cls, **kwargs):
        errors = super(AbstractRendition, cls).check(**kwargs)

        return errors
```

I hope this will be clear enough to be taken in consideration, and I will stay available provide more information if needed.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.5
* Wagtail version: 1.9
* Browser version: Chrome 55

**Comment by lb-** [comment] 2024-01-22 07:12
As it's been a little while, I will flag this as a bug unconfirmed. Needs to be re-checked to see if the checks are still an issue.

**Comment by pierremanceaux** [comment] 2024-01-22 13:00
Hey @lb-. I completely forgot about this one!

I guess it isn't an issue anymore, this is what I'm running with since years. I assume this issue could be closed. Up to you, and thank you.

```
class SEORendition(AbstractRendition):
    image = models.ForeignKey(
        SEOImage, related_name="renditions", on_delete=models.CASCADE
    )

    class Meta:
        unique_together = (("image", "filter_spec", "focal_point_key"),)

    @property
    def alt(self):
        return self.image.alt_tag

    @property
    def attrs_dict(self):
        """
        A dict of the src, width, height, and alt attributes for an <img> tag.
        """
        return OrderedDict(
            [
                ("src", self.url),
                ("width", self.width),
                ("height", self.height),
                ("alt", self.alt),
                ("title", self.image.title),
            ]
        )
```

**Comment by gasman** [comment] 2024-01-22 15:12
@pierremanceaux Thanks for the feedback! It's not clear to me why `proxy = True` would be needed here, and it's on our roadmap to [improve the handling of alt text](https://github.com/wagtail/rfcs/pull/51) (both as a property of the image and in the context where it's used on a page), at which point this customisation hopefully won't be needed at all. Since this is no longer an issue for you, I'll close this until a new use-case for proxy models comes up.

**Closed by gasman** 2024-01-22 15:12 UTC
Labels: type:Bug, component:Images, status:Unconfirmed, component:Checks
