### ISSUE TITLE
PageChooserPanel not using the admin display title on showing the selected page

### ISSUE THREAD

**Issue by edwinmp** [wagtail/wagtail#6403] opened 2020-09-24 07:46 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.

I used the `get_admin_display_title` function and in most cases my custom title is shown except for the inlined PageChooserPanel i.e. the chooser shows the correct title, but on choosing a page, the inlined display is still showing the original page title.

In the chooser:
![image](https://user-images.githubusercontent.com/5672438/94115959-1833a580-fe53-11ea-9d56-d8dfafacd750.png)

On the page after selecting:
![image](https://user-images.githubusercontent.com/5672438/94115941-12d65b00-fe53-11ea-9902-a6a7ec86ee52.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Pasted the code below to your home app `models.py`

```
from django.db import models

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import PageChooserPanel


class HomePage(Page):
    pass


class PageOne(Page):
    def get_admin_display_title(self):
        return "Testing - " + self.draft_title


class PageTwo(Page):
    page = models.ForeignKey(
        PageOne,
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        PageChooserPanel('page')
    ]
```
3. Make migrations and migrate
4. Log into the Wagtail admin
5. Create an instance of PageOne - display title on publishing should be prefixed with `Testing - `
6. On creating an instance of PageTwo, navigate to the page chooser field & click `Choose a page` - in the chooser modal, the PageOne page should be prefixed with `Testing - `
7. Select a PageOne page
8. In the display of the selected page, there's no `Testing - ` prefix as in the others.

I expected that since this is still part of the admin interface, the result of `get_admin_display_title` should still be shown

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES

### Technical details

* Python version: 3.7.0
* Django version: 3.1.1
* Wagtail version: 2.10.1
* Browser version: Chrome 85

**Comment by loicteixeira** [comment] 2020-09-24 10:53
Thanks for the detailed report @edwinmp 
Closing though as it is a duplicate of #5726 and the other issue has details on how to fix the issue.
FWIW, the issue is flagged as *good first issue* if you wanted to give it a go.

**Closed by loicteixeira** 2020-09-24 10:53 UTC
Labels: type:Bug
