### ISSUE TITLE
Changing default slug causes get_site to return no pages.

### ISSUE THREAD

**Issue by kimberlyherman** [wagtail/wagtail#9848] opened 2023-01-05 07:09 UTC
### Issue Summary
When we change the slug for a page, the get_url_paths method (called by get_site) in the Page class returns no pages

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Set up a basic [content site](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#:~:text=tags%20aren%E2%80%99t%20loaded.-,A%20basic%20blog,-We%20are%20now)_ with a few index child pages _or use an existing demo built on Wagtail 2.16 that has child pages and the Promote tab in the admin parent page_
3. Add this method to the BlogIndexPage in models.py _to get all child pages_
`def get_collections():`
`    res = None`
`    site = self.get_site()`
`    if site:`
`       res = res.in_site(site)`
`    return res`
4. in your index template add this _not pretty, but enough to show the data_
`<div> {% page.get_collections %}</div>`
5. run your site and go to the Promote tab on the index page
6. change the slug, save draft, publish
7. refresh the index page and see that the data is gone

I expected all results for get_site

### Technical details

-   Python version: 3.8
-   Django version: 2.2
-   Wagtail version: 2.16
-   Browser version: Chrome 108

**Comment by NXPY123** [comment] 2023-09-30 11:36
@kimberlyherman Can you specify the steps better? I'm having trouble reproducing the issue

**Comment by gasman** [comment] 2023-09-30 12:30
The code snippet above looks incorrect to me - if `site` is defined, then the line `res = res.in_site(site)` will attempt to call `in_site` on `None`.

**Comment by gasman** [comment] 2023-11-08 13:15
Closing due to lack of updates (and Wagtail 2.16 is well out of support now).

**Closed by gasman** 2023-11-08 13:15 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed
