### ISSUE TITLE
Broken page edition UI for RTL languages 

### ISSUE THREAD

**Issue by engAmirEng** [wagtail/wagtail#9800] opened 2022-12-16 19:23 UTC
### Issue Summary
In page editing UI when language is a RTL one things get funny (broken)
[See this](https://drive.google.com/file/d/11tPK0n5GegrQx8lS4Ya37AaW7x5b5yYH/view?usp=share_link) 

### Steps to Reproduce

Active a RTL language of your choice

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

### Technical details

-   Wagtail version: 4.1.1

**Comment by ash1895-web** [comment] 2022-12-17 11:18
Hey @engAmirEng @zerolab ,
I would like to give a try to this issue.

**Comment by pyzenberg** [comment] 2023-01-13 18:02
It seems Tailwind CSS not supporting RTL. For this specific issue I made a workaround:
1. Create a CSS admin hook inside `wagtail_hooks.py`
```python
from django.conf import settings
from django.templatetags.static import static
from django.utils.html import format_html
from django.utils.translation import get_language_bidi
from wagtail import hooks


@hooks.register("insert_global_admin_css")
def global_admin_css():
    if get_language_bidi():
        return format_html(
            '<link rel="stylesheet" href="{}">',
            static("extended/wagtail/rtl.css"),
        )
    return ""
```
2. Inside the specified static path (`extended/wagtail/rtl.css`):
```css
.form-side {
    --tw-translate-x: -100%;
}

.form-side--open {
    --tw-translate-x: 0%;
}
```

There are most probably many more issues (especially with Tailwind CSS) which could resolved by try-and-errors and then added to this file or, a better solution (and more time consuming) would be to add decent support for RTL inside Wagtail's Tailwind CSS codes.

**Comment by engAmirEng** [comment] 2023-01-17 09:34
> It seems Tailwind CSS not supporting RTL. For this specific issue I made a workaround:
> 
> 1. Create a CSS admin hook inside `wagtail_hooks.py`
> 
> ```python
> from django.conf import settings
> from django.templatetags.static import static
> from django.utils.html import format_html
> from django.utils.translation import get_language_bidi
> from wagtail import hooks
> 
> 
> @hooks.register("insert_global_admin_css")
> def global_admin_css():
>     if get_language_bidi():
>         return format_html(
>             '<link rel="stylesheet" href="{}">',
>             static("extended/wagtail/rtl.css"),
>         )
>     return ""
> ```
> 
> 2. Inside the specified static path (`extended/wagtail/rtl.css`):
> 
> ```css
> .form-side {
>     --tw-translate-x: -100%;
> }
> 
> .form-side--open {
>     --tw-translate-x: 0%;
> }
> ```
> 
> There are most probably many more issues (especially with Tailwind CSS) which could resolved by try-and-errors and then added to this file or, a better solution (and more time consuming) would be to add decent support for RTL inside Wagtail's Tailwind CSS codes.

Hey, 
It makes the the opening and closing the preview panel fixed, thanks for that, 
can you make something similar for other two main problems? I mean 
1-broken panel preview for tablet and desktop (the mobile preview seems fine) 
2-and the blinking of the minimap

**Comment by thibaudcolas** [comment] 2023-01-18 09:51
👋 thanks for reporting this! We don’t currently formally support right-to-left languages, so as much as I’d like to see this fixed, to me this is an enhancement rather than a bug in the intended behavior.

There are a lot of known issues with how the admin interface displays with RTL languages (see #7793 for more context). If anyone wants to help getting this particular issue sorted, I’d really recommend making a pull request directly to Wagtail rather than making your own `rtl.css` overrides (though that’s definitely a good workaround in the short term).

If anyone thinks this really ought to be treated as a bug, then you need to spend some time making the case for why Wagtail should _now_ officially support RTL languages, backed with a summary of known issues so we don’t claim support for something that’s completely broken.

---

Back to this specific issue – I believe none of our usage of CSS translations (`translateX`) is reversed in RTL languages. So my preference would be to fix this for all areas of the UI at once – introduce a CSS variable equal to `1` or `-1` depending on the language direction, and use that variable in all our translations to change their direction.

**Closed** 2023-01-19 12:06 UTC
Labels: type:Bug, type:Enhancement, component:UI localization

**Comment by engAmirEng** [comment] 2023-01-20 14:57
Looks awsome, thanks 👍
