### ISSUE TITLE
RichTextField not visible when used as a field on custom Image model

### ISSUE THREAD

**Issue by eyemyth** [wagtail/wagtail#4466] opened 2018-04-11 15:10 UTC
### Issue Summary

RichTextField fields are not visible in the CMS when used as a field on custom Image model.

### Steps to Reproduce

I set up a custom image model as described [here](http://docs.wagtail.io/en/v2.0.1/advanced_topics/images/custom_image_model.html). I added a `wagtail.core.fields.RichTextField` as one of the fields, and added that field name to `admin_form_fields`. I expected the field to appear at /cms/images/{pk} but it does not. Other standard-issue Django fields added in the same way do appear in the CMS.

### Technical details

* Python version: Python 3.6.4
* Django version: Django 2.0.4
* Wagtail version: Wagtail 2.0.1
* Browser version: Safari 11.1; Chrome 65.0.3325.181

**Comment by thibaudcolas** [comment] 2018-04-11 18:54
@eyemyth 👍 this looks like a cache issue but would you mind copying the full error so I can confirm?

**Comment by eyemyth** [comment] 2018-04-11 19:02
The actual error as printed in the Safari console is:

```
[Error] TypeError: undefined is not an object (evaluating 'window.draftail.initEditor')
	Global Code (4482:384)
```

**Comment by thibaudcolas** [comment] 2018-04-11 19:39
I get the same error when the editor's code isn't loaded on the page. There are two things that I think might cause this:

- Most likely – An outdated cache. Please have a look at https://github.com/wagtail/wagtail/issues/3700#issuecomment-375474765 (and the linked SO answers) to find cache-clearing instructions.
- Potentially – the `draftail.js` file isn't loading on the page where your field is defined for some other reason.

Once you've tried clearing browser / static file caches, have a look at the HTML source for your page and make sure it contains `<script type="text/javascript" src="/static/wagtailadmin/js/draftail.js"></script>`. This line should be *before* the actual content of the page (on my test site it's line 185, towards the end of the list of `<script>` tags at the start of the `<body>`.

If the `<script>` is not there, I would suspect that for some reason the `admin_form_fields` doesn't properly handle the field's widget's `media`.

**Comment by eyemyth** [comment] 2018-04-11 20:15
Hm, yeah that `script` tag is definitely not in my page. I emptied my browser caches too.

Here's the complete HTML output from the Safari Resources tab: https://gist.github.com/eyemyth/685344a45652ff871ce0047712f87d72

**Comment by thibaudcolas** [comment] 2018-04-11 21:36
Ok, the problem is easier to understand now. This page template (https://github.com/wagtail/wagtail/blob/master/wagtail/images/templates/wagtailimages/images/edit.html) does not load the required JS and CSS for the widgets rendered there, nor any of the other requirements for rich text editor fields in Wagtail.

A quick fix might be to override this template's `extra_js` block to load the `_editor_js.html` template (eg. https://github.com/wagtail/wagtail/blame/master/wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/add.html#L40), but I think this will be a bit brittle.

Looking at the code, I doubt this has ever worked, so I'm also worried that even if you do manage to get the field to display you will run into more issues down the line.

Let's way to hear from others who may be more knowledgeable about image overrides.

**Comment by eyemyth** [comment] 2018-04-12 13:45
I managed to get the fields to render on the page, although oddly they do not have the field names listed. Here's a [screenshot](https://i.imgur.com/CmLFelS.png).

I overrode the edit.html template and added `<link rel="stylesheet" href="{% static 'wagtailadmin/css/panels/draftail.css' %}" type="text/css">` to the `extra_css` block, and `<script src="{% static 'wagtailadmin/js/draftail.js' %}"></script>` to the `extra_js` block.

I would be nice to have native/out of the box RichTextField functionality here. Our editors will want to have some basic text formatting tools for image captions.

**Comment by gasman** [comment] 2018-05-30 19:39
I think the 'proper' fix for this will be to ensure that the edit form's [media property](https://docs.djangoproject.com/en/stable/topics/forms/media/#media-on-forms) is output onto the page - this should include the necessary draftail.css and draftail.js includes. (However, it may still be lacking some of the additional includes normally found in `_editor_js.html`, such as modal-workflow.js, and so you might find that some functionality is missing, such as chooser popups.)

Note that having a rich text field within the image model could also cause problems with the 'upload' tab of the image chooser popup, because the rich text field may itself trigger popups, and a popup within a popup isn't officially supported...

**Comment by lb-** [comment] 2019-08-18 05:25
Aside from the caveats mentioned by @gasman  - this has now been fixed.

Merged #5286 via  https://github.com/wagtail/wagtail/commit/eaad01308142337739d7edd9f08bd8e714be23f0

**Closed by lb-** 2019-08-18 05:25 UTC
Labels: component:Images, component:Rich text, type:Bug

**Comment by sir-sigurd** [comment] 2019-08-29 14:48
I have the same problem, but with custom Document model, and it seems that #5286 has fixes only for Image model, so should it be fixed for Document separately?

**Comment by gasman** [comment] 2019-08-29 16:53
@sir-sigurd Yes - a similar fix for custom document models would be very welcome, and will probably look a lot like this one.

(As I recall, I considered fixing documents at the same time as doing this, but eventually decided it was best not to get carried away doing too much in one PR :-) )

**Comment by sir-sigurd** [comment] 2019-08-29 16:58
@gasman, OK, I’ll probably have time to fix it.

**Comment by urlsangel** [comment] 2024-04-24 10:44
If anyone else is looking for an answer to this question, I’ve fixed it by implementing the fix from here:

- https://github.com/wagtail/wagtail/pull/11754
- https://github.com/wagtail/wagtail/pull/11803/files#diff-4ee7f72163f125b407b463a6a0318dfed050983223c9af385be2f8fa631bea28

Essentially, the old implementation should be replaced with this:

```
{% block extra_js %}
    {{ block.super }}
    {{ media.js }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
{% endblock %}
```
