### ISSUE TITLE
Slow page admin - timeout with many users in DB

### ISSUE THREAD

**Issue by PetrDlouhy** [wagtail/wagtail#5703] opened 2019-11-13 08:48 UTC
### Issue Summary

I have tens of thousands users in my DB and the `page` admin change site is very slow - so slow that it timeouts.

### Steps to Reproduce

1. fill many users to your DB
2. create Wagtail page
3. go to `admin`->`Wagtail core`->`page`
4. page is very slow or timeouts

Wagtail should use `autocomplete_fields` or `raw_id_fields` for the user field.

**Comment by gasman** [comment] 2019-11-13 09:21
Hi @PetrDlouhy - can you give more detail on how to reproduce this, please? "Go to `admin` -> `Wagtail core` -> `page`" doesn't match the description of anything in the Wagtail admin (the term "Wagtail core" is never used in the admin interface), and the basic page model does not contain an editable user field. Are you using an extension package such as wagtailtrans or Puput, perhaps?

**Comment by PetrDlouhy** [comment] 2019-11-13 14:44
@gasman Sorry, I didn't realize, that my description could confuse Django ModelAdmin with Wagtail admin. The page is of course in Django ModelAdmin for `wagtailcore.Page` model on URL like `/admin/wagtailcore/page/1/change/`

**Comment by gasman** [comment] 2019-11-13 15:12
Thanks for the clarification. I don't think there's any reason for wagtailcore.Page to be registered with the Django admin at all - I suspect that was only ever done for the benefit of very early Wagtail versions that didn't have a dedicated Settings -> Groups interface in the Wagtail admin and required you to set up page permissions through the Django admin instead (which in turn required wagtailcore.Page to be registered in order for the page chooser to work).

I propose that we remove wagtail/wagtailcore/admin.py completely - I don't believe that any more than a tiny fraction of Wagtail users have ever made use of it (it's certainly not been edited in any meaningful way since the initial release of Wagtail), and anyone who needs to edit pages through Django admin for whatever reason can easily register it within their own project (and tweak the configuration as they need, e.g. setting `autocomplete_fields` / `raw_id_fields` appropriately).

**Comment by lb-** [comment] 2019-11-26 12:53
Resolved via #5706

**Closed** 2019-11-26 12:52 UTC
Labels: size:Small, type:Cleanup/Optimisation
