### ISSUE TITLE
ModelAdmin: Adding model in `users` app gets `ValueError: Invalid Literal for Base 10`

### ISSUE THREAD

**Issue by williln** [wagtail/wagtail#4713] opened 2018-08-02 18:37 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have a `users` app with a custom `User` model. When I tried to add a `Profile` model to `users/models.py` and then register it with the Wagtail admin with `ModelAdmin`, I got a `ValueError: invalid literal for base 10`. When I moved the `Profile` model to its own app, using the `ModelAdmin` worked perfectly. 

Full traceback: 
```
web_1     | Internal Server Error: /admin/users/myprofile/
web_1     | Traceback (most recent call last):
web_1     |   File "/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1     |     response = get_response(request)
web_1     |   File "/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)
web_1     |   File "/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
web_1     |     response = viewfunc(request, *args, **kw)
web_1     |   File "/venv/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
web_1     |     return view_func(request, *args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
web_1     |     return view_func(request, *args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/wagtail/admin/utils.py", line 145, in wrapped_view_func
web_1     |     return view_func(request, *args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/wagtail/users/views/users.py", line 140, in edit
web_1     |     user = get_object_or_404(User, pk=user_id)
web_1     |   File "/venv/lib/python3.6/site-packages/django/shortcuts.py", line 85, in get_object_or_404
web_1     |     return queryset.get(*args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
web_1     |     clone = self.filter(*args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
web_1     |     return self._filter_or_exclude(False, *args, **kwargs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
web_1     |     clone.query.add_q(Q(*args, **kwargs))
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
web_1     |     clause, _ = self._add_q(q_object, self.used_aliases)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
web_1     |     allow_joins=allow_joins, split_subq=split_subq,
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
web_1     |     condition = self.build_lookup(lookups, col, value)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
web_1     |     return final_lookup(lhs, rhs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
web_1     |     self.rhs = self.get_prep_lookup()
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
web_1     |     return self.lhs.output_field.get_prep_value(self.rhs)
web_1     |   File "/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
web_1     |     return int(value)
web_1     | ValueError: invalid literal for int() with base 10: 'myprofile'
```

### Steps to Reproduce

1. Start a new project, create a new app called `users`, create a custom `User` model that inherits from `AbstractBaseUser` and `PermissionsMixin` from `django.contrib.auth.models`. Run migrations. 
2. Create a new model `Profile` that inherits from `models.Model` in the same `users/models.py`. It doesn't matter what attributes it contains (I tried with a `OneToOneField` to `User` and then stripped down to just one `CharField` attribute to try and isolate the error). Run migrations. 
3. Create `wagtail_hooks.py` in the `users` app, and create a new `ProfileAdmin` with wagtail `ModelAdmin`. Register with `modeladmin_register`. Make `add_to_settings` True and `exclude_from_explorer` False. 
4. In the Wagtail admin, navigate to the `Profile` admin. You should see an error. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expected to be able to register this model with the Wagtail Admin, as I had with another model in a different app in my project. 

### Technical details

* Python version: Run `python --version`. __Python 3.6.5__
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`. __Django 1.11.15__
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`. __Wagtail 2.1.1__
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out. __Chrome 67__ 

__Solution__ for anyone else who comes across this: Move the model to its own app.

**Comment by BertrandBordage** [comment] 2018-08-02 18:41
Thanks for the report @williln!

Could you check your traceback please? An `ImportError` is raised in your traceback, not a `ValueError`.

**Comment by williln** [comment] 2018-08-02 18:57
@BertrandBordage Sorry about that! Updated. (The ImportError was from when I was refactoring to move the model into another app and is unrelated.)

**Comment by williln** [comment] 2018-08-02 18:59
Note: This happened both before I'd saved any instances of the model, and once I'd saved an instance in the shell, so the ValueError doesn't seem to be related to any actual data in an instance. The model name I was messing with was `MyProfile`.

**Comment by BertrandBordage** [comment] 2018-08-02 19:10
Ah, I think I found the cause of the issue: the URL `/admin/users/` is dedicated to `wagtail.users`, so when you ask for `/admin/users/myprofile/` to get to the index of your users, you end up calling the edit page of a Wagtail user, using `myprofile` as PK.

To work around this clash, please [define `url_help_class` in your `ModelAdmin`](http://docs.wagtail.io/en/v2.1.1/reference/contrib/modeladmin/primer.html#modeladmin-url-helper-class) with a subclass of `AdminURLHelper` that customizes [the `_get_action_url_pattern` method](https://github.com/wagtail/wagtail/blob/v2.1.1/wagtail/contrib/modeladmin/helpers/url.py#L12-L16).

I’ll close this issue for now as I don’t think we’ll change the URLs of Wagtail’s admin to handle clashes with admin extensions.

**Closed by BertrandBordage** 2018-08-02 19:10 UTC

**Comment by rgs258** [comment] 2019-08-08 15:24
Thank you for this issue!!! Lacey, you saved us COUNTLESS hours with this one!!
