### ISSUE TITLE
Search in the image chooser does not consider tags when using the database search backend

### ISSUE THREAD

**Issue by pcraston** [wagtail/wagtail#278] opened 2014-06-02 10:43 UTC
Currently it seems to only search by the image title - it would be great if it would be possible to also search by tag and show all images with a certain tag.

**Comment by mhnbcu** [comment] 2015-02-08 03:35
:+1:

**Comment by davecranwell** [comment] 2015-02-09 09:45
As far as I'm aware image tags are indexed like any other text attributed to an image (such as title). Although you don't get any kind of auto-compete interface to choose a tag when doing a text search, any search term you use will search for tags with those words used. This feature may however depend on Elasticsearch. 

Tests to ensure searching by image tag worked were written here: https://github.com/torchbox/wagtail/issues/613

@pcraston are you able to confirm this is still the case with a more recent version installed? Given this ticket is quite old, we'll close it unless this can be reproduced in master.

**Comment by pcraston** [comment] 2015-02-09 10:55
We haven't had time to upgrade wagtail for while but are planning to update our project soon. I'll check once we have the latest version running.

**Comment by gasman** [comment] 2015-02-09 17:37
In #973 @mhnbcu is (indirectly) reporting that this behaviour is still present in Wagtail 0.8.4, so let's keep this issue open for further investigation.

**Comment by olifante** [comment] 2015-09-23 19:32
any update on this? I'm using Wagtail 1.1 and this issue is still present. It's quite counter-intuitive to provide the ability to tag images and not allow admins to search by tag.

**Comment by jorge-marques** [comment] 2015-11-18 18:13
:+1:

**Comment by jorge-marques** [comment] 2015-11-18 18:14
It would be nice if we could search pages by tag as well.

**Comment by gasman** [comment] 2015-11-18 18:45
This one confused me for a while during final testing of Wagtail 1.2 before I figured out what was going on. Searching on tags only currently works when using the Elasticsearch search backend, not the database one <http://docs.wagtail.io/en/v1.2/topics/search/backends.html>. This fact isn't at all obvious, and it's probably become worse in recent releases as the project template has been stripped back to a 'vanilla' setup with no mention of Elasticsearch.

It's particularly unfortunate that clicking on 'popular tags' in the image chooser relies on having functional tag search (#973) - in other words, this is one feature that's visibly broken on a default Wagtail install. Let's get this fixed for 1.3 - if we can't make tag search work with the db backend, we should at least update the 'popular tags' listing to use plain SQL filtering rather than going through search.

**Comment by gasman** [comment] 2015-12-10 15:17
Have implemented a workaround for the 'popular tags' listing on images in #2026, so #973 is now addressed. Will keep this open because ideally we do want tags to be considered when running a regular search using the Postgres backend (otherwise there's no way to filter on non-'popular' tags).

**Comment by benebun** [comment] 2016-01-20 11:40
@gasman Is there a difference between the search in the image chooser and the search on the top when browsing the images (/admin/images/). There seems to be since in the latter I can't search for image tags but in the image chooser I can.
I thought the original author also meant that scenario but since you added "image chooser" to the title I'm now confused :)

**Comment by benebun** [comment] 2016-02-09 17:30
@gasman Any update on this? Is there a workaround that makes tags searchable? As @olifante mentioned above it is quite counter-intuitive.
Thanks!

**Comment by gasman** [comment] 2022-07-01 13:22
With the new database search backend in Wagtail 2.15, tags are now included in the indexed content of images.

**Closed as completed by gasman** 2022-07-01 13:22 UTC
Labels: type:Bug, component:Search, component:Images, component:Choosers
