### ISSUE TITLE
InlinePanel doesn't work with ModelViewSet

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#11760] opened 2024-03-14 23:58 UTC
### Issue Summary

InlinePanel will render but none of the controls (move/delete/add) will work. There's a JS error in the console. 

```
Uncaught ReferenceError: InlinePanel is not defined
```
Similar to #11739 I reckon there's some assumed js that's missing

### Steps to Reproduce

```py
from django.db import models
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.panels import FieldPanel, InlinePanel
from wagtail.models import Orderable


class Tags(Orderable):
    page = ParentalKey("home.Resource", related_name="tags")
    name = models.CharField(max_length=255)

    panels = [FieldPanel("name")]


class Resource(ClusterableModel):
    file = models.ForeignKey(
        "wagtaildocs.Document", on_delete=models.CASCADE, related_name="+"
    )

    panels = [FieldPanel("file"), InlinePanel("tags")]
```

ModelViewSet for Resource registered, go to create a new one and click 'Add'

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes, also tested with latest main branch (cd50955b49)

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: v6.1a0
-   Browser version: Latest FF, Chromium

**Comment by seb-b** [comment] 2024-03-21 23:10
I worked around this just by overriding the edit template and adding `{% include "wagtailadmin/pages/_editor_js.html" %}` to the ` extra_js` block (similar to the snippet edit view). Not sure if there's anything stopping something similar being added to the next patch release while the stimulus stiff is being worked through?

**Comment by lb-** [comment] 2024-03-24 07:20
Relates to https://github.com/wagtail/wagtail/issues/2936 - we need to eventually resolve the usage of this import which contains other JS.

There is a way forward (longer term) with adoption of Stimulus for `InlinePanel`, of which https://github.com/wagtail/wagtail/pull/11633 is the first step.

For now, I agree we may just need to do something similar to https://github.com/wagtail/wagtail/pull/11620 or more specifically this backport (small scoped) PR https://github.com/wagtail/wagtail/pull/11754

Removing `<script src="{% versioned_static 'wagtailadmin/js/expanding-formset.js' %}"></script>`  from `wagtail/admin/templates/wagtailadmin/pages/_editor_js.html` AND `wagtail/users/templates/wagtailusers/groups/includes/group_form_js.html`. Then adding it to `wagtail/admin/templates/wagtailadmin/admin_base.html` just before the `modal-workflow.js` import.

Should be good for anyone to pick up this as a good second issue, they will just need to understand how to reproduce the problem (confirm they have with a comment) and then submit the fix + check any unit tests that need changing.

**Comment by laymonage** [comment] 2024-03-26 13:58
@lb- it looks like we don't need `expanding-formset.js` for this (it's only used for configuring permissions and assigning workflows to pages). The `InlinePanel` and `MultipleChooserPanel` come from `page-editor.js`:

https://github.com/wagtail/wagtail/blob/5bc9731616efdd3452dd0749362ac085faa46419/client/src/entrypoints/admin/page-editor.js#L2-L6

This can be fixed by including the above bits to the `wagtailadmin/generic/form.html` template in some way. If we include the `page-editor.js` completely, there will be an error as it tries to access `Mousetrap.bind` in `initKeyboardShortcuts`, which won't work unless we also bring in the Mousetrap lib's JS or if we check whether `Mousetrap` is available before proceeding with the call.

I think we should just bite the bullet for now and include `_editor_js.html` in `wagtailadmin/generic/form.html`. See my comment in https://github.com/wagtail/wagtail/issues/11799#issuecomment-2020497240 for more details.

**Comment by lb-** [comment] 2024-03-26 20:27
Ok. I'll take a look, thanks for digging into it - some extra context also. 

There is active development on this PR to streamline how Mousetrap is used https://github.com/wagtail/wagtail/pull/11740 - I'm hopeful this will be done by the contributor ready for review before the 6.1 release candidate.

Additionally, if you could review https://github.com/wagtail/wagtail/pull/11168 - this will go a long way to removing extra bulk in the editor JS html import both now and when we can fully remove the depreciations in the next major bump.

@laymonage

**Closed** 2024-03-27 08:47 UTC
Labels: type:Bug, component:Panels
