### ISSUE TITLE
Extending Draftail rich text with BlockFeature with icon as a list of SVG paths results in raw text displayed in the ComboBox

### ISSUE THREAD

**Issue by DominicLGit** [wagtail/wagtail#10319] opened 2023-04-06 11:51 UTC
### Issue Summary
SVG path is displayed as raw text in ComboBox when BlockFeature has an icon defined as a list of svg paths.

### Steps to Reproduce

1. Register Draftail BlockFeature with control["icon"] as a list of svg path strings. 
2. View ComboBox of a rich text field with that feature implemented.

![image](https://user-images.githubusercontent.com/50773668/230359294-53af952e-a0fb-42d6-bb20-66fd2c0a1000.png)

![image](https://user-images.githubusercontent.com/50773668/230361775-4f9c4682-e0f2-45e3-b821-1ae8c35e6505.png)

1024 x 1024 svg path for testing

`control["icon"] = [
        "m21 892l160-240 160 240zm383-557h600v150h-600zm0 204h600v150h-600zm0 204h600v150h-600zm0-612h600v150h-600zm-64 1l-160 240-160-240z"
    ]`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Expected behaviour: display SVG path as a 1024 x 1024 viewbox SVG similar to Draftail-Icon icons in Draftail header. 

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Wagtail version: v4.2.2

**Comment by richie-blake** [comment] 2023-04-22 11:52
I'm also seeing this behaviour. Wagtail 4.2.2

**Comment by zerolab** [comment] 2023-04-22 14:56
Wagtail does not support defining Draftil icons as SVG paths. All icons are an id reference
see https://github.com/wagtail/wagtail/blob/main/wagtail/admin/wagtail_hooks.py#L550

See the custom icons documentation at https://docs.wagtail.org/en/latest/advanced_topics/icons.html#icons. The `register_icons` hook works with Wagtail 4.2

Given the above, closing this issue. I do not think there's any plan to support SVG paths when registering a Draftail feature

**Comment by zerolab** [comment] 2023-04-22 15:02
I take it back,
https://docs.wagtail.org/en/stable/extending/extending_draftail.html

mentions

> The controls’ icon can be a string to use an icon font with CSS classes, say 'icon': 'fas fa-user',. It can also be an array of strings, to use SVG paths, or SVG symbol references for example 'icon': ['M100 100 H 900 V 900 H 100 Z'],. The paths need to be set for a 1024x1024 viewbox.

**Comment by gasman** [comment] 2023-10-17 07:54
Closing as a duplicate of #11051 (which came later, but has more detailed reproduction steps).

**Closed by gasman** 2023-10-17 07:54 UTC
Labels: type:Bug, status:Unconfirmed
