### ISSUE TITLE
inline field not saving records

### ISSUE THREAD

**Issue by dima23113** [wagtail/wagtail#9802] opened 2022-12-16 23:39 UTC
### Issue Summary
Inline field does not save records. I fill in the required fields of the linked model, click "publish" and nothing happens. The page is saved, but the associated post is not. If I create a record through the model, and not through inline, then everything works and then this created record appears in the inline field.

https://imgur.com/YYUN53A
https://imgur.com/a/eJoDzlf

### Steps to Reproduce

1. Edit models.py as follows...
```
class Product(SeoMixin, Page):
    subpage_types = []
    content_panels = [
        FieldPanel('title'),
        InlinePanel('materials')]

class ProductMaterial(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    img = models.ForeignKey(
        'wagtailimages.Image',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )
    product = models.ManyToManyField(Product, through='Material', blank=True)

class Material(Orderable):
    product = ParentalKey('Product', on_delete=models.CASCADE, related_name='materials')
    material = models.ForeignKey(
        ProductMaterial,
        on_delete=models.CASCADE,
        related_name='material_products',
    )
    qty = models.IntegerField()
    article = models.CharField(max_length=256, null=True, blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    specifications = StreamField([
        ('weight', blocks.CharBlock(max_length=256)),
        ('width', blocks.CharBlock(max_length=256)),
        ('height', blocks.CharBlock(max_length=256)),
        ('length', blocks.CharBlock(max_length=256))
    ],
        max_length=1,
        block_counts={
            'weight': {'max_num': 1},
            'width': {'max_num': 1},
            'height': {'max_num': 1},
            'length': {'max_num': 1}
        },
        use_json_field=True, blank=True, null=True
    )
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

    Python version: 3.9
    Django version: 4.1.4
    Wagtail version: 4.1.1
    Browser version: Firefox 107

**Comment by gasman** [comment] 2022-12-17 00:20
This bug report is too unclear for us to work with, sorry. The code you have given is incomplete - for example, `SeoMixin` is not defined, it seems from the screenshot that you have registered the Material model through either snippets or ModelAdmin, but I don't know which (and I can't work it out from the screenshot, because I don't speak Russian). In the second screenshot, the InlinePanel is collapsed, so I don't know what I'm supposed to be looking at.

When we say "this issue can be reproduced as described on a fresh Wagtail project", this means that we need exact steps to follow, starting from a totally new Wagtail project - not just an excerpt from an existing project. See #9391 for an example of the detail we need.

I'll close this now, but feel free to open a new issue with the required detail.

**Closed by gasman** 2022-12-17 00:20 UTC
Labels: type:Bug, status:Unconfirmed
