### ISSUE TITLE
No good way to subclass the Django form fields used in wagtail Panels.

### ISSUE THREAD

**Issue by ptink** [wagtail/wagtail#2103] opened 2016-01-12 14:58 UTC
Hi, I wrote support thread for this on the [google group](https://groups.google.com/forum/#!topic/wagtail/31DyjslZqSE) but haven't gotten a reply there yet and rooting around in the code isn't providing me with a tidy way of doing this.

The actual task is quite simple, I want to override the ModelChoiceField that is used in the form for an InlinePanel on my page. The issue is that exposing the form and modifying it appears to be convoluted at best unless I'm missing an easier way to do it. Are there any plans to allow for easier (or indeed, possible) modification of the forms generated automatically for panels?

**Comment by gasman** [comment] 2016-01-14 17:33
Have just had a dig into this, and I can't see a good way to do it either. We hit the dead end at `form_for_model` https://github.com/torchbox/wagtail/blob/4065bece78c68292b99bf50b2471405f5c2a527c/wagtail/wagtailadmin/edit_handlers.py#L94, which doesn't allow overriding field classes, only widgets. Django 1.9 added a `field_classes` parameter to `modelform_factory` (which is what `form_for_model` is based on) presumably for this reason - we could do the same for our version (assuming we can't find a more developer-friendly solution, that is).

As a workaround, I guess you could override the widget class to make the call to `obj.get_full_name` itself when generating the label text, rather than going through the field's `label_from_instance`...

**Comment by thibaudcolas** [comment] 2024-11-01 16:19
Reviewed today – this might now be possible. Could someone review and report back? Assigning to @gasman

**Comment by gasman** [comment] 2024-11-01 18:23
The way we'd like this to work would be to define a [custom form class](https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html#customizing-generated-forms) with the appropriate form fields defined on it, and set that as the `base_form_class` on the model. This doesn't currently work for InlinePanels, but the discussion on #3175 suggests that it is possible with some fiddly subclassing of InlinePanel. As such, I'll close this as a duplicate of #3175.

**Closed by gasman** 2024-11-01 18:23 UTC
Labels: type:Enhancement, status:Unconfirmed
