### ISSUE TITLE
Extra whitelisted attributes on <a> element are ignored

### ISSUE THREAD

**Issue by warhotdog** [wagtail/wagtail#897] opened 2015-01-08 07:50 UTC
Apparently hooks whitelist not work if they have the attributes data-linktype for example if you wanted to add a class to the element "A" simply ignores .. seeing a little further back apparently only has contemplated that clean content not attribute the same thing would happen with documents the problem.

Well in question some projects that needed control classes in the link. create a plugin hallo.js hallowagtaillink taking just some basic controls "rel class title ... etc" as the old wysiwyg simply can not be added ..

Although the short time I made some changes to make this possible I think is not the most elegant solution .. but it works for now .. I hope in a few days you can add a more elegant solution but for now this is what did

An apology for the extra code but the code editor just did

rick_text.patch

```
Index: wagtail/wagtailcore/rich_text.py
<+>UTF-8
===================================================================
--- wagtail/wagtailcore/rich_text.py    (revision )
+++ wagtail/wagtailcore/rich_text.py    (revision )
@@ -29,6 +29,7 @@
     representation will be:
     <embed embedtype="image" id="42" format="thumb" alt="some custom alt text">
     """
+
     @staticmethod
     def get_db_attributes(tag):
         """
@@ -72,6 +73,7 @@
     representation will be:
     <embed embedtype="media" url="http://vimeo.com/XXXXX">
     """
+
     @staticmethod
     def get_db_attributes(tag):
         """
@@ -90,6 +92,7 @@
         representation.
         """
         from wagtail.wagtailembeds import format
+
         if for_editor:
             return format.embed_to_editor_html(attrs['url'])
         else:
@@ -103,6 +106,7 @@
     representation will be:
     <a linktype="page" id="42">hello world</a>
     """
+
     @staticmethod
     def get_db_attributes(tag):
         """
@@ -122,6 +126,12 @@
             else:
                 editor_attrs = ''

+            #adding other attributes
+            #Not add ID or linktype
+            for attr, value in attrs.iteritems():
+                if attr not in ['id','linktype']:
+                    editor_attrs += ' %s="%s" ' % (attr, value)
+
             return '<a %shref="%s">' % (editor_attrs, escape(page.url))
         except Page.DoesNotExist:
             return "<a>"
@@ -205,8 +215,15 @@
             link_handler = LINK_HANDLERS[link_type]
             link_attrs = link_handler.get_db_attributes(tag)
             link_attrs['linktype'] = link_type
+
+            if 'href' in tag.attrs:
+                del tag.attrs['href']
+                super(DbWhitelister, cls).clean_tag_node(doc, tag)
+                attrs = tag.attrs.copy()
+
             tag.attrs.clear()
             tag.attrs.update(**link_attrs)
+            tag.attrs.update(**attrs)
         elif tag.name == 'div':
             tag.name = 'p'
         else:
@@ -233,6 +250,7 @@
     Expand database-representation HTML into proper HTML usable in either
     templates or the rich text editor
     """
+
     def replace_a_tag(m):
         attrs = extract_attrs(m.group(1))
         if 'linktype' not in attrs:
```

**Comment by jordij** [comment] 2015-01-09 02:11
Hi there,

I was actually implementing the same feature as a hallo plugin and ended up realising the "class" attribute isn't being saved for <a> elements.

Would you guys contemplate to use the whitelist engine to allow extra attributes to link elements inside the richtext editor? 

Cheers

**Comment by gasman** [comment] 2015-01-28 11:02
Hi @warhotdog - thanks for the report. I see that the [documentation for `construct_whitelister_element_rules`](http://docs.wagtail.io/en/latest/core_components/pages/editing_api.html#construct-whitelister-element-rules) uses the 'a' element as an example, so it would be good to make sure our example actually works...

This would be quite a low-priority bug for us, as we would prefer to avoid custom HTML whitelisting wherever possible; the rich text field is only intended for simple text formatting, not to be a general-purpose HTML authoring tool. I can't imagine any valid reason for placing `class` attributes on links within rich text (although I'm willing to be persuaded!) - I think it would be mostly used for styling, and I definitely want to keep style information out of article content.

However, I would be willing to consider a pull request to fix support for the 'a' element in `construct_whitelister_element_rules`, provided it includes unit tests and does not permit arbitrary attributes (e.g. it must not allow `<a href="http://example.com/" onclick="runScript()">`).

**Comment by warhotdog** [comment] 2015-01-28 19:05
Hi Gasman.
Maybe I not explain very well but the white list for items that contain "data-linktype" is not executed. Actually this is a bit problematic for me because "some designers smoking something very strong": P usually put colors in the content and especially the links, If you touch it 1 color if providers to contact another color. although in this case was for a simple lightbox not all information should be shown to whole page otherwise in lightbox. to some extent could be solved with css but not in all cases this applies.

In theory if not in the whitelist should not be allowed to put attributes outside the permitted but anyway. Makes unit tests. and perhaps a slightly more elegant solution.

**Comment by jordij** [comment] 2015-01-28 21:34
Hi guys, sorry for the meddling. I think what we're asking here is to be able to define and run a whitelist against the <a> elements with attribute data-linktype appearing in a richtext field. Because as @warhotdog points, this is not happening right now.

Personally @gasman , I'd like to be able to add a "class" attribute to those elements, just to style them as "buttons" but still being simple links. I don't want to do that for all <a> elements in an article, so that would be handy way to choose which ones do I want to style and which ones I don't want.

Hopefully I'm making some sense. Thanks!

**Comment by gasman** [comment] 2015-02-02 13:31
@jordij: I don't know the details of your site, so I don't know what you're using these buttons for... maybe it's page furniture, maybe it's for linking between sections of a page. However, I'm going to guess that you're not placing these buttons in the middle of a paragraph of text. :-)

This is what I mean about over-using RichTextField... it's only really intended for formatting paragraphs of text. If you find yourself needing the RichTextField field for other things - things that need special design elements - then that probably means that Wagtail is failing to provide the right tools for the job, and I would rather concentrate on providing those (such as StreamField: #823) rather than trying to make RichTextField handle every possible situation.

Anyway, I'm going off-topic a bit... I accept that there's a bug in the whitelist behaviour here, and this should be fixed regardless of any other 'political' views I have :-)

**Comment by jordij** [comment] 2015-02-03 03:41
@gasman I totally understand what you're saying. It's just that right now I'm "over-using" the RichTextField to add more contents than paragraphs of text :-) But I'm more than ok waiting for the StreamField, it looks very very promising. Thanks!

**Comment by kave** [comment] 2016-03-17 15:07
@gasman Is there an update on when this will be taken care off?

**Comment by gasman** [comment] 2016-03-18 17:38
@kave Not curently, no. Patches welcome!

**Comment by NathanQ** [comment] 2017-11-16 23:13
Looks like an old issue, like @warhotdog, we'd like to add a class to an `a` tag and also add an `id` to a heading. But the construct_whitelister_element_rules doesn't look like it's called. How do we do that? The insert_editor_js and insert_editor_css are called and functions per the docs and are usable. Also, tested images just to see what happens and nothing changes.

```
from django.conf import settings
from django.utils.html import format_html, format_html_join
from wagtail.wagtailcore import hooks
from wagtail.wagtailcore.whitelist import attribute_rule, check_url, allow_without_attributes


@hooks.register('construct_whitelister_element_rules')
def whitelister_element_rules():
    return {
        'a': attribute_rule({
            'href': check_url,
            'target': True,
            'class': True
         }),
        'img': attribute_rule({
            'src': False,
            'width': False,
            'height': False,
            'alt': False
         }),
        'h1': attribute_rule({
            'id': True
        }),
        'h2': attribute_rule({
            'id': True
        }),
        'div': attribute_rule({
            'class': True
        })
    }

hooks.register('insert_editor_js')
def editor_js():
    js_files = [
        'js/hallo_button_plugin.js',
    ]
    js_includes = format_html_join('\n', '<script src="{0}{1}"></script>',
        ((settings.STATIC_URL, filename) for filename in js_files)
    )

    return js_includes + format_html(
        """
        <script>
            registerHalloPlugin('hallowagtailbutton');
        </script>
        """
    )

hooks.register('insert_editor_css')
def editor_css():
    return format_html('<link rel="stylesheet" href="'+ settings.STATIC_URL + 'css/font-awesome.min.css">')

```

## html as set by plugins:
A tag has classes set as intended and image has a bunch of stuff to get whitelisted/stripped.
```
<a data-linktype="page" data-id="3" data-parent-id="1" href="/" data-original-title="" title="" class="btn btn-primary">button</a>
<img data-embedtype="image" data-id="11" data-format="left" data-alt="phonez" class="richtext-image left" src="/media/images/phonez.width-500.jpg" width="500" height="468" alt="phonez">

```
## html after page save:
A tag has intended items stripped and image remains the same because the above whitelisting rules are ignored.
```
<a data-linktype="page" data-id="3" data-parent-id="1" href="/">button</a>
<img data-embedtype="image" data-id="11" data-format="left" data-alt="phonez" class="richtext-image left" src="/media/images/phonez.width-500.jpg" width="500" height="468" alt="phonez">
```

How do we go about utilizing the whitelist?

Thanks a lot!

**Comment by gasman** [comment] 2017-11-17 23:42
Rich text is not an HTML authoring tool. It's a tool for writing structured formatted text, somewhat like Markdown (but with an interface that's friendlier for people who are used to writing in Word). If you try to use it as an HTML authoring tool, you'll be painting yourself into a corner - especially with Wagtail 2.0, which will change the default rich text editor to one which natively uses a non-HTML data format. (https://draftjs-exporter.herokuapp.com/)

I realise it probably looks like we're putting up arbitrary roadblocks to using it as a general HTML editor, and that it ought to be possible with the right set of plugin hacks - but giving direct control over the HTML markup just isn't compatible with the principles of content management that Wagtail promotes (such as providing better editing controls, create-once-publish-everywhere, and more mundane details like ensuring text is consistently wrapped in `<p>` tags and pasting from Word doesn't turn everything into Times New Roman). To make that work, we need to handle text content at a higher level of abstraction away from HTML - for Wagtail 1.x, that means using a subset of HTML that strictly represents text semantics, not design elements; and for Wagtail 2.x, it means representing it in terms of blocks and inline entities, as Draftail / draft.js does.

@NathanQ, I'm 99% certain that rich text isn't the right tool for what you're trying to do. (See the notes on separation of roles at http://docs.wagtail.io/en/v1.13.1/getting_started/the_zen_of_wagtail.html#always-wear-the-right-hat - positioning buttons on a webpage is not the task of a content author.) Most likely, your buttons are navigation (which would be better served by a dynamic query or something like [wagtailmenus](http://wagtailmenus.readthedocs.io/en/stable/)) or a call-to-action element (which would be better implemented as something like a snippet or StreamField block, where the text and link destination are distinct data fields and the button markup is defined as part of the template).

If you do believe putting buttons into rich text makes sense for your use case, then I think that can be done by registering 'button' as a new `data-linktype` and defining the different representations it has within the editor, in the database, and as rendered on the front-end. See [the definition of `PageLinkHandler`](https://github.com/wagtail/wagtail/blob/392cd210147be701dd83b03f538d9ce21a4e9457/wagtail/wagtailcore/rich_text.py#L20-L51) (which sets up the behaviour of the standard linktype="page"), and the way the wagtaildocs module [uses the `register_rich_text_link_handler` hook](https://github.com/wagtail/wagtail/blob/392cd210147be701dd83b03f538d9ce21a4e9457/wagtail/wagtaildocs/wagtail_hooks.py#L88-L90) to register a similar one for documents. (However, bear in mind that this is currently an internal undocumented hook, and may well change in Wagtail 2.0.) By going down this route, you're working _with_ Wagtail's link-rewriting model, rather than employing hacks to bypass it.

**Comment by gasman** [comment] 2017-11-19 20:13
When this ticket originally came up, I think I missed the detail that this was specifically happening for links elements with a `linktype` defined. That changes the picture quite a bit, and in this case I think it counts as a 'wontfix'.

When you set up a whitelist rule, what you're implicitly saying is "Add this element to the data model understood by rich text fields, and when converting it between the database representation and the editor, or from the database representation to front-end HTML, pass it through with no modifications". In the case of links with a `linktype`, this doesn't make sense because modifying the HTML is already part of the deal - there's a special-case rule in place to deal with converting IDs to `href`s, which takes precedence over any instruction to "leave this unmodified".

The good news is that as part of the rewrites to rich text coming in Wagtail 2.0 (#2409, #3852), we'll be codifying some of these currently-undocumented APIs dealing with converting elements between editor/database/front-end representations, so there'll be a properly supported way to customise these rules, beyond the basic "leave this element unmodified" rule.

**Closed by gasman** 2017-11-19 20:13 UTC
Labels: component:Rich text, type:Bug

**Comment by NathanQ** [comment] 2017-11-20 15:38
@gasman Thank you so much for your candor and the note regarding abstraction level in regards to linktype. Light bulb: On. Much appreciated!
