### ISSUE TITLE
get_site_root_paths is not respecting the current default site

### ISSUE THREAD

**Issue by kakulukia** [wagtail/wagtail#3691] opened 2017-07-05 09:36 UTC
and thus it results in the wrong site (base url) being used although we have a defined default page.
Its even getting more weird, because the last saved site will be used instead of the defined default.

The function should query all sites the following way:

    Site.objects.select_related('root_page').order_by('-is_default_site', '-root_page__url_path')

**Comment by gasman** [comment] 2017-07-05 09:46
Hi @kakulukia,
You seem to have jumped straight to the diagnosis without explaining what the problem is :-) Please can you give specific steps to reproduce the bug you're seeing?

**Comment by kakulukia** [comment] 2017-07-05 10:07
Hehe .. we have multiple sites setup referring to the same root page because of staging and production systems having the "same" database. So when syncing the production database to the stage DB the system hast to respect the other default page. The problem is that its not respecting the current default page but instead takes the last saved one.

**Comment by kakulukia** [comment] 2017-07-05 10:15
Its easily adjustable by just saving the right site last, but saving any other site after that will cause a lot of trouble. :)

BTW: we are using Page.url which is giving us the wrong url in this case

**Comment by gasman** [comment] 2017-07-05 13:36
Thanks for the clarification!

Having two Site records pointing to the same page is not a well-defined setup, because it means there are two possible URLs for a given page. Giving priority to the default site would be a possible way of resolving this, but:

1) that's not what the 'default' flag was designed for (it only means "use this site to handle any requests to hostnames which aren't recognised")
2) it doesn't solve the general problem, because we can still have two non-default sites pointing to the same place.

Please see #1282 and #1283 for previous discussion about the "correct" behaviour for two sites with the same root page - it's still an open question.

**Closed by gasman** 2017-07-05 13:36 UTC
Labels: status:Needs info
