### ISSUE TITLE
Easy way to generate responsive image sets

### ISSUE THREAD

**Issue by overshard** [wagtail/wagtail#3573] opened 2017-04-28 18:05 UTC
Right now we only generate a single image when calling {% image %}. It would be cool if we could inform the image tag to generate a responsive set of images.

![webflow1](https://cloud.githubusercontent.com/assets/7016/25541121/80f75372-2c1b-11e7-9ae6-467b48d5ed24.png)

See https://blog.ycombinator.com/how-to-use-responsive-images/ for more information.

Was just reminded of this today via this article though it's something I've wanted to automate better via a template tag for a while.

**Comment by jeffreyckchau** [comment] 2017-06-05 20:56
hi @overshard, this might be of use to you. it was written for an outdated version of wagtail but the concept is the same: https://gist.github.com/davecranwell/baf42b089d71b94fd229

**Comment by overshard** [comment] 2017-06-06 14:49
@jeffreyckchau It looks like there is fork of that plugin that fixes it for the latest wagtail: https://gist.github.com/coredumperror/41f9f8fe511ac4e88547487d6d43c69b

Definitely something that should be native in wagtail or referenced in the docs somehow.

**Comment by gasman** [comment] 2017-06-28 10:12
Related: #285 
(Has there been any consensus in the web community yet over `<picture>` vs `srcset`...?)

**Comment by zerolab** [comment] 2017-06-28 13:02
As far as I can tell, `<img srcset="" />` is used for "simple" responsive image. `<picture>` is for a more of an art direction approach.

Why can't Wagtail support both? Start with `srcset` then expand to picture?

**Comment by BertrandBordage** [comment] 2017-08-31 01:20
This is a duplicate of #285.

**Comment by lb-** [comment] 2017-11-24 10:57
Closing as this discussion can continue on #285

**Comment by lb-** [comment] 2017-11-24 10:57
Closing as this discussion can continue on #285

**Closed by lb-** 2017-11-24 10:57 UTC
