### ISSUE TITLE
Edit view redirects to live preview panel URL

### ISSUE THREAD

**Issue by jlnugteren** [wagtail/wagtail#10251] opened 2023-03-20 20:51 UTC
### Issue Summary

Hello, I'm upgrading from wagtail 2.15 to 4.1 and have encountered an issue after doing all of the recommended upgrades. When going to the "edit" page of any page, I instantly get redirected to the preview panel's url rather than staying in the edit window. For example:

/admin/pages/3/edit/

gets redirected instantly to

/admin/pages/3/edit/preview/?in_preview_panel=true&mode=

### Technical details

-   Python version: Run 3.8.12.
-   Django version: 3.2.17.
-   Wagtail version: 4.1.
-   Browser version: Any.

**Comment by laymonage** [comment] 2023-03-21 05:58
Hello, could you please provide more details to your setup? For example, what third party packages you have installed, and whether you have any customisations applied to the page edit view.

Also, how did you upgrade to 4.1, did you do it from 2.15 straight to 4.1? We recommend upgrading incrementally, e.g. from 2.15 to 2.16, then to 3.0, 4.0, and finally 4.1. This helps identify the root cause of any issues.

I cannot replicate your issue on a fresh Wagtail project or the bakerydemo, so I'm flagging this as needs info.

**Comment by jlnugteren** [comment] 2023-03-21 12:55
Hello, thanks for helping me out. I did the changes incrementally like you said, and this issue didn't appear until Wagtail 4.1 in my environment. I don't think I have any customizations to the Page Edit view as well. Here is a list of other packages I also have installed:

psycopg2-binary==2.8.6
gunicorn==19.7.1
elasticsearch==7.16
django-compressor==3.1
django-libsass==0.9
django-redis==5.2.0
mistune==0.8.4
wand==0.6.7
coverage==4.5.1
mock==2.0.0
python-dateutil==2.8.2
markdown==3.0.1
bleach==3.1.3
Pygments==2.7.4
lxml==4.3.1
pylint==2.11.1
wagtail-django-recaptcha==1.0

**Comment by jlnugteren** [comment] 2023-03-21 13:13
I just noticed I haven't gotten to 4.1 yet, my apologies. I am running the latest version of Wagtail 4.0.

**Comment by thibaudcolas** [comment] 2023-03-21 22:33
Hi @jlnugteren, thanks for reporting. We currently no longer support Wagtail 4.0 so I’d recommend upgrading to 4.1 (LTS) when possible. I can’t reproduce this either when testing on our demo site in v4.0.4, so I suspect there is something specific to your site causing this, or a browser extension, or perhaps outdated static files causing issues as you’ve upgraded.

You mention a redirect, is that an HTTP 301/302, or something happening in the browser in JS when the page loads? This preview panel only shows in an iframe, I can’t see what browser behavior would force it onto the parent window but I guess it’s worth double checking where the redirect comes from.

**Comment by jlnugteren** [comment] 2023-03-23 12:58
I was on my way to 4.1 when this issue occurred. I'll try to test 4.1 then and see if any issues are fixed.

**Comment by jlnugteren** [comment] 2023-03-23 20:49
Wagtail 4.1 didn't work either. I'm still seeing the same issue I had before. Is there anything you recommend I look for in my files that might be changing the behavior of Wagtail?

**Comment by laymonage** [comment] 2023-03-23 22:05
Are you using any browser extensions? Try using an incognito/InPrivate mode which disables all extensions by default (and if you have explicitly enable an extension to run in incognito, disable it).

**Comment by jlnugteren** [comment] 2023-03-27 12:58
I am currently not using any browser extensions at all.

**Comment by laymonage** [comment] 2023-03-27 13:04
Have you added `<base target="_blank">` to your `base.html` template as per the [recommendation in the release notes](https://docs.wagtail.org/en/stable/releases/4.0.html#opening-links-within-the-live-preview-panel)?

**Comment by lb-** [comment] 2023-03-27 13:05
@jlnugteren we will need some more help here to confirm this issue, I've not been able to reproduce this and it seems very odd. 

Could you please see if the issue happens on your machine with a brand new Wagtail project?

Also, can you add a recording of the problem and maybe even export the browser HAR file. Please update the issue description with the exact browser and os you are using (exact versions).

**Comment by jlnugteren** [comment] 2023-03-27 15:27
I do notice this when I stop the page from finishing loading. 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/78452633/227987797-50c64683-0d3c-4f1c-8e12-25b4786b0437.png">

**Comment by laymonage** [comment] 2023-03-27 15:34
The loading spinner is still there, so I think it's to be expected because the preview data has not been populated on the server.

**Comment by jlnugteren** [comment] 2023-03-27 18:38
I made a new instance and it seemed to not have any issues. I feel like it's something else I have added.

**Comment by jlnugteren** [comment] 2023-03-28 19:36
I finally found the problem. I had some javascript int my base template that checks for clickjacking and moves the window to the parent window.

**Comment by lb-** [comment] 2023-03-28 20:11
Thanks @jlnugteren I'll close this issue for now. 
If possible - please add another comment with any more info about this for future people searching. Such as how you stopped the issue and what library (JS) was causing the problem.

**Closed by lb-** 2023-03-28 20:11 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed

**Comment by jlnugteren** [comment] 2023-03-28 21:08
I just had some homemade javascript in my base template to prevent clickjacking. This was the following code in my base template that I removed: 

<style id="antiClickjack">
                body{display:none !important;}
            </style>
            <script type="text/javascript">
                if (self === top) {
                    var antiClickjack = document.getElementById("antiClickjack");
                    antiClickjack.parentNode.removeChild(antiClickjack);
                } else {
                    top.location = self.location;
                }
            </script>

This was useful a couple of years ago during one of the updates to prevent clickjacking. Now though, you can add the nginx header X-Frame-Options SAMEORIGIN and it should do the same thing. This fixed the issue I was seeing where the iframe url got inserted into the parent page's url.

**Comment by lb-** [comment] 2023-03-28 22:17
No problems thanks. For future reference you can vary the template output for preview or live also. 
https://docs.wagtail.org/en/stable/topics/writing_templates.html#varying-output-between-preview-and-live
