### ISSUE TITLE
Saving an empty rich text field sometimes saves <p><br/></p>

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#4046] opened 2017-11-19 10:23 UTC
### Issue Summary

When entering a single character in an empty a richtext field and then wiping it straight away with backspace before saving, it can end up saving `<p><br/></p>.`

### Steps to Reproduce

If I have a model with the following field:

    intro = RichTextField(blank=True)

If the user types a single character in this field and hits the backspace to erase it again, then save, what is actually saves is this:

    <p><br/></p>

I expect it to save nothing instead, e.g. a blank string.

I can still edit the field again after the save and hit backspace again and then save it, it's fine the second time around.  But it should have not saved `<p><br/></p>` first time around I think.

### Technical details

* Python version: 3.5
* Django version: 1.11.7
* Wagtail version: 1.13.1
* Browser version: Chrome 62 on Linux

**Comment by lb-** [comment] 2017-11-19 10:30
@robvdl thank you for submitting this issue.

The current text editor has some confusing behaviour with paragraph tags, some of the reason for this is to ensure we can accept pasting from external sources like Microsoft Word, but this causes issues eg. #3111 

This editor is in the progress of being deprecated, and a new one called Draftail is planned for the next major release - see #2409

**Comment by gasman** [comment] 2017-11-19 20:18
Closing as a duplicate of #3111.

**Closed by gasman** 2017-11-19 20:18 UTC
Labels: component:Rich text
