### ISSUE TITLE
Browser field validation breaks save button

### ISSUE THREAD

**Issue by ghostwords** [wagtail/wagtail#2425] opened 2016-03-31 13:34 UTC
URL input fields temporarily break the save button when their browser-supplied validation fails. The selected button action gets stuck in its unclickable spinner phase. You can wait for that to time out, but the timeout takes a while. Here is what this looks like in Chrome with Wagtail 1.4.1:

![screenshot from 2016-03-31 09 27 05](https://cloud.githubusercontent.com/assets/794578/14177137/e53c4f38-f722-11e5-811b-291f49a62c4e.png)

Related, kind of: #1230

**Comment by gasman** [comment] 2016-04-28 13:45
Also related: #2007

@kapito is currently working on tying up the loose end on that ticket - adding a `cancelSpinner` function to call if the validation fails. It seems like we ought to be able to do the same thing here, but since the validation here is browser-supplied, it relies on the browser firing some sort of "I've just blocked the form submission" event that we can attach the code to. Need to check if such a thing exists...

**Comment by thibaudcolas** [comment] 2022-08-01 09:56
I believe this has been fixed in #2942 – can’t reproduce with a URLField at least!

**Closed by thibaudcolas** 2022-08-01 09:56 UTC
Labels: component:Frontend
