### ISSUE TITLE
Boolean fields in snippet model render with labels behind checkbox

### ISSUE THREAD

**Issue by DanielSwain** [wagtail/wagtail#4386] opened 2018-03-15 18:42 UTC
### Technical details

* Python version: 2.7.12
* Django version: 1.11.11.
* Wagtail version: 1.13.1
* Browser version: Chrome 64

### Issue Summary
Boolean fields on a snippet model that are rendered in a FieldRowPanel have their label directly behind the checkbox:
![image](https://user-images.githubusercontent.com/7819909/37483892-5b1eb3ea-285d-11e8-9005-c27c3bd2bd25.png)

**Also note** that the order of the rendered boolean fields is incorrect - it does not match either the order that the fields are declared on the model or the order that the fields are listed in the FieldRowPanel.

### Steps to Reproduce

After creating a site in Settings, in models.py do:
`from wagtail.wagtailcore.models import Site`

and then create the following snippet model to see the above rendering in the Wagtail Admin:

```
@register_snippet
@python_2_unicode_compatible
class SiteInfo(models.Model):
    site = models.OneToOneField(Site, null=True, on_delete=models.SET_NULL)
    logo = models.OneToOneField(Image, null=True, blank=True, on_delete=models.SET_NULL, related_name='+')
    business_name = models.CharField(max_length=150, default='', help_text='Full business name including type such as LLC, Inc., etc.')
    address1 = models.CharField(max_length=255, null=True, blank=True)
    address2 = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=75, null=True, blank=True)
    state = models.CharField(max_length=75, null=True, blank=True)
    postal_code = models.CharField(max_length=25, null=True, blank=True)
    email = models.CharField(max_length=150, null=True, blank=True)
    phone_primary_number = models.CharField(max_length=15, null=True, blank=True, verbose_name='Primary Phone Number')
    phone_primary_label = models.CharField(max_length=25, null=True, blank=True, verbose_name='Label', help_text="'Phone', 'Mobile', 'Fax', etc.")
    phone_other_1_number = models.CharField(max_length=15, null=True, blank=True, verbose_name='Other Number 1')
    phone_other_1_label = models.CharField(max_length=25, null=True, blank=True, verbose_name='Label', help_text="'Phone', 'Mobile', 'Fax', etc.")
    phone_other_2_number = models.CharField(max_length=15, null=True, blank=True, verbose_name='Other Number 2')
    phone_other_2_label = models.CharField(max_length=25, null=True, blank=True, verbose_name='Label', help_text="'Phone', 'Mobile', 'Fax', etc.")
    business_hours = RichTextField(max_length=500, default='', blank=True, features=['bold', 'italic'])
    social_facebook = models.BooleanField(default=False, verbose_name="Facebook")
    social_twitter = models.BooleanField(default=False, verbose_name="Twitter")
    social_pinterest = models.BooleanField(default=False, verbose_name="Pinterest")
    social_instagram = models.BooleanField(default=False, verbose_name="Instagram")
    social_google_plus = models.BooleanField(default=False, verbose_name="Google Plus")
    social_linkedin = models.BooleanField(default=False, verbose_name="LinkedIn")
    social_youtube = models.BooleanField(default=False, verbose_name="YouTube")
    social_vimeo = models.BooleanField(default=False, verbose_name="Vimeo")
    social_skype = models.BooleanField(default=False, verbose_name="Skype")
    social_dribbble = models.BooleanField(default=False, verbose_name="Dribbble")
    miscellaneous =  RichTextField(max_length=1000, default='', blank=True, features=['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed'])

    panels = [
        FieldPanel('site'),
        ImageChooserPanel('logo'),
        FieldPanel('business_name'),
        MultiFieldPanel([
            FieldPanel('address1'),
            FieldPanel('address2'),
            FieldPanel('city'),
            FieldPanel('state'),
            FieldPanel('postal_code'),
        ], 'Location Information'),
        FieldRowPanel([
            FieldPanel('phone_primary_number'),
            FieldPanel('phone_primary_label'),
        ]),
        FieldRowPanel([
            FieldPanel('phone_other_1_number'),
            FieldPanel('phone_other_1_label'),
        ]),
        FieldRowPanel([
            FieldPanel('phone_other_2_number'),
            FieldPanel('phone_other_2_label'),
        ]),
        FieldPanel('email'),
        FieldPanel('business_hours'),
        FieldRowPanel({
            FieldPanel('social_facebook'),
            FieldPanel('social_twitter'),
            FieldPanel('social_pinterest'),
            FieldPanel('social_instagram'),
            FieldPanel('social_google_plus'),
            FieldPanel('social_linkedin'),
            FieldPanel('social_youtube'),
            FieldPanel('social_vimeo'),
            FieldPanel('social_skype'),
            FieldPanel('social_dribbble'),
        }),
        FieldPanel('miscellaneous')
    ]

    class Meta:
        verbose_name_plural = "Site Information"

    def __str__(self):
        return 'Site Name:  {}    Business Name:  {}'.format(self.site, self.business_name)
```

**Comment by lucasmoeskops** [comment] 2018-03-16 08:45
One thing that occurs to me is that you are providing the FieldPanels to the FieldPanel as set instead of as list. Since a set is unordered, that will probably cause the ordering problem.

`FieldRowPanel([
            FieldPanel('social_facebook'),
            FieldPanel('social_twitter'),
            FieldPanel('social_pinterest'),
            FieldPanel('social_instagram'),
            FieldPanel('social_google_plus'),
            FieldPanel('social_linkedin'),
            FieldPanel('social_youtube'),
            FieldPanel('social_vimeo'),
            FieldPanel('social_skype'),
            FieldPanel('social_dribbble'),
        ]),`

**Comment by thibaudcolas** [comment] 2018-03-16 09:28
This looks a lot like #3522.

**Comment by lb-** [comment] 2022-03-21 09:38
Would be good to get an update if this can still be reproduced after Wagtail 2.4.
Flagging as bug but unconfirmed

**Comment by thibaudcolas** [comment] 2022-08-16 12:28
This has been fixed in Wagtail 4, where Boolean fields render with the label above the widget:

<img width="953" alt="boolean-field-row" src="https://user-images.githubusercontent.com/877585/184879376-4d6f80c3-5fc6-4ae7-82dc-7d10353ee62b.png">

I don’t think there is anything specific to boolean fields about the order so this could just be the set vs. list issue mentioned by Lucas.

**Closed by thibaudcolas** 2022-08-16 12:28 UTC
Labels: type:Bug, component:Snippets, status:Unconfirmed
