### ISSUE TITLE
ModelAdmin inspect view field labels do not use short_description when the field is a method of the ModelAdmin subclass

### ISSUE THREAD

**Issue by bcdickinson** [wagtail/wagtail#10316] opened 2023-04-05 19:13 UTC
### Issue Summary

When using Wagtail's `ModelAdmin` class, fields in the inspect view that are methods of a `ModelAdmin` subclass do not take their label from the methods' `short_description` attribute. This is inconsistent with the list/index view.

### Steps to Reproduce

When using something like the following `ModelAdmin` subclass (with a method field that has a `short_description` attribute)...

```python
class MyModelAdmin(ModelAdmin):
    model = MyModel
    inspect_view_enabled = True
    inspect_view_fields = ['my_method']

    def my_method(self, obj):
        return obj.some_field

    my_method.short_description = "My Method Label"
```

Expected behaviour: The label for the `my_method` field is "My Method Label"

Actual behaviour: The label is "method"

### Technical details

-   Python version: 3.10
-   Django version: 3.2
-   Wagtail version: 4.1.3

**Comment by lb-** [comment] 2023-04-05 20:58
@bcdickinson I cannot reproduce with the steps you described, from what I can see in the docs the way you are doing this is not correct.

The `inspect_view_fields` -> https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/inspectview.html#modeladmin-inspect-view-fields
> Expected value: A list or tuple, where each item is the name of a field or attribute on the instance that you’d like InspectView to render.

Then if you look at how the general field list display works, the custom method should be on the model class, not the `ModelAdmin` class. 
https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/indexview.html#modeladmin-list-display

So, if I do the following;

```python
class BreadIngredientAdmin(ModelAdmin):
    model = BreadIngredient
    search_fields = ("name",)
    list_display = ('my_method', 'name',)

    inspect_view_enabled = True
    inspect_view_fields = ('my_method', 'name',)
```

```python
@register_snippet
class BreadIngredient(DraftStateMixin, RevisionMixin, models.Model):
    name = models.CharField(max_length=255)

    panels = [FieldPanel("name"),]

    def my_method(self):
        print('my method???')
        return f"Foo {self.name}"

    my_method.short_description = "My Method Label"

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Bread ingredients"
```

I correctly get the short_description label in the inspect view.

<img width="905" alt="Screenshot 2023-04-06 at 6 57 30 am" src="https://user-images.githubusercontent.com/1396140/230209847-f3c2cb71-7dd6-47e3-ab57-3b590702a44d.png">


I will close this for now, but please let us know if there are some other steps to reproduce the problem maybe. I am also surprised the code you provided worked at all, it simply gave an error for me.

**Closed by lb-** 2023-04-05 20:58 UTC
Labels: type:Bug, status:Unconfirmed
