### ISSUE TITLE
Tell editors when a snippet is 'used' more than once.

### ISSUE THREAD

**Issue by tmsndrs** [wagtail/wagtail#4169] opened 2018-01-04 09:24 UTC
As an editor I want to know if a snippet has been referenced more than once so that I don't mistakenly change content I don't intend to. 

I know some work was done on this at the Bristol sprint (maybe more around images?) but it would be great implement.

**Comment by zerolab** [comment] 2018-01-04 09:45
#3961 is the first step for this.
Worth pitching in for https://github.com/wagtail/wagtail/pull/3961#issuecomment-351602697 (point 1), https://github.com/wagtail/wagtail/pull/3961#issuecomment-351689851

**Comment by tmsndrs** [comment] 2018-01-04 09:59
Thanks @zerolab

**Comment by gasman** [comment] 2018-01-04 10:11
Closing as a duplicate of #3961

**Closed by gasman** 2018-01-04 10:11 UTC
Labels: status:Needs UI design, type:Enhancement
