### ISSUE TITLE
Collapsible structblocks inside streamfield?

### ISSUE THREAD

**Issue by MechanisM** [wagtail/wagtail#1532] opened 2015-07-20 06:39 UTC
I think that it would be nice if already filled structblocks inside streamfield on editing were collapsed/collapsible, just like field collections(it's so hard to scroll a lot a lot of structblocks, especially if they consist of some ListBocks). And when there's a lot of already filled structblocks and you editing content, it's hard to realise which structblock is it, only on hover I can see on top-right corner some info. I think would be good to have smth like icon of this block on top-left corner. Or maybe some bolder borders(dotted) to better realise where's the edges of blocks.

**Comment by davecranwell** [comment] 2015-07-20 08:13
Thanks @MechanisM, good points. 

Our vision for streamfield has so far been more like google docs, where you don't see any boundary between a paragraph, and an image, and another paragraph, but people don't seem to be appreciating that in practice. We'll certainly consider this further.

**Comment by MechanisM** [comment] 2015-07-20 08:25
I got it! Btw, google docs' approach looks nice, coz they're using smth like contenteditable(not sure, need to take a look) and I don't see any fields and/or textareas - all content looks okay and I don't look at it like some separate parts(blocks). Wagtail's streamfield shows me a lot of fields and textareas and choosers and it's a mess. It's not so easy to recognise which block you currently scrolling. Wagtail makes me think that these blocks are separate, while google docs makes me think about content and not separate parts of it in mind - like it's just single rich text block and not a few blocks combined together one by one.

**Comment by BertrandBordage** [comment] 2018-04-16 14:49
As part of the Wagtail’s first Kickstarter campaign, I’m working on this!
https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch

**Comment by gasman** [comment] 2019-08-23 15:01
Closing as duplicate of #1336.

**Closed by gasman** 2019-08-23 15:01 UTC
Labels: component:Streamfield
