### ISSUE TITLE
TableBlock is support merge cells？

### ISSUE THREAD

**Issue by bright-pan** [wagtail/wagtail#2846] opened 2016-07-16 06:04 UTC
HI，@alexgleason 

i use the feature for my project, but i can not merge cells.

how can i fix it?

**Comment by Proper-Job** [comment] 2016-07-18 06:54
@bright-pan What do you mean, merge cells?  Do you mean [colspan](http://www.w3schools.com/tags/att_td_colspan.asp)?

**Comment by bright-pan** [comment] 2016-07-19 01:39
@Proper-Job yes， i have not better way to support colspan in TableBlock.

**Comment by kunambi** [comment] 2017-04-06 03:02
Please add support for rowspan, if possible

**Comment by gasman** [comment] 2020-06-16 16:04
Closing this as a duplicate of #5503 (which provides some additional detail).

**Closed by gasman** 2020-06-16 16:04 UTC
Labels: component:Streamfield, type:Enhancement
