### ISSUE TITLE
PageChooserBlock dialog search functionality is broken?

### ISSUE THREAD

**Issue by paul-apacio** [wagtail/wagtail#3609] opened 2017-05-24 10:46 UTC
### Issue Summary

When using the PageChooserBlock dialog in the CMS, and using it's search functionality, I get a very broken modal window.  it almost seems that some page content from elsewhere on the site is being embedded, which is turn breaks modal.

### Steps to Reproduce

1. Open a Page Chooser element somewhere in the CMS
2. Type text into the search bar in this modal
3. Observe scrambled display

Here is an example screenshot: http://imgur.com/a/WI4z7

### Technical details

* Python version: 2.7.13
* Django version: 1.10.7
* Wagtail version: 1.9.1
* Browser version: Chrome Latest

**Comment by gasman** [comment] 2017-05-24 11:05
Hi @paul-apacio - thanks for the report.

It looks like you've used a filename for one of your front-end templates which clashes with the ones used within Wagtail, although I'd only expect that to happen if you've placed them in a location with a Wagtail-specific name such as `templates/wagtailadmin/`.

Will close this for now as there's not enough information here for someone to independently replicate this issue - if you're able to reproduce it on a fresh Wagtail installation, please update here with full details and we'll be happy to investigate further.

**Closed by gasman** 2017-05-24 11:05 UTC

**Comment by paul-apacio** [comment] 2017-05-24 11:11
Thanks for the assistance.  We do override some templates, I wonder if possibly we have overridden some from a previous version and not updated them for a more recent version.  I'll post back my results for the record.

**Comment by paul-apacio** [comment] 2017-05-30 08:56
I have removed all of our wagtailadmin template overrides but have had no success fixing the issue.  I now suspect the seach functionality here is clashing with one of our react functions.
