### ISSUE TITLE
Option to run tests without running migrations

### ISSUE THREAD

**Issue by jeffreyckchau** [wagtail/wagtail#3323] opened 2017-02-01 22:15 UTC
In writing some features/extensions for Wagtail Admin, I've found it helpful to be able to test against custom test fixtures. The problem is, fixtures created with django's `manage.py dumpdata` command have conflicts with the initial data migrations in `0002_initial_data.py` in wagtailcore. 

Would it be possible to create a Wagtail specific configuration that would allow developers to specify tests to be run without running migrations? I say Wagtail specific as there appears to be some debate within the Django community as to whether allowing the option to disable migrations completely is valid for their timeline going forward (ref: [https://groups.google.com/forum/#!msg/django-developers/PWPj3etj3-U/kCl6pMsQYYoJ](url))

Some considerations:
1) Is it even possible to run some modules with one version of the database and others without? 
2) There are currently fixtures in the repo that work without disabling migrations (`test_explorable_pages.json`). What configuration makes these work when other fixtures created through django do not? 
3) If we give developers the ability to create custom test fixtures, extra caution would have to be taken to make sure redundant fixtures are not added to the repository. 

I would love to get your guys thoughts on this, for it would make developing tests for some features in our pipeline much easier. If this is something that we agree would be useful, I would be happy to start development on it as well.

**Comment by jeffreyckchau** [comment] 2017-02-01 22:16
Related issue to my original problem in #1937

**Comment by gasman** [comment] 2017-02-07 15:30
Hi @jeffreyckchau - I'd like to establish exactly what's failing with your fixture before we start looking for workarounds. Can you share a test fixture (and steps to reproduce) that demonstrates this issue, please?

**Comment by jeffreyckchau** [comment] 2017-02-13 19:28
Hi @gasman, here are my steps to reproduce.

On a fresh project created with `wagtail start test_project`, I run `./manage.py migrate`. 

Through the admin dashboard I create one child page, one user, and one group. I gave the group a page permission on the child page, group edit permissions, and admin access for the dashboard, and I added the user to that page.

I then dumped the fixture using `./manage.py dumpdata` as follows: 

```
[
  {
    "model": "wagtailcore.site",
    "pk": 2,
    "fields": {
      "hostname": "localhost",
      "port": 80,
      "site_name": null,
      "root_page": 3,
      "is_default_site": true
    }
  },
  {
    "model": "wagtailcore.collection",
    "pk": 1,
    "fields": {
      "path": "0001",
      "depth": 1,
      "numchild": 0,
      "name": "Root"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 1,
    "fields": {
      "app_label": "wagtailcore",
      "model": "page"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 2,
    "fields": {
      "app_label": "home",
      "model": "homepage"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 3,
    "fields": {
      "app_label": "wagtailadmin",
      "model": "admin"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 4,
    "fields": {
      "app_label": "wagtaildocs",
      "model": "document"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 5,
    "fields": {
      "app_label": "wagtailimages",
      "model": "image"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 6,
    "fields": {
      "app_label": "wagtailforms",
      "model": "formsubmission"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 7,
    "fields": {
      "app_label": "wagtailredirects",
      "model": "redirect"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 8,
    "fields": {
      "app_label": "wagtailembeds",
      "model": "embed"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 9,
    "fields": {
      "app_label": "wagtailusers",
      "model": "userprofile"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 10,
    "fields": {
      "app_label": "wagtailimages",
      "model": "filter"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 11,
    "fields": {
      "app_label": "wagtailimages",
      "model": "rendition"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 12,
    "fields": {
      "app_label": "wagtailsearch",
      "model": "query"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 13,
    "fields": {
      "app_label": "wagtailsearch",
      "model": "querydailyhits"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 14,
    "fields": {
      "app_label": "wagtailcore",
      "model": "site"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 15,
    "fields": {
      "app_label": "wagtailcore",
      "model": "pagerevision"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 16,
    "fields": {
      "app_label": "wagtailcore",
      "model": "grouppagepermission"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 17,
    "fields": {
      "app_label": "wagtailcore",
      "model": "pageviewrestriction"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 18,
    "fields": {
      "app_label": "wagtailcore",
      "model": "collection"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 19,
    "fields": {
      "app_label": "wagtailcore",
      "model": "groupcollectionpermission"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 20,
    "fields": {
      "app_label": "taggit",
      "model": "tag"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 21,
    "fields": {
      "app_label": "taggit",
      "model": "taggeditem"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 22,
    "fields": {
      "app_label": "admin",
      "model": "logentry"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 23,
    "fields": {
      "app_label": "auth",
      "model": "permission"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 24,
    "fields": {
      "app_label": "auth",
      "model": "group"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 25,
    "fields": {
      "app_label": "auth",
      "model": "user"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 26,
    "fields": {
      "app_label": "contenttypes",
      "model": "contenttype"
    }
  },
  {
    "model": "contenttypes.contenttype",
    "pk": 27,
    "fields": {
      "app_label": "sessions",
      "model": "session"
    }
  },
  {
    "model": "sessions.session",
    "pk": "4gmc46x1bhxpfag3zivpy1olvo97cc66",
    "fields": {
      "session_data": "MWMyM2QwMzU2OWMzZTE4Yjk2YTRhMzkwNjM2YTJhMDNhOTNjZmIxZTp7Il9hdXRoX3VzZXJfaGFzaCI6ImI4NGE5MjcyN2QwNjMzOWVhNzdhZGMyMjZlZGEyODY0MmNjNGRmMzgiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=",
      "expire_date": "2017-02-27T18:50:59.143Z"
    }
  },
  {
    "model": "auth.permission",
    "pk": 1,
    "fields": {
      "name": "Can access Wagtail admin",
      "content_type": 3,
      "codename": "access_admin"
    }
  },
  {
    "model": "auth.permission",
    "pk": 2,
    "fields": {
      "name": "Can add document",
      "content_type": 4,
      "codename": "add_document"
    }
  },
  {
    "model": "auth.permission",
    "pk": 3,
    "fields": {
      "name": "Can change document",
      "content_type": 4,
      "codename": "change_document"
    }
  },
  {
    "model": "auth.permission",
    "pk": 4,
    "fields": {
      "name": "Can delete document",
      "content_type": 4,
      "codename": "delete_document"
    }
  },
  {
    "model": "auth.permission",
    "pk": 5,
    "fields": {
      "name": "Can add image",
      "content_type": 5,
      "codename": "add_image"
    }
  },
  {
    "model": "auth.permission",
    "pk": 6,
    "fields": {
      "name": "Can change image",
      "content_type": 5,
      "codename": "change_image"
    }
  },
  {
    "model": "auth.permission",
    "pk": 7,
    "fields": {
      "name": "Can delete image",
      "content_type": 5,
      "codename": "delete_image"
    }
  },
  {
    "model": "auth.permission",
    "pk": 8,
    "fields": {
      "name": "Can add home page",
      "content_type": 2,
      "codename": "add_homepage"
    }
  },
  {
    "model": "auth.permission",
    "pk": 9,
    "fields": {
      "name": "Can change home page",
      "content_type": 2,
      "codename": "change_homepage"
    }
  },
  {
    "model": "auth.permission",
    "pk": 10,
    "fields": {
      "name": "Can delete home page",
      "content_type": 2,
      "codename": "delete_homepage"
    }
  },
  {
    "model": "auth.permission",
    "pk": 11,
    "fields": {
      "name": "Can add form submission",
      "content_type": 6,
      "codename": "add_formsubmission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 12,
    "fields": {
      "name": "Can change form submission",
      "content_type": 6,
      "codename": "change_formsubmission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 13,
    "fields": {
      "name": "Can delete form submission",
      "content_type": 6,
      "codename": "delete_formsubmission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 14,
    "fields": {
      "name": "Can add redirect",
      "content_type": 7,
      "codename": "add_redirect"
    }
  },
  {
    "model": "auth.permission",
    "pk": 15,
    "fields": {
      "name": "Can change redirect",
      "content_type": 7,
      "codename": "change_redirect"
    }
  },
  {
    "model": "auth.permission",
    "pk": 16,
    "fields": {
      "name": "Can delete redirect",
      "content_type": 7,
      "codename": "delete_redirect"
    }
  },
  {
    "model": "auth.permission",
    "pk": 17,
    "fields": {
      "name": "Can add embed",
      "content_type": 8,
      "codename": "add_embed"
    }
  },
  {
    "model": "auth.permission",
    "pk": 18,
    "fields": {
      "name": "Can change embed",
      "content_type": 8,
      "codename": "change_embed"
    }
  },
  {
    "model": "auth.permission",
    "pk": 19,
    "fields": {
      "name": "Can delete embed",
      "content_type": 8,
      "codename": "delete_embed"
    }
  },
  {
    "model": "auth.permission",
    "pk": 20,
    "fields": {
      "name": "Can add user profile",
      "content_type": 9,
      "codename": "add_userprofile"
    }
  },
  {
    "model": "auth.permission",
    "pk": 21,
    "fields": {
      "name": "Can change user profile",
      "content_type": 9,
      "codename": "change_userprofile"
    }
  },
  {
    "model": "auth.permission",
    "pk": 22,
    "fields": {
      "name": "Can delete user profile",
      "content_type": 9,
      "codename": "delete_userprofile"
    }
  },
  {
    "model": "auth.permission",
    "pk": 23,
    "fields": {
      "name": "Can add filter",
      "content_type": 10,
      "codename": "add_filter"
    }
  },
  {
    "model": "auth.permission",
    "pk": 24,
    "fields": {
      "name": "Can change filter",
      "content_type": 10,
      "codename": "change_filter"
    }
  },
  {
    "model": "auth.permission",
    "pk": 25,
    "fields": {
      "name": "Can delete filter",
      "content_type": 10,
      "codename": "delete_filter"
    }
  },
  {
    "model": "auth.permission",
    "pk": 26,
    "fields": {
      "name": "Can add rendition",
      "content_type": 11,
      "codename": "add_rendition"
    }
  },
  {
    "model": "auth.permission",
    "pk": 27,
    "fields": {
      "name": "Can change rendition",
      "content_type": 11,
      "codename": "change_rendition"
    }
  },
  {
    "model": "auth.permission",
    "pk": 28,
    "fields": {
      "name": "Can delete rendition",
      "content_type": 11,
      "codename": "delete_rendition"
    }
  },
  {
    "model": "auth.permission",
    "pk": 29,
    "fields": {
      "name": "Can add query",
      "content_type": 12,
      "codename": "add_query"
    }
  },
  {
    "model": "auth.permission",
    "pk": 30,
    "fields": {
      "name": "Can change query",
      "content_type": 12,
      "codename": "change_query"
    }
  },
  {
    "model": "auth.permission",
    "pk": 31,
    "fields": {
      "name": "Can delete query",
      "content_type": 12,
      "codename": "delete_query"
    }
  },
  {
    "model": "auth.permission",
    "pk": 32,
    "fields": {
      "name": "Can add Query Daily Hits",
      "content_type": 13,
      "codename": "add_querydailyhits"
    }
  },
  {
    "model": "auth.permission",
    "pk": 33,
    "fields": {
      "name": "Can change Query Daily Hits",
      "content_type": 13,
      "codename": "change_querydailyhits"
    }
  },
  {
    "model": "auth.permission",
    "pk": 34,
    "fields": {
      "name": "Can delete Query Daily Hits",
      "content_type": 13,
      "codename": "delete_querydailyhits"
    }
  },
  {
    "model": "auth.permission",
    "pk": 35,
    "fields": {
      "name": "Can add site",
      "content_type": 14,
      "codename": "add_site"
    }
  },
  {
    "model": "auth.permission",
    "pk": 36,
    "fields": {
      "name": "Can change site",
      "content_type": 14,
      "codename": "change_site"
    }
  },
  {
    "model": "auth.permission",
    "pk": 37,
    "fields": {
      "name": "Can delete site",
      "content_type": 14,
      "codename": "delete_site"
    }
  },
  {
    "model": "auth.permission",
    "pk": 38,
    "fields": {
      "name": "Can add page",
      "content_type": 1,
      "codename": "add_page"
    }
  },
  {
    "model": "auth.permission",
    "pk": 39,
    "fields": {
      "name": "Can change page",
      "content_type": 1,
      "codename": "change_page"
    }
  },
  {
    "model": "auth.permission",
    "pk": 40,
    "fields": {
      "name": "Can delete page",
      "content_type": 1,
      "codename": "delete_page"
    }
  },
  {
    "model": "auth.permission",
    "pk": 41,
    "fields": {
      "name": "Can add page revision",
      "content_type": 15,
      "codename": "add_pagerevision"
    }
  },
  {
    "model": "auth.permission",
    "pk": 42,
    "fields": {
      "name": "Can change page revision",
      "content_type": 15,
      "codename": "change_pagerevision"
    }
  },
  {
    "model": "auth.permission",
    "pk": 43,
    "fields": {
      "name": "Can delete page revision",
      "content_type": 15,
      "codename": "delete_pagerevision"
    }
  },
  {
    "model": "auth.permission",
    "pk": 44,
    "fields": {
      "name": "Can add group page permission",
      "content_type": 16,
      "codename": "add_grouppagepermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 45,
    "fields": {
      "name": "Can change group page permission",
      "content_type": 16,
      "codename": "change_grouppagepermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 46,
    "fields": {
      "name": "Can delete group page permission",
      "content_type": 16,
      "codename": "delete_grouppagepermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 47,
    "fields": {
      "name": "Can add page view restriction",
      "content_type": 17,
      "codename": "add_pageviewrestriction"
    }
  },
  {
    "model": "auth.permission",
    "pk": 48,
    "fields": {
      "name": "Can change page view restriction",
      "content_type": 17,
      "codename": "change_pageviewrestriction"
    }
  },
  {
    "model": "auth.permission",
    "pk": 49,
    "fields": {
      "name": "Can delete page view restriction",
      "content_type": 17,
      "codename": "delete_pageviewrestriction"
    }
  },
  {
    "model": "auth.permission",
    "pk": 50,
    "fields": {
      "name": "Can add collection",
      "content_type": 18,
      "codename": "add_collection"
    }
  },
  {
    "model": "auth.permission",
    "pk": 51,
    "fields": {
      "name": "Can change collection",
      "content_type": 18,
      "codename": "change_collection"
    }
  },
  {
    "model": "auth.permission",
    "pk": 52,
    "fields": {
      "name": "Can delete collection",
      "content_type": 18,
      "codename": "delete_collection"
    }
  },
  {
    "model": "auth.permission",
    "pk": 53,
    "fields": {
      "name": "Can add group collection permission",
      "content_type": 19,
      "codename": "add_groupcollectionpermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 54,
    "fields": {
      "name": "Can change group collection permission",
      "content_type": 19,
      "codename": "change_groupcollectionpermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 55,
    "fields": {
      "name": "Can delete group collection permission",
      "content_type": 19,
      "codename": "delete_groupcollectionpermission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 56,
    "fields": {
      "name": "Can add Tag",
      "content_type": 20,
      "codename": "add_tag"
    }
  },
  {
    "model": "auth.permission",
    "pk": 57,
    "fields": {
      "name": "Can change Tag",
      "content_type": 20,
      "codename": "change_tag"
    }
  },
  {
    "model": "auth.permission",
    "pk": 58,
    "fields": {
      "name": "Can delete Tag",
      "content_type": 20,
      "codename": "delete_tag"
    }
  },
  {
    "model": "auth.permission",
    "pk": 59,
    "fields": {
      "name": "Can add Tagged Item",
      "content_type": 21,
      "codename": "add_taggeditem"
    }
  },
  {
    "model": "auth.permission",
    "pk": 60,
    "fields": {
      "name": "Can change Tagged Item",
      "content_type": 21,
      "codename": "change_taggeditem"
    }
  },
  {
    "model": "auth.permission",
    "pk": 61,
    "fields": {
      "name": "Can delete Tagged Item",
      "content_type": 21,
      "codename": "delete_taggeditem"
    }
  },
  {
    "model": "auth.permission",
    "pk": 62,
    "fields": {
      "name": "Can add log entry",
      "content_type": 22,
      "codename": "add_logentry"
    }
  },
  {
    "model": "auth.permission",
    "pk": 63,
    "fields": {
      "name": "Can change log entry",
      "content_type": 22,
      "codename": "change_logentry"
    }
  },
  {
    "model": "auth.permission",
    "pk": 64,
    "fields": {
      "name": "Can delete log entry",
      "content_type": 22,
      "codename": "delete_logentry"
    }
  },
  {
    "model": "auth.permission",
    "pk": 65,
    "fields": {
      "name": "Can add permission",
      "content_type": 23,
      "codename": "add_permission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 66,
    "fields": {
      "name": "Can change permission",
      "content_type": 23,
      "codename": "change_permission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 67,
    "fields": {
      "name": "Can delete permission",
      "content_type": 23,
      "codename": "delete_permission"
    }
  },
  {
    "model": "auth.permission",
    "pk": 68,
    "fields": {
      "name": "Can add group",
      "content_type": 24,
      "codename": "add_group"
    }
  },
  {
    "model": "auth.permission",
    "pk": 69,
    "fields": {
      "name": "Can change group",
      "content_type": 24,
      "codename": "change_group"
    }
  },
  {
    "model": "auth.permission",
    "pk": 70,
    "fields": {
      "name": "Can delete group",
      "content_type": 24,
      "codename": "delete_group"
    }
  },
  {
    "model": "auth.permission",
    "pk": 71,
    "fields": {
      "name": "Can add user",
      "content_type": 25,
      "codename": "add_user"
    }
  },
  {
    "model": "auth.permission",
    "pk": 72,
    "fields": {
      "name": "Can change user",
      "content_type": 25,
      "codename": "change_user"
    }
  },
  {
    "model": "auth.permission",
    "pk": 73,
    "fields": {
      "name": "Can delete user",
      "content_type": 25,
      "codename": "delete_user"
    }
  },
  {
    "model": "auth.permission",
    "pk": 74,
    "fields": {
      "name": "Can add content type",
      "content_type": 26,
      "codename": "add_contenttype"
    }
  },
  {
    "model": "auth.permission",
    "pk": 75,
    "fields": {
      "name": "Can change content type",
      "content_type": 26,
      "codename": "change_contenttype"
    }
  },
  {
    "model": "auth.permission",
    "pk": 76,
    "fields": {
      "name": "Can delete content type",
      "content_type": 26,
      "codename": "delete_contenttype"
    }
  },
  {
    "model": "auth.permission",
    "pk": 77,
    "fields": {
      "name": "Can add session",
      "content_type": 27,
      "codename": "add_session"
    }
  },
  {
    "model": "auth.permission",
    "pk": 78,
    "fields": {
      "name": "Can change session",
      "content_type": 27,
      "codename": "change_session"
    }
  },
  {
    "model": "auth.permission",
    "pk": 79,
    "fields": {
      "name": "Can delete session",
      "content_type": 27,
      "codename": "delete_session"
    }
  },
  {
    "model": "auth.group",
    "pk": 1,
    "fields": {
      "name": "Moderators",
      "permissions": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    }
  },
  {
    "model": "auth.group",
    "pk": 2,
    "fields": {
      "name": "Editors",
      "permissions": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    }
  },
  {
    "model": "auth.group",
    "pk": 3,
    "fields": {
      "name": "My Group",
      "permissions": [
        68,
        69,
        1
      ]
    }
  },
  {
    "model": "customuser.customuser",
    "pk": 1,
    "fields": {
      "password": "pbkdf2_sha256$30000$Bdtkt4xqiv7x$luP1jz4mow1ILCj/qxvCdP19eWDpsAsn/Yl3+Awl/MQ=",
      "last_login": "2017-02-13T18:50:59.140Z",
      "is_superuser": true,
      "username": "jchau",
      "first_name": "",
      "last_name": "",
      "email": "",
      "is_staff": true,
      "is_active": true,
      "groups": [],
      "user_permissions": [],
      "country": "",
      "attachment": ""
    }
  },
  {
    "model": "customuser.customuser",
    "pk": 2,
    "fields": {
      "password": "pbkdf2_sha256$30000$hhocRMdjDibS$6pHmQUcSEOTKYTU4X4lDd/DwvIA+h1BaLSNqQvMbi3o=",
      "last_login": null,
      "is_superuser": false,
      "username": "test1",
      "first_name": "John",
      "last_name": "Doe",
      "email": "foo@bar.com",
      "is_staff": false,
      "is_active": true,
      "groups": [],
      "user_permissions": [],
      "country": "",
      "attachment": ""
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 1,
    "fields": {
      "group": 2,
      "collection": 1,
      "permission": 2
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 2,
    "fields": {
      "group": 1,
      "collection": 1,
      "permission": 2
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 3,
    "fields": {
      "group": 2,
      "collection": 1,
      "permission": 3
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 4,
    "fields": {
      "group": 1,
      "collection": 1,
      "permission": 3
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 5,
    "fields": {
      "group": 2,
      "collection": 1,
      "permission": 5
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 6,
    "fields": {
      "group": 1,
      "collection": 1,
      "permission": 5
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 7,
    "fields": {
      "group": 2,
      "collection": 1,
      "permission": 6
    }
  },
  {
    "model": "wagtailcore.groupcollectionpermission",
    "pk": 8,
    "fields": {
      "group": 1,
      "collection": 1,
      "permission": 6
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 1,
    "fields": {
      "group": 1,
      "page": 1,
      "permission_type": "add"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 2,
    "fields": {
      "group": 1,
      "page": 1,
      "permission_type": "edit"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 3,
    "fields": {
      "group": 1,
      "page": 1,
      "permission_type": "publish"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 4,
    "fields": {
      "group": 2,
      "page": 1,
      "permission_type": "add"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 5,
    "fields": {
      "group": 2,
      "page": 1,
      "permission_type": "edit"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 6,
    "fields": {
      "group": 1,
      "page": 1,
      "permission_type": "lock"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 7,
    "fields": {
      "group": 3,
      "page": 4,
      "permission_type": "add"
    }
  },
  {
    "model": "wagtailcore.grouppagepermission",
    "pk": 8,
    "fields": {
      "group": 3,
      "page": 4,
      "permission_type": "edit"
    }
  },
  {
    "model": "wagtailcore.pagerevision",
    "pk": 1,
    "fields": {
      "page": 4,
      "submitted_for_moderation": false,
      "created_at": "2017-02-13T18:54:48.248Z",
      "user": 1,
      "content_json": "{\"locked\": false, \"title\": \"My Child Page\", \"numchild\": 0, \"show_in_menus\": false, \"live\": false, \"seo_title\": \"\", \"search_description\": \"\", \"depth\": 3, \"latest_revision_created_at\": null, \"has_unpublished_changes\": false, \"content_type\": 2, \"path\": \"000100010001\", \"owner\": 1, \"pk\": 4, \"first_published_at\": null, \"url_path\": \"/home/my-child-page/\", \"expired\": false, \"slug\": \"my-child-page\", \"expire_at\": null, \"go_live_at\": null}",
      "approved_go_live_at": null
    }
  },
  {
    "model": "wagtailcore.pagerevision",
    "pk": 2,
    "fields": {
      "page": 4,
      "submitted_for_moderation": false,
      "created_at": "2017-02-13T18:54:56.293Z",
      "user": 1,
      "content_json": "{\"locked\": false, \"title\": \"My Child Page\", \"numchild\": 0, \"show_in_menus\": false, \"live\": false, \"seo_title\": \"\", \"search_description\": \"\", \"depth\": 3, \"latest_revision_created_at\": \"2017-02-13T18:54:48.248Z\", \"has_unpublished_changes\": true, \"content_type\": 2, \"path\": \"000100010001\", \"owner\": 1, \"pk\": 4, \"first_published_at\": null, \"url_path\": \"/home/my-child-page/\", \"expired\": false, \"slug\": \"my-child-page\", \"expire_at\": null, \"go_live_at\": null}",
      "approved_go_live_at": null
    }
  },
  {
    "model": "wagtailcore.page",
    "pk": 1,
    "fields": {
      "path": "0001",
      "depth": 1,
      "numchild": 1,
      "title": "Root",
      "slug": "root",
      "content_type": 1,
      "live": true,
      "has_unpublished_changes": false,
      "url_path": "/",
      "owner": null,
      "seo_title": "",
      "show_in_menus": false,
      "search_description": "",
      "go_live_at": null,
      "expire_at": null,
      "expired": false,
      "locked": false,
      "first_published_at": null,
      "latest_revision_created_at": null
    }
  },
  {
    "model": "wagtailcore.page",
    "pk": 3,
    "fields": {
      "path": "00010001",
      "depth": 2,
      "numchild": 1,
      "title": "Homepage",
      "slug": "home",
      "content_type": 2,
      "live": true,
      "has_unpublished_changes": false,
      "url_path": "/home/",
      "owner": null,
      "seo_title": "",
      "show_in_menus": false,
      "search_description": "",
      "go_live_at": null,
      "expire_at": null,
      "expired": false,
      "locked": false,
      "first_published_at": null,
      "latest_revision_created_at": null
    }
  },
  {
    "model": "wagtailcore.page",
    "pk": 4,
    "fields": {
      "path": "000100010001",
      "depth": 3,
      "numchild": 0,
      "title": "My Child Page",
      "slug": "my-child-page",
      "content_type": 2,
      "live": true,
      "has_unpublished_changes": false,
      "url_path": "/home/my-child-page/",
      "owner": 1,
      "seo_title": "",
      "show_in_menus": false,
      "search_description": "",
      "go_live_at": null,
      "expire_at": null,
      "expired": false,
      "locked": false,
      "first_published_at": "2017-02-13T18:54:56.313Z",
      "latest_revision_created_at": "2017-02-13T18:54:56.293Z"
    }
  },
  {
    "model": "home.homepage",
    "pk": 3,
    "fields": {}
  },
  {
    "model": "home.homepage",
    "pk": 4,
    "fields": {}
  }
]
```

I then create this simple test to use the fixture:

```
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.test import TestCase

from wagtail.tests.utils import WagtailTestUtils


class TestNewFixture(TestCase, WagtailTestUtils):
    fixtures = ['test_data.json']

    def test_my_fixture_works(self):
        self.assertTrue(self.client.login(username='test1', password='asdf'))
        response = self.client.get(reverse('wagtailgroups'))
        pass
```

which gives the following error:

```
IntegrityError: Problem installing fixture '/Users/jchau/Documents/wagtail/wagtail/tests/testapp/fixtures/test_data.json': Could not load wagtailcore.Site(pk=2): UNIQUE constraint failed: wagtailcore_site.hostname, wagtailcore_site.port
```

**Comment by gasman** [comment] 2017-03-07 15:41
I believe the failure here occurs as a result of the following steps:

* The migrations in `wagtailcore` create a root Page (page id=1), a barebones homepage of type Page (page id=2), and a Site (site id=1) pointing to that homepage
* The migrations in the `wagtail start` project template run after this; they delete and recreate the homepage (creating page id=3) and site record (creating site id=2), so that we end up with a homepage whose type is the project template's `HomePage` type, rather than a plain Page.
* Your fixture therefore captures the database state that would be expected from a `wagtail start` project-template-based project: site ID 2, and page IDs 1 and 3 (amongst others).
* The test app (wagtail/tests/testapp) is _not_ based on the `wagtail start` project template, and doesn't have the 'delete and recreate' step in its migrations. Therefore, at the point during test startup where the migrations have just run, the database contains site ID 1, and page IDs 1 and 2 (all originating from the `wagtailcore` migrations).
* Loading a fixture causes the fixture data to be 'overlaid' on top of the existing database contents - a fixture item that matches an existing record by ID will replace that old record, and a fixture item that doesn't match an existing ID will be inserted.
* In this case, the fixture will try to insert a Site record with ID 2 and a Page record with ID 3, which conflict with the existing records for localhost and the homepage respectively.

The immediate problem here could be fixed by editing the page / site IDs in the fixture manually - but then I suspect you'll run into the problem that the test app doesn't define a HomePage model. The root of the issue is that you're expecting to load a fixture originating from the project template into what's effectively a completely different Django project. Disabling migrations isn't going to solve that.

A couple of possible ways to take this forward:

* Work out and document a way of generating test-app-compatible fixtures. I think you could get a lot of the way there by starting from `wagtail start`, but replacing `'home'` with `'wagtail.tests.testapp'` in `INSTALLED_APPS` before migrating. There's probably more details to be ironed out there, though.
* Longer term, see if we can move away from fixtures completely - they're not very human-hackable at all (especially when it comes to dealing with Treebeard-related fields) and that leads to people treating them as something of a "black box", limiting our ability to troubleshoot and extend them. [factory_boy](https://factoryboy.readthedocs.io/en/latest/) would be something to investigate here...

**Closed by gasman** 2017-03-07 15:41 UTC
Labels: status:Needs info
