### ISSUE TITLE
Styles for the save button on settings pages are broken

### ISSUE THREAD

**Issue by jrstewart** [wagtail/wagtail#3836] opened 2017-09-06 18:15 UTC
### Issue Summary

The button styles for the save button on custom settings pages does not appear to have padding on the right side.

<img width="114" alt="screen shot 2017-09-06 at 1 05 07 pm" src="https://user-images.githubusercontent.com/116638/30127458-f6490f80-9304-11e7-9adf-a18bd8970639.png">

### Steps to Reproduce

1. Create a new settings model that inherits from wagtail.contrib.settings.models.BaseSettings and registered with Wagtail using wagtail.contrib.settings.models.register_settings.
2. Go to the Wagtail admin page for the settings model and the save button styling appears without right padding.

### Technical details

* Python version: 3.6.2
* Django version: 1.11.4
* Wagtail version: 1.12.1
* Browser version: Chrome 60.0.3112.113, Firefox Developer Edition 58.0b9

**Comment by gasman** [comment] 2017-09-11 14:14
Thanks for the report @jrstewart!

It looks like this was introduced by #3785, which was intended to fix a similar issue with the preview button on the page editor. The preview button (in its normal single-mode version) and wagtailsettings appear to be the only places in Wagtail where we have a button in the footer bar _without_ a drop-up menu.

**Comment by gasman** [comment] 2017-09-13 14:50
Fixed in #3848

**Closed by gasman** 2017-09-13 14:50 UTC
Labels: component:Frontend, type:Bug
