### ISSUE TITLE
Feature request: add "Add child page" to the menu

### ISSUE THREAD

**Issue by kunambi** [wagtail/wagtail#6542] opened 2020-11-12 10:32 UTC
### Is your proposal related to a problem?

Would like to lessen the amount of clicks/actions needed when adding a child page.

### Describe the solution you'd like

I would like to see a plus-link (or similar) in the menu. The link would be a shortcut for clicking e.g. "English" and then clicking "Add child page". This solution allows us to have one less page load.

![image](https://user-images.githubusercontent.com/739112/98928494-22306700-24da-11eb-8f6c-4054d6587382.png)

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by thibaudcolas** [comment] 2022-01-20 00:16
Closing as duplicate of #4658.

**Closed by thibaudcolas** 2022-01-20 00:16 UTC
Labels: type:Enhancement, status:Needs UI Design
