### ISSUE TITLE
Image filenames are hard to cache-bust

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#785] opened 2014-11-05 15:13 UTC
(I'm aware this overlaps with an existing conversation on google groups)

While trying to obtain the best Google PageSpeed score (https://developers.google.com/speed/pagespeed/) we've discovered that giving images served from /media/ a long cache expiry, as recommended/sensible, is tricky because users can replace the images without anything about the image url changing.

Received wisdom says most static assets should be cacheable for for several days, but if users are able to replace an image with an altered version using the very same filename, this makes cache busting impossible.

Perhaps image urls could include something unique like the "last updated" timestamp, or have the human-readable filename replaced entirely with a hash?

**Comment by BertrandBordage** [comment] 2017-08-31 01:00
Will be fixed by #3822, and #3817 is a duplicate of this.

**Comment by gasman** [comment] 2017-10-06 13:21
Fixed in #3822

**Closed by gasman** 2017-10-06 13:21 UTC
Labels: component:Images, type:Enhancement
