### ISSUE TITLE
ManyToManyField in inline model is not saved

### ISSUE THREAD

**Issue by jaap3** [wagtail/wagtail#3412] opened 2017-02-28 14:24 UTC
When saving a page that has an inline panel with a ManyToMany field the m2m relation is not saved.

Validation happens, but after saving the many to many table is empty.

I've created an example project using wagtail 1.9 that illustrates the issue:

https://github.com/jaap3/wagtail-inline-m2m-issue

**Comment by gasman** [comment] 2017-02-28 14:30
Hi @jaap3,

I think it might work with the following definition for HomePageInline:

    from modelcluster.models import ClusterableModel

    class HomePageInline(Orderable, ClusterableModel):
        page = ParentalKey(HomePage, related_name='related_content')
        title = models.CharField(max_length=255)
        sites = ParentalManyToManyField(Site)

Please could you give that a try? If that works, we should document it.

**Comment by jaap3** [comment] 2017-02-28 14:36
I tried but the issue remains. I've stepped through the code and the issue is probably somewhere in modelclusters' `BaseChildFormSet` but I wasn't able to pinpoint it or get it to work by just calling `self.save_m2m()` there. I'm not too familiar with Wagtail or modelclusters, so I'm afraid I cannot provide more help.

**Comment by thornycrackers** [comment] 2017-02-28 23:15
I am also running into this exact same problem right now with one of my projects the same model setup as the example project.

**Comment by lucasmoeskops** [comment] 2017-03-25 22:32
I tested out the example and got it working with the following changes:
* It seems that while the ClusterForm class has a built-in option to save the m2m data when not committing, BaseChildFormSet doesn't, but does have the ParentalM2M relation. I, naively, just copied these lines from the ClusterForm.save method to the BaseChildFormSet.save:
`# Since ParentalManyToManyField _does_ provide a way to write back to the relation without
        # writing to the database, we'll reverse this behaviour by calling save_m2m immediately.
        if not commit:
            self.save_m2m()`
 I pasted them just below the `saved_instances = super(BaseChildFormSet, self).save(commit=False)` line (modelcluster/forms.py, line 62).
* Like @gasman suggested, the model should be ClusterableModel instead of models.Model, to allow the data from the ParentalM2M field to be correctly serialized.

After changing this, the m2m data is saved.

**Comment by hjwp** [comment] 2017-08-05 11:54
I ran into this issue as well, and I can confirm that @lucasmoeskops' fix works, for both save draft and publish.

* the `if not commit save_m2m` hack for me was at line 102: https://github.com/wagtail/django-modelcluster/blob/master/modelcluster/forms.py#L102
* I also switched to ClusterableModel and ParentalManyToManyField

**Comment by hjwp** [comment] 2017-08-05 12:59
I have had a completely naive flail at fixing this bug:  https://github.com/wagtail/django-modelcluster/pull/81

**Comment by hjwp** [comment] 2017-08-05 16:28
having played about with it a bit more I think that PR is sane now, maybe someone could sanity-check it?  @lucasmoeskops you might be able to check whether the unit test i wrote looks right, at least?

**Comment by lucasmoeskops** [comment] 2017-08-24 20:56
Looks nice! Although the tests fail for python 2.7. Maybe something with unicode support?

**Comment by hjwp** [comment] 2017-08-25 05:59
fixed i think.  @gasman, is it starting to look mergeable?

**Comment by hjwp** [comment] 2017-08-25 06:41
hm, i'm a bit this only works for "publish"  and not for "save draft", but i'm not sure how i could test that at the level of the modelcuster UTs?

**Comment by hjwp** [comment] 2017-08-27 23:15
OK I've reviewed my fix and determined that one of the two places I added "fix" code to save m2m instances wasn't actually necessary.

so the patch is now a one-line change: just add a `self.save_m2m()`

unit tests are included.

**Comment by hjwp** [comment] 2017-11-04 14:39
I've also created a simple wagtail project that reproduces the bug, including a UT that demonstrates the bug: https://github.com/hjwp/wagtail-m2m-bug-repro

**Comment by gasman** [comment] 2017-12-13 23:33
Fixed in https://github.com/wagtail/django-modelcluster/pull/81

**Closed by gasman** 2017-12-13 23:33 UTC
Labels: type:Bug

**Comment by devRawnie** [comment] 2021-06-15 07:36
I used a ParentalManyToManyField and extended the ClusterableModel, and it is saving the details now
