### ISSUE TITLE
FieldPanel seems to ignore `heading` kwarg in template.

### ISSUE THREAD

**Issue by mvdwaeter** [wagtail/wagtail#4476] opened 2018-04-17 12:08 UTC
### Issue Summary

`FieldPanel` seems to ignore `heading` kwarg in template.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit `home/models.py` as follows:
```
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel
from wagtail.core.models import Page


class HomePage(Page):
    special_field = models.CharField(
        default='',
        max_length=255,
        blank=True
    )

    content_panels = Page.content_panels + [
        FieldPanel('special_field', heading='Bananas'),
        MultiFieldPanel(
            [
                FieldPanel('special_field', heading='Apples'),
            ],
            heading='Multiple example',
            classname='collapsible'
        ),
    ]
```
3. Run `python manage.py makemigrations home`
4. Run `python manage.py migrate`
5. Create a superuser `python manage.py createsuperuser`
6. Run server `python manage.py runserver`
7. Goto: `http://localhost:8000/admin/pages/3/edit/`

I'm expecting to see Bananas & Apples there.

I expect when you give a `label` to a FieldPanel the label is used instead of the fieldname.

### Technical details

* Python version: 3.6.4
* Django version: 2.0.4
* Wagtail version: 2.0.1
* Browser version: Firefox 59

**Comment by lb-** [comment] 2019-03-16 09:32
@mvdwaeter - thank you so much for submitting this detailed issue.

We found that this appears to be a duplicate of #4471 so will close this one for now.

**Closed by lb-** 2019-03-16 09:32 UTC
Labels: type:Enhancement
