### ISSUE TITLE
Postgres search backend returning duplicated results between pages

### ISSUE THREAD

**Issue by Brett-Mitchell** [wagtail/wagtail#3729] opened 2017-07-20 19:17 UTC
### Issue Summary

Currently, the Postgres search backend uses just `ORDER BY index_entry.rank DESC`.  This is great for one-time searches, but when we start getting incremental paginated search results, duplicates begin to appear between pages.  This happens when several results have the same search rank, causing for unpredictable row ordering from Postgres.  (See [this](https://www.postgresql.org/docs/9.1/static/queries-limit.html) page in the docs, 4th paragraph.).

### Steps to Reproduce

1. Begin a new project and setup the Postgres search backend
2. Create enough pages to get multiple pages of results (20-30 for default results_per_page 10 should do).  Works best when you choose a search term and then include it in varying levels several articles at a time.
3. Perform requests for consecutive pages of results.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.5
* Wagtail version: 1.10.1
* Browser version: Chrome 59

**Comment by BertrandBordage** [comment] 2017-08-21 15:19
Hey @Brett-Mitchell, could not reproduce the bug, although I created a test for that. It’s maybe a different behaviour between PostgreSQL versions. Could you tell me what your version is?
Also, please test that #3777 fixes your issue and check that the test seems correct to you.

**Comment by Brett-Mitchell** [comment] 2017-08-22 19:18
@BertrandBordage, my Postgresql version is 9.5.7.

**Comment by gasman** [comment] 2017-08-24 10:54
Hopefully fixed by #3777 (please report if not, and we'll reopen...)

**Closed by gasman** 2017-08-24 10:54 UTC
Labels: component:Search, type:Bug
