### ISSUE TITLE
setting up redirects that kick in for "real pages" rather than 404

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4544] opened 2018-05-15 20:48 UTC
In order to automatically generate a menu with correct menu headings, we've created pages in a way that a particular root (let's say the "about" page) has several real, and several placeholder pages. For example:
```
about
|- impact *
|- leadership
|- trademarks
|- public-records
|- strategy *
|- support
|- careers *
```
In this, `impact`, `strategy`, and `careers` are actually content-less pages that we would like to redirect when visited, but using the wagtail redirects doesn't quite work, as those will only kick in for routes that don't exist.

In order to deal with that, we figured we'd make a `RedirectingPage` type, with a single `URL` field that indicates which URL to immediately redirect to using a meta refresh, but it seemed a good idea to check in with the wagtail team to see if that's a sensible thing to do, or whether there is already an established way to deal with this that's different from our idea.

**Comment by gasman** [comment] 2018-05-15 21:03
Hi @Pomax,
You might want to look at #655 and the linked blog post - much the same concept, except that by overriding the `serve` method you can perform the redirect server-side (which is probably neater than a `<meta>` refresh). The only real thing blocking us from shipping this as a standard Wagtail feature is figuring out how we'd communicate the difference between the two kinds of redirect...

(closing as duplicate of #655)

**Closed by gasman** 2018-05-15 21:03 UTC

**Comment by Pomax** [comment] 2018-05-15 23:01
Ah, you're right that is much neater!

Communication wise, it might make sense to make this part of the `settings` tab, so you'd see a publish/expiration date, and a second option "this page acts as (temporary/permanent) redirect to: [.....]" maybe? 

For our purpose, the `serve` override is definitely good enough, and instant rather than briefly seeing a template file before the meta refresh kicks in.
