### ISSUE TITLE
TextBlock autoresize broken on firefox

### ISSUE THREAD

**Issue by QiYuTechDev** [wagtail/wagtail#7402] opened 2021-08-05 03:02 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

TextBlock autoresize broken on firefox (90.0.2)

### Steps to Reproduce

* create new empty page with Textblock field
* fill TextBlock fields with multi line text (at least > 3 lines)
* save as draft
* close the edit
* re-edit the create page (currently it seems the TextBlock is not autoresize)

### Technical details

* Python version: Python 3.9.6.
* Django version: django==3.2.6;
* Wagtail version: 2.14.0
* Browser version: firefox 90.0.2 on macOS 11.5.1

**Comment by thibaudcolas** [comment] 2022-08-16 11:09
This all seems to be working as expected for me, following those same steps – so I’ll close this now.

Tested in Wagtail `main` / "4.0", Firefox 103. @QiYuTechDev if you can still reproduce the issue with different steps, please let us know!

**Closed by thibaudcolas** 2022-08-16 11:09 UTC
Labels: type:Bug, component:Frontend
