### ISSUE TITLE
choose page: slight graphics glitch with the filter box

### ISSUE THREAD

**Issue by matiasli** [wagtail/wagtail#3855] opened 2017-09-13 21:07 UTC
![screen shot 2017-08-28 at 1 15 47 pm](https://user-images.githubusercontent.com/18155551/30400913-41c9c944-988d-11e7-8ac8-899bf400f902.png)
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When on the CMS, when a user attemtps to choose another page and uses the filter, there is a slight graphics glitch on the filter

### Steps to Reproduce

1. open and edit a page in the CMS

2. go to the cta link and select choose another page

3. in the filter enter a letter ('a') and scroll

### Technical details
* Wagtail version: 1.12
* Browser version: chrome Version 61.0.3163.79

**Comment by thibaudcolas** [comment] 2017-11-23 09:34
Hi @matiasli, thank you for reporting this and sorry it took us so long to get back to you.

I can't reproduce the issue you are describing, using the latest version of Wagtail (2.0 alpha) and Chrome (`Version 62.0.3202.94 (Official Build) (64-bit)`, macOS 10.13).

I don't think we've changed this code much recently so I would suspect a browser-specific issue – please let me know whether you are still experiencing this, and also which operating system you are using.

Thank you!

**Comment by gasman** [comment] 2018-01-10 13:54
Closing as unable to replicate.

**Closed by gasman** 2018-01-10 13:54 UTC
Labels: component:Frontend, status:Needs info, type:Bug
