### ISSUE TITLE
formbuilde fieldtype date

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9311] opened 2022-10-11 13:35 UTC
### Issue Summary
Formbuilder field types should reflect choices. Example date fieldtype
You can select date field in in the formbuilder. I would expect that the form would render
`<form type="date" ...> and not <form type="text" ..>
` One extra thing that would be handy is you can add placeholders to your form so the field will be
`<form type="date" placeholder="...>
`
### Steps to Reproduce
Create form with form builder and select field date. render form in template and see this the ="text"

### Technical details
-   Wagtail version: 4

**Comment by lb-** [comment] 2022-10-11 22:42
Thanks @onno-timmerman - not sure that this is a bug but probably an evolution of browser support to be considered for the HTML5 input types. 

Nonetheless can you please update this issue with a description that uses the template a bit more. Steps to reproduce, alternative work around that may exist and links to why the type should be used by default (browser support/ best practices). 

As for the placeholder comment - to keep issues focused I recommend you remove that note as it's already covered in https://github.com/wagtail/wagtail/issues/6132

Thanks again.

**Comment by onno-timmerman** [comment] 2022-10-12 07:09
Well the form uses "email" as type but not "date" as type so maybe its a bug. But this can also be concidered as a feature request :)

Don't know what more to describe then render a form and see if the field types are used for date and datetime?
I think its handy because then you have a date widget in your form. All modern browsers have these types email, date, time ... with a free interface.

**Comment by lb-** [comment] 2022-10-12 08:13
I think if we introduce type=date by default we open up a bit of a mess of problems. 

Date input can be a minefield of issues if not handled correctly, users may want to enter a value but cannot. Formats of dates may come in more inconsistently than with a plain text box. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#handling_browser_support

Doing a bit more digging now.

**Comment by lb-** [comment] 2022-10-12 08:26
So, looks like the code uses the Django built in `DateField` 

* https://docs.djangoproject.com/en/4.1/ref/forms/fields/#django.forms.DateField
* This uses the the DateInput widget by default https://docs.djangoproject.com/en/4.1/ref/forms/widgets/#django.forms.DateInput
* Which renders as `input_type: 'text'`

I think for now we would not want work against Django's default fields here, the reason `EmailField` has type=email is due to the default Django behaviour.

There are two reasonable ways to work around this with light customisations based on what you want.

## 1. Override the `form_builder` on your `Formpage`

This is similar to the documentation example here https://docs.wagtail.org/en/stable/reference/contrib/forms/customisation.html#adding-a-custom-field-type

Note: Code below has not been run locally by me but should be close enough to give you a sense of things.

```python
class CustomFormBuilder(FormBuilder):
    def create_date_field(self, field, options):
        attrs = options.pop('attrs')
        return django.forms.DateField(**options, attrs={**attrs, 'type': 'date'})


class FormPage(AbstractEmailForm):
    # intro, thank_you_text, edit_handlers, etc...

    # use custom form builder defined above
    form_builder = CustomFormBuilder
```

## 2. Override the form rendering on the page.

* Using something like crispy forms could work
* Alternatively you could use the new Django 4.0 Form template rendering solution https://docs.djangoproject.com/en/4.1/ref/forms/renderers/#overriding-built-in-form-templates

Based on this, I think we can close this for now as there are reasonable workarounds and being too opinionated about how pages are rendered is not ideal. Unless we see a critical reason for it.

See also
* Gov.uk design system reasoning of not using the date field type (tldr - locale issues can be a complicated problem) https://github.com/alphagov/govuk-design-system-backlog/issues/43#issuecomment-1160139594 (remember some Wagtail sites still need to support IE11, just because Wagtail admin does not)
* Good accessibility round up from 2019 (may be a bit outdated) - recommends against this input type for now. https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/
* We are considering using the date input type for Wagtail admin date pickers, but we will have a lot more control over how this renders, how locale is determined, validation and very specific browser support options. see https://github.com/wagtail/wagtail/issues/8056

**Closed by lb-** 2022-10-12 08:26 UTC
Labels: type:Bug, status:Needs Info, component:Form builder, status:Unconfirmed
