### ISSUE TITLE
RichTextEditor CSS bug

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#5728] opened 2019-12-04 13:19 UTC
### Issue Summary
When using OL list element in Wagtail richtext you will get a layout issue. From number 10. on the first number will be gone.

### Steps to Reproduce
1. Make a richtext editor.
2. use Orderd list option
3. create 10+ items in the orderd list
4. see that 10, 11 ... the first digit is not shown.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

* Python version: Run `python --3.7`.
* Django version: 2.2
* Wagtail version: 2.7.
* Browser version: Chrome 78.

**Comment by thibaudcolas** [comment] 2022-01-19 23:45
Dupe of #7019 / fixed in #7775.

**Closed by thibaudcolas** 2022-01-19 23:45 UTC
Labels: type:Bug, component:Rich text
