### ISSUE TITLE
Wagtail API /page/find will not work for internationalized urls

### ISSUE THREAD

**Issue by funkhauscreative** [wagtail/wagtail#6606] opened 2020-12-02 19:08 UTC
I have configured the Wagtail site to use the new internationalization settings and i18n_patterns for the urls.

If you need to find a page to a url path (necessary in headless configurations) you would usually call the endpoint "/api/v2/pages/find/html_path=...". This path is not taking care of the i18n module. A reference to the method can be found here.

https://github.com/wagtail/wagtail/blob/25b9139a7cad6574f99ad3a316920f56bfedd855/wagtail/api/v2/views.py#L486

**How to solve this issue?**
I beleive implementing it the same way like the normal Viewset does it would be fine. Instead of just checking one root site the url should be checked against all available translated roots like here:

https://github.com/wagtail/wagtail/blob/25b9139a7cad6574f99ad3a316920f56bfedd855/wagtail/api/v2/views.py#L452

**Comment by DanStuartDept** [comment] 2022-02-17 11:40
+1

**Comment by zerolab** [comment] 2022-02-17 15:05
Closing this as duplicate of #6679 which has an example workaround. A PR would be very welcome, thank you

**Closed by zerolab** 2022-02-17 15:05 UTC
Labels: component:i18n, component:API
