### ISSUE TITLE
Cannot copy a draft page with OneToOneField

### ISSUE THREAD

**Issue by lucaskuzma** [wagtail/wagtail#5172] opened 2019-03-25 09:44 UTC
### Issue Summary

When making a copy of a Page with a `OneToOneField`, we get an error if we uncheck the `Publish copied page` checkbox. Making a copy with publishing turned on works as expected provided the `OneToOneField` is listed in `exclude_fields_in_copy`.  For some reason turning off publishing results in validation which ignores `exclude_fields_in_copy`.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows:

```
from django.contrib.auth.models import User
from django.db import models

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    foo = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    exclude_fields_in_copy = ['foo']

    content_panels = [
        FieldPanel('foo'),
    ]
```

3. Make a page with `foo` set to your superuser. Attempt to copy the page with `Publish copied page:` unchecked. Expect a successful copy. Result:

```
[...]
  File "/Users/lucas/.local/share/virtualenvs/test_wagtail-PLuuhPI6/lib/python3.6/site-packages/wagtail/core/models.py", line 1171, in copy
    latest_revision_as_page_revision = latest_revision.save_revision(user=user, changed=False)
  File "/Users/lucas/.local/share/virtualenvs/test_wagtail-PLuuhPI6/lib/python3.6/site-packages/wagtail/core/models.py", line 635, in save_revision
    self.full_clean()
  File "/Users/lucas/.local/share/virtualenvs/test_wagtail-PLuuhPI6/lib/python3.6/site-packages/wagtail/core/models.py", line 436, in full_clean
    super().full_clean(*args, **kwargs)
  File "/Users/lucas/.local/share/virtualenvs/test_wagtail-PLuuhPI6/lib/python3.6/site-packages/django/db/models/base.py", line 1152, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'foo': ['Home page with this Foo already exists.']}
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: 

Yes

### Technical details

* Python version: Python 3.6.1
* Django version: 2.1.7
* Wagtail version: 2.4
* Browser version: Chrome 72

**Comment by cloudratha** [comment] 2019-05-20 14:12
Correct me if I'm wrong, but isn't a `OneToOneField` a unique `ForeignKey`. Meaning only one HomePage can have a particular User. So makes sense that Django is throwing the Validation error.

**Comment by lucaskuzma** [comment] 2019-05-20 14:37
@cloudratha The field in question is listed in `exclude_fields_in_copy`, which can be used to skip unique fields during a copy, and, furthermore, the copy operation works fine when `Publish copied page:` is checked.

**Comment by jsma** [comment] 2022-02-25 20:54
This appears to be a general issue where ``exclude_fields_in_copy`` is not consulted when copying but not publishing the new page. We just encountered this while trying to copy a _published_ page to a new draft, where the page type had a reverse ``GenericRelation`` defined and was included in ``exclude_fields_in_copy``:

```
TypeError at /cms/pages/XYZ/copy/
Direct assignment to the reverse side of a related set is prohibited. Use +.set() instead.
```

We _solved_ this by removing the ``GenericRelation`` since it wasn't actually being used elsewhere but this does appear to be a bug in Wagtail (tested on wagtail==2.16.1).

**Comment by zerolab** [comment] 2022-04-08 10:22
I tried the test from #8048 on the `stable/2.15.x` branch and it was successful.

Will close this on that bases. #8048 will be in 3.0, and 491449e backports it to 2.16.

If you happen to be able to reproduce it  on 2.15 (as an LTS), do shout and we'll reopen.

**Closed by zerolab** 2022-04-08 10:22 UTC
Labels: type:Bug
