### ISSUE TITLE
RichText editor allowing empty value

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#4561] opened 2018-05-23 23:55 UTC
### Issue Summary

The RichText fields on my models are allowing blank values to be saved via the admin if published/save attempted twice in a row.

### Steps to Reproduce

```
class ContentPage(Page):
  body = RichTextField()

  content_panels = Page.content_panels + [
    FieldPanel('body');
  ]
```
If a user then attempts to publish the page with only the title filled out, the validation fails. If the user then publishes the page again without touching the richtext field, it works.
If I then jump into a shell and grab the saved page I get the following:

```
p = Page.objects.get(title='Test').specific
p.body
'<p></p>'
```

### Technical details

* Python version: 3.5.2
* Django version: 1.11.1
* Wagtail version: 2.0 and 2.1
* Browser version: Latest Opera/Chrome/Firefox

**Comment by thibaudcolas** [comment] 2018-05-24 06:10
Hey @seb-b, thank you for taking the time to report this. I'm pretty sure this is a duplicate of #4549 so I'll close this issue, but let us know if you think otherwise.

**Closed by thibaudcolas** 2018-05-24 06:10 UTC
Labels: component:Rich text, type:Bug
