### ISSUE TITLE
`srcset_image` tag fails on SVG with `preserve-svg` and `format-` arguments

### ISSUE THREAD

**Issue by eykd** [wagtail/wagtail#12285] opened 2024-09-05 00:11 UTC
### Issue Summary

Usage like this with an SVG results in a traceback:

```
{% srcset_image image format-{avif,jpeg} width-{400,800} preserve-svg sizes="(max-width: 600px) 400px" %}
```

### Steps to Reproduce

With `wagtail` 6.2.1, `Django` 5.1, and `wagtail_factories` installed, in a Django project with wagtail installed and migrations run:

```python
from django.template import Context, Template
from wagtail_factories import ImageFactory

template = Template("""
{% load wagtailimages_tags %}
{% srcset_image image format-{avif,jpeg} width-{400,800} preserve-svg sizes="(max-width: 600px) 400px" %}
""")

raster_image = ImageFactory.create()

# This works fine:
template.render(Context({"image": raster_image}))

with open("./test.svg", "w") as fo:
    fo.write(
        '<svg xmlns="http://www.w3.org/2000/svg"><rect width="300" height="100" fill="red" /></svg>'
    )

svg_image = ImageFactory.create(file__from_path="./test.svg")
# This explodes:
template.render(Context({"image": svg_image}))
```

Leaving off the `format-{...}` arguments will work just fine.

I would expect it to ignore any `format-{...}` arguments when using an SVG.

Strangely, calling `Template.render(...)` a second time appears to work:

```python
In [11]: template.render(Context({"image": svg_image}))
Out[11]: '\n\n<img alt="An image" height="150" sizes="(max-width: 600px) 400px" src="/media/images/test_HZdqjL1.width-400.svg" srcset="/media/images/test_HZdqjL1.width-400.svg 300w, /me
dia/images/test_HZdqjL1.width-800.svg 300w" width="300">\n'
```

### Traceback

```python
----> 1 template.render(Context({"image": svg_image}))

File ~/myproject/.venv/lib/python3.12/site-packages/django/template/base.py:171, in Template.render(self, context)
    169     with context.bind_template(self):
    170         context.template_name = self.name
--> 171         return self._render(context)
    172 else:
    173     return self._render(context)

File ~/myproject/.venv/lib/python3.12/site-packages/django/test/utils.py:114, in instrumented_test_render(self, context)
    109 """
    110 An instrumented Template render method, providing a signal that can be
    111 intercepted by the test Client.
    111 intercepted by the test Client.
    112 """
    113 template_rendered.send(sender=self, template=self, context=context)
--> 114 return self.nodelist.render(context)

File ~/myproject/.venv/lib/python3.12/site-packages/django/template/base.py:1008, in NodeList.render(self, context)
   1007 def render(self, context):
-> 1008     return SafeString("".join([node.render_annotated(context) for node in self]))

File ~/myproject/.venv/lib/python3.12/site-packages/django/template/base.py:969, in Node.render_annotated(self, context)
    962 """
    963 Render the node. If debug is True and an exception occurs during
    964 rendering, the exception is annotated with contextual line information
    965 where it occurred in the template. For internal usage this method is
    966 preferred over using the render method directly.
    967 """
    968 try:
--> 969     return self.render(context)
    970 except Exception as e:
    971     if context.template.engine.debug:
    972         # Store the actual node that caused the exception.

File ~/myproject/.venv/lib/python3.12/site-packages/wagtail/images/templatetags/wagtailimages_tags.py:181, in SrcsetImageNode.render(self, context)
    178     return ""
    180 specs = self.get_filters(preserve_svg=self.preserve_svg and image.is_svg())
--> 181 renditions = get_renditions_or_not_found(image, specs)
    183 if self.output_var_name:
    184     # Wrap the renditions in ResponsiveImage object, to support both
    185     # rendering as-is and access to the data.
    186     context[self.output_var_name] = ResponsiveImage(renditions)

File ~/myproject/.venv/lib/python3.12/site-packages/wagtail/images/shortcuts.py:35, in get_renditions_or_not_found(image, specs)
     27 """
     28 Like get_rendition_or_not_found, but for multiple renditions.
     29 Tries to get / create the renditions for the image or renders not-found images if the image does not exist.
   (...)
     32 :param specs: iterable of str or Filter
     33 """
     34 try:
---> 35     return image.get_renditions(*specs)
     36 except SourceImageIOError:
     37     Rendition = image.renditions.model

File ~/myproject/.venv/lib/python3.12/site-packages/wagtail/images/models.py:566, in AbstractImage.get_renditions(self, *filters)
    563     Rendition.cache_backend.set_many(cache_additions)
    565 # Make sure key insertion order matches the input order.
--> 566 return {filter.spec: renditions[filter] for filter in filters}

KeyError: <wagtail.images.models.Filter object at 0x107ed3a10>
```

A little time in the debugger at the point of exception shows this:

```python
ipdb> [rf.spec for rf in renditions.keys()]
['width-400', 'width-800']
ipdb> [f.spec for f in filters]
['width-400', 'width-800', 'width-400', 'width-800']
```

It appears maybe the filters are getting de-duplicated in one spot, but not another?

### Technical details

-   Python version: 3.12.5
-   Django version: 5.1
-   Wagtail version: 6.2.1

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by thibaudcolas** [comment] 2024-09-05 10:40
Hi @eykd, thank you for the solid bug report!

I can reproduce this on our bakerydemo website, for example on the [homepage picture tag usage](https://github.com/wagtail/bakerydemo/blob/63c95cac3bd39d863604b8b40bbfedeb18aaed88/bakerydemo/templates/base/home_page.html#L58).

Looking at our test suite it’s very light for `preserve-svg` ([one test method](https://github.com/wagtail/wagtail/blob/954519390753ab47b1f43c05d377496fe38f8c93/wagtail/images/tests/test_templatetags.py#L80)), and we didn’t add any tests for it in combination with `srcset_image`. So yes I suspect we’re missing a code path. The bug is probably in the [get_filters logic](https://github.com/wagtail/wagtail/blob/954519390753ab47b1f43c05d377496fe38f8c93/wagtail/images/templatetags/wagtailimages_tags.py#L168-L172) to decide what renditions to generate based on the provided arguments.


We don’t have any SVG images or `preserve-svg` usage, so should add that too, that will help in fixing this bug now and making sure it works in the future (see [bakerydemo#457](https://github.com/wagtail/bakerydemo/issues/457)).

**Comment by laymonage** [comment] 2024-09-05 10:59
@thibaudcolas Note that this seems related or similar to #10868, #11439, #11570, and #12008. There's also an existing PR #12011.

**Comment by thibaudcolas** [comment] 2024-09-05 15:19
Thank you, I believe this is a dupe of #11570.

**Closed by thibaudcolas** 2024-09-05 15:19 UTC
Labels: type:Bug, component:Images
