### ISSUE TITLE
Deleting comment in storybook is broken

### ISSUE THREAD

**Issue by PaarthAgarwal** [wagtail/wagtail#9098] opened 2022-08-29 19:41 UTC
Deleting comment is no longer appearing in storybook. It's throwing errors.

![Screenshot from 2022-08-30 01-01-18](https://user-images.githubusercontent.com/86092410/187284101-47a16f9b-0278-4179-8aff-3dfc6fa79c6c.png)

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details
Wagtail version: Latest main branch
Browser version: Chrome 98 (Edge on Ubuntu)

**Comment by lb-** [comment] 2022-08-29 19:49
Duplicate of https://github.com/wagtail/wagtail/issues/8031

**Closed by lb-** 2022-08-29 19:49 UTC
Labels: type:Bug, status:Unconfirmed
