### ISSUE TITLE
Rendition support for ImageFields

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6704] opened 2021-01-18 14:45 UTC
This is a feature request for [Django ImageField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#imagefield) to have Wagtails Rendition support. For example:

```
# models.py
class SomePage(Page):
    image = models.ImageField(...)

# some_page.html
{% load wagtailimages_tags %}
{% image page.image width-400 %}
```
Currently the `image` tag expects an ForeignKey to a Wagtail Image (this pseudo code will fail).

Some advantages of rendition support for image fields are:
- The image isn't displayed in the Image library.
- The image is tightly bound to the page permissions, the page revisions, page locking and  page privacy settings.
- Wagtail image fields, for example `avatar` can also use the same 'enhanced' ImageField and therefore be rendered in the frontend in specific sizes.
- Some images are per page only, like `og:image` meta tag. It makes sense to store it on the page.
- No double rendition engines. Projects don't need django-thumbnails, sorl-thumbnail or any other third-party package.

**Comment by tomkins** [comment] 2023-09-19 16:32
Duplicate of #755?

(Yes, would also love to see support for this at some point)

**Closed** 2023-09-19 16:34 UTC
Labels: type:Enhancement, component:Images
