### ISSUE TITLE
Set Page Privacy only on parent page.

### ISSUE THREAD

**Issue by JaredOzzy** [wagtail/wagtail#5502] opened 2019-08-14 08:00 UTC
I have a ParentPage and two ChildPages, the one is a DetailPage and the other SomePage(Multiple of these)

i want to set the ParentPage access to only have logged in users access the page, Logged in Users should also be able to access the detail Page, but only users with specific permissions should be able to access the SomePage pages, but if i set the permission for the parentpage to logged in required it goes to all child pages of that page and i cannot set any specific permissions on those child pages. such as those pages require a user with a specific group etc.

### Steps to Reproduce

1. Create 3 Page Models, a ParentPage, DetailPage and AnotherPage
2. AnotherPage and DetailPage should be children of ParentPage.
3. Create the pages in wagtail cms
4. Change the ParentPage privacy permissions in wagtail
5. cannot change child page permissions

### Technical details

wagtail==2.6

**Comment by JaredOzzy** [comment] 2019-08-14 08:06
Actually think This this relates to  #4277

**Comment by ParitoshKabra** [comment] 2022-03-15 15:16
@loicteixeira It seems this issue still persists. Can I work on this?

**Comment by lb-** [comment] 2022-03-15 19:54
@ParitoshKabra go for it. No need to ask for permission to work on something. 

However, I recommend you first attempt to reproduce the issue on the latest wagtail code and report back on this issue with your findings. 

Then, if you feel confident to fix it - go for it. 

Please also remember to include unit tests.

**Comment by laymonage** [comment] 2024-07-29 15:03
As mentioned in the second comment, I think this is a duplicate of #4277. Not sure why this issue was reopened after it was closed, so it's probably a mistake.

**Closed by laymonage** 2024-07-29 15:03 UTC
Labels: type:Bug, component:Privacy
