### ISSUE TITLE
FieldPanel should use SlugInput widget for Slugfield by default - necessary for correct auto-slugifying titles

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#11185] opened 2023-11-04 03:16 UTC
### Is your proposal related to a problem?

Not a problem, just an inconvenience ;-)

To correctly auto-update a slug field from a title field, it currently requires adding `widget=SlugInput` to the slug `FieldPanel` declaration. Without this, the title text is just copied without being slugified.

```python
    title = models.CharField(
        max_length=255, 
        verbose_name=_("Menu Title"),
        help_text=_("A descriptive name for this menu (not displayed)")
    )
    slug = models.SlugField(unique=True)

    panels = [
        TitleFieldPanel("title"),
        FieldPanel("slug"),
    ]
```

![image](https://github.com/wagtail/wagtail/assets/72310199/96f56054-2d62-4223-96ff-9eeb56672886)

### Describe the solution you'd like

Specifying the `SlugInput` widget for the slug field fixes this:

```python
from wagtail.admin.widgets.slug import SlugInput
....
    panels = [
        TitleFieldPanel("title"),
        FieldPanel("slug", widget=SlugInput),
    ]
```

![image](https://github.com/wagtail/wagtail/assets/72310199/280b905e-6fe1-48d4-b916-5a104c686013)

For fields of type `SlugField`, `FieldPanel` should select `SlugInput` for the widget by default.

**Comment by Temidayo32** [comment] 2023-11-04 13:15
@enzedonline what wagtail version are we talking about here. Cause it appears if there was this issue it might have been fixed in later versions of Wagtail. Version 5.1.1, 5.2 I tested locally displays the expected behaviour.
![chrome_A0QdoX8h8j](https://github.com/wagtail/wagtail/assets/87539866/3418d2fe-9aef-408a-bf3f-b160953849df)

**Comment by lb-** [comment] 2023-11-04 22:08
@enzedonline was this in a page model or a non-page model?

By the looks of your screenshot, I'm guessing this is a non-page model. 

I think we only set the slug widget on Page models.

I'm not sure on a global default, I guess we do that for tags, dates, choosers and others though.

**Comment by pySilver** [comment] 2023-11-07 22:29
I've had a recent issue with my `CategoryPage` model that uses custom `TabbedInteface` this way:

```python
content_panels = BasePage.content_panels + [
        FieldPanel("description"),
        # ...
    ]

    autodiscovery_panels = []  # many panels here
    promote_panels = [
        MultiFieldPanel(
            [
                FieldPanel("slug", widget=SlugInput),   # Without explicitly defined widget field wasn't working
                FieldPanel("seo_title"),
                # ...
            ],
            _("Common page configuration"),
        )
    ]

    edit_handler = TabbedInterface(
        [
            ObjectList(content_panels, heading=_("Content")),
            ObjectList(promote_panels, heading=_("Promote")),
            ObjectList(autodiscovery_panels, heading=_("Products autodiscovery")),
            ObjectList(
                BasePage.settings_panels, heading=_("Settings"), classname="settings"
            ),
        ]
    )
````

For some reason `FieldPanel("slug")` did not pick up the proper widget automatically. Thankfully I was quickly saved by awesome chat support on Slack.

**Comment by enzedonline** [comment] 2023-11-07 23:36
@Temidayo32 it's on Wagtail 5.0.x and 5.1.x, since the synchronisation switched to using Stimulus

@LB yes, this is a snippet model

**Comment by enzedonline** [comment] 2023-11-29 20:54
I just came across this again on a site that had recently been upgraded to 5.x

The promote panel for all pages had always been defined with:

```python
    promote_panels = [
        MultiFieldPanel([
            FieldPanel('slug'),
            FieldPanel('search_image'),
            FieldPanel('seo_title'),
            FieldPanel('search_description'),
        ], _('SEO Page Configuration')),
        MultiFieldPanel([
            FieldPanel('search_engine_index'),
            FieldPanel('search_engine_changefreq'),
            FieldPanel('search_engine_priority'),
        ], _("Search Engine Indexing")),
    ]
```

The auto slug had stopped slugifying and just copied the title instead. I needed to add the SlugInput widget to remedy.

**Comment by lb-** [comment] 2023-12-06 22:31
Adding needs design decision to get feedback from others in the core team.

**Comment by thibaudcolas** [comment] 2023-12-13 09:58
Discussed in today’s core team meeting – happy for SlugInput to be the default widget for SlugField. Less friction for devs. Clear way to opt out. Needs to be flagged in release notes so the change is clear.

**Comment by laymonage** [comment] 2023-12-13 10:27
> I am not sure on the best way to do this

I was thinking about this as well.

> whether we add the widget in the base Page field definition here

I don't think it's possible to set the widget on the `Page` model (model fields do not accept a `widget` kwarg, form fields do).

> Or on the model's meta widgets (but we are not doing that for Page that I can see at all).

Nor is this possible, I believe `Meta.widgets` is only available in the `ModelForm` class, not the model itself.

> Or maybe we use a similar approach to how we work with date widgets.

This is one way to do it, but the downside is that it will be applied to all `SlugField`s by default, not just `Page.slug`. I don't think it's ideal.

I think the right way to do this would be somewhere in the `WagtailAdminPageForm`:

https://github.com/wagtail/wagtail/blob/0024751a5380ee36c99b31e77fe4e52c8d586110/wagtail/admin/forms/pages.py#L132

which is nice because the `CopyForm` mentioned in a previous comment is placed just above this class.

That said, I haven't checked whether this will work or not, considering that the slug is defined via a `FieldPanel`. As in, I'm not sure if `FieldPanel` will automatically pick up the widget we define in `WagtailAdminPageForm`, or if it will override it with some other default widget for example.

**Comment by enzedonline** [comment] 2023-12-13 10:37
Good to hear this will be implemented. Thanks for that. 

It's important that this also happens when used on snippets, it's common to need an auto slug field in non-page models.

**Comment by laymonage** [comment] 2023-12-13 10:51
Ah, I just realised the `SlugInput` is only responsible for slugifying the input and not auto-syncing with the title field (or at least only half-responsible for that, the other half needs to be done via `SyncController` which is applied in `TitleFieldPanel` by default).

In that case, I think the registering the form field override makes sense, which ensures it's also picked up on Snippets (and anything that uses `WagtailAdminModelForm`).

**Comment by lb-** [comment] 2023-12-14 22:06
PR up for review https://github.com/wagtail/wagtail/pull/11341

**Closed** 2024-01-02 13:44 UTC
Labels: type:Enhancement, component:Page, javascript, component:Stimulus
