### ISSUE TITLE
Allow users to update user-, first-, lastname

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4501] opened 2018-04-29 15:21 UTC
In the current implementation, users who can access Wagtail admin can’t update their username etc.
Unless the 'can change user' permission is enabled for the users member group.

I guess a 'change user settings view' to enable this isn’t hard to implement, is it?

Cheers,

Rob

**Comment by chrisranjana** [comment] 2018-06-05 09:59
Submitted a pull request https://github.com/wagtail/wagtail/pull/4585

**Comment by lb-** [comment] 2019-12-22 03:49
Closing as a duplicate of #615 which is now resolved as part of PR #5425 & merged in via https://github.com/wagtail/wagtail/commit/31e3dab4ec3ddad9d18e342df206ca7dcc925e8f

**Closed by lb-** 2019-12-22 03:49 UTC
Labels: component:User Management
