### ISSUE TITLE
Custom document model with inherited fields doesn't render inherited fields in upload form

### ISSUE THREAD

**Issue by jeffreyckchau** [wagtail/wagtail#3629] opened 2017-06-05 20:44 UTC
### Issue Summary

We are using a custom document model that includes a mixin that declares some options (boolean) options fields. These fields are rendered during the edit view and show up in the DB, but are missing during the upload/multiple view. 

### Steps to Reproduce

Starting with a basic wagtail installation:

Document model: 
```
class DocumentWithMixin(AbstractDocument, DocumentMixin):

    admin_form_fields = Document.admin_form_fields + ('my_boolean_field', 'my_second_boolean_field')
```

Mixin code:
```
class DocumentMixin(models.Model):

    my_boolean_field = models.BooleanField(default=False, help_text="Here have some help text")
    my_second_boolean_field = models.BooleanField(default=False, help_text="Here have some help text")

    class Meta:
        abstract = True
```

Expected result: All fields declared both in the model and and the mixin are editable during the multiple upload form.

Actual result: Only the name, collection, and tag fields are rendered.

I see that the document upload form and document multiple upload form take a different subset of fields. This is probably the cause. Is there a good reason for this, or should we unify the form production? 

### Technical details

* Python version: 2.7.8
* Django version: 1.11
* Wagtail version: 1.10
* Browser version: Chrome 58

**Comment by lb-** [comment] 2017-11-19 08:07
@jeffreyckchau this appears to be a duplicate of #3921 and there is a current PR in progress relating to that issue: #3928

**Closed by lb-** 2017-11-19 08:07 UTC
