### ISSUE TITLE
Now work images in loop for

### ISSUE THREAD

**Issue by Vladorld** [wagtail/wagtail#10321] opened 2023-04-06 23:10 UTC
In template:
```
{% for post in blogpages %}
    {{ post.title }}
    {% image post.imagepost original %}
{% endfor %}
```
The title is displayed, but the image is not. The models are standard for the blog. The image is uploaded through the admin panel and is in the database.

### Technical details

-   Python 3.11.1
-   Django Version: 4.1.8
-   Wagtail Version: 4.2.2
-   Browser version: Chrome 111

**Comment by Vladorld** [comment] 2023-04-07 01:56
Chatgpt gave the answer
`{% image post.specific.imagepost original %}`

**Comment by lb-** [comment] 2023-04-07 02:13
Thanks @Vladorld glad you got it sorted - please use the recommended support methods in the future for general questions. 

https://github.com/wagtail/wagtail#-community-support

I'll close this as it's not a bug.

**Closed by lb-** 2023-04-07 02:13 UTC
Labels: type:Bug, status:Unconfirmed
