### ISSUE TITLE
Draftail extension wagtailcolourpicker stops working with webpack 4 (since wagtail 2.11)

### ISSUE THREAD

**Issue by favoyang** [wagtail/wagtail#6724] opened 2021-01-24 03:55 UTC
### Issue Summary

wagtailcolourpicker is a colour picker for Wagtail's DraftJS editor. The project is archived but @Vadim-Karpenko managed it to work with later wagtail versions.

https://github.com/Vadim-Karpenko/wagtailcolourpicker

The plugin works fine with wagtail v2.10.2 but failed with v2.11. After some digging, I found that it failed with the webpack 4 upgrades for the v2.11. The last working commit is accdbd21742219a1e78660755b2630ca1b77334a, and failed since de2d66e08e6555dd69ca02eeb1a5d9f6ef5f07f7.

![image](https://user-images.githubusercontent.com/125390/105620421-e69a0d80-5e37-11eb-832c-31cdefaff001.png)

When clicking the _text color_ icon on the draftail editor, the editor crashed with the below information.
![image](https://user-images.githubusercontent.com/125390/105620438-2cef6c80-5e38-11eb-8868-a926be59e151.png)

![image](https://user-images.githubusercontent.com/125390/105620461-645e1900-5e38-11eb-87e8-034b0706a1ba.png)

```js
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DraftailEditor`.

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DraftailEditor`.
    at createFiberFromTypeAndProps (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:35332:21)
    at createFiberFromElement (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:35355:15)
    at updateElement (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:24947:19)
    at updateFromMap (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:25108:20)
    at reconcileChildrenArray (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:25292:24)
    at reconcileChildFibers (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:25672:14)
    at reconcileChildren (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:28136:28)
    at updateHostComponent (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:28669:3)
    at beginWork (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:29994:14)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:8001/static/wagtailadmin/js/vendor.js?v=63f5a5ce:11555:14)

    in div (created by DraftailEditor)
    in DraftailEditor
    in EditorFallback
```

### Steps to Reproduce

1. Start a new project with `wagtail start mysite`
2. Install a wagtail debug version, so you can see more React debug information
  - Clone wagtail to a folder, say "../wagtail"
  - Checkout a commit `git checkout de2d66e08e6555dd69ca02eeb1a5d9f6ef5f07f7`
  - Build a debug version, `npm install --no-save && npm run watch`
  - Install the version, `pip install -e '../wagtail[testing,docs]'`
3. Install wagtailcolourpicker. To make it easier to debug, let's install from the source "../wagtailcolourpicker"
```sh
cd ..
git clone git@github.com:Vadim-Karpenko/wagtailcolourpicker.git
cd mysite
pip install -e '../wagtailcolourpicker'
```
4. Add `"wagtailcolourpicker"` to the `INSTALLED_APPS`
5. Add some colors to settings
```py
WAGTAILCOLOURPICKER_COLOURS = {
    "black": "#000000",
    "blue": "#004d99",
    "cyan": "#22b8cf",
    "orange": "#fd7e14",
    "purple": "#4f0862",
    "spruce green": "#077452",
    "red": "#c80813",
    "white": "#fff",
}
WAGTAILCOLOURPICKER_COLOURS_FEATURES = ["colour_%s" % x[0] for x in WAGTAILCOLOURPICKER_COLOURS.items()]
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    "default": {
        "WIDGET": "wagtail.admin.rich_text.DraftailRichTextArea",
        "OPTIONS": {
            "features": [
                "bold",
                "italic",
                "underline",
                "h2",
                "h3",
                "h4",
                "ol",
                "ul",
                "hr",
                "link",
                "document-link",
                "image",
                "embed",
                "textcolour",
                *WAGTAILCOLOURPICKER_COLOURS_FEATURES,
            ]
        },
    },
}
```
6. Create a model with a RichTextBlock
```py
from django.db import models

from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.core.blocks import RichTextBlock
from wagtail.core.fields import StreamField
from wagtail.core.models import Page


class HomePage(Page):
    pass


class BasicPage(Page):

    body = StreamField([
        ('rich_text', RichTextBlock())
    ])

    # show in menu ticked by default
    show_in_menus_default = True

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]

```
7. Run `python manage.py migrate`
8. Start the server
9. Go to the admin backend, create the new page. Click the `Text Colour` icon on the draftail editor toolbar. You will see the error above.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Now rebuild the wagtail with commit accdbd21742219a1e78660755b2630ca1b77334a, you will see the plugin works again.

![image](https://user-images.githubusercontent.com/125390/105620679-7640bb80-5e3a-11eb-9a88-e01fa183529e.png)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: Python 3.6.9
* Django version: v3.1.5
* Wagtail version: See above
* Browser version: Chrome 87

**Comment by gasman** [comment] 2021-01-24 16:01
Hi @favoyang - thanks for the report.
To confirm this as a Wagtail bug, we'd need to verify that this isn't caused by wagtailcolourpicker calling undocumented internal Wagtail APIs - these are liable to change on any release, and we can't be responsible for third-party extensions breaking as a result of that.

**Comment by favoyang** [comment] 2021-01-24 18:39
@gasman 

Thanks for the comment.

The wagtail integration is in https://github.com/Vadim-Karpenko/wagtailcolourpicker/blob/master/wagtailcolourpicker/wagtail_hooks.py. It seems trivial.

Because it is a webpack related issue, the fails right after the webpack update. It maybe relates to the js part. https://github.com/Vadim-Karpenko/wagtailcolourpicker/blob/master/wagtailcolourpicker/static/colourpicker/js/colourpicker.js

**Comment by thibaudcolas** [comment] 2021-01-26 16:25
Thank you for the report @favoyang! It’s pretty clear from your description that something is broken since the Webpack 4 config changes, although it’s unclear to me what exactly.

Investigating this with a dummy extension, the issue seems to be with the `draftail.js` bundle being executed twice – once before the plugin loads, and once after. That second run will reset the client-side registry of Draftail plugins, thereby causing the crash when the editor attempts to display the correct plugin’s `source` component.

I’ll spend more time on this tomorrow to figure out why the Webpack switch caused this, and what options we have to fix it.

**Comment by favoyang** [comment] 2021-01-26 17:18
@thibaudcolas,

Thanks for the help. Looks like you already made some progression.

https://github.com/Vadim-Karpenko/wagtailcolourpicker/blob/master/wagtailcolourpicker/wagtail_hooks.py#L40-L45

Just found that the plugin manually references `wagtailadmin/js/draftail.js` in the `insert_editor_js` hook. But seems the author has a reason to do that from the comment.

```
def insert_editor_js():
    js_files = [
        # We require this file here to make sure it is loaded before the other.
        'wagtailadmin/js/draftail.js',
        'colourpicker/js/colourpicker.js',
    ]
```

I try to remove that line `wagtailadmin/js/draftail.js`, but it didn't help. So maybe not related.

**Comment by thibaudcolas** [comment] 2021-02-12 10:53
I’m currently completely swamped so haven’t had time to look at this any further, even though this seems like a big bug to me. It probably makes Wagtail 2.11 unusable for people who rely on those APIs.

If others want to take a look please feel free to – for me I’ll return to this on Friday 19th of Feb, one week from now.

**Comment by gasman** [comment] 2021-02-15 18:14
I think the `insert_editor_js` hook is indeed the problem here. This would have started outputting `wagtailadmin/js/draftail.js` twice starting from Wagtail 2.7, when Wagtail started [wrapping its own JS includes in `versioned_static`](https://github.com/wagtail/wagtail/blob/v2.7/wagtail/admin/rich_text/editors/draftail/__init__.py#L28). As a result, the two references to `wagtailadmin/js/draftail.js` would no longer compare as equal when Django tried to figure out the correct import order.

Evidently the double include of draftail.js still continued working "by accident" up until the webpack change...

I'd say that wagtailcolourpicker's use of insert_editor_js to insert colourpicker.js isn't really correct here - it should be declaring it as part of the plugin's media. I was able to fix it for current Wagtail by changing wagtail_hooks.py as follows:

```python
@hooks.register('insert_editor_js')
def insert_editor_js():
    js_includes = format_html(
        "<script>window.chooserUrls.colourChooser = '{0}';</script>",
        reverse('wagtailcolourpicker:chooser')
    )
    return js_includes


@hooks.register('register_rich_text_features')
def register_textcolour_feature(features):
    # register all colour features
    register_all_colour_features(features)

    # register the color picker
    feature_name = 'textcolour'
    type_ = feature_name.upper()

    control = {
        'type': type_,
        'icon': get_setting('ICON'),
        'description': _('Text Colour'),
    }

    features.register_editor_plugin(
        'draftail',
        feature_name,
        draftail_features.EntityFeature(
            control,
            js=[
                'colourpicker/js/chooser.js',
                'colourpicker/js/colourpicker.js',
            ],
        )
    )

    features.default_features.append(feature_name)
```
I'll open a PR for wagtailcolourpicker shortly.

Since the double-inclusion of draftail.js here was ultimately caused by an unsupported 'hack' in the plugin, I'll close this as wontfix - although if @thibaudcolas or anyone else thinks it would be a relatively quick win to fix whatever broke in the webpack upgrade to allow it to work again when included twice, I wouldn't say no to that :-)

**Closed by gasman** 2021-02-15 18:14 UTC
Labels: component:Rich text, type:Bug

**Comment by thibaudcolas** [comment] 2021-02-15 22:59
👍  Nice catch! I think I’m still interested in investigating this to understand the impact on other extensions of Wagtail in JavaScript, if any. For all Draftail entities, usage of the EntityFeature’s media files is definitely more correct.

We had introduced this in [Wagtail v2.2](https://docs.wagtail.io/en/stable/releases/2.2.html), so that also explains why there might be a fair amount of code out there using `insert_editor_js`.

**Comment by favoyang** [comment] 2021-02-16 16:51
Thank you for the fix and the PR. will test it soon.
