### ISSUE TITLE
Richtext editor converter AssertionError

### ISSUE THREAD

**Issue by vladox** [wagtail/wagtail#5832] opened 2020-02-17 12:35 UTC
### Issue Summary

When trying to edit synchronized content on a page the RTE converter is complaining about unmatched end tags for BR tags:

`Unmatched tags: expected br, got p`

### Steps to Reproduce

1. edit RTE field in DB to have look like `<p>Something<br>somthing else</p>`
2. Try to edit page in admin 
3. Unmatched tags: expected br, got p error is returned 
4. Changing filed content to `<p>Something<br/>somthing else</p>` solves the problem 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

standalone br tags are valid standalone tags, linebreaks django function returns them without the trailing forward slash (/)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: Python 3.6.8
* Django version: Version: 2.2.10
* Wagtail version: Version: 2.7.1
* Browser version: Version 80.0.3987.66 (Developer Build) Ubuntu 19.10 (64-bit)

**Comment by thibaudcolas** [comment] 2022-04-11 09:22
Hi @vladox, I see this hasn’t been discussed in over two years so I’m going to close this now.

From my perspective this is working as intended – Wagtail’s rich text storage format is a bespoke XML dialect, where we chose the trailing slash in `<br/>` isn’t optional. If we supported both `<br>` and `<br/>`, we’d still have our code only output one of the two, which would lead to rich text content changing between versions of a page even though the visible content is the same.

It would be nice for us to document this `<br/>` requirement better on our [rich text internals](https://docs.wagtail.org/en/stable/extending/rich_text_internals.html) page (PRs welcome!), or in an ideal world, to have an "arbitrary HTML to Wagtail XML" import function (third-party package welcome!).

**Closed by thibaudcolas** 2022-04-11 09:22 UTC
Labels: type:Bug
