### ISSUE TITLE
Allow to edit one-to-one related objects

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#4408] opened 2018-03-21 12:29 UTC
Currently Wagtail allows to edit many-to-one relations using [`InlinePanel`](http://docs.wagtail.io/en/v2.0/reference/pages/panels.html#inlinepanel), but there is no way to edit one-to-one relations.

This can be useful when you want to attach some meta information to a page or a snippet.

Meta information for all pages, probably, is the most useful use case. So you define one-to-one relation with the `wagtailcore.Page` model and enable edit panels where you need them without creating a new non-abstract base page for all pages on your website.

This can be useful for things like listing title, listing image and listing description. All pages need these fields, but most likely you are going to use these fields only in page teasers on listing pages.

I think, in the editing interface related fields should look absolutely the same as model's own fields, because from editor's point of view it doesn't make much difference where the data is stored. 

I guess, it will require changes in `django-modelcluster`.

**Comment by marteinn** [comment] 2020-08-02 12:56
Related: https://github.com/wagtail/wagtail/issues/1831

**Comment by thibaudcolas** [comment] 2024-11-01 16:41
Dupe of #1831

**Closed by thibaudcolas** 2024-11-01 16:41 UTC
Labels: type:Enhancement
