### ISSUE TITLE
Field defined in `exclude_fields_in_copy` still gets copied

### ISSUE THREAD

**Issue by Tijani-Dia** [wagtail/wagtail#10001] opened 2023-02-01 15:43 UTC
### Issue Summary

When I copy a page in the admin, some fields get copied even if they're added to the `exclude_fields_in_copy` list.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows:
```python
from django.db import models

from wagtail.models import Page
from wagtail.admin.panels import FieldPanel


class HomePage(Page):
    pass


class TestPage(Page):
    name = models.CharField(max_length=255, default="name")

    content_panels = Page.content_panels + [FieldPanel("name")]

    exclude_fields_in_copy = ["name"]
```
3. Create a `TestPage` in the admin UI and set any value other than the default one for the `name` field e.g `original`:

![original](https://user-images.githubusercontent.com/71412737/216087671-9b893176-8cdf-473f-b177-24c4a4f8e2d7.png)

4. Copy the page (without ticking the `Publish copied page` and `Alias` checkboxes):

![copy](https://user-images.githubusercontent.com/71412737/216088395-ea7a5540-41f5-4daf-a97e-ec079a428269.png)

5. Go to the edit view for the copied page: **the name value is copied from the original page** 

![edit-copied-page](https://user-images.githubusercontent.com/71412737/216089032-f9a15f76-40a1-4571-b3c6-5e18c7d7272c.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- Since I've added the `name` field in the `exclude_fields_in_copy` list, I'd expect the copied page to have the default value for that field.

- I wasn't able to reproduce the issue with the latest Wagtail version (4.1.1)

- I don't have any issue when I tick the `Publish copied page` checkbox

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.0.9
-   Wagtail version: 3.0.3
-   Browser version: Chrome 109

**Comment by zerolab** [comment] 2023-02-01 16:14
@Tijani-Dia considering we no longer support 3.x and you cannot reproduce in 4.1.x I suggest we close with "won't fix"

**Comment by laymonage** [comment] 2023-02-01 16:20
It's weird that this showed up in 3.0.3 though, considering it was supposed to be fixed in #8048 (which was merged before 3.0rc1).

**Comment by Tijani-Dia** [comment] 2023-02-01 17:01
It's weird indeed. I've been able to add a failing test:

```python
def test_page_with_exclude_fields_in_copy_bug(self):
        original_page = self.test_page.add_child(
            instance=PageWithExcludedCopyField(
                title="Page with exclude_fields_in_copy",
                slug="page-with-exclude-fields-in-copy",
                content="Copy me",
                special_field="Don't copy me",
            )
        )
        original_page.save_revision().publish()
        post_data = {
            "new_title": f"{original_page.title} 2",
            "new_slug": f"{original_page.slug}-2",
            "new_parent_page": str(self.test_page.id),
            "copy_subpages": False,
            "publish_copies": False,
            "alias": False,
        }
        self.client.post(
            reverse("wagtailadmin_pages:copy", args=(original_page.id,)), post_data
        )
        # Get copy
        page_copy = PageWithExcludedCopyField.objects.get(slug=post_data["new_slug"])
        self.assertEqual(page_copy.content, original_page.content)
        self.assertNotEqual(page_copy.special_field, original_page.special_field)
        self.assertEqual(
            page_copy.special_field, page_copy._meta.get_field("special_field").default
        )
        # This fails
        self.assertEqual(page_copy.get_latest_revision().content["special_field"], page_copy.special_field)
```

It seems that the data in the page instance is correct initially but the latest revision attached to it reflects the changes in the original page. Therefore, when publishing the revision, the initial value gets overridden.

**Comment by Tijani-Dia** [comment] 2023-02-01 17:02
@zerolab, I wasn't able to reproduce it with Wagtail 4.0 either so I think it'd be legitimate to close as wontfix.

**Closed** 2023-02-01 17:22 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by drimacus182** [comment] 2024-01-08 14:07
It reproduces in Wagtail 5.2.2 #11428

**Comment by drimacus182** [comment] 2024-01-08 18:25
I've found an interesting detail. While the test @Tijani-Dia attached above passes, a `name` value rendered in admin edit page is not the same as a name in the database. Also, the `name` inside the latest revision of the copy is the same as in original page:
```python3
>>> from home.models import TestPage
>>> copy = TestPage.objects.get(slug='copy')
>>> copy.name
'name'
>>> copy.latest_revision.content['name']
'original'
>>> 
```
