### ISSUE TITLE
When creating/updating a site in Firefox 60.9, I'm unable to set the root page

### ISSUE THREAD

**Issue by ryannowarm** [wagtail/wagtail#5657] opened 2019-10-26 18:36 UTC
### Issue Summary
When creating/updating a site in Firefox 60.9, I'm unable to set the root page.  When clicking the page in the root page selector modal, nothing happens.  The modal remains.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Go to the default site in Firefox 60.9
3. Try to set the root page
4. Nothing happens (the modal stays)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.7.3
* Django version: 2.2.6
* Wagtail version: 2.6.3
* Browser version: Firefox 60.9

**Comment by loicteixeira** [comment] 2019-10-28 18:11
I'm unable to reproduce with Wagtail 2.7a and Firefox 70.0. Arguably those aren't the exact same version but that's what I had handy for a quick test.

Could you open the Console (under Tools > Web Developer > Web Console) and share whatever error message you are seeing? Make sure to open the console before navigating to the site settings page and copy the errors after experiencing the bug again.

Also, do this still happens after [clearing the cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache)?

**Comment by gasman** [comment] 2019-11-13 10:26
Closing due to lack of update - if you can provide the requested information, we'll be happy to investigate further.

**Closed by gasman** 2019-11-13 10:26 UTC
Labels: component:Frontend, component:Multi-site, status:Needs Info, type:Bug
