### ISSUE TITLE
Unique constraint for the WorkflowState

### ISSUE THREAD

**Issue by byshen** [wagtail/wagtail#8088] opened 2022-03-08 01:03 UTC
### Issue Summary

Currently, the `WorkflowState` describes the state of the workflow for a given page. The unique constraints in file `wagtail/core/models/__init__.py` describes that the state for a given page should be unique for status `in_progress` or `needs_changes`.

However, I feel that the state should be unique for the page in each workflow, otherwise it would be possible that the page  in the same workflow has different states, which may indicate that the data is wrong.

Currently,
```python
class WorkflowState(models.Model):
    ...
    class Meta:
        ...

        # prevent multiple STATUS_IN_PROGRESS/STATUS_NEEDS_CHANGES workflows for the same page. This is only supported by specific databases (e.g. Postgres, SQL Server), so is checked additionally on save.
        constraints = [
            models.UniqueConstraint(
                fields=["page"],
                condition=Q(status__in=("in_progress", "needs_changes")),
                name="unique_in_progress_workflow",
            )
        ]
```

This may be improved by adding the constraint

```python
class WorkflowState(models.Model):
    ...
    class Meta:
        ...

        # prevent multiple STATUS_IN_PROGRESS/STATUS_NEEDS_CHANGES workflows for the same page. This is only supported by specific databases (e.g. Postgres, SQL Server), so is checked additionally on save.
        constraints = [
            models.UniqueConstraint(
                fields=["page"],
                condition=Q(status__in=("in_progress", "needs_changes")),
                name="unique_in_progress_workflow",
            ),
+            models.UniqueConstraint(
+                fields=["page", "workflow"],
+                name="unique_page_in_workflow",
            )
        ]
```

Please let me know your thoughts. Thanks a lot.
### Technical details

* Python version:3 .8.8
* Django version: 4.0.2
* Wagtail version: 2.17a0
* Browser version: Chrome/99.0.4844.51 Safari/537.36

**Comment by byshen** [comment] 2022-03-16 21:26
@gasman Could you help take a look? This is similar to #8089. I can create a PR to fix if needed. Thanks

**Comment by lb-** [comment] 2022-03-24 11:21
See https://github.com/wagtail/wagtail/issues/8089#issuecomment-1077518164 - due to limited DB support, flagging this as an optimisation for now and not a bug.

**Comment by lb-** [comment] 2022-04-20 09:17
Closing as per comments
https://github.com/wagtail/wagtail/pull/8152#issuecomment-1103677236
https://github.com/wagtail/wagtail/issues/8089#issuecomment-1103680226

We may reopen in the future.

**Closed by lb-** 2022-04-20 09:17 UTC
Labels: type:Cleanup/Optimisation, component:Workflow
