### ISSUE TITLE
Broken images in admin menu on Safari

### ISSUE THREAD

**Issue by juliaranne** [wagtail/wagtail#3927] opened 2017-10-11 17:30 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When logging in to admin there are three or four broken images over the left hand menu. It seems to be an issue with Safari browser.

### Steps to Reproduce
Log in to admin on Safari v11.0
![screen shot 2017-10-11 at 09 58 15](https://user-images.githubusercontent.com/14149821/31456456-bde4c634-aeb1-11e7-969e-4b02e91b3ef3.png)

### Technical details

* Python version: Run `python --version`.
2.7.10
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
1.9.1
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
1.5
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.
Safari 11.0

**Comment by gasman** [comment] 2017-10-12 11:18
Thanks for the report @juliaranne. When we've seen similar issues elsewhere (#3809 #3811), it's just needed a force-refresh to fix - please can you try holding down shift while clicking the refresh button in the location bar?

(Also, you say you're using Wagtail 1.5 but your screenshot shows 1.12.2 - is 1.5 the result of running `pip show wagtail | grep Version:`? Having two conflicting versions of Wagtail probably wouldn't help here.)

**Comment by juliaranne** [comment] 2017-10-18 13:53
Refreshing, clearing my cache/history doesn't seem to work for this.

Yes, my mistake I'm running version 1.12.1 locally. We have another website using Wagtail version 1.13 where there's no problem, so seems it's just an issue with Safari and Wagtail version 1.12?

**Comment by thibaudcolas** [comment] 2017-10-25 10:59
Thanks for taking the time to look at this in multiple versions of Wagtail!

This part of the code has been changed a bit in 1.13 as part of the work on the new 404 page, although I don't see how this would have failed before. Reference: #3705, https://github.com/wagtail/wagtail/compare/stable/1.12.x...stable/1.13.x#diff-af73d62081be0b72ac854d96958429fb.

I can't reproduce this in the latest Wagtail (2.0a) either, so I think we can assume it was fixed in 1.13.  Closing.

**Closed by thibaudcolas** 2017-10-25 10:59 UTC
Labels: status:Needs info
