### ISSUE TITLE
Redirects do not work when using Django's i18n_patterns() wrapper

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#6587] opened 2020-11-27 00:00 UTC
### Issue Summary

When using Wagtail wrapped by Django's `i18n_patterns`, redirects only work for "exactly that URL" instead of also for the localised versions. E.g. `/from-page => /to-page` only works for `http://site/from-page` but not `http://site/en-us/from-page`. 

### Steps to Reproduce

1. Set up a standard wagtail install
2. follow the wagtail instructions on turning on internationalisation, with at least on `LANGUAGES` entry, I'd recommend `en-us`.
3. create a redirect for `/test` to the homepage.
4. navigate to `localhost:8000/test` and observe it redirecting to `localhost:8000`
5. navigate to `localhost:8000/es-us/test`
6. this is a 404 instead of redirecting properly

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

The fix for this is updating the wagtail.contrib.redirects middleware to, in `_get_redirect`, remove the locale prefix from the path to resolve, if `request.LANGUAGE_CODE` exists.

### Technical details

* Python version: 3.7.7
* Django version: 3.1
* Wagtail version: 2.11.2
* Browser version: irrelevant

**Comment by kaedroho** [comment] 2020-11-27 13:49
Sorry if I haven't fully understood the issue, but the existing behaviour looks like the expected behaviour to me. Redirects are supposed to bypass all of the page routing logic because they are mainly used to support legacy URLs or allow editors to define a shortened URL for a page. I'm not sure how also making them work with all the language prefixes by default helps either of these use cases.

**Comment by Pomax** [comment] 2020-11-27 18:39
When one uses wagtail-modeltranslation (which is recommended as one of the two localization strategies) there are no "different pages". Every localised page is _the same_ page, and redirects should kick in for everything with a local code. Right now, redirects simply don't work, at all, for setups that use that approach.

If there is additional code that can be checked to determine whether a wagtail instance is using "full, distinct, page trees" vs. "field-based localisation", then the PR can be improved to take that into account.

**Comment by kaedroho** [comment] 2020-11-27 22:57
> setting a redirect without the locale code will redirect only when users directly navigate to that specific unprefixed URL

This is exactly what the redirects module is supposed to do, if you need to redirect from a locale prefix then you can add this on to the redirect.

Since this issue is specific to ``wagtail-modeltranslation``, I think the best approach for solving this issue is probably going to be copying [middleware.py](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/redirects/middleware.py) into ``wagtail-modeltranslation`` and customising the logic there.

**Comment by Pomax** [comment] 2020-11-28 00:17
Can you go into what you mean with "you can add this on to the redirect"? How would one do that, and are there wagtaill docs already written so that folks can actually read up on how to do that? If not, those definitely need to be written and linked to on https://docs.wagtail.io/en/stable/advanced_topics/i18n.html?highlight=internationalisation

**Comment by kaedroho** [comment] 2020-11-28 11:11
Sorry if I wasn't clear enough. I meant add it to the redirect path.

So instead of creating a redirect for `/test`, you create a redirect with the path `/en-us/test` and this should give the behaviour you are looking for.

**Comment by Pomax** [comment] 2020-11-28 18:19
If I do that, the redirects do not work, so that is not the solution.

**Comment by ababic** [comment] 2021-01-03 22:08
Am closing this issue, as the redirects app was never designed to be compatible with `i18n_patterns`. I concur with @kaedroho that this would be best resolved as part of `wagtail-modeltranslation` - as the requirements seem quite specific to that approach (which I believe haven't been recommended as a localisation solution by Wagtail for some time).

**Closed by ababic** 2021-01-03 22:08 UTC
Labels: type:Enhancement

**Comment by Pomax** [comment] 2021-01-04 00:15
fair enough, but note that the docs still tell folks to use either wagtailtrans or wagtail-modeltranslations over on https://docs.wagtail.io/en/stable/advanced_topics/i18n.html?highlight=localization#alternative-internationalisation-plugins if they need an alternative, meaning it's basically one of the two official recommendations.

**Comment by raminjrmz** [comment] 2022-08-11 20:49
Same problem :(

**Comment by lb-** [comment] 2022-08-12 02:13
@raminjrmz this issue has been closed for some time - see above comments. 

I recommend you start a discussion about your problem and see if others can provide a work around. Or if you feel there is a bug that is not covered by this response above - maybe a new bug is needed.
