### ISSUE TITLE
popup container height jumps when searching snippets

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9891] opened 2023-01-14 15:09 UTC
### Is your proposal related to a problem?
I have long list of on snippet items. I added search to it so the user can find the correct snippet when editing his page. When you are adding a snippet to your page a nice popup opens with the search bar. 
However when you start searching your list will **go from 10 items to 0 items.** The consequence is that the **popup container height jumps**. When a result show up the container jumps again. This is could be done better by giving this container a fixed height. So the jumps in the container are not there

<img width="941" alt="snippet finder" src="https://user-images.githubusercontent.com/178425/212478705-a3e3fae0-b61e-4f99-8334-6eb443a2a4a4.png">

### Describe the solution you'd like
Give the popup container a fixed height. Or at least transition height that move not very fast.

### Describe alternatives you've considered
- Transition would also be nice.
- have a better search implementation???

**Comment by gasman** [comment] 2023-01-16 11:37
I think it's probably a matter of taste whether it's better to have the height jumping to adjust to the content, or to add a load of extra whitespace to keep it fixed - flagging this for a UI design decision.

**Comment by onno-timmerman** [comment] 2023-01-16 12:29
Wel the only argument I can give is that if you do the search autocomplete. And the list jumps from 10 items to 1 item then back to 8 items to then jump again in quick succession it's a bit much of jumping around.

**Comment by gasman** [comment] 2023-01-16 12:36
OK - in that case, what you're really looking for is a fix for #7720 (since if it performs an autocomplete search as intended, the list will progressively reduce rather than going down and back up again), so I'll close this as a duplicate.

**Closed by gasman** 2023-01-16 12:36 UTC
Labels: type:Enhancement, status:Needs UI Design
