### ISSUE TITLE
no horizontal scrollbar for breadcrumbs in editor

### ISSUE THREAD

**Issue by minusf** [wagtail/wagtail#9218] opened 2022-09-16 14:49 UTC
### Issue Summary

It seems that it's not possible to scroll horizontally anymore in the breadcrumbs in the page listings.

<img width="1082" alt="Screenshot 2022-09-16 at 16 37 35" src="https://user-images.githubusercontent.com/3632883/190666070-76c954fc-4f93-4863-b291-af4a2baf3bbf.png">

("Central" is cut off from "Central Asia something something")
### Technical details

-   Wagtail version: 4.0.1
-   Browser version: Chrome, Firefox

**Comment by minusf** [comment] 2022-09-16 15:37
bit of clarification.  the breadcrumb is there when hovering over the "arrow" in an `/edit/` page, it's not there in "folder" views.

**Comment by vicky1312** [comment] 2022-10-10 15:51
Hello, I would love to work on this issue.

**Comment by lb-** [comment] 2022-10-12 03:01
@vicky1312 can you please try to reproduce this issue - maybe add a recording and test in some other browsers. 

This bug is still flagged as unconfirmed so it would be good to get additional info and steps to reproduce before we work on a fix. 

Also, it might be helpful to add a comment where you think the issue is in the code. Not sure if it's a CSS issue or a JS one.

**Comment by vicky1312** [comment] 2022-10-13 09:51
@lb- Alright, I'm on it.

**Comment by vicky1312** [comment] 2022-10-13 15:44
@lb- I have tested this issue and I can see that there is a scroll bar
<img width="955" alt="Annotation 2022-10-13 164026" src="https://user-images.githubusercontent.com/63854917/195643287-6679a1a0-2c8d-4136-9a16-7685a8dbc8bd.png">

**Comment by vicky1312** [comment] 2022-10-14 23:54
@minusf Ahh, yes, yes. I can see it doesn't. I will check where the error is and try to recreate the issue

**Comment by vicky1312** [comment] 2022-10-15 11:23
##Issue Summary
The horizontal scroll bar does not appear in the header section of the wagtail admin pages.

Steps to Reproduce
1. Open wagtail admin
2. Navigate to pages
3. Open multiple pages
A horizontal scroll bar should appear if the pages are to0 large to fit the space, but it doesn't. The scroll bar, however, appears when editing.

- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project
- I have opened the site on both Chrome and Firefox to confirm that the issue persists across different browsers
 ##Google test

https://user-images.githubusercontent.com/63854917/195983840-1e800df9-cb8e-4acd-a271-a69efc511e3f.mp4

##Firefox test

https://user-images.githubusercontent.com/63854917/195983889-787c3c2a-644c-4ef3-8a08-33b7a8f609c9.mp4

**Comment by thibaudcolas** [comment] 2022-10-20 05:39
Thank you both for investigating this! I can also reproduce this in Wagtail v4.0.4, but it seems to have been fixed in [just freshly released](https://github.com/wagtail/wagtail/discussions/9410) v4.1rc1, most likely in #9090 by @stevedya.

I’ll close this now – if you can still reproduce in v4.1 once you’ve had a chance to try please re-open.

**Closed by thibaudcolas** 2022-10-20 05:39 UTC
Labels: type:Bug, status:Unconfirmed
