### ISSUE TITLE
Deprecate Hallo.js 

### ISSUE THREAD

**Issue by JoshBarr** [wagtail/wagtail#2409] opened 2016-03-28 21:37 UTC
The last commit on the Hallo.js master was Jun 12, 2015. I'm worried we're coupling a crucial function in Wagtail (editing text) to a package which seems to have gone off the boil somewhat. 

I would suggest migrating to Draft.js, as this supports our aspirations to move to a more React-driven frontend, as well as being more actively maintained and sporting a much nicer API to write plugins against. It's also used in production by _Facebook_. 

---

Edit: see progress updates at

- https://github.com/wagtail/wagtail/issues/2409#issuecomment-264019860
- https://github.com/wagtail/wagtail/issues/2409#issuecomment-277226739
- https://github.com/wagtail/wagtail/issues/2409#issuecomment-297354841

-----

There's some prerequisite work to do:
- [x] Allow for pluggable rich text editors (so that we don't backwards-break every Wagtail site) [#2416]
- [x] Create a new JSONField and a widget to control it. 
- [x] Allow for HTML export from a structured text editor, so that people who want to store Rich Text as HTML in the database can continue to do so. 
- [x] Write an extension to the `richtext` template filter to parse structured data into HTML. 

Check out the [Draft.js intro site](https://facebook.github.io/draft-js/)

Read an article about how Draft represents data on [Medium](https://medium.com/@rajaraodv/how-draft-js-represents-rich-text-data-eeabb5f25cf2#.cswovooto)

There's a solution for saving HTML if required, too: [Draft JS HTML export](https://github.com/sstur/draft-js-export-html)

**Comment by alexgleason** [comment] 2016-03-28 22:25
Nice. Love the way it represents data. I think everyone is in favor of switching to a better editor.

Side note: was playing with the demo hoping you could press tab to indent lists (see: #2212) but it doesn't seem so. Would be awesome if there's a way to do that with this.

**Comment by JoshBarr** [comment] 2016-03-28 22:39
I think Draft supports that tab-to-create-list functionality, but the demo doesn't have it enabled.

**Comment by SalahAdDin** [comment] 2016-03-29 01:05
:+1:

**Comment by robmoorman** [comment] 2016-03-29 09:55
Draft.js is perfect, +1!

**Comment by ababic** [comment] 2016-03-30 21:14
I wasn't overly impressed with the demo on the Draft.js homepage, but it's encouraging to see projects like https://github.com/sstur/react-rte (based on Draft.js). Their demo is much closer to how I'd expect a default rich-text widget in a CMS to behave. It looks like they got the 'tab-for-list-indentation' functionality enabled too, if you'd like to see it in action @alexgleason.

**Comment by SableWalnut** [comment] 2016-04-04 06:49
:+1:

**Comment by coredumperror** [comment] 2016-05-09 21:03
I'll also drop in my vote for Draft over Hallo.

**Comment by ddiazpinto** [comment] 2016-05-12 11:29
:+1:
I'm agree to stop using hallo.js but I think that It would be a terrible mistake only switch it by another, maintaining this way a high coupling between Wagtail and the editor system... I think that the best approach is make de editor pluggable even if Wagtail came with a recomended one.

**Comment by tomdyson** [comment] 2016-05-12 11:31
@ddiazpinto we agree! https://github.com/torchbox/wagtail/pull/2416

**Comment by BertrandBordage** [comment] 2016-05-12 13:46
Draft.js seems very good, but I’m concerned that it will add a lot of dependencies for something we can manage ourselves.
To me, **it sounds like an overkill** to use React and a bunch of other dependencies considering the requirements we have.

I made [a small demo](https://gist.github.com/BertrandBordage/cef9b4b1f3ac4c3e39424e48af1b85e6) showing how we can create a basic WYSIWYG editor with only jQuery in less than 2 hours & 200 lines. Compared to Draft.js, it mainly lacks a few selection/style application possibilities, a complete undo/redo feature, and a way to add more than simple tags. The undo/redo is what will really take some time (in order to make it clever), but it’s not a huge work. And it certainly doesn’t require React.

Plus, using Draft.js means we store a very complex JSON object, which requires us to create a renderer, leading to potential bugs, etc. In my opinion, **the optimal solution is to store HTML**.
But how do we store a link to a wagtail page? We don’t want to parse HTML before rendering it. The solution can be pretty simple: the WYSIWYG generates a Django template tag, like `<a href="{% url … %}">link</a>`. Of course, we need to validate these tags on the server-side, but then we only need to render that template.

I know this is very hypothetical, but it’s in my opinion the best solution. (And yes, you can guess I trust neither NPM nor Facebook ;) )

**Comment by gasman** [comment] 2016-05-12 14:14
@BertrandBordage We won't be changing our internal rich text data representation at the same time as switching to a new editor widget - IMHO that's too big a change to make in one go, and I would reject any PR that proposes to do that.

I believe it should be possible to make draft.js (or any other rich text widget) interoperate with our existing data representation, even if that means rewriting the markup on the Python side - if not, that would be a deal-breaker for me.

**Comment by thibaudcolas** [comment] 2016-11-30 22:41
For everyone interested in this conversation, Springload has been busy playing with Draft.js + Wagtail. Right now this looks like:

- A Python Draft.js data to HTML exporter, https://github.com/springload/draftjs_exporter
- A (very buggy at the moment) Draft.js based rich text editor, https://github.com/springload/draftail

It is still very early. The exporter is relatively stable, the editor still needs heavy debugging, refactoring & testing.

**Comment by SalahAdDin** [comment] 2016-12-02 14:47
The problem is that draft is not open, have payments.

**Comment by coredumperror** [comment] 2016-12-02 20:10
It's not? I don't see anything about license fees on their site. 

It appears to be [BSD Licensed](https://github.com/facebook/draft-js#license), actually.

**Comment by thibaudcolas** [comment] 2017-02-03 11:33
Here is a progress update for people interested in this:

- https://springload.github.io/draftail/ is a more stable editor now, although still not feature complete (nor documentation complete).
- https://github.com/springload/draftjs_exporter (Draft.js content -> HTML) is nearly feature complete (documentation in progress too).

We/I are trying to make those two projects usable and relevant outside of Wagtail. It's not that much more effort, and I think it will make the efforts more viable in the long run. And I think it's just a better practice to keep the coupling low.

The glue between Draftail and Wagtail is here: https://github.com/springload/wagtaildraftail. This is **WIP, pre-alpha, and completely unusable as-is at the moment**. It just outlines our current approach to combine the pieces.

One of the big design decisions here is whether the content coming out of the editor gets stored using the Draft.js representation (JSON) or an HTML export of it. The main design tradeoffs are:

- Storing JSON means you have to convert it to HTML (and potentially hydrate it with data from the DB) when rendering the content.
- Storing HTML means that you tie rendering the content to Wagtail.

There are many more tradeoffs (performance, lower common denominator with other editors, etc) that I hope we will get to cover in upcoming documentation. The takeaway is that:

- Draftail, the editor, attempts to be agnostic to what happens to the content once it is saved. It gives you the Draft.js/JSON representation, then up to you to combine it with any of the exporters that are available: https://github.com/nikgraf/awesome-draft-js#common-utilities.
- `draftjs_exporter`, the Python Draft.js -> HTML exporter, attempts to be agnostic to this too. It can be run when the page is saved, or when it is displayed.
- `wagtaildraftail` has the opinions. In this WIP implementation, content is stored as JSON and exported to HTML when pages are rendered. We are keen to explore the other scenario as well.

**Comment by thibaudcolas** [comment] 2017-04-26 10:55
Another progress update:

- https://springload.github.io/draftail/ hasn't evolved much from the last time, but it has gotten more use and also UI/UX reviews. WIP.
- https://github.com/springload/draftjs_exporter has just reached 1.0. It is now feature complete, and documentation good enough.
- The demo of those two at https://draftjs-exporter.herokuapp.com/ is a good example of how they work together.

@loicteixeira and I, with support from lots of others (at the dev sprint in Reykjavík, online, at SL), have worked on glueing all of this together in https://github.com/springload/wagtaildraftail. It is now usable, although still unstable, and a big release is due this week.

The next steps for me are to:

- Define further the scope / backlog of those three projects to foster contributions from outside of Springload
- Make a blog post detailing the thinking so far.
- Make a public demo of `wagtaildraftail` to gather further feedback and facilitate collaboration.
- Work on Draftail's features.

Finally, in the last progress update I was highlighting our thinking around data storage and conversion (in what stage of the lifecycle to convert from Draft.js to HTML, what to store, how).

- The current implementation in `wagtaildraftail`, storing Draft.js content state as JSON, seems to work well for us so far. (2 projects using this at Springload, close to going live).
- We've opened the way to future format transformations by allowing [custom exporter backing engines](https://github.com/springload/draftjs_exporter#custom-backing-engines). This is very early, and only goes in one direction Draft.js -> HTML/other at the moment, but it's a start.
- I will start exploring the HTML -> Draft.js route as part of https://github.com/springload/draftail/pull/50 – note that this will be in JS (for the copy/paste of arbitrary content into the editor), but it's a start :)

**Comment by thibaudcolas** [comment] 2017-05-02 19:25
This is a bigger problem than Springload can chew on its own, we could really use contributions from the wider Wagtail community in order to make this happen in 2017. To this effect, I have spent a bit of time thoroughly detailing what needs to happen with the Draft.js integration for it to reach general availability (and hopefully become the default for Wagtail sites).

The high-level backlog is available on wagtaildraftail – [Road to Wagtail](https://github.com/springload/wagtaildraftail/projects/2). It also references "v1.0.0" milestones on the other projects, that track the finer details.

Contributions that would be particularly welcome:

- You want to dive deep into modern immutable JS & React, learning the Draft.js API along the way.
- You've always wanted to learn more about the numbers game - memory profiling and benchmarks in Python & JS.
- You want to experience how awesome unit testing is in JS in 2017 – Jest is set up on all those projects, snapshot tests are waiting for you.

PS if you're looking for a job, submit a good PR and I'll hire you right away ❤️.

**Comment by thibaudcolas** [comment] 2017-10-20 09:26
Keeping track of open issues that will be fixed when Hallo.js is replaced (from the ["rich text" label](https://github.com/wagtail/wagtail/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22component%3ARich+text%22)):

- #65
- #445

**Comment by thibaudcolas** [comment] 2017-12-04 13:54
:wave: I'm looking for help to battle test Draftail. It's all mostly there (and all mostly working), but it would be nice to have more eyes over it and more hands doing all the things people do with text editors.

There are lots of demos available at https://springload.github.io/draftail/, reflecting what it will be like inside Wagtail (except for the UI for the links, documents, images, embeds, which will be Wagtail's).

Please have a try, and if you have feedback or concerns either go to https://github.com/springload/draftail/issues or join the new #draftail channel on Wagtail's Slack workspace.

**Comment by thibaudcolas** [comment] 2017-12-20 13:22
## Affected issues / PRs

### Fixed in Draftail

- Pasting content into rich text fields retains HTML text styles from source #65
- Deselecting header tags in rich text editor could be more intuitive #445
- Make it easier to delete images in rich text editor #447
- Text pasted into rich text editor doesn't always get wrapped with Paragraph tags #559

### Potentially conflicting / may need rework

- [WIP] Unify link choosers #1645
- Add option to insert tel links in rich text editor #3776

For each of these, we'll need to look into their status, bearing in mind that Hallo.js isn't going away just yet so some may still need to remain open.

**Comment by thibaudcolas** [comment] 2017-12-20 16:39
## Affected issues / PRs

### Works in Draftail

- Pasting content into rich text fields retains HTML text styles from source #65
- Deselecting header tags in rich text editor could be more intuitive #445
- Make it easier to delete images in rich text editor #447
- Text pasted into rich text editor doesn't always get wrapped with Paragraph tags #559
- Adding external links can insert url into field #1548
- Difficult to create multi-level lists #2212
- Add ability to edit images and embeds in rich text editor #2674
- Extra Paragraph Tags in Rich Text #3111
- IE11 p, h2, h3, undo, redo buttons not working in hallo RichText editor #3400
- RichTextField: Link is not inserted when selected text starts or end with italic and has also non-italic part #3677
- RichText fails to add link if selected text contains non-Text node (rangy issue) #3775
- Applying any heading style to OL or UL increases font size unlimitedly #3778
- Link or Headings not working with RichTextEditor in Internet Explorer #3825
- Correcting a typo through browser spelling doesn't count as a changed field #4016

### Related

- Ability to insert StreamField blocks programatically in page editor #2265
- [WIP] Unify link choosers #1645
- Add option to insert tel links in rich text editor #3776
- Not possible to add link with fragment identifier #1049
- Document the register_rich_text_embed_handler / register_rich_text_link_handler hooks (#1093) #1094
- Target for Richtext links #1167
- Migrating from TextField/CharField to RichTextField should insert paragraph tags around text #2290
- Extend WYSIWYG with new buttons and customized behavior #2277
- Feature Request: Blacklist for Richtext elements #2646 
- Specifying rich text features does not whitelist only these features #3852
- Keyboard shortcut documentation for editor in the Wagtail UI #3949

### Further check status

- Some fields insert unnecessary markup into templates #1214
- Image Chooser pop up doesn't close after insert in Streamfield paragraph block #1880
- Rich text fields should show "invisible" characters. #2188
- Character count UX improvements #2268
- Character count of rich text fields should ignore markup #4150
- Reduce specificity of CSS icon classes #2600
- hallohtml icon incorrect. #2849
- Inserting link in editor doesn't work sometimes #3023
- Editing links on images on RichTextField #3214

For each of these, we'll need to look into their status, bearing in mind that Hallo.js isn't going away just yet so some may still need to remain open.

**Closed** 2018-01-25 16:49 UTC
Labels: component:Frontend, component:Rich text
