### ISSUE TITLE
Admin Edit View Tabs CSS Issue

### ISSUE THREAD

**Issue by vedodedo** [wagtail/wagtail#8704] opened 2022-06-19 12:42 UTC
Hello All, 
i just upgraded a project from wagtail v2 to wagtail v3, i found this issue in the admin edit view tabs 
the tabs are out of screen size.
so a lot of them will not be displayed to user.

### Steps to Reproduce

1. you just need to increase the number of tab panels in the model admin.  

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`. >> 3.9
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`. >> 3.2
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. v3.0.1
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out. Firefox 94
![Selection_771](https://user-images.githubusercontent.com/93770601/174481858-c9214fbe-ab70-4b28-969a-db6d2df58118.png)

**Comment by lb-** [comment] 2022-08-01 10:32
@vedodedo  I have not been able to reproduce this issue, when there are lots of tabs it correctly creates a scrollbar for me.

https://github.com/wagtail/wagtail/blob/63e0181f93794deac7f92182935985102fd5ed1d/client/scss/components/_tabs.scss#L14

The styles are using the correct overflow classes from what I can see also.

It's hard to track the changes on that line (tailwind -- all items on a single line) but it appears to have been that way from the start.

I will close this as not able to reproduce - please provide more details if you feel this is still a problem.


<img width="1418" alt="Screen Shot 2022-08-01 at 8 29 24 pm" src="https://user-images.githubusercontent.com/1396140/182129617-259daed9-05fd-4b89-9cfb-09f4c48fcce6.png">

**Closed by lb-** 2022-08-01 10:32 UTC
Labels: type:Bug, status:Unconfirmed
