### ISSUE TITLE
min_num Parameter in InlinePanel - Wagtail 1.10rc1

### ISSUE THREAD

**Issue by bauersebastian** [wagtail/wagtail#3563] opened 2017-04-23 10:33 UTC
### Issue Summary

After upgrading to 1.10rc1 I've come across an issue with the min_num parameter in InlinePanel. 
I save a page draft once and everything is fine. 
Saving the page again as a draft I get an error - 'please send 1 or more forms'.
The min_num parameter was set to 1. I have not deleted or added any entry in the inline panel before saving the page draft again. 
I had one entry in the inline panel in the first draft and did not change anything.

The error disappears if you delete and add the entry in the inline panel (so you submit a new form).

I have deleted the parameter in my model for now. Now everythings works again.
I did not have this issue in version 1.9

### Steps to Reproduce

1. This is the first step
Use the min_num parameter in an inline panel.

2. This is the second step, etc.
Save the draft more than once.

### Technical details

* Python version: 3.6.0
* Django version: 1.11
* Wagtail version: 1.10rc1
* Browser version: Chrome latest version

**Comment by gasman** [comment] 2017-04-26 14:23
Hi @bauersebastian,

I can't reproduce this issue as described on a new 1.10rc1 install. Starting from a new `wagtail start` project, I updated home/models.py

    from __future__ import absolute_import, unicode_literals

    from django.db import models

    from modelcluster.fields import ParentalKey

    from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel
    from wagtail.wagtailcore.models import Orderable, Page


    class HomePage(Page):
        content_panels = [
            FieldPanel('title'),
            InlinePanel('links', label="Links", min_num=1),
        ]


    class HomePageLink(Orderable):
        page = ParentalKey(HomePage, related_name='links')
        url = models.CharField(max_length=250)

        panels = [
            FieldPanel('url'),
        ]

and ran `./manage.py makemigrations`, `./manage.py migrate`, `./manage.py createsuperuser`, `./manage.py runserver`.

I was then able to edit the existing homepage, add a link URL, and save it multiple times, as well as doing the same on a newly-created page.

Please can you provide detailed steps for reproducing this issue on a new project?

**Comment by bauersebastian** [comment] 2017-05-01 21:26
Hi @gasman,

I could reproduce the error with exactly your settings.
Instead of adding new links, just change the title of a published page.

Steps to reproduce:
Your settings as above mentioned.

Publish a new page with one link.
Edit the title of the published page and save the draft.

I get the error: 
'The page could not be saved due to validation errors'
'Please submit 1 or more forms.'

Best regards
Sebastian

**Comment by gasman** [comment] 2017-05-02 10:08
Thanks @bauersebastian! I can confirm I'm seeing this issue now. It looks like this may be a Django 1.11 bug, due to be fixed in 1.11.1: https://code.djangoproject.com/ticket/28130 - will investigate.

**Comment by gasman** [comment] 2017-05-02 10:44
Yep, the commit for the above Django ticket <https://github.com/django/django/commit/e93135b067c4f2bfe423e605bdfe0786eaecaef2> does indeed fix this, so this will be fixed in Django 1.11.1.

**Closed by gasman** 2017-05-02 10:44 UTC
Labels: type:Bug
