### ISSUE TITLE
Image chooser modal slow to open

### ISSUE THREAD

**Issue by jaydensmith** [wagtail/wagtail#2889] opened 2016-08-04 03:02 UTC
If there are a number of image thumbs to be generated when opening an image chooser, there can be a delay of a few seconds before the modal appears. While waiting you can click any button that opens the image chooser modal again and open multiple instances which breaks all of them.

**Comment by thibaudcolas** [comment] 2017-02-05 14:54
Closing as duplicate of #2364

**Closed** 2017-02-05 14:56 UTC
Labels: type:Bug
