### ISSUE TITLE
Search autocomplete

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#9895] opened 2023-01-15 09:25 UTC
Upon getting stuck on search autocomplete that acts a bit weird in my opionion. For example I got a list of names in snippets and have index.autocomplete in the search I still have to write full words to get some results. This is for people not the expected behavior. Researching the subject I notice the following ticket: https://github.com/wagtail/wagtail/issues/7720

There they mention the following hack:
from wagtail.search.backends.database.postgres.postgres import PostgresSearchQueryCompiler
PostgresSearchQueryCompiler.LAST_TERM_IS_PREFIX = True

Adding this to you code will result in expected behavior of your autocomplete search. However this is no where mentioned in the documentation. Nor is it explained why the autocomplete function acts so strange. 

### Pertinent section of the Wagtail docs
https://docs.wagtail.org/en/latest/topics/search/indexing.html#index-autocompletefield
The above link does not seem true.

### Details
I would like the search documentation explain why index.autocomplete works the way it does now. Why adding the code snippet makes it works as expected?

**Comment by gasman** [comment] 2023-01-15 10:23
`PostgresSearchQueryCompiler.LAST_TERM_IS_PREFIX = True` is not a valid fix, as this enables 'autocomplete' behaviour on all searches, not just ones where autocompletion is requested.

Closing as a duplicate of #7720.

**Closed by gasman** 2023-01-15 10:23 UTC
Labels: Documentation
