### ISSUE TITLE
Need contributing guidelines for browser support

### ISSUE THREAD

**Issue by alexgleason** [wagtail/wagtail#1724] opened 2015-09-23 17:28 UTC
Hi again. I'm wanting to make some contributions to Wagtail's admin on the front-end, but need to know what browsers it intends to support so I can plan accordingly. I wasn't able to find this information in the [contributing guidelines](http://docs.wagtail.io/en/v1.1/contributing/index.html).

For instance, I want to use an inset CSS box-shadow to give the impression of an inner border, but this won't be the best solution if Wagtail intends to support IE8 since [box-shadow is an unsupported property in IE8](http://caniuse.com/#search=box-shadow).

Thanks!

**Comment by kaedroho** [comment] 2015-09-23 19:57
Not sure if support starts at IE9 or IE10 (@davecranwell should be able to confirm). I'm pretty certain that Wagtail does not support IE8 though.

**Comment by davecranwell** [comment] 2015-09-24 08:26
It's IE9+

**Comment by nealtodd** [comment] 2015-09-24 08:37
(Django Admin [drops IE8 support](https://docs.djangoproject.com/en/1.9/releases/1.9/#contrib-admin-browser-support) in 1.9, making Wagtail Admin consistent with that)

**Comment by FlipperPA** [comment] 2015-09-24 14:34
I noticed the drop of IE8 support in the release notes yesterday. Is Wagtail committed to support the same browsers that the Django Admin does? That seems like a good goal.

**Comment by davecranwell** [comment] 2015-09-24 14:40
Wagtail was originally written for a specific client website where we were only supporting IE9+. As a result Wagtail has never supported less than IE9. I'm broadly in favour of matching Django Admin in terms of the lowest support level, although we've not committed to that officially.

**Comment by thibaudcolas** [comment] 2017-02-05 18:03
I've had a stab at this in #3337 for end users, and more importantly #3338 for the contribution guidelines. Keen to get feedback on that PR.

For IE9, I wanted to see for myself so I opened up a VM. It works, mostly, but there are issues. I made a list below.

| Issue in IE9 | In what context | Origin / clues |
|--------------|-----------------|----------------|
| On the login form, placeholders for username and password do not show. This is problematic because there are no labels on those fields. | `/admin/login` | `placeholder` is not supported in IE9 |
| In the sidebar, the placeholder for the Search field does not show. Problematic because this field does not have a label. | `/admin/` | `placeholder` is not supported in IE9 |
| In the page list view, the human-readable date does not display the absolute date on hover, flickering instead. | `/admin/` and other views | ? |
| In the header, the collapsed "mobile" menu does not open when clicking the hamburger icon. | `/admin/` on mobile (all pages?) | ? | 
| In the groups CRUD, the custom dropdown styles are broken | `/admin/groups/x/` | CSS issue |
| On the page view, the "More" button for the page and its child pages does not open its popover. | `/admin/pages/x/` | Produces a "Unable to get value of the property 'add'" JS error. This is because of https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/core.js#L420 (IE9 does not support `classList`) |
| When entering rich text, the browser crashed. Not sure what I was doing exactly, didn't reproduce it right away. | `/admin/pages/x/ | ? |
| When entering rich text, embeds are not inserted in the editor. | `/admin/pages/x/ | ? the AJAX request succeeds but nothing displays. |
| When entering rich text, inserting a document does not automatically close the chooser, and the rich text content is not saved, if the document is the only thing in the field | `/admin/pages/x/ | ? |

(I won't open separate issues for each of those things because I don't think IE9 is worth supporting – most of those problems would surface very quickly when using Wagtail, which tells me that not many people use Wagtail in IE9)

**Comment by FlipperPA** [comment] 2017-02-06 02:16
Wow, that's a thorough job! I'd just like to add here that it has been over a year since Microsoft ended support (including security releases) for IE 8, 9, and 10: they ended on January 12, 2016. As you've mentioned, they're not worth supporting, and probably should be actively unsupported to encourage people to upgrade insecure browsers.

**Comment by gasman** [comment] 2017-02-20 20:49
Completed in #3338

**Closed by gasman** 2017-02-20 20:49 UTC
Labels: component:Frontend, Documentation
