### ISSUE TITLE
Wagtail permission collision when contenttype has Proxy model

### ISSUE THREAD

**Issue by jordmantheman** [wagtail/wagtail#4273] opened 2018-02-12 17:41 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm using django-admin to supplement some of my site, which resulted in the declaration of a simple Proxy model -

`
class FooProxy(Foo):
    class Meta:
        proxy = True
`

It seems this model is being registered via GroupForm.__init__, but is somehow being coalesced into a single permission for the base model. This stems from the fact that django does **not** make a unique contenttype for proxy models.

The wagtail view lists only 1 permission in the Group edit permission list, and on form submit, picks an arbitrary (the high index one) to associate with said permission.

I think I'd the GroupForm to not index on contenttype, but the model itself - allowing for proxy models to be listed. This would follow the principle of least surprise when configuring.

### Steps to Reproduce

As said above - create a non-page django model AND an associated Proxy model. You may need to register the proxy model w/ django admin.

### Technical details

* Python version: 3.6.3.
* Django version: 1.11.7
* Wagtail version: 1.12.2

**Comment by gasman** [comment] 2018-02-12 22:46
Hi @jordmantheman - thanks for the report.

Please can you provide a full code example demonstrating this issue (i.e. a complete models.py, wagtail_hooks.py and whatever other files are necessary to reproduce this)?

I can see roughly how the grouping logic at https://github.com/wagtail/wagtail/blob/4cab7d67c32683fce571ef281f2cbc211b3d7d3f/wagtail/users/templatetags/wagtailusers_tags.py#L52 would be tripped up by multiple models sharing the same content type, but I'm finding it hard to see how a permission model set up like that can work at all, given that the content type is the only link from the Permission record back to the model. (Perhaps it's distinguishing them purely on the suffixes of the labels `add_foo` versus `add_fooproxy`? That would be quite annoying here, since there's no reliable way to translate those suffixes back to the correct model, which we need to do to output a correctly formatted label for the row...)

**Comment by jordmantheman** [comment] 2018-02-13 02:58
Sure thing - will add it shortly.

That snippet is about as far as I got in my debugging. From what I saw, the permissions share a contenttype but have a unique codename.

In the meantime, my workaround is to add `default_permissions = ()` to the Meta class of any Proxy (and a migration to drop the permissions that already took hold)

**Comment by jordmantheman** [comment] 2018-02-13 04:03
Not sure how you guys provide sample code, but here's my first go from a new repo.

> `wagtail start foo`
> `./manage.py migrate`
> `./manage.py createsuperuser`

**models.py**
```
from __future__ import absolute_import, unicode_literals

from django.db import models

from wagtail.wagtailcore.models import Page


class HomePage(Page):
    pass


class Foo(models.Model):
    pass


class FooProxy(Foo):

    class Meta:
        proxy = True
```
> `./manage.py makemigrations`
> `./manage.py migrate`

**wagtail_hooks.py**
```
from wagtail.contrib.modeladmin.options import ModelAdmin, modeladmin_register

from .models import Foo


class FooAdmin(ModelAdmin):
    model = Foo


modeladmin_register(FooAdmin)
```

1) Log in as an admin and make a user, give it the moderator role
```
>>> from django.contrib.auth.models import User
>>> User.objects.get(pk=2).get_group_permissions()
{'wagtailimages.add_image', 'wagtaildocs.delete_document', 'wagtailadmin.access_admin', 'wagtailimages.change_image', 'wagtaildocs.change_document', 'wagtaildocs.add_document', 'wagtailimages.delete_image'}
```
2) As admin you should be able to also assign `Foo` permissions to the moderator role.
```
>>> from django.contrib.auth.models import User
>>> User.objects.get(pk=2).get_group_permissions()
{'wagtailadmin.access_admin', 'home.delete_fooproxy', 'wagtaildocs.add_document', 'wagtailimages.add_image', 'home.add_fooproxy', 'wagtailimages.delete_image', 'wagtaildocs.delete_document', 'wagtaildocs.change_document', 'wagtailimages.change_image', 'home.change_fooproxy'}
```
As you can see, it assigned fooproxy permissions which probably isn't expected. Let me know if you need a zip of files or anything. My virtualenv for this example was being a little wonky and didn't take the time to fix it.

**Comment by arthurio** [comment] 2018-08-30 01:46
I believe this is a known Django bug and not a wagtail one. This bug has been opened for 9 years (https://code.djangoproject.com/ticket/11154) but some non agreed upon workarounds exist, see this [gist](https://gist.github.com/magopian/7543724), referenced from [stackoverflow](https://stackoverflow.com/questions/15037642/django-proxy-model-permissions-do-not-appear).

**Comment by zerolab** [comment] 2022-04-20 09:43
Closing in favour of #4973 / #5202

**Closed by zerolab** 2022-04-20 09:43 UTC
Labels: type:Bug
