### ISSUE TITLE
BUG documentation search

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#8195] opened 2022-03-23 12:04 UTC
I search something on google, came on wagtail docs. Didn't like what I read and wanted to search the docs via the search field. This gave in all cases 0 results. After a bit testing I noticed that the search not always works from Algolia.

For example if you go to: https://docs.wagtail.org/en/v2.16.1/ the search wil not work
if you go to: https://docs.wagtail.org/en/stable/

the search will work

**Comment by lb-** [comment] 2022-03-23 12:17
Duplicate of https://github.com/wagtail/wagtail/issues/8159

**Closed by lb-** 2022-03-23 12:17 UTC
Labels: Documentation
