### ISSUE TITLE
Non editable USERNAME_FIELD breaks wagtail

### ISSUE THREAD

**Issue by stan-sack** [wagtail/wagtail#5924] opened 2020-04-01 10:03 UTC
I've been playing around with a non-editable username field:

```
class CustomUser( AbstractUser):
    user_id = models.CharField(max_length=36, default=create_uuid_string, unique=True, null=False, editable=False)
    USERNAME_FIELD = 'user_id'
```

Unfortunately this breaks `UserEditForm`, but this can be fixed by changing `fields = set([User.USERNAME_FIELD, "is_active"]) | standard_fields | custom_fields` to `fields = standard_fields | custom_fields` [here](https://github.com/wagtail/wagtail/blob/master/wagtail/users/forms.py#L201).

I'm not sure whats the best generic way to handle this but I thought I'd open an issue so you can track it

**Comment by lb-** [comment] 2020-04-12 07:33
@stan-sack  - thanks for submitting this issue, I have been able to reproduce this issue (details below). I will make an additional comment with some recommended ways to work around this and the probable root cause.

## Steps to get this error
Note:  Assumes you are starting from an existing app (e.g. bakerydemo) and that you have backed up your database (this is a destructive operation).

1. Follow the instructions to create a custom User model & update the settings (do not update the edit/create templates yet, and only add a basic extra field like country from the example) - https://docs.wagtail.io/en/v2.8/advanced_topics/customisation/custom_user_models.html
2. For an existing Django app, you will need to follow some extra instructions to set up the custom user model - https://code.djangoproject.com/ticket/25313#comment:18 (comment 18 is the best instructions)
3. Now update your CustomUser model as follows (note: the commented out editable is intentional)
```python
import uuid 
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    user_id = models.UUIDField(
        default = uuid.uuid4, 
        # editable = False,
        null=False,
        unique=True
    )

    USERNAME_FIELD = 'user_id'

    class Meta:
        db_table = 'auth_user'
```
4. Migrate your application
5. Start your application
6. Uncomment the line `editable = False,`
7. Expected result: no errors, should be able to run the application and edit/create users with the field being editable
8. Actual result:  error `django.core.exceptions.FieldError: 'user_id' cannot be specified for User model form as it is a non-editable field` (full below)


## Full Error
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/vagrant/wagtail/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/vagrant/wagtail/wagtail/admin/edit_handlers.py", line 355, in get_form_class
    widgets=self.widget_overrides())
  File "/vagrant/wagtail/wagtail/admin/edit_handlers.py", line 62, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/vagrant/wagtail/wagtail/admin/forms/models.py", line 75, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/modelcluster/forms.py", line 233, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/forms/models.py", line 176, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/forms/models.py", line 56, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/vagrant/wagtail/wagtail/core/fields.py", line 18, in formfield
    defaults = {'widget': get_rich_text_editor_widget(self.editor, features=self.features)}
  File "/vagrant/wagtail/wagtail/admin/rich_text/__init__.py", line 37, in get_rich_text_editor_widget
    return cls(**kwargs)
  File "/vagrant/wagtail/wagtail/admin/rich_text/editors/draftail/__init__.py", line 31, in __init__
    self.features = feature_registry.get_default_features()
  File "/vagrant/wagtail/wagtail/core/rich_text/feature_registry.py", line 49, in get_default_features
    self._scan_for_features()
  File "/vagrant/wagtail/wagtail/core/rich_text/feature_registry.py", line 54, in _scan_for_features
    for fn in hooks.get_hooks('register_rich_text_features'):
  File "/vagrant/wagtail/wagtail/core/hooks.py", line 47, in get_hooks
    search_for_hooks()
  File "/vagrant/wagtail/wagtail/core/hooks.py", line 41, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "/vagrant/wagtail/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/wagtail/wagtail/users/wagtail_hooks.py", line 11, in <module>
    from wagtail.users.urls import users
  File "/vagrant/wagtail/wagtail/users/urls/users.py", line 3, in <module>
    from wagtail.users.views import users
  File "/vagrant/wagtail/wagtail/users/views/users.py", line 15, in <module>
    from wagtail.users.forms import UserCreationForm, UserEditForm
  File "/vagrant/wagtail/wagtail/users/forms.py", line 179, in <module>
    class UserCreationForm(UserForm):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.5/site-packages/django/forms/models.py", line 149, in fields_for_model
    f.name, model.__name__)
django.core.exceptions.FieldError: 'user_id' cannot be specified for User model form as it is a non-editable field
```

**Comment by lb-** [comment] 2020-04-12 07:44
@stan-sack 

The underlying problem here is probably not Wagtail specific, as the error explains:

`django.core.exceptions.FieldError: 'user_id' cannot be specified for User model form as it is a non-editable field`

In the Wagtail docs, it explains how to extend both the user edit and user creation form
https://docs.wagtail.io/en/v2.8/advanced_topics/customisation/custom_user_models.html

Following these steps, considering your desired customisation gives you a few options.

## Basic work around 

The simplest work around would be to override the method `separate_username_field` to always return false. This will ensure the template never attempts to render the username field (see - https://github.com/wagtail/wagtail/blob/master/wagtail/users/templates/wagtailusers/users/edit.html#L22).

Note: you will also need to remove the `editable=False` on your `CustomUser` model in this case.

```python
from django import forms
from wagtail.users.forms import UserEditForm, UserCreationForm

class CustomUserEditForm(UserEditForm):

    def separate_username_field(self):
        return False

class CustomUserCreationForm(UserCreationForm):
    
    def separate_username_field(self):
        return False
```

The downsides with this approach are that technically this form still handles editing of the username field.

## More complex work around

As you now have full control over the forms and templates, you can customise the fields and and what fields are shown. While this is more work, it gives you fine grained control over every aspect of the form and its rendering.

For example...

**forms.py**
```python
class CustomUserEditForm(UserEditForm):

    def separate_username_field(self):
        return False

    class Meta(UserEditForm.Meta):
        # adjust as needed
        fields = {'is_superuser', 'is_active', 'user_id', 'email', 'groups', 'last_name'}
```

**templates/wagtailusers/users/edit.html**
```
{% extends "wagtailusers/users/edit.html" %}

{% block fields %}
  CUSTOM FIELDS HERE
{% endblock fields %}
```

**Comment by lb-** [comment] 2020-04-12 07:46
@stan-sack  - I think we will close this for now, if you want to raise a new feature request, I think that would be more suitable, maybe a setting to 'remove' some fields from the create/edit form or some other method that is on the form that builds up the fields which can be overridden.

It appears that Wagtail in its current state does make a hard assumption that the username will be editable but there are documented ways to override any of this behaviour that works the same way as Django itself.

https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#extending-the-existing-user-model

**Closed by lb-** 2020-04-12 07:46 UTC
Labels: type:Bug
