### ISSUE TITLE
wagtail v2 api always calls "abstract" get_url_parts in list

### ISSUE THREAD

**Issue by faxioman** [wagtail/wagtail#4205] opened 2018-01-18 18:10 UTC
Using wagtail v2 api, the get_url_parts method overridden in my models is called only for page detail api.
The page list api always calls the get_url_parts method of class wagtail.wagtailcore.models.Page.

**Comment by rgant** [comment] 2018-01-25 02:31
I'm having this same problem. Given that the whole point of this function is to change the URL for the Page it seems like it needs to be accessible to `pageurl`.

The work around is to call `specific` on the model before passing it to pageurl:
```
{% pageurl item.page.specific %}
``` 

Related issues include #3370 & #3355

**Comment by lb-** [comment] 2022-03-18 21:31
Have not reproduced myself but looks like a bug.

Looks like this is still the case `wagtail/api/v2/views.py`
`get_body_fields` used via `PagesAPIViewSet` appears to get the class definitions, not the specific model definitions for methods

Needs further digging though so marked as unconfirmed.

**Comment by lb-** [comment] 2023-09-20 09:05
This should be fixed by https://github.com/wagtail/wagtail/pull/10902 - the queryset will now honour any sub-class `model`.

 I will close this for now and if anyone sees this problem, please raise a new bug with a bit more detail with steps to reproduce and code used.

Most things should be able to be overridden by the documented approach here https://docs.wagtail.org/en/latest/advanced_topics/api/v2/configuration.html#configure-endpoints (note this is the latest docs #10902 will be released in v5.2)

**Closed by lb-** 2023-09-20 09:05 UTC
Labels: type:Bug, component:API, status:Unconfirmed
