### ISSUE TITLE
Make the library compatible with drf-yasg library

### ISSUE THREAD

**Issue by fazpu** [wagtail/wagtail#4811] opened 2018-10-15 21:02 UTC
https://github.com/axnsan12/drf-yasg is the best swagger generator out there by far.

Unfortunately, it is not possible to integrate with wagtail due to the current API design.

The error when generating swagger schema:
```
Traceback (most recent call last):
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 94, in get_view_serializer
    return self.view.get_serializer()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 110, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/wagtail/api/v2/endpoints.py", line 300, in get_serializer_class
    model = type(self.get_object())
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/wagtail/api/v2/endpoints.py", line 437, in get_object
    base = super().get_object()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 94, in get_object
    (self.__class__.__name__, lookup_url_kwarg)
AssertionError: Expected view PagesAdminAPIEndpoint to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/renderers.py", line 34, in render
    return codec.encode(data)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/codecs.py", line 73, in encode
    raise SwaggerValidationError("spec validation failed", errors, spec, self)
drf_yasg.errors.SwaggerValidationError: spec validation failed
```

**Comment by jasonHav** [comment] 2019-03-19 06:53
I have a number of projects that need both Wagtail and DRF API's - and drf-yasg is our weapon of choice for documents. Definitely looking forward to seeing this merged.

**Comment by thclark** [comment] 2019-03-20 14:37
This is a bit finicky to achieve, but can be done with a polymorphic serialiser, and generally bypasses wagtail's API to use DRF out of the box. [Example here, showing different page schema on the /pages_read endpoint](
https://tpast.herokuapp.com/api/doc/#operation/pages_read). 

@jasonHav If folks are interested and can raise money to sponsor for a couple of weeks' work for me (I have a couple of weeks spare at end of april / early may) I could tidy what I've done as a package on pypi (`drf-wagtail`, maybe) with a couple of examples.

**Comment by amalhotraskrunch** [comment] 2019-08-11 07:47
is there any traction on this issue?  would be amazing if Wagtail API could generate some good documentation

**Comment by Windfarer** [comment] 2019-11-25 04:41
any update about this issue?

**Comment by zerolab** [comment] 2019-11-25 10:19
Hey all, it would help if you could review and test #4922 which aims to fix this

**Comment by lingster** [comment] 2020-03-16 16:19
> Hey all, it would help if you could review and test #4922 which aims to fix this

@zerolab , I'd be happy to test out #4922, but looks like the code has been refactored since this PR. Is there another PR I can look at or shall I just apply these changes and test?

**Comment by lb-** [comment] 2020-05-13 09:24
Based on validation from @lingster (below), we will close this issue as it appears to be resolved. If this still is a problem for some specific scenario it would be good for a new bug to be raised with exact steps to reproduce.

> The generation of the swagger schema works correctly for wagtail >=2.8 version including the current 2.10rc.
> I have tested as well with drf_yasg == 1.17.1 and django >2.2 and 3.0.x
There is an AssertionError raised when loading the swagger schema in 2.8 but this does not appear to impact the loading of the swagger page. The error is:
> `AssertionError: Expected view PagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the .lookup_fieldattribute on the view correctly.`
https://github.com/wagtail/wagtail/pull/4922#issuecomment-626399255

**Closed by lb-** 2020-05-13 09:24 UTC
Labels: component:API, type:Enhancement
