### ISSUE TITLE
Padding/Size issues with dropdown buttons with 4.1rc1

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#9476] opened 2022-10-24 12:28 UTC
### Issue Summary

I've first opened an issue for wagtailmedia https://github.com/torchbox/wagtailmedia/issues/183, but the dropdown-part is actually an issue within wagtail's core, because it can be "reproduced" in the styleguide app (https://docs.wagtail.org/en/stable/contributing/styleguide.html) and the site history for example:
![wagtail_dropdown_padding_size_issues](https://user-images.githubusercontent.com/468164/197524654-b1ea45fe-972e-4f5b-9a2d-475947dc4e5c.png)

The dropdown in wagtailmedia also uses icons (similar to the site report's export-dropdown), where the issue is more obvious:
![wagtailmedia_add_button_sizes](https://user-images.githubusercontent.com/468164/197524898-5390bc43-f9e9-4ff2-9d21-dc88846da3b3.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `./manage.py makemigrations && ./manage.py migrate && ./manage.py createsuperuser && ./manage.py runserver`
3. Login to the CMS and open the "Site history"
4. Look at the export button/dropdown

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.10
-   Django version: 3.2, 4.1
-   Wagtail version: 4.1rc1
-   Browser version: Firefox 106

**Comment by Theresa-o** [comment] 2022-10-24 12:33
I would reproduce this from my end and provide feedback

**Comment by Theresa-o** [comment] 2022-10-24 14:44
@th3hamm0r please guide me on where I can find "Site report" via this screenshot as I have tried reproducing the error but would need further guidance to understand better

![cmssitereport](https://user-images.githubusercontent.com/62052443/197554404-a788f32f-7e36-422d-9cc5-0fa4f2af6552.PNG)

**Comment by th3hamm0r** [comment] 2022-10-24 15:31
@Theresa-o sry, I've used the wrong title, I meant the "Site history" :sweat_smile: 
(I've updated the steps in the description above)

**Comment by Theresa-o** [comment] 2022-10-24 15:37
Thank you, it's ok :smiley:

I would reproduce this and provide feedback.

**Comment by zerolab** [comment] 2022-10-24 18:40
Two things here:
1. white dropdown in the styleguide doesn't have the `match-width` class as the other dropdowns
2. the icon mismatch comes from `.dropdown ul .button { 0.95em }` which, by my guess, comes from the changes #9104, so it defaults to https://github.com/wagtail/wagtail/blob/main/client/scss/components/_dropdown.legacy.scss#L114

**Comment by gutogalego** [comment] 2022-10-24 18:43
![Captura de tela_20221024_204012](https://user-images.githubusercontent.com/31139680/197601089-1fddb5a0-602e-4258-af4a-8361b213b44b.png)

can reproduced it here. However, mine in english seems to be different than yours in german(?). I'll take a look and see if I can fix it

**Comment by Theresa-o** [comment] 2022-10-25 04:08
Hi @gutogalego I'm working on this.

I'm currently researching the best fix for this

![iconmismatch](https://user-images.githubusercontent.com/62052443/197680253-4bb59b99-a264-49b2-a878-d4ef1d7c1244.PNG)

**Comment by Theresa-o** [comment] 2022-10-26 15:21
@zerolab Thank you for the feedback and the information shared.

Learnt a lot, a PR has been raised for this.

**Closed** 2022-10-31 16:06 UTC
Labels: type:Bug
