### ISSUE TITLE
bottom bar in admin pages can obscure page content

### ISSUE THREAD

**Issue by indirectlylit** [wagtail/wagtail#5742] opened 2019-12-26 16:47 UTC
### Issue Summary

Some content is either not accessible or visually cramped:

| small| medium |
|--|--|
|![image](https://user-images.githubusercontent.com/2367265/71483152-7fdd9700-27d4-11ea-8233-69d5a32afceb.png)|![image](https://user-images.githubusercontent.com/2367265/71483258-f1b5e080-27d4-11ea-8d17-656461d72335.png)|

### Steps to Reproduce

Make the browser window smaller

### Technical details

* Python version: 3.7
* Django version: 2.2.9
* Wagtail version: 2.7
* Browser version: Mac Chrome 79

### Possible solutions

* Add more padding to the bottom of all editor pages
* Make the bottom bar full-width panel, and have the editor page scroll area "end" above the bar

**Comment by thibaudcolas** [comment] 2020-03-03 13:36
Thank you for reporting this @indirectlylit, as far as I can see this is a duplicate of #4641 so I’ll close this in favour of that issue.

**Closed by thibaudcolas** 2020-03-03 13:36 UTC
Labels: component:Frontend, type:Bug
