### ISSUE TITLE
Error tab detection no longer works

### ISSUE THREAD

**Issue by robslotboom** [wagtail/wagtail#4411] opened 2018-03-21 17:15 UTC
When a validation error occurs, a red badge should be pinned to any tab which contains a validation error. This no longer seems to work with StreamField errors.

Django 2.0.2
Wagtail 2.0

As an example a Page with a simplistic StreamBlock
When nothing the body is left empty an error occurs.
When multiple prefaces are added an error occurs.
None of these are pinned to the corresponding second tab though.

`class SimpleStreamBlock(StreamBlock):

	preface = PrefaceBlock(
		required = False
	)
	text = MarkdownBlock(
		required = False
	)
	callout = CalloutBlock(
		required = False
	)

	class Meta:
		template = 'courgette/blocks/simple_stream_block.html'
		block_counts = {'preface': {'max_num': 1}}

class SimplePage(Page):
	
	body = StreamField(
		SimpleStreamBlock,
		verbose_name = _('body text'),
		blank = True,
		null = True,
	)
	titles_panels = [
		MultiFieldPanel(
			[
				FieldPanel('title', classname='full'),
				FieldPanel('slug'),
				
			],
			_('Titles and slug')
		),
	]
	content_panels = [
		FieldPanel('summary'),
		StreamFieldPanel('body')
	]
	edit_handler = TabbedInterface([
		ObjectList(titles_panels, heading=_('General')),
		ObjectList(content_panels, heading=_('Content')),
	])

`

**Comment by gasman** [comment] 2018-03-21 17:30
Hi @robslotboom - thanks for the report.
I think this may be a duplicate of #4122 (and I suspect it's an existing bug on earlier versions, rather than a regression in 2.0) - if this is a different issue to the one described here, let me know and I'll be happy to reopen.

**Closed by gasman** 2018-03-21 17:30 UTC
