### ISSUE TITLE
"Edit this Page" missing from userbar

### ISSUE THREAD

**Issue by cnk** [wagtail/wagtail#10002] opened 2023-02-01 17:22 UTC
### Issue Summary

In previous versions of Wagtail, the userbar contains a link to "Edit this page" on both the live page and when viewing draft pages. The userbar shown on live pages still contains this link.

<img width="272" alt="UserbarOnLivePage" src="https://user-images.githubusercontent.com/5952/216113309-3a8e4115-8430-41c1-b39a-ac1baf44c7fd.png">

But the version displayed on "View Draft", e.g. example url: https://example.com/admin/pages/25185/view_draft/, does not.
<img width="272" alt="UserbarOnViewDraft" src="https://user-images.githubusercontent.com/5952/216113332-25cb4e7b-ab10-4d2a-8341-d10b97d7dd47.png">

### Steps to Reproduce

1. Create a site using Wagtail 4.1.1 or 4.2rc1
3. Create a page and "Save draft"
4. From the page explorer for the parent of the draft page above, choose "View Draft"
5. Click on the Wagtail icon to display the menu

I have only found this on existing projects I have upgraded. I have not confirmed that this issue can be reproduced as described on a fresh Wagtail project.

### Technical details

-   Python version:  3.8.16
-   Django version: 4.1.5
-   Wagtail version: 4.1.1 and 4.2rc1
-   Browser version: Chrome 109

**Comment by Scotchester** [comment] 2023-02-01 18:27
I can confirm this on my own Wagtail 4.1.1 installation, and confirm that it previously worked on a (different) Wagtail 3.0.1 site.

I have also confirmed it on a fresh Wagtail project with no modifications (using 4.1.1).

**Comment by satvikvash** [comment] 2023-02-01 18:55
Hi, I want to work on this issue, if possible would you please assign this issue to me?

**Comment by gasman** [comment] 2023-02-01 19:00
Thanks for your interest @satvikvash! You are welcome to work on this. We do not assign issues outside of the core team - we just ask that people indicate their intention to work on an issue (as you have now done), to avoid duplicating efforts.

For further help in getting started, please see https://dev.to/lb/ten-tasty-ingredients-for-a-delicious-pull-request-hgc - you may also wish to join [our #new-contributors channel on Slack](https://github.com/wagtail/wagtail/wiki/Slack).

**Comment by Ananjan-R** [comment] 2023-02-02 21:37
Hi, would it be possible to work on this issue as well?

**Comment by Aravind2203** [comment] 2023-02-03 15:54
Hello, Removing
`try:`
           `   if request.is_preview:`
                `       return ""`
        `except AttributeError:`
           `    pass`
from **EditPageItem** class of userbar.py will solve the issue.
I will be happy to create a pull request.

**Comment by satvikvash** [comment] 2023-02-03 16:03
Hi @Aravind2203, if you do this it creates an edit button on preview page also, and this whole code is for not having an edit button on preview page userbar (this is also mentioned in the comment written above this code). I think removing this code will resolve this issue but create a new issue. I have solved this issue using a different approach and presently I am working on writing the tests for the pull request.

**Comment by laymonage** [comment] 2023-02-06 10:23
This is a regression in https://github.com/wagtail/wagtail/pull/8766, because the "view draft" view uses `Page.make_preview_request()`.

**Comment by satvikvash** [comment] 2023-02-06 11:13
Hi @laymonage, are you suggesting that the edit button is missing on purpose from view_draft? Could you please clarify?

**Comment by laymonage** [comment] 2023-02-06 11:19
To add, this also means the "Edit" link is also missing from other previews, namely the revision preview and the workflow preview.

Accessing the Preview from here:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/6379424/216955847-ad9296ca-da4f-45f6-ba94-05e504a577ed.png">

and here:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/6379424/216955972-e86c6bd3-e79b-4224-af9e-96053c4323c8.png">

will result in the same issue.

Looking at the reasoning behind #8766, I feel like the changes made in that PR should be redone in a different approach, so that the edit link is hidden when viewing the preview on edit/create views only (and not the other previews).

This can be done by adding another extra attribute to the request object, e.g. `is_editing`, on the `PreviewOnEdit` view:
https://github.com/wagtail/wagtail/blob/59c0044df369752fc00071fdadbd51eabbc7b53c/wagtail/admin/views/generic/preview.py#L108-L112

Then, check for the new attribute in here:

https://github.com/wagtail/wagtail/blob/59c0044df369752fc00071fdadbd51eabbc7b53c/wagtail/admin/userbar.py#L140-L146

e.g.

```diff
- if request.is_preview:
+ if request.is_preview and request.is_editing:
```

**Closed** 2023-02-14 15:58 UTC
Labels: type:Bug, component:Preview, component:Userbar
