### ISSUE TITLE
Dateinput widget does not work in Custom Document modal chooser

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#9406] opened 2022-10-18 04:16 UTC
I create a custom document model with a custom datefield named "record_date". Its default value is the current date.
HomePage has a field named "doc" which is referenced by the custom document.

The problem is that when I click the "record_date" field in the document modal chooser, the datepicker widget does not show.
![image](https://user-images.githubusercontent.com/81170508/196334075-8d04ca9c-1dfc-4694-b893-bf1c0f62a725.png)

However, when I edit the document in document edition page, the datepicker shows properly.

Wagtail version: 4.0.2
django version: 4.1.2
python version: 3.10

**Comment by FatumaA** [comment] 2022-10-20 15:08
@thibaudcolas I'd like to attempt this. (Outreachy participant)

**Comment by aliceni81** [comment] 2022-10-25 04:35
@FatumaA

class CustomDocument(AbstractDocument):
    record_date = models.DateField(default=datetime.date.today)

    admin_form_fields = Document.admin_form_fields + (
        'record_date',
    )

class HomePage(Page):
    body = RichTextField(blank=True)
    doc = models.ForeignKey(
        get_document_model_string(),
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    content_panels = Page.content_panels + [
        FieldPanel("body"),
        FieldPanel("doc"),
    ]


![image](https://user-images.githubusercontent.com/81170508/197683395-ec478880-a7c5-4fee-9aea-72ac2d6e52a0.png)

The datepicker widget do not show in the document modal chooser
![image](https://user-images.githubusercontent.com/81170508/197683442-32a8fe61-8d6d-41ed-8207-828e80720c85.png)

**Comment by FatumaA** [comment] 2022-10-27 12:54
Can reproduce this bug. Date picker does not show up even when editing

**Comment by lb-** [comment] 2023-03-24 22:11
Note: this is actually just a duplicate of #3604 - the date picker correctly works but rather is just not visible inside the modal (z-index stacking issue).

Also, the steps to reproduce were not very close at all to getting to reproduce the problem.

```py
from wagtail.documents.forms import BaseDocumentForm

from wagtail.admin.widgets.datetime import AdminDateInput


class CustomDocumentForm(BaseDocumentForm):
    class Meta(BaseDocumentForm.Meta):
        widgets = {"record_date": AdminDateInput}
```

For reference - a custom form is also required, along with the relevant settings.

```py

WAGTAILDOCS_DOCUMENT_MODEL = 'base.CustomDocument'
WAGTAILDOCS_DOCUMENT_FORM_BASE = 'bakerydemo.base.forms.CustomDocumentForm'
```

**Closed by lb-** 2023-03-24 22:11 UTC
Labels: type:Bug
