### ISSUE TITLE
Using ImageChooserBlock does not update the used # of times in the image panel.

### ISSUE THREAD

**Issue by bmoe872** [wagtail/wagtail#3622] opened 2017-06-01 04:13 UTC
### Summary

If you have a Streamfield with an `ImageChooserBlock()`, the images uploaded through that block will not be called out as "used" by the # of times used display in the image panel admin.

<img width="342" alt="screen shot 2017-05-31 at 11 05 07 pm" src="https://cloud.githubusercontent.com/assets/3431862/26664241/a3ff1504-4655-11e7-902f-f8c850ba5629.png">

### Steps to Reproduce

Simply create a streamfield on a page, and put a `ImageChooserBlock()` in it. 

Then in the admin, add an image to the page with the streamfield using the ImageChooserBlock. Go to the images page within the admin, and find your uploaded image. The number does not update to reflect that the image has been used.

### Technical details

* Python version: 3.5.2
* Django version: 1.11
* Wagtail version: 1.10.1

**Comment by gasman** [comment] 2017-06-01 10:38
Thanks for the report @bmoe872! The same problem exists with images inserted into rich text fields - since the reference to the image is stored embedded within another value and isn't directly accessible in the database, there's no efficient way to query for it. Probably the best way to deal with this would be to add an extra model / database table specifically for tracking image usage on pages, which is populated on page save. (Although then we'd have to decide whether it tracks live or draft versions of pages...)

**Comment by bmoe872** [comment] 2017-06-02 16:03
@gasman I kind of figured it was a referencing issue after I noticed it worked with all the images I had explicitly defined as a model. Thanks for getting back to me so quickly!

**Comment by lb-** [comment] 2017-12-04 07:55
Potentially a duplicate of #1162

**Comment by gasman** [comment] 2017-12-04 09:09
Closing as duplicate of #1162

**Closed by gasman** 2017-12-04 09:09 UTC
Labels: type:Bug
