### ISSUE TITLE
SQLiteSearchResults.annotate_score("_score"): no such column: wagtailsearch_indexentry_fts

### ISSUE THREAD

**Issue by AndersFelde** [wagtail/wagtail#10481] opened 2023-05-25 08:17 UTC
### Issue Summary

Trying to annotate the score to the result of a search on SQLite DB.

### Steps to Reproduce

From bakery demo
Created a person named "Joe"
```python
>>> from bakerydemo.locations.models import LocationPage
KeyboardInterrupt
>>> from bakerydemo.base.models import Person
>>> from wagtail.search.backends import get_search_backend
>>> s = get_search_backend()
>>> s.search("Joe", Person)
<SearchResults [<Person: Joe A>]>
>>> s.search("Joe", Person).annotate_score("_score")
Traceback (most recent call last):
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: wagtailsearch_indexentry_fts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/wagtail/search/backends/base.py", line 320, in __repr__
    data = list(self[:21])
           ^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/wagtail/search/backends/base.py", line 314, in __iter__
    return iter(self.results())
                ^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/wagtail/search/backends/base.py", line 280, in results
    self._results_cache = list(self._do_search())
                               ^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/wagtail/search/backends/database/sqlite/sqlite.py", line 622, in _do_search
    return list(self.get_queryset())
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kippster/.local/share/virtualenvs/bakerydemo-W8UYPjOU/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: wagtailsearch_indexentry_fts
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on the wagtail bakery demo

### Technical details

-   Python version: Python 3.11.3
-   Django version: 4.2.1
-   Wagtail version: v5.0
-   Browser version: Brave Browser 113.1.51.118

**Comment by gasman** [comment] 2023-05-25 08:23
Closing as duplicate of #10218.

**Closed by gasman** 2023-05-25 08:23 UTC
Labels: type:Bug, status:Unconfirmed
