### ISSUE TITLE
InlinePanel reordering does not get saved

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail#4477] opened 2018-04-17 16:28 UTC
It looks like there might be a bug around reordering fields that use an InlinePanel - in the pages we're trying to reorder items in a list on, we can hit the up/down arrows, then hit "publish" after reordering, and it looks like publishing succeeds. However, inspecting the page in the admin again then shows that the new ordering was not saved.

**Comment by gasman** [comment] 2018-04-17 17:39
Thanks for the report @Pomax! Please could you provide specific steps for reproducing this issue, either from a fresh Wagtail project or (perhaps more conveniently) a newly-installed instance of [bakerydemo](https://github.com/wagtail/bakerydemo)?

**Comment by Proper-Job** [comment] 2018-04-18 06:30
@Pomax Have you tried setting the ordering field explicitly on the Model's Meta class?

```python
class MyModel(Orderable, Model):
    class Meta:
        ordering = ['sort_order']  # ordering is not automatically inherited from Orderable
```

**Comment by Pomax** [comment] 2018-04-19 18:44
Hm, odd. Our codebase doesn't save the reordering without that Meta property, but we'll have to dig around when there's some free time (we're sprinting towards a switchover atm) to see if there's a way to properly reproduce it.

**Comment by Proper-Job** [comment] 2018-04-20 08:32
@Pomax did you customize the formset that the InlinePanel uses?

**Comment by Pomax** [comment] 2018-04-20 20:30
no, although it's an inlinepanel through a parentalkey relation:

model: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L368
panel: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L450

**Comment by Proper-Job** [comment] 2018-04-23 07:00
@Pomax What Django and Python versions are you using?

**Comment by Pomax** [comment] 2018-04-23 16:27
Dango v1.11.12, Python 3.6

**Comment by Proper-Job** [comment] 2018-04-24 08:08
So according to the [docs](https://docs.djangoproject.com/en/2.0/topics/db/models/#meta-inheritance) the sort_order field really should be inherited. And as gasman [verified](https://github.com/wagtail/wagtail/issues/4477#issuecomment-382685039) it does in common scenarios.

I was able to reproduce this behavior on a clean Django 1.11.12 installation (no Wagtail). It appears that even though the related manager does order the objects correctly according to the ``Meta.ordering`` attribute (possibly) the modelformset_factory does not.

I'll double check my findings and if need be will create a bug report with Django.

**Comment by gasman** [comment] 2018-04-24 08:32
Closing for now - happy to reopen if it turns out this is a Wagtail issue after all.

**Closed by gasman** 2018-04-24 08:32 UTC
Labels: status:Needs info, type:Bug

**Comment by Proper-Job** [comment] 2018-04-24 09:49
https://code.djangoproject.com/ticket/29354

**Comment by Proper-Job** [comment] 2018-04-24 12:41
Ok I think I can shed some light on this subject.  The Orderable.Meta.sort_order field is inherited by subclasses, as long as they don't define their own Meta class.  Once subclasses do define their own Meta class, they should inherit from Orderable.Meta.
It would have helped me to read the django docs a bit more fully.
Let's wait and see what happens on the upstream Django ticket, but a documentation update is probably in order.

**Comment by PeteAndersen** [comment] 2018-04-26 20:41
I also ran into this issue due to class inheritance order. My model was inheriting from an abstract model and Orderable. Since abstract models have a Meta defined to declare it as abstract, it was overwriting the Orderable Meta definition. The proper way is to inherit Orderable first

```python
class MyModel(Orderable, MyAbstractModel):
    pass
```

There is an example of this in the bakery demo here, but the significance of putting Orderable first isn't  clear: https://github.com/wagtail/bakerydemo/blob/2d43a7120acca72771e28005c4089b28423b8360/bakerydemo/locations/models.py#L70

**Comment by ztasre** [comment] 2020-04-01 19:06
ran into this issue on wagtail 2.5.2
```
class Meta:
        ordering = ['sort_order']
```
the above fixed it

**Comment by gasman** [comment] 2020-04-01 19:25
As @Proper-Job notes, this will happen if you've defined a `class Meta:` on your `Orderable` subclass to set properties such as `verbose_name`, as this overwrites the Meta class that `Orderable` uses to set up the ordering. You can fix this by adding back the `ordering = ['sort_order']` property, but the "more correct" fix is to ensure that your Meta class inherits from `Orderable.Meta`:

    class Meta(Orderable.Meta):
        # add your other options here
