### ISSUE TITLE
PrivacyModalPanel doesn't have enough spacing

### ISSUE THREAD

**Issue by KalobTaulien** [wagtail/wagtail#6449] opened 2020-10-07 20:59 UTC
### Issue Summary

The PrivacyModalPanel in the Page.settings tab doesn't have enough spacing and overlaps when there's another FieldPanel below it. 

I _think_ this is just a frontend issue, though it may require some backend tweaking

### Steps to Reproduce

1. `wagtail start myproject`
2. Edit models.py and add `settings_panels = Page.settings_panels + [ FieldPanel("title") ]` to your class
3. Edit your home page.
4. Go to "settings" tab and you should see overlapping like this:
![image](https://user-images.githubusercontent.com/4743971/95386547-b6d8f100-08ac-11eb-8dff-43549d09cf30.png)

### Technical details

* Python version: 3.8.0
* Django version: 3.1.2
* Wagtail version: 2.10.2
* Browser version: https://www.whatsmybrowser.org/b/H24EP

**Comment by zerolab** [comment] 2020-10-07 22:00
This is a duplicate of #6446.
Has to do with the negative margin on `.object-list`. Will submit a fix on Friday, if no one beats me to it

**Closed by zerolab** 2020-10-07 22:00 UTC
Labels: component:Panels, type:Bug
