### ISSUE TITLE
MultipleChooserPanel lose checkbox on search

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#10451] opened 2023-05-18 12:33 UTC
`MultipleChooserPanel("companies", chooser_field_name="company", label=_("Companies")),
`
Above is a pointing to a page. The checkboxes are to make the checkbox select dissapear if you use the search field. This renders the multipagechooser useless at the moment. This only happens when you relate to page, snippets and other models are fine.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  no, not on a fresh install

### Technical details

-   Python version: Run`python 3.10
-   Django version: 4.2
-   Wagtail version: 5.0
-   Browser version: chrome latest

**Comment by chris-marmalade** [comment] 2023-08-03 20:18
Thanks for filing this. This appears to still be an issue in Wagtail 5.1.

**Comment by gasman** [comment] 2023-08-04 11:30
Marking this as a duplicate of #10754 since that one encompasses navigation in general, not specifically search.

**Closed by gasman** 2023-08-04 11:30 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by dopry** [comment] 2024-09-03 19:07
@gasman This is specific to search within the panel. The checkboxes simply do not appear when searching.

**Comment by gasman** [comment] 2024-09-03 19:13
@dopry That's covered by #11955, I believe. The searching/filtering operations are not passing on the URL parameter to enable multiple selection, which initially results in the missing checkboxes and then throws the mentioned JS error in submit (because the results are not returned in the required format).
