### ISSUE TITLE
RichTextField widget choosers crash Draftail in image models

### ISSUE THREAD

**Issue by nhstephan** [wagtail/wagtail#10377] opened 2023-04-21 11:06 UTC
### Issue Summary

When extending the core Image model by adding a RichTextField, Drafttail crashes when selecting a chooser-based option (i.e. links, etc) in the admin UI toolbar of the RichTextField widget.

### Steps to Reproduce

1. Create a custom image model by extending `wagtail.images.models.AbstractImage`
2. Add a field that uses `RichTextField` (`caption = RichTextField(features=['bold', 'italic', 'link'], null=True, blank=True)`)
3. Set the project to use the new custom image model.
4. Browse to the images section of the admin UI and upload an image.
6. Edit the image and add a caption in the newly created caption field.
7. Highlight a piece of text and select the Link option from the toolbar widget menu.
8. Widget should crash with the following JS error: `TypeError: n.g.chooserUrls is undefined`

![link_widget](https://user-images.githubusercontent.com/14984514/233620125-5d8ed720-5bef-4f93-8d00-ff724b931369.png)

![js_error](https://user-images.githubusercontent.com/14984514/233620167-02ccfa8d-640e-41ac-bb68-366042c154b5.png)

### Technical details

-   Python version: 3.10.
-   Django version: 4.1.8.
-   Wagtail version: 4.2.2.
-   Browser version: Firefox 112

**Comment by Zeki-Abdulhamid** [comment] 2023-04-21 15:45
Could you please assign me this issue. I am interested in working onit.

**Comment by gasman** [comment] 2023-04-21 15:50
Thanks for your interest @Zeki-Abdulhamid! We do not assign issues outside of the core team - anyone is free to work on any issue. Now that you've expressed an interest, other people may choose to hold off on picking this up, but they are not required to. We recommend thoroughly reading https://github.com/wagtail/wagtail/issues/10070 before making your first contribution.

For further help in getting started, please see https://dev.to/lb/ten-tasty-ingredients-for-a-delicious-pull-request-hgc - you may also wish to join [our #new-contributors channel on Slack](https://github.com/wagtail/wagtail/wiki/Slack).

**Comment by jeromelebleu** [comment] 2023-06-28 10:31
I have a similar issue and I would reformulate this issue as *the Draftail editor cannot be used outside the page editor out-of-the-box*. I realized that the `link`, `document-link`, `embed` and `image` features are looking for a `chooserUrls` variable in order to open the chooser modal - see for example [LinkModalWorkflowSource](https://github.com/wagtail/wagtail/blob/stable/5.0.x/client/src/components/Draftail/sources/ModalWorkflowSource.js#L240). This JavaScript variable is currently defined by the `wagtailadmin/pages/_editor_js.html` template which also outputs the result of the `insert_editor_js` hook.

Currently, in order to load the Draftail editor in a custom Image model or a custom view, I see at least these "solutions":
* import `wagtailadmin/pages/_editor_js.html` in the form template - as it is done in [`contrib.modeladmin`](https://github.com/wagtail/wagtail/blob/stable/5.0.x/wagtail/contrib/modeladmin/templates/modeladmin/create.html#L15) - which is in my opinion a beat overkill since a lot of useless JavaScript code is load
* define manually the required code in your form template - as we have done [here](https://framagit.org/cliss21/wagtail-webradio/-/commit/65391eb1e96000dbe10d93e2861ed7f055fee575) for some custom views - but it requires to know how it is working under the hood and which features are used - or to output the `insert_editor_js` hook…

As another solution with less drawbacks, would it be possible to attach this code to the Draftail widget itself?

**Comment by lb-** [comment] 2024-01-15 07:09
Could be a duplicate of or related to https://github.com/wagtail/wagtail/issues/11421

**Comment by lb-** [comment] 2024-02-01 21:28
Can confirm this error exists.

**Comment by lb-** [comment] 2024-02-28 10:24
Note - the basic usage of Draftail / RichText within custom image models will be fixed by https://github.com/wagtail/wagtail/pull/11620

However, nested choosers will not be supported yet, so the RichText choosers can only be functional on edit image and bulk upload image views.

**Closed** 2024-02-28 11:36 UTC
Labels: type:Bug, component:Images, component:Rich text, component:Choosers
