### ISSUE TITLE
Reveal Controller does not handle external toggles outside of scope

### ISSUE THREAD

**Issue by SebCorbin** [wagtail/wagtail#11276] opened 2023-11-24 17:07 UTC
### Issue Summary

There is little documentation and usage examples about this controller in the wild so I have been referring to the unit tests, especially the one about `should support dispatching on & updating toggles that are not in the controlled element scope`.

This test passes, be cause toggle are effectively updated, but in return there are not controlling their respective `aria-controls`

### Steps to Reproduce

Take the template from the unit tests

```html
<main>
  <header>
    <button type="button" aria-controls="panel-red-content" data-w-reveal-target="toggle">Toggle</button>
    <button type="button" aria-controls="panel-blue-content" data-w-reveal-target="toggle">Toggle</button>
  </header>
  <aside class="container" id="panel-red" data-controller="w-reveal">
    <button type="button" aria-controls="panel-red-content" data-w-reveal-target="toggle" data-action="w-reveal#toggle">Toggle</button>
    <div data-w-reveal-target="content" id="panel-red-content">CONTENT</div>
  </aside>
  <aside class="container" id="panel-blue" data-controller="w-reveal">
    <button type="button" aria-controls="panel-blue-content" data-w-reveal-target="toggle" data-action="w-reveal#toggle">Toggle</button>
    <div data-w-reveal-target="content" id="panel-blue-content">CONTENT</div>
  </aside>
</main>
```

- when i click on the toggles inside `<aside>` element, their respective content are effectively closed
- when i click on the toggles outside `<aside>` element, their respective content are not closed

Any help appreciated, because I'm not sure that a bug

**Comment by lb-** [comment] 2023-11-24 20:40
Hey @SebCorbin - nice to see you're interested in this area of the code. 

It would be good to be aware that these controllers are intentionally not documented at this point. This is because we need the freedom to change these without too much backwards compatibility risks. We may document some controllers in the future when we are more confident with their APIs. 

We are still actively building out this controller - you can track the progress here https://github.com/wagtail/wagtail/issues/10168

The next stage of this controller will hopefully support a similar use case to yours but not by the Reveal controller listening to clicks on the 'external' buttons. 

Instead we will provide a way (I think) for an external button to dispatch events to any other targets. This better aligns with more generic controllers and is much more flexible. Stimulus' docs encourage the use of events to communicate across controllers. 

You can see some WIP here https://github.com/wagtail/wagtail/compare/main...lb-:wagtail:feature/adopt-reveal-controller-side-panels-v3?expand=1

**Comment by lb-** [comment] 2023-11-24 20:43
For now I think it's best to close this for now. It's not a bug as it's basically still being built. When we have a finalised version of this (used for Side Panels and  Panels) we may consider documenting this as supported. 

In the meantime it's best to reach out in the support channels for guidance on using Stimulus. If you'd like to see something specific built for this controller (or just explain why this is useful for you) please add a comment to https://github.com/wagtail/wagtail/issues/10168

**Closed by lb-** 2023-11-24 20:43 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by lb-** [comment] 2023-11-24 21:04
Another place to start discussing 'documented Stimulus controllers' would be https://github.com/wagtail/wagtail/discussions/11125

I'm not sure if we will do that anytime soon but would love to see what you and others in the community would want this to look like. Including examples of use cases. 

We are hopeful that for common behaviour, developers will not need to reach for much JS or even HTML. Instead using the core parts of the Python APIs should allow you to do a lot.
