### ISSUE TITLE
null value in column "draft_title" violates not-null constraint

### ISSUE THREAD

**Issue by phptek** [wagtail/wagtail#6069] opened 2020-05-24 23:29 UTC
### Issue Summary

Running unit tests in our local and CI (Docker) environments, results in the following exception:

```
psycopg2.errors.NotNullViolation: null value in column "draft_title" violates not-null constraint
DETAIL:  Failing row contains (15, 0001, 1, 1, Root, root, t, f, /, , f, , null, null, f, 1, null, f, null, null, null, null, null, null, null).
```

**Notes**

* The DJango setup comprises apps and test-suites that were written _prior_ to the introduction of Wagtail as its own app.
* Wagtail is running off its own DB connector which currently just points to the "default" connection but I have observed the same problem when connecting to an entirely separate schema with the same connection name (in Postgres)
* I'm suspecting that migrations are probably being run out of order. But seeing that DJango migrations are auto-generated then they should therefore "know best", we cannot easily alter their order to some arbitrary definition

### Steps to Reproduce

Running unit tests using `BasicNoseRunner` we see:

```
#> docker-compose exec my-app bin/runner test --noinput --verbosity=3 --config=nose.cfg
DefaultPluginManager load plugin xcover = nosexcover.nosexcover:XCoverage
DefaultPluginManager load plugin nose_ignoredoc = nose_ignoredoc:IgnoreDocstrings
nosetests --config=/usr/share/my-app/nose.cfg --verbosity=3 --config=nose.cfg
DefaultPluginManager load plugin xcover = nosexcover.nosexcover:XCoverage
DefaultPluginManager load plugin nose_ignoredoc = nose_ignoredoc:IgnoreDocstrings
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.plugins.xcover: INFO: Coverage report will include only packages: ['app', 'app']
nose.plugins.cover: INFO: Coverage report will include only packages: ['app', 'app']
Creating test database for alias 'default' ('test_foo')...
Got an error creating the test database: database "test_foo" already exists

Destroying old test database for alias 'default' ('test_foo')...
Operations to perform:
  Synchronize unmigrated apps: admindocs, api, ckeditor, django_extensions, django_filters, django_nose, humanize, invites, manage, messages, modelcluster, personalgroups, pipeline, rest_framework, settings, staticfiles, wagtailapi_v2, wagtailsites, wagtailsnippets, wizard
  Apply all migrations: accounts, admin, auth, cms, contenttypes, eventlog, sessions, sites, switch, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailsearchpromotions, wagtailusers
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application sites
...
...
Running pre-migrate handlers for application wagtailforms
Running pre-migrate handlers for application wagtailredirects
Running pre-migrate handlers for application wagtailembeds
Running pre-migrate handlers for application wagtailusers
Running pre-migrate handlers for application wagtailsnippets
Running pre-migrate handlers for application wagtaildocs
Running pre-migrate handlers for application wagtailimages
Running pre-migrate handlers for application wagtailsearch
Running pre-migrate handlers for application wagtailsearchpromotions
Running pre-migrate handlers for application wagtailadmin
Running pre-migrate handlers for application wagtailcore
Running pre-migrate handlers for application cms
Running pre-migrate handlers for application modelcluster
Running pre-migrate handlers for application django_extensions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK (0.034s)
  Applying auth.0001_initial... OK (0.164s)
  ...
  ...
  Applying contenttypes.0002_remove_content_type_name... OK (0.100s)
  Applying auth.0002_alter_permission_name_max_length... OK (0.013s)
  Applying auth.0003_alter_user_email_max_length... OK (0.039s)
  Applying auth.0004_alter_user_username_opts... OK (0.031s)
  Applying auth.0005_alter_user_last_login_null... OK (0.033s)
  Applying auth.0006_require_contenttypes_0002... OK (0.003s)
  Applying auth.0007_alter_validators_add_error_messages... OK (0.035s)
  Applying auth.0008_alter_user_username_max_length... OK (0.036s)
  Applying auth.0009_alter_user_last_name_max_length... OK (0.034s)
  Applying auth.0010_alter_group_name_max_length... OK (0.023s)
  Applying auth.0011_update_proxy_permissions... OK (0.080s)
  Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field...Traceback (most recent call last):
  File "/opt/virtual-environment/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "draft_title" violates not-null constraint
DETAIL:  Failing row contains (15, 0001, 1, 1, Root, root, t, f, /, , f, , null, null, f, 1, null, f, null, null, null, null, null, null, null).
```

Relevant Info:

* DJango 2.2 / Wagtail 2.8 / docker-compose 1.23.2
* Similar description to this SO post (which suggests the underlying problem was fixed?) https://stackoverflow.com/questions/51985358/wagtail-running-tests-raises-psycopg2-integrityerror-null-value-in-column-dr#51985754
* Using x2 `DATABASE` connections "default" and "cms" with simple `DATABASE_ROUTERS` implementation:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': fetch_config(config.get, "database", "name"),
        'USER': fetch_config(config.get, "database", "user"),
        'HOST': fetch_config(config.get, "database", "host"),
        'PASSWORD': fetch_config(config.get, "database", "password")
    },
    # "cms" is just a dumb DB connection back to the default DB. We do this to make it easier in future
    # to modify Puppet/Ansible config and point credentials/vars at a separate DB
    'cms': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': fetch_config(config.get, "database", "name"),
        'USER': fetch_config(config.get, "database", "user"),
        'HOST': fetch_config(config.get, "database", "host"),
        'PASSWORD': fetch_config(config.get, "database", "password")
    },
}
```

```
import re, sys


class DBRouter():
    """
    Switch to the appropriate DB connection based on a model's `app_label`.

    Note: Migrations will default to using the "default" connection in DATABASES unless
    `--database <name>` is passed.
    """

    def _is_cms(self, model):
        return re.match(r"^wagtail", model._meta.app_label)

    def db_for_read(self, model, **hints):
        if self._is_cms(model):
            return 'cms'

        return 'default'

    def db_for_write(self, model, **hints):
        if self._is_cms(model):
            return 'cms'

        return 'default'

    def allow_relation(self, obj1, obj2, **hints):
        return True

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        return True
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: "Yes"

### Technical details

* Python version: 3.6
* Django version: 2.2
* Wagtail version: 2.8
* Browser version: Brave

**Comment by gasman** [comment] 2020-05-24 23:40
Hi @phptek - thanks for the report.

It looks like your "steps to reproduce" are describing the setup from your existing project. As you say you've been able to reproduce this from a fresh Wagtail project, please can you provide steps that will replicate this starting from a clean installation?

**Comment by phptek** [comment] 2020-05-25 00:11
Hmm I knew you'd hit me up on that! It's "fresh" with respect to the main Django project (last week), but I guess this question is asking for an isolated case, outside of any other DJango apps right?

Regardless, Wagtail is just another Django app, so it should be able to be run as well with other apps as without right?

**Comment by gasman** [comment] 2020-05-25 13:38
It doesn't have to be an isolated case with no other Django apps involved, but it does need to be a set of steps that someone else can follow independently to reach the same error. If the problem only occurs within this one project, then there are really too many variables for us to effectively diagnose the problem or verify when it's been fixed - it could be the multiple databases, it could be something non-standard you've done in the migration history, or it could be something else in your setup that hasn't been mentioned here.

**Comment by eeintech** [comment] 2020-05-26 21:19
I ran into the same issue.

Steps to reproduce:
1. Add new database to `base.py` configuration:
```
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	},
	'postgresql': {
		'NAME': 'mypsql',
		'ENGINE': 'django.db.backends.postgresql',
		'USER': 'username',
		'PASSWORD': 'xxxxx',
		'HOST': '127.0.0.1',
		'PORT': '5432',
	}
}
```

2. Run migrate with `--database=postgresql` option:
```
$ ./manage.py migrate --database=postgresql
Operations to perform:
  Apply all migrations: admin, auth, blog, coderedcms, contenttypes, home, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailmenus, wagtailredirects, wagtailsearch, wagtailusers
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
  Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field...Traceback (most recent call last):
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "draft_title" violates not-null constraint
DETAIL:  Failing row contains (3, 0001, 1, 1, Root, root, t, f, /, , f, , null, null, f, 1, null, f, null, null, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)

(... troncated data ...)

django.db.utils.IntegrityError: null value in column "draft_title" violates not-null constraint
DETAIL:  Failing row contains (3, 0001, 1, 1, Root, root, t, f, /, , f, , null, null, f, 1, null, f, null, null, null, null, null, null, null).
```

**Comment by phptek** [comment] 2020-05-26 21:56
For me, this issue always occurred running our app's test suite, the app works A-OK via a browser. So just this morning I have managed to work around it by only including the "cms" DB connection when _not_ in a test scenario:

```
IN_UNIT_TESTS = ('test' in sys.argv and sys.argv[1] == 'test')

if not IN_UNIT_TESTS:
    DATABASE_ROUTERS = [
        'app.settings.routers.cms.CMSRouter',
    ]
    DATABASES['cms'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': fetch_config(config.get, "database", "name"),
        'USER': fetch_config(config.get, "database", "user"),
        'HOST': fetch_config(config.get, "database", "host"),
        'PASSWORD': fetch_config(config.get, "database", "password")
    }
```

**Comment by gasman** [comment] 2020-05-27 00:19
Thanks for the additional details. It sounds like this is a duplicate of #2234 - essentially, if you want to use multiple databases, then it's your responsibility to set up [a database router](https://docs.djangoproject.com/en/3.0/topics/db/multi-db/#automatic-database-routing) to define how models are divided or replicated between those databases. In this case, the errors are happening because the migrations are running for a second time but performing insertions against the first database.

It may well be that Wagtail isn't currently doing everything it should be doing to support multi-database setups, but if all we know is "there are some multi-database configurations that fail" then we have no way to tell whether that's user error or a Wagtail bug. What we've been missing up to now is someone with enough familiarity with multi-DB setups to definitively say "with router config X, A should be happening but Wagtail is doing B instead".

**Closed by gasman** 2020-05-27 00:19 UTC
Labels: status:Needs Info, type:Bug

**Comment by phptek** [comment] 2020-05-27 00:49
Well I gave you a DB router above. If that's not enough then I'm not sure what else you need.

**Comment by eeintech** [comment] 2020-05-27 13:12
@gasman Does running `/manage.py migrate --database=xxx` need a router as well?

**Comment by gasman** [comment] 2020-05-27 14:00
@eeintech I believe so, yes.

**Comment by frontendr** [comment] 2021-09-13 14:09
> @eeintech I believe so, yes.

@gasman, sorry for replying to a closed issue but I believe this is not the case. According to the [docs](https://docs.djangoproject.com/en/3.2/topics/db/multi-db/#database-routers), a router determines which connection is used for read or write operations and whether a relation is allowed between two objects. The `allow_migrate()` method simply allows or denies a migration based on its arguments.

The `--database=somedatabase` argument for `manage.py migrate` can be easily supported in migration `RunPython` methods (see the [`RunPython` docs](https://docs.djangoproject.com/en/3.2/ref/migration-operations/#runpython)) by using `schema_editor.connection.alias` (`schema_editor` is the 2nd argument for the method provided to `RunPython`) like (example from the docs):

```python
def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Country = apps.get_model("myapp", "Country")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).bulk_create([
        Country(name="USA", code="us"),
        Country(name="France", code="fr"),
    ])
```

So I would suggest that at the minimum the `RunPython` methods should simply operate on `schema_editor.connection.alias` instead of 'hard coded' on the default connection.

Of course this doesn't automatically propagate to underlying methods but for the `initial_data()` method from `core.0001_squashed_0016_change_page_url_path_to_text_field.py` it would simply mean adding the `.using()` call on the querysets:

```
db_alias = schema_editor.connection.alias
root = Page.objects.using(db_alias).create(
    ...
```

The "hints" suggested in #2234 are not a solution for simply allowing developers to run migrations on a specific connection/alias.

I'm currently working on a workaround for my current project where I want to create a 'template' testing database next to my production database but it would help ALOT if Wagtail's migrations would simply use the `--database` argument in the migrations.

Regards!

**Comment by frontendr** [comment] 2021-09-13 15:45
@gasman I Just started on a PR and already noticed that the [`get_fill_filter_spec_migrations()`](https://github.com/wagtail/wagtail/blob/fb4a5a6961c20ab9d0b2bdd0aa8374af9d61cb2d/wagtail/images/utils.py#L11) already uses this db_alias in its migration methods which is called in the [images.0015_fill_filter_spec_field](https://github.com/wagtail/wagtail/blob/main/wagtail/images/migrations/0015_fill_filter_spec_field.py) migration.

Most of the migrations can be easily updated by adding `.using(db_alias)`.

One problem I noticed though is the [core.0059_apply_collection_ordering](https://github.com/wagtail/wagtail/blob/main/wagtail/core/migrations/0059_apply_collection_ordering.py) migration. This migration calls `Collection.fix_tree()` which in turn calls treebeard.. stuff.. This would mean that all these methods would need to accept a `db_alias` argument which I find quite scary as I have no clue what the impact of that would be.

**Comment by frontendr** [comment] 2021-09-14 07:27
Ongoing development: https://github.com/frontendr/wagtail/commit/eed08e171a6dc3b46e95dec08d25276ccc211764

**Comment by madqueendany** [comment] 2022-01-17 10:23
Hey! If you're having the same specific scenario as mine where I need to migrate the test database, i just reconfigured the `DATABASES` dict to set the `default` to my `test_database`.

Did that, called `./manage.py migrate`, and then it migrated successfully.

**Comment by gasman** [comment] 2023-11-15 21:10
Revisiting this in the light of #11184, which has demonstrated that 1) people have been successfully using Wagtail in certain multi-database configurations (until we broke them 🤦), and 2) we need to properly formalise which configurations are and aren't supported (and test the ones that are).

I've now opened #11237 to address this subject. Under that proposal as it currently stands, we would only support configurations where Wagtail's tables exist in the default database and nowhere else, and Wagtail's migrations are suppressed from running in non-default databases. This means that the configuration that triggers this error (in which the Wagtail migrations are allowed to run on multiple databases) would be deemed invalid.

I'm happy to reconsider this if anyone feels that this is excluding valid setups that we ought to be supporting - if so, further feedback would be very welcome at #11237.

**Comment by chokosabe** [comment] 2024-06-04 14:31
So, was there ever a fix for this? Running into the same issue.

**Comment by gasman** [comment] 2024-06-04 14:42
@chokosabe The current status is as described in #11237 - if your project is configured to use multiple databases, you must provide a [database router](https://docs.djangoproject.com/en/stable/topics/db/multi-db/#automatic-database-routing) that places Wagtail's tables only in the 'default' database.

**Comment by chokosabe** [comment] 2024-06-04 18:00
Have tried editing the router to no avail: 

`
# routers.py

class TimescaledbDatabaseRouter:
    """
    A router to control all database operations on models for the second database,
    while ensuring the 'wagtail' app always uses the default database.
    """
    def db_for_read(self, model, **hints):
        """
        Attempts to read models go to timescaledb for 'timeseries' app,
        and default for 'wagtail' app.
        """
        if model._meta.app_label in ['timeseries']:
            return 'timescaledb'
        elif model._meta.app_label in ['wagtail']:
            return 'default'
        return None

    def db_for_write(self, model, **hints):
        """
        Attempts to write models go to timescaledb for 'timeseries' app,
        and default for 'wagtail' app.
        """
        if model._meta.app_label in ['timeseries']:
            return 'timescaledb'
        elif model._meta.app_label in ['wagtail']:
            return 'default'
        return None

    def allow_relation(self, obj1, obj2, **hints):
        """
        Allow relations if a model in timeseries is involved.
        """
        if obj1._meta.app_label in ['timeseries'] or obj2._meta.app_label in ['timeseries']:
            return True
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """
        Make sure the timeseries models get created on the right database,
        and wagtail models get created on the default database.
        """
        if app_label in ['timeseries']:
            return db == 'timescaledb'
        elif app_label in ['wagtail']:
            return db == 'default'
        return None

`
