### ISSUE TITLE
ModelAdmin Group and Settings link not working

### ISSUE THREAD

**Issue by josephkohlmaier** [wagtail/wagtail#5492] opened 2019-08-08 12:15 UTC
Since upgrading to 2.6.1, the ModelAdminGroup and Settings links in the sidebar do not produce a submenu on click. See video here: https://www.dropbox.com/s/dvmwhipyb85hxjd/issue_submenu.mov?dl=0 – the event defaults as can be seen (# appearing in URL on click)

Python 2.7.12
Django>=2.1,<2.2
All browsers

**Comment by gasman** [comment] 2019-08-08 13:05
Please see #5480 - have you tried clearing your browser cache (and running `manage.py collectstatic`, if this is a production site rather than a local development instance)?

**Comment by josephkohlmaier** [comment] 2019-08-08 13:23
Yes, I have done both as a first step, both locally and in the live Docker container although I now see an error (attached). Has the location for static files changed? When I set the version back to 2.5 and rebuild the container, the menu appears again without problems. Incidentally, there is something very strange happening (only locally, and after collectstatic, but not locally) in another project – watch the icons appear and disappear as I hard refresh the page. This might be related: https://www.dropbox.com/s/w8hkw9btdka4tne/icons-missing.mov?dl=0
![Screenshot 2019-08-08 at 14 20 36](https://user-images.githubusercontent.com/40425066/62706679-ee69b600-b9e7-11e9-8080-e66ca970a092.png)

**Comment by gasman** [comment] 2019-08-08 15:08
This definitely looks like a configuration issue causing static files from a previous Wagtail installation to show up - the icon font is one thing that has been updated in 2.6. From the video I notice that the icons are breaking when you navigate to another page, and fixed again when you hard refresh - which matches the behaviour we'd see if a `STATICFILES_STORAGE` backend that assigns distinct filenames for different versions, such as `ManifestStaticFilesStorage`, and those pages were being cached.

Will close this for now as it doesn't look like Wagtail itself is at fault here, but happy to investigate further if you're able to reproduce this consistently on a newly-created project. You might have more success asking on [our support channels](https://docs.wagtail.io/en/stable/support.html).

**Closed by gasman** 2019-08-08 15:08 UTC
Labels: status:Needs info

**Comment by Constuelo** [comment] 2019-08-11 18:18
Having the same issue but on localhost, need to hard refresh for it to work... still looking for the cause

**Comment by DanielSwain** [comment] 2019-09-17 20:41
I've just encountered this same issue after updating six sites to 2.6.1.  This issue occurs on only one site, and the only difference between the sites is that the problem site uses `ModelAdminGroup` to create two groups on the left menu.  I have run `collectstatic` and hard refreshed many times to get the latest static files.

When I set an Event Listener Breakpoint in Chrome's dev tools to catch mouse clicks and then click on the `Settings` menu, on all other sites I can see the following `js` files called in this order:

1. webpack:///./client/src/includes/initSubmenus.js
2. https://mysite.com/static/wagtailadmin/js/vendor/jquery-3.2.1.min.js
3. webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js

On the problem site, I only see these `js` files accessed when I click on either the `Settings` menu or either of the two `ModelAdminGroup` menus:

1. https://mysite.com/static/wagtailadmin/js/vendor/jquery-3.2.1.min.js
2. webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js

My development machine is Ubuntu 16.04.  The production server is Ubuntu 18.04.  Both use uWSGI/Nginx.  Python is 3.6 on both.  The problem behavior occurs on both machines.  The problem site was previously at Wagtail 2.5.1.

**Comment by gasman** [comment] 2019-09-18 08:49
Hi @DanielSwain,
The [bakerydemo](https://github.com/wagtail/bakerydemo) demo site also has two `ModelAdminGroup`s in the left menu, and we've been using that for testing and development on 2.6.x with no issues, so that wouldn't seem to be the cause of the problem in itself.

I'd suggest making a local copy of the affected site, and progressively removing apps and code until you arrive at a minimal test case that reproduces the issue - that should make it easier to see whether this is indeed a Wagtail bug, and if so, allow us to investigate further.

**Comment by adpio** [comment] 2019-10-10 15:20
I have the same problem. However I've found out that everything works fine in incognito mode (chrome and safari). Very odd...

**Comment by DanielSwain** [comment] 2019-10-12 01:30
I just tried incognito mode with my problem site, and it does not work.

**Comment by DanielSwain** [comment] 2019-11-11 19:12
I finally solved this problem.  I needed to display an image using Wagtails `{% image %}` tag on a `ModelAdmin` edit page.  The image had to display below the other fields on the model.  The only way I could determine to do this a year ago when Wagtail was at version 2.5 was to create a new version of Wagtail's `base.html` [template in wagtailadmin](https://docs.wagtail.io/en/latest/reference/contrib/modeladmin/primer.html#overriding-templates).  Wagtail's `base.html` had a major change in version 2.6:

`<div class="nav-wrapper">`

was changed to:

`<aside class="nav-wrapper" data-nav-primary>`

This data attribute is used as a selector for the Settings flyout menu.  I finally discovered that the proper way to accomplish the display of the image is by using Django's `{{ block.super }}` [command](https://docs.djangoproject.com/en/2.2/ref/templates/language/#template-inheritance).  I used `{{ block.super }}` to override within `{{ block content }}` and then, within that block and under the `{{ block.super }}`  statement, I added the `{% image %}` tag and some explanatory text.  I'm also going to propose a change to the docs [here](https://docs.wagtail.io/en/latest/reference/contrib/modeladmin/primer.html#overriding-templates) to mention `{{ block.super }}` in the same way that it is mentioned [here](https://docs.wagtail.io/en/latest/advanced_topics/customisation/admin_templates.html#extending-the-login-form).

**Comment by tomdyson** [comment] 2019-11-11 19:44
Thank you for following up @DanielSwain!
