### ISSUE TITLE
BaseSiteSetting - Permissions

### ISSUE THREAD

**Issue by mschiegg** [wagtail/wagtail#9169] opened 2022-09-08 10:29 UTC
### Is your proposal related to a problem?

I've a Project with multiple Websites und multiple Groups. Each Group have access to one Site. The User in the Group should only have Access to his own Site.
No i have implemented a BaseSiteSetting and give Access zu the User. But every User can edit every Site Settings.
I don't find a way to restrict.

![image](https://user-images.githubusercontent.com/24289995/189099833-1ee2c03e-1613-47a3-8361-a3989eebb9df.png)

### Describe the solution you'd like

Expand BaseSiteSettings so that users have access only to the pages selected in the group.

![image](https://user-images.githubusercontent.com/24289995/189100008-da831418-e059-4c07-a065-c06f38d039de.png)

**Comment by laymonage** [comment] 2024-07-29 14:58
Closing as duplicate of #2574.

**Closed by laymonage** 2024-07-29 14:58 UTC
Labels: type:Enhancement, component:Permissions, component:Settings
