### ISSUE TITLE
Add unique constraint for the TaskState

### ISSUE THREAD

**Issue by byshen** [wagtail/wagtail#8090] opened 2022-03-08 01:37 UTC
### Issue Summary

In file `wagtail/core/models/__init__.py`, the `TaskState` is defined to track the status of a given task for a particular page revision.

There are code logics to handle the case. For example, in file `wagtail/admin/views/pages/workflow.py`
```python
    try:
        task_state = TaskState.objects.get(
            page_revision__page=page, task=task, status=TaskState.STATUS_IN_PROGRESS
        )
    except TaskState.DoesNotExist:
        ...
```

To improve the data integrity, we can enforce this with data constraint in class `TaskState`. For example, we can add a constraint like this.

```python
class Meta:
    ...
    constraints = [
        UniqueConstraint(
            fields=["page_revision", "task"],
            condition=Q(status='in_progress')),
```

Please let me know your thoughts. Thanks a lot :D 

### Technical details

* Python version:3 .8.8
* Django version: 4.0.2
* Wagtail version: 2.17a0
* Browser version: Chrome/99.0.4844.51 Safari/537.36

**Comment by byshen** [comment] 2022-03-16 21:25
@gasman Could you help take a look? This is similar to #8089. I can create a PR to fix this. Thanks

**Comment by lb-** [comment] 2022-03-24 11:21
See https://github.com/wagtail/wagtail/issues/8089#issuecomment-1077518164 - due to limited DB support, flagging this as an optimisation for now and not a bug.

**Comment by lb-** [comment] 2022-04-20 09:17
Closing as per comments
https://github.com/wagtail/wagtail/pull/8152#issuecomment-1103677236
https://github.com/wagtail/wagtail/issues/8089#issuecomment-1103680226

We may reopen in the future.

**Closed by lb-** 2022-04-20 09:17 UTC
Labels: type:Cleanup/Optimisation, component:Workflow
