### ISSUE TITLE
Changing name of a published page and saving as draft doesn't change page name in explorer

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#529] opened 2014-08-06 14:46 UTC
1. Create a page, set a title, publish it
2. Edit the page again, change the title completely, save as draft: don't publish.

In the explorer listing, the title of the page will be that of the published version. I found this very confusing. It looks like the save didn't actually work despite the notification claiming it did. Even given my knowledge of the revision system I found myself repeatedly editing the page and saving again, just to double-check I changed the title.

Given that we only allow one draft, I'd suggest that the page information displayed in the explorer be that of the draft revision, not whatever it currently is. 

I wonder if this ticket will also be affected by this issue: https://github.com/torchbox/wagtail/issues/418 Will the "last edited date" actually be that of the published version, not the draft?

**Comment by marctc** [comment] 2016-04-11 07:30
Hi @davecranwell. Why this ticket is closed? I'm using wagtail 1.4 and still happends. It is an expected behaviour?

**Comment by kaedroho** [comment] 2016-04-11 09:45
@marctc This is expected as a page in "live + draft" status has it's live content in the database and draft changes packed in the "revisions" table. Wagtail's listing pages always use the title as it is in the database as this is best for performance.

(Note this isn't the case for unpublished pages, for these the latest draft revision is always stored in the database so changes to the title take effect immediately)

I think this ticket was closed as looking up the title from the revision would be very tricky to implement without impacting performance very much.

**Comment by marctc** [comment] 2016-04-11 10:19
I understand your point but in my opinion is not and expected behaviour. It's not a big deal, but this ticket shouldn't be closed.

**Comment by kaedroho** [comment] 2016-04-11 12:23
I agree. The fact that we can't think of a good solution at the moment doesn't make the bug invalid.

I'll reopen, thanks!

**Comment by marctc** [comment] 2016-04-11 12:45
Thanks!

**Comment by dpratter** [comment] 2016-09-19 09:16
@kaedroho commented on Apr 11
> (Note this isn't the case for unpublished pages, for these the latest draft revision is always stored in the database so changes to the title take effect immediately)

At least for **wagtail==1.6.2** I think that this does not work (anymore).
I changed titles of unpublished pages and saved them as drafts but can still see the old titles in explorer view.

**Comment by gasman** [comment] 2016-09-19 16:58
> At least for wagtail==1.6.2 I think that this does not work (anymore).
I changed titles of unpublished pages and saved them as drafts but can still see the old titles in explorer view.

Confirmed - I'm seeing this too. Will investigate...

**Comment by gasman** [comment] 2016-09-19 18:35
Hmm, looks like this hasn't been the case ever since Wagtail 1.0, when #1133 was merged - as of that commit, we only ever save to the revisions table, not to pages. @kaedroho, do you remember whether this was intentional?

**Comment by kaedroho** [comment] 2016-09-20 08:32
@gasman Nope, that wasn't intentional

**Comment by ghostwords** [comment] 2016-12-02 21:59
Still an issue, at least in 1.6.3. Updating a draft-only status page's title is not reflected in explorer.

Another way for this issue to surface is when you make an [index page model that retrieves all child pages, not just live pages, when the index page itself is unpublished](https://github.com/ghostwords/localore/commit/bfdd71db55ffe999110a83ba0c884429d8971729) in order to allow index page previewing without having to publish child pages. In this case, it's not just titles that are out-of-date, it's any property used by the index page.

**Comment by gasman** [comment] 2016-12-05 12:43
It's worth bearing in mind that the [wagtail-experiments](https://github.com/torchbox/wagtail-experiments) module currently relies on the assumption that a draft edit to an unpublished page _will not_ update the main pages table... if we change this behaviour, it will need to be documented accordingly (and to make wagtail-experiments work, we'd probably have to introduce the concept of additional page states besides 'published' which keep the page record frozen at a particular point).

**Comment by gasman** [comment] 2017-08-29 11:26
Fixed in #3285

**Closed by gasman** 2017-08-29 11:26 UTC
Labels: type:Bug
