### ISSUE TITLE
Cannot Reorder the page with children pages between the pages with children pages

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#8036] opened 2022-02-24 03:59 UTC
### Issue Summary

The page having children pages cannot be reordered between the pages those also have children pages.
But the page having children pages can be reordered between single pages.

### Steps to Reproduce

1. I have the following pages. **China** and **Global strategy** have their own children pages while **Joyce Poon** is single page. 
![image](https://user-images.githubusercontent.com/81170508/155455175-6b9917c9-6ea1-45c5-bf89-b4540cee4903.png)
2. I fail to move **Global strategy** _above_ **China**, but I can move **Global strategy** _below_ **Joyce Poon**.

### Technical details
Python version: 3.10
Wagtail version: 2.16.1

**Comment by zerolab** [comment] 2022-02-24 09:18
Thank you for the bug report, @aliceni81. This looks like a duplicate of #8004 which will be fixed by #8013.

Closing the issue on that basis. Do shout if this is different from #8004

**Comment by aliceni81** [comment] 2022-02-24 09:37
@zerolab The problems are different.

**Comment by zerolab** [comment] 2022-02-24 09:40
@aliceni81 fair enough. Do you get any errors when re-ordering? If not, do you drag and drop, but nothing happens? Are there any errors in the developer console?

**Comment by aliceni81** [comment] 2022-02-24 09:45
@zerolab Thanks. No any errors shown in developer console. I can drag and drop, but nothing happens. I found the path in the database are not changed. I solve this problem by manually updating path in the table "wagtailcore_page" in the database.

**Comment by jsma** [comment] 2022-03-22 01:11
I was able to reproduce this, but it does appear to be the same issue as #8004 and can probably be closed again.

@aliceni81 can you check again and look at the Django debug server output? This was the only place I noticed the error, e.g.:

```
WARNING Forbidden (Permission denied): /cms/pages/186/set_position/
Traceback (most recent call last):
  ...snip...
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/pages/ordering.py", line 37, in set_page_position
    page_to_move.move(position_page, pos='left', user=request.user)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models/__init__.py", line 1449, in move
    return MovePageAction(self, target, pos=pos, user=user).execute()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/actions/move_page.py", line 107, in execute
    self.check(skip_permission_checks=skip_permission_checks)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/actions/move_page.py", line 32, in check
    raise MovePagePermissionError(
wagtail.core.actions.move_page.MovePagePermissionError: You do not have permission to move the page to the target specified.
[21/Mar/2022 21:04:52] "POST /cms/pages/186/set_position/?position=12 HTTP/1.1" 403 35665
```

**Comment by aliceni81** [comment] 2022-03-25 10:29
@jsma This issue can be reproduced without defining parent_page_types in the Page class. I still cannot find any error in console with debug mode on.

**Comment by jsma** [comment] 2022-03-27 01:38
Oops, I thought I had tested with pages that did not specify parent_page_types but just fact-checked myself and I was wrong. I removed parent_page_types from my test pages and I am no longer able to reproduce your issue, I can insert a childless page in between two pages with children, refresh the page and it preserves the new sort order.

**Comment by aliceni81** [comment] 2022-03-28 06:31
@jsma Thanks for checking. 
Actually my problem is that the page with children cannot be moved up/down the another page with children.

**Comment by zerolab** [comment] 2022-03-29 16:29
@jsma @aliceni81 could you give the latest `main` or `stable/2.16.x` (#8227) branch a try?

**Comment by cnk** [comment] 2022-03-30 04:37
I tried to reproduce this issue using the bakerydemo project and the 2.16.x branch containing the sorting fix. But all sorting that I tried worked fine.

**Comment by aliceni81** [comment] 2022-03-30 06:04
@zerolab @cnk Oops, you are right. 
I found that I actually defined "subpage_types" in AuthorIndexPage. Once I remove subpage_types, the pages with children can be moved successfully.

**Closed** 2022-03-30 16:31 UTC
Labels: type:Bug
