### ISSUE TITLE
Grid from TableBlock is missing after saving a page (from wagtail.contrib.table_block.blocks import TableBlock)

### ISSUE THREAD

**Issue by pdiede** [wagtail/wagtail#9107] opened 2022-08-31 08:52 UTC
### Issue Summary

I imported the default TableBlock of the wagtail.contrib.table_block.blocks. After importing i used the TableBlock to display some content in a table. The TableBlock is initially working fine but after saving the grid is missing, to change some saved data maybe fix a typo or something.

Before saving:
![image](https://user-images.githubusercontent.com/111868515/187638841-c0a43f39-c829-4815-9bce-33f6b254d93c.png)

After saving:
![image](https://user-images.githubusercontent.com/111868515/187639000-ad9a3d62-3bdb-47d6-bd9a-8d1c87fda84f.png)

### Error Message

No error message

### Steps to Reproduce

Steps to Reproduce:

Setup a fresh wagtail instance.

Import TableBlock for creating a table as content. This import statement was being used "from wagtail.contrib.table_block.blocks import TableBlock" to import the TableBlock for a page model content.

Now we should be able to pick TableBlock as content for our content page.

After adding some content to the selected Table save the page as preview.

After saving and reopening the page to edit some content i can't see the grid from the table, as shown in the second screenshot.

Install Wagtail with all the libraries in techincal details

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

    Django>=4.0,<4.1
    wagtail>3
    wagtail_localize==1.2.1
    django-extensions==3.2.0
    psycopg2==2.9.3
    loglevel==0.1.2
    Wand==0.6.10

Thank you very much in advance.

I look forward to your feedback.

**Comment by gasman** [comment] 2022-08-31 09:52
Hi @pdiede - your "steps to reproduce" section doesn't include any information on how to actually reproduce this. Please can you add more detail here?

**Comment by pdiede** [comment] 2022-08-31 09:59
Steps to Reproduce:

Setup a fresh wagtail instance.

Import TableBlock for creating a table as content. This import statement was being used "from wagtail.contrib.table_block.blocks import TableBlock" to import the TableBlock for a page model content. 

Now we should be able to pick TableBlock as content for our content page.

After adding some content to the selected Table save the page as preview.

After saving and reopening the page to edit some content i can't see the grid from the table, as shown in the second screenshot.

I hope this helps.

**Comment by pdiede** [comment] 2022-08-31 13:41
@gasman this is our page model:

`class ContentPage(Page):
    template = "home/content_page.html"
    body = StreamField(STREAMBLOCKS, null=True, blank=True, collapsed=True)

    content_panels = Page.content_panels + [
        FieldPanel("body"),
    ]

    parent_page_types = ["hintbox.HomePage"]
    subpage_types = []

    class Meta:
        verbose_name = "Inhaltsseite"`

In the StreamField we want every block collapsed so we set it to True. If the collapsed is True then the grid is missing after updating the content of a page.

But if we are not using the option collapsed it works like charm the grid will be shown.

**Comment by seb-b** [comment] 2022-09-07 06:32
I've also come across this, seems to be if the streamfield is collapsed. Funnily enough resizing the page brings the table back into existence.

**Comment by faboosh** [comment] 2022-09-28 13:57
Can also confirm that this is the case. As @seb-b mentioned, both setting `collapsed=False` and resizing the browser window redraws the table contents. Running Wagtail 3.0.1 and Chrome 105.

**Comment by vertexer** [comment] 2022-10-06 10:30
Issue confirmed as described above.

**Comment by ayy-em** [comment] 2022-11-08 03:02
Confirming this to be the case on:
- Wagtail 4.1
- Django 4.1.2

collapsed=True was set on StreamField containing my `body` element, which the table was part of
kinda sucks that I now need to choose whether I want tables and endless scrolling or no tables

**Comment by spapas** [comment] 2023-02-22 16:32
I'm getting the same behavior *without* collapsed on wagtail 4.2:

```
body = StreamField(StoryBlock(), use_json_field=True)
```

I have instructed my editors to resize their browsers in order to be able to edit the table (!) 

Can somebody please give some love to this issue? 

Thank you

**Comment by spapas** [comment] 2023-02-22 18:22
I did some research and the issue is resolved if the table resize thingie that is run at the end of the `initTable` function is run after half a second (or something like that):  
```
  window.setTimeout(() => {
    if ('resize' in $(window)) {
      resizeHeight(getHeight());
      $(window).on('load', () => {
        $(window).trigger('resize');
      });
    }
  }, 500);
```

I don't know if that helps with resolving the issue. However in my case it would be enough if I could *override* the existing `initTable` from table.js with my own initTable that includes the setTimeout ? Is this possible somehow ?

**Comment by jams2** [comment] 2023-03-08 09:53
I can reproduce this on Wagtail 4.2, Django 4.0.8.

Page definition:

```
from wagtail.models import Page
from wagtail.fields import StreamField
from wagtail.admin.panels import FieldPanel
from wagtail.contrib.table_block.blocks import TableBlock


class TableTestPage(Page):
    body = StreamField([("table", TableBlock(required=False))], blank=True)

    content_panels = Page.content_panels + [FieldPanel("body")]
```

The table widget renders when adding a new block to the stream field. After saving the page and revisiting the edit form, the existing table block does not render until the viewport is resized.

**Comment by thibaudcolas** [comment] 2023-03-08 12:59
Thank you for investigating. I’m going to guess this broke due to form markup changes in Wagtail 4.0 (reference to `sequence-member-inner`). I suspect we/I missed this due to the error only happening with saved content. I’ll assign to myself to be picked up in _2 weeks_ if anyone wants to have a go in the meantime please do.

I think the issue is indeed with this `resize` logic, either the calculation or when it is triggered. It’s very odd for this code to be firing a custom `resize` event for the whole page just so one widget gets styled correctly.

**Comment by Wasabiiiiiii** [comment] 2023-03-14 10:43
Same issue on Wagtail 4.1, Django 3.2.18.

I confirm that triggering a resize event resolves the issue.
I attach for speed the code I am using to resolve the issue.

`window.addEventListener('load', (event) => {
  window.dispatchEvent(new Event('resize'))
})
`

**Closed** 2023-03-20 21:02 UTC
Labels: type:Bug, component:Streamfield
