### ISSUE TITLE
"New password confirmation" validation error 

### ISSUE THREAD

**Issue by mo-waseem** [wagtail/wagtail#10564] opened 2023-06-14 06:50 UTC
### Issue Summary

In /admin/account (Account) there is a validation error appear for the "New password confirmation" field appeared, when it shouldn't be.

The field is empty and the "New password" field as well, so the validation should skip those fields.

### Steps to Reproduce

1- Go to "/YOUR_ADMIN_NAME/account".
2- Just save and you will see the validation error.

### Technical details

-   Python version: Python 3.10.6
-   Django version: Django 4.0.5
-   Wagtail version: 5.0.1
-   Browser version: Chrome 113

**Comment by cosmos1721** [comment] 2023-06-14 08:00
hi
i tried to reproduce the same, but it seems fine to me. what i tried:
 1. changing password traditionally
 2. leaving the fields empty to generate errors.
 3. trying passwords that don't match 
All of these works fine. 
if there's anything I'm unable to understand, can you please explain?
if the issue persists, can I work on it?

**Comment by lb-** [comment] 2023-06-14 08:03
I cannot really reproduce anything with the steps provided, what do you mean by "Just save and you will see the validation error."

My guess though is that your browser is auto-filling the 'old password' field, when you save you get an error because you have not entered a new password field.


<img width="1060" alt="Screenshot 2023-06-14 at 6 01 49 pm" src="https://github.com/wagtail/wagtail/assets/1396140/b4937e55-c5b2-4857-abd2-2de27f748834">


Let me know if this is what you mean, the error message in this case is "This password is too short. It must contain at least 8 characters." though.

**Comment by mo-waseem** [comment] 2023-06-14 08:23
OR.. 
as you said, we can disable the auto filling because it's bad UX to empty the old password field each time we need to edit the account.

**Comment by cosmos1721** [comment] 2023-06-14 10:08
> Yes you're right, the error showed only when the old password is auto completed.
> 
> I think it's better to do the validation only if there a values in one of the two fields "New password" & "New password confirmation".





> OR.. as you said, we can disable the auto filling because it's bad UX to empty the old password field each time we need to edit the account.

i tried working with autocomplete, but seems like my browser's autocomplete isn't allowing me to enter values there itself.
but at times it gives async errors. Though I have seen this with material UI if its used in the project (I don't have much expertise in Django for now, so I might be wrong)

**Comment by lb-** [comment] 2023-09-22 22:10
Ok. I recommend that this be fixed by the following (from above)

1. Putting the password fields in a new collapsible panel section that's collapsed by default
2. When the form submits ignore the password fields if new password field is NOT empty AND password confirmation field IS empty

This creates a clearer intention from the user that they want to modify the other user's password and solves for the browser autofill issue while still letting this be used.

There could be an argument for blocking autofill on the password field as admins will likely be changing a password that's not thairs. However, in my experience, browsers and various password managers do not always respect this attribute on password fields. 

This is probably not a 'good first issue' but it's a solid issue for someone to pick up with some basic experience.

**Comment by Chiemezuo** [comment] 2023-10-22 16:47
Pushing a fix for this in a bit...

**Closed** 2023-10-23 15:27 UTC
Labels: type:Bug, component:User Management
