### ISSUE TITLE
Drop downs in date / datetime widget are unusable on Macbook's touchpad

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3113] opened 2016-10-26 15:07 UTC
It' impossible to change month or year in date / datetime pickers on Macbook's touchpad.

See [this demo video](https://www.youtube.com/watch?v=mSvkYfO5QDM).

Can reproduce it with:
- Firefox 49.0.1
- Chrome 54.0.2840.71 (64-bit)
- Safari 9.1 (11601.5.17.1)

**Comment by gasman** [comment] 2016-10-26 16:32
Confirmed. (Are you on OS X Sierra? I have the impression that the Sierra upgrade has generally broken a lot of scrolling behaviour...)

The version on http://xdsoft.net/jqplugins/datetimepicker/ seems to behave a bit better - https://github.com/xdan/datetimepicker/issues/179 might be the bugfix in question, but I'm not 100% sure. Either way, it's definitely worth us upgrading to the latest version.

**Comment by m1kola** [comment] 2016-10-26 16:39
Sorry, I've forgotten to add OS version. I use El Capitan at the moment (0.11.4 (15E65)). I'll try on Windows laptop tomorrow.

> The version on http://xdsoft.net/jqplugins/datetimepicker/ seems to behave a bit better

At least in Chrome I see no difference with our version.

**Comment by MechanisM** [comment] 2016-10-26 17:24
It works for me.
macOS Sierra(10.12.1)
Chrome 56.0.2901.0 canary (64-bit)

**Comment by m1kola** [comment] 2016-10-27 18:30
I can confirm the same issue on WIndows 7 with 

* Google Chrome 53.0.2785.143 m (64-bit)
* Firefox 49.0.1

Laptop: Acer Aspire V3-772G

But in this case it behaves *a bit* better.

**Comment by jjanssen** [comment] 2017-03-24 13:07
Fixed for now, QA'ed by @HvandenBerg and merged in 87a7a79

Part of my comment within the PR:
> The upgrade to a more recent version would probably more desirable but would also have more impact. Doing that is probably part of a larger discussion on what we are going to do regarding updates. The general concern we are a falling a bit behind on maintenance whereas browsers are moving forward. That would be something for the team discussion.

@m1kola feel free to the reopen if your are still encountering some issues with this.

**Closed by jjanssen** 2017-03-24 13:07 UTC
Labels: component:Frontend, size:Small, sprint:Arnhem2017, type:Bug
