### ISSUE TITLE
Rich text areas swallowing keyboard shortcut events

### ISSUE THREAD

**Issue by ptink** [wagtail/wagtail#2191] opened 2016-02-03 12:36 UTC
Trying to implement a few keyboard shortcuts to compliment the `ctrl+s/ctrl+p` for save/preview already in wagtail. I notice that these keyboard shortcut events don't fire if the cursor is active on the page, whether it's a text field or select box or rich text field. Unsure if this is a browser thing or something within wagtail causing this, but it happens in both firefox and chrome.

**Comment by thibaudcolas** [comment] 2017-02-03 22:14
Hey @ptink, I've tried to reproduce this in Chrome but couldn't (in the latest version of Wagtail). The issue is from a year ago so:

- Are you still experiencing this issue?
- If so, can you let me know in which version of Wagtail, for which shortcut, which keyboard events, and which browser on which OS?

**Comment by ptink** [comment] 2017-02-08 17:54
Hi @thibaudcolas, I'm not actively using wagtail in a project at the moment so I couldn't tell you if it's still happening, the wagtail version was 1.3 from what I can remember.

**Comment by thibaudcolas** [comment] 2017-02-08 22:19
Thanks! I will close this issue for now, if you stumble upon it again with a recent version (or if someone else does) we will reopen.

**Closed by thibaudcolas** 2017-02-08 22:19 UTC
Labels: component:Frontend, component:Rich text, status:Needs info
