### ISSUE TITLE
annotate_score crashes when query string is blank

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#3156] opened 2016-11-14 10:21 UTC
When the query is blank, ``.search()`` returns an empty list instead of an instance of ``SearchResults``. This means that a call to ``.annotate_score()`` will fail with an ``AttributeError``.

https://github.com/torchbox/wagtail/blob/9a57e39cfd233e51851712684e97cd873ddcc06f/wagtail/wagtailsearch/backends/base.py#L235-L236

Example:

```python
# Works
Page.objects.search("hello").annotate_score("_score")

# Breaks
Page.objects.search("").annotate_score("_score")
```

**Comment by lb-** [comment] 2023-10-10 21:51
I think this is fixed, I cannot reproduce with the steps provided.

```sh
>>> from wagtail.models import Page
>>> Page.objects.search("").annotate_score("_score")
<SearchResults []>
>>> Page.objects.search("hello").annotate_score("_score")
<SearchResults []>
>>> Page.objects.search("bread").annotate_score("_score")
<SearchResults [<Page: Breads>, <Page: Bread and Circuses>, <Page: Black bread>, <Page: The Greatest Thing Since Sliced Bread>, <Page: The Great Icelandic Baking Show>, <Page: The Joy of (Baking) Soda>, <Page: Hot Cross Bun>]>
>>> 
```

Did some code digging, it looks like it was fixed in https://github.com/wagtail/wagtail/pull/3523 0cb16f2a01a87c7f4f45e2751fa3c2eb6075255b

**Closed by lb-** 2023-10-10 21:51 UTC
Labels: type:Bug, component:Search
