### ISSUE TITLE
Privacy option radio buttons display horizontally under Django 4.0

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#8190] opened 2022-03-22 11:05 UTC
The radio buttons in the Page Privacy modal are laid out horizontally when running under Django 4.0.3, where previously they were arranged vertically. (I think I've seen similar glitches in other places where radio buttons / checkboxes are used - e.g. m2m relations in the page edit form - although I don't have any examples to hand)

Under Django 3.2.12:
![Screenshot 2022-03-22 at 10 49 00](https://user-images.githubusercontent.com/85097/159466923-2f4e3caf-557e-4819-a5a1-170219b62d40.png)

Under Django 4.0.3:
![Screenshot 2022-03-22 at 10 49 26](https://user-images.githubusercontent.com/85097/159467013-6b45039a-a093-45b6-bb7a-8cd771e5640f.png)

### Steps to Reproduce

1. Set up bakerydemo with Django 3.2
2. Log in to admin and edit a blog page
3. Switch to the Settings tab and click on "Set page privacy"; see options laid out vertically
4. `pip install "Django>=4"` and restart server
5. Refresh page and click on "Set page privacy" again; see options laid out horizontally

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no (just on bakerydemo)

### Technical details

* Python version: 3.8.0
* Django version: 4.0.3
* Wagtail version: stable/2.16.x
* Browser version: Chrome 99 https://www.whatsmybrowser.org/b/PQC9L

**Comment by gasman** [comment] 2022-03-22 23:34
This also shows up on the groups listing on editing a workflow task:

![Screenshot 2022-03-22 at 23 33 04](https://user-images.githubusercontent.com/85097/159593222-63adc480-3e30-4606-b2ac-62ef03cbb268.png)

**Comment by proshee** [comment] 2022-03-24 03:57
hello, I'm working on this project please guide me for things to consider while fixing

**Comment by lb-** [comment] 2022-03-24 10:28
@proshee assuming you have a development environment up and running, the first step is to reproduce this locally.

Once you can reproduce it you should be able to have one browser open with the 'working' version and another with the 'broken' version.

From here, start exploring the CSS used in the browser inspector to see what could be wrong, my guess this is a DOM structure change (e.g. maybe the radio buttons are in `ul` and the used to be in a `ol`) or a classes change.

Other avenues of exploration
* look at what widget / field is in use here and whether that is built in with Django, or something Wagtail uses with a custom widget
* look at the Django 4.0 release notes about any changes that may have caused this issue
* Google 'Django 4.0 radio not showing correctly' and see what comes up

Hope that helps.

**Comment by lb-** [comment] 2022-03-24 20:15
@proshee I do not think adding br elements would be a good solution here. 
As noted in the comment above, once you open the inspector the viewport width changes and it shows correctly. 

This leans me more towards thinking this is a css issue. 

I vaguely recall a change to the code to allow radios / checkboxes to go to one line if space is available. Trying to find the PR but maybe that could be the issue (a false assumption of content widths).

**Comment by proshee** [comment] 2022-03-25 05:26
<img width="1440" alt="Screenshot 2022-03-25 at 10 55 26 AM" src="https://user-images.githubusercontent.com/96814072/160059917-00b5151f-e4b0-4c6e-8624-6b8a8a2e01d1.png">

adding br was the wrong idea, i fixed this by fixing CSS

**Comment by proshee** [comment] 2022-03-25 05:28
<img width="1440" alt="Screenshot 2022-03-25 at 10 57 41 AM" src="https://user-images.githubusercontent.com/96814072/160060126-30a5a742-42c4-41e9-afa0-c8065f7fb448.png">
![Uploading Screenshot 2022-03-25 at 10.57.39 AM.png…]()

**Comment by proshee** [comment] 2022-03-25 05:32
<img width="1440" alt="Screenshot 2022-03-25 at 10 57 39 AM" src="https://user-images.githubusercontent.com/96814072/160060208-a2cc6e5b-48b5-4b34-a5ed-a0b2cea134cc.png"

**Comment by talkshrey** [comment] 2022-03-27 10:45
Is this issue resolved yet? Because I have fixed it too

**Comment by gasman** [comment] 2022-03-27 12:52
No, I haven't seen anyone else submitting a PR for this yet...
I see you've been working on this at #8192, but please note that when you start a new piece of work, you should create a new branch starting from Wagtail's 'main' branch - otherwise, all your previous work gets mixed into a single PR.

**Comment by yash112-lang** [comment] 2022-03-28 04:08
Hey @gasman , I'm interested in solving this issue, can you please assign it to me?

**Comment by zerolab** [comment] 2022-03-28 09:07
@[yash112-lang](https://github.com/yash112-lang) we do not assing issues to anyone outside of the core team. 
It looks like @talkshrey may have fixed this (#8192), so definitely not one to double up on.

See https://github.com/wagtail/wagtail/wiki/New-contributor-FAQ for a few questions around new contributors

**Closed** 2022-05-24 22:31 UTC
Labels: type:Bug, component:Frontend, good first issue
