### ISSUE TITLE
Change of color when attempting autofill in textarea

### ISSUE THREAD

**Issue by nandini584** [wagtail/wagtail#11455] opened 2024-01-14 17:21 UTC
### Issue Summary

Try using the autofill when entering the text in an input field, 
![Screenshot 2024-01-14 224445](https://github.com/wagtail/wagtail/assets/117419442/94a66077-b985-4573-bd94-b45bf19aae42)

### Steps to Reproduce

1. Start a wagtail project and go to ```localhost:8000/admin/pages/```
2. Edit the page title, suppose ```Marketing```, try again and do autofill.
3. You will see the bg as white

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by AmanSal1** [comment] 2024-01-14 18:45
@nandini584 Hey if anyone is not working on this can I give it a shot ?

**Comment by lb-** [comment] 2024-01-15 07:06
Closing as a duplicate of https://github.com/wagtail/wagtail/issues/11309

Feel free to add any extra context there.

**Closed by lb-** 2024-01-15 07:06 UTC
Labels: type:Bug, status:Unconfirmed
