### ISSUE TITLE
Dipping preview spinner

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail#2334] opened 2016-03-10 13:39 UTC
I think the preview spinner rocks up and down by a pixel and / or has a sheared edge on a small section of the circumference. Here's a screen capture, which has been accidentally but conveniently slowed down in some part of the capture / gif conversion process:

![wagtail-spinner](https://cloud.githubusercontent.com/assets/15543/13670971/f93f6740-e6c4-11e5-8a59-f0577cde44f5.gif)

See https://gfycat.com/RevolvingFondCommabutterfly for a full-speed capture.

**Comment by heymonkeyriot** [comment] 2016-03-12 08:48
There's a definite wobble. It's most clear if you have the stylesheet module installed at navigate to `/admin/styleguide/#icons`

**Comment by kapito** [comment] 2017-07-14 11:57
I believe the cause of this is that the loading icon appears to be a character inside a text box, and due to the character not being perfectly centered within the text box it is wobbling as the text box rotates. A possible (hopefully not too difficult) fix could be to replace the text box with an actual image like this:

![image](https://user-images.githubusercontent.com/14837124/28211334-f8ccfc80-6893-11e7-9e8b-9eb9ee67c082.png)

This way there will be no wobble as the image itself can be rotated.

**Comment by BertrandBordage** [comment] 2018-02-15 13:25
No longer relevant, the admin preview has no preview spinner since #3383 was merged.

**Closed by BertrandBordage** 2018-02-15 13:25 UTC
Labels: component:Frontend
