### ISSUE TITLE
RoutablePageMixin classes don't prevent child pages from overriding their routes

### ISSUE THREAD

**Issue by kurtrwall** [wagtail/wagtail#2908] opened 2016-08-11 13:10 UTC
### Preferred behavior

There should be a warning or exception for creating child pages on routable pages that have a route path equal to the child page's path.
### To test:
- create a routable page in admin and publish

``` python
from wagtail.wagtailcore.models import Page
from wagtail.contrib.wagtailroutablepage.models import RoutablePageMixin, route

class MyRoutablePage(RoutablePageMixin, Page):
    ...
    @route(r'^test/$')
    def view_func(self, request):
        ....
```
- create a child page of it with the slug `test` (same as the route path)
  - Note no exception or Warning message
- Visit the URL and observe the new page created, not the path

This is somewhat opinionated, but it seems like a good thing to have. The content editor is _very_ likely to not know about this feature, and can consequently disrupt functionality with creating content.

**Comment by gasman** [comment] 2016-09-05 15:10
I can't reproduce the reported behaviour on latest master - RoutablePageMixin routes always take precedence over child pages, as far as I can see, and this is definitely the preferred behaviour.

I tested this with a fresh Wagtail instance:
```
wagtail start routabletest
cd routabletest
```
Edit `home/models.py` and add:

```python
from wagtail.contrib.wagtailroutablepage.models import RoutablePageMixin, route
from django.http import HttpResponse


class MyRoutablePage(RoutablePageMixin, Page):
    @route(r'^test/$')
    def view_func(self, request):
        return HttpResponse('test!')
```

```
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver 0.0.0.0:8000
```

* Log in to http://localhost:8000/admin/pages/3/add_subpage/ , add 'my routable page'
* enter 'routable' as title/slug, publish
* create Home Page as child
* give it the title/slug 'test', publish
* Visit http://localhost:8000/routable/test/ - this gives the `test!` response, not the child page

We could still add the proposed warning, to inform the editor that their page won't be accessible, but I think this is much lower priority as there's no possibility of an editor accidentally breaking RoutablePageMixin functionality. (It's also consistent with the result of creating pages at other 'reserved' URLs, such as `admin` or `images`.)

**Comment by lb-** [comment] 2022-05-12 20:13
Others have not posted on this issue for a while and the proposed solution would not be ideal so will close this and anyone is free to re-open if they encounter this and are unable to resolve it.

**Closed by lb-** 2022-05-12 20:13 UTC
Labels: type:Enhancement
