### ISSUE TITLE
TableBlock leading to javascript error in admin

### ISSUE THREAD

**Issue by andreaslans** [wagtail/wagtail#7631] opened 2021-10-19 09:08 UTC
### Issue Summary

We just upgraded an old Wagtail instance to `2.13.2`. When reloading the admin we get no visible blocks at all in the body section where a streamfield with all our blocks normally are present.

The error when editing a page in the admin: 
```
index.js:190 Uncaught TypeError: undefined is not a constructor
    at t.value (index.js:190)
```

We can see that register is run when importing the TableBlock from our own TableBlock which overrides the template.
```

from wagtail.contrib.table_block.blocks import TableBlock as WagtailTableBlock

class TableBlock(WagtailTableBlock):
    class Meta:
        template = "common/blocks/table.html"

```

**Comment by gasman** [comment] 2021-11-04 10:30
Closing due to lack of updates - happy to take another look if you can provide details for reproducing this issue.

**Closed by gasman** 2021-11-04 10:30 UTC
Labels: type:Bug, status:Needs Info
