### ISSUE TITLE
Strange issue with create homepage migration

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#3805] opened 2017-08-27 20:49 UTC
For some projects the create homepage migration creates a page without a title in the admin slide out menu.  Editing and simply re-saving the homepage fixes it, however this is a bit strange.

### A summary of the issue

I have a few wagtail projects, in some of them when I provision my dev container the "create homepage" migration ends up creating a homepage without the title "Home" showing in the slide out menu in the Wagtail admin.  If I then edit that page it shows it does have a title, and all I have to do is simply hit publish, it fixes it.

It could have something to do with migration order of other apps? who knows, it's hard do say.  One thing is this project starts with an "a" while other projects that don't do it start with a higher letter in the alphabet after "h".  Could this be it?

It's not a huge issue but very strange indeed.

### Technical details

* Python version: 3.5
* Django version: 1.11.4
* Wagtail version: 1.12
* Browser version: Chrome 60

**Comment by robvdl** [comment] 2017-08-27 20:56
The reason why I thought it could have something to do with migration order and the names of apps, is because I had one project that didn't do it.  I then renamed one app from "cms" to "main" and it affected the "home" migration after I rebuild my dev container.  Rename the app back to "cms" and rebuild my dev container and it's fixed again. Very strange indeed.

**Comment by gasman** [comment] 2017-08-27 21:31
Thanks for the report @robvdl! This sounds like the issue addressed by #3799 (caused by the migration for the new `draft_title` field happening before the homepage is created).

**Comment by gasman** [comment] 2017-08-30 16:02
Fixed in #3799 / #3820

**Closed by gasman** 2017-08-30 16:02 UTC
