### ISSUE TITLE
Reduce size of save/preview buttons on mobile

### ISSUE THREAD

**Issue by resakse** [wagtail/wagtail#2780] opened 2016-06-25 06:19 UTC
hi, first let me say how grateful i am working with wagtail, but when I tested it using mobile devices (oneplus one and nexus 6), got a few problem on js side.
1. Edit bird doesnt working (working good on desktop)
2. Would be good if can that 'save draft and preview button' on below can be minimize so user can have better experience. 

thats all, otherwise I'm super happy with wagtail.
![screenshot_20160625-140406](https://cloud.githubusercontent.com/assets/7651624/16355086/60d08808-3adf-11e6-9ac3-62a987e6bc88.png)

**Comment by gasman** [comment] 2016-08-30 11:26
Edit bird is now fixed (hopefully - couldn't reproduce the problem myself, but I'm on an ancient version of iOS...) in #2938.

**Comment by maartenkling** [comment] 2017-03-22 15:44
https://github.com/wagtail/wagtail/pull/3480

**Comment by gasman** [comment] 2017-03-25 13:34
Fixed in #3480

**Closed by gasman** 2017-03-25 13:34 UTC
Labels: component:Frontend, sprint:Arnhem2017, type:Enhancement
