### ISSUE TITLE
Embedding a URL longer than 200 chars results in DataError

### ISSUE THREAD

**Issue by dmarcelino** [wagtail/wagtail#4292] opened 2018-02-15 20:22 UTC
Hi!

### Issue Summary

Embedding a URL longer than 200 chars results in: `DataError: value too long for type character varying(200)`.

This shouldn't be an issue for most providers but I came across this while writing a provider for [Matomo](http://matomo.org/) (formerly Piwik Analytics - an alternative to Google Analytics). A typical URL looks like this: `https://analytics.example.org/index.php?module=Widgetize&action=iframe&containerId=VisitOverviewWithGraph&widget=1&moduleToWidgetize=CoreHome&actionToWidgetize=renderWidgetContainer&idSite=1&period=day&date=today&disableLink=1&widget=1` (236 chars).

### Steps to Reproduce

1. In a Wagtail project using `StreamField`
2. Add `('embed', EmbedBlock()),` to it
3. Create/edit a page and add an Embed block
4. Add an URL with more than 200 chars (for example: `https://youtu.be/YBpdL9hSac4?module=Widgetize&action=iframe&containerId=VisitOverviewWithGraph&widget=1&moduleToWidgetize=CoreHome&actionToWidgetize=renderWidgetContainer&idSite=1&period=day&date=today&disableLink=1&widget=1`

### Suggestion

From [wagtail/embeds/models.py#L23](https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/models.py#L23) (`url = models.URLField()`) `url` is being created with a default `max_length` of 200. We should be able to safely increase this limit to `max_length=255`. I may still run into issues with Matomo URLs but I can't think of a reason to not allow 255 chars. More would give me more breathing room but that can potentially cause issues with some (older) backends, MySQL < 5.0.3 comes to mind.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.2
* Wagtail version: 1.12.3
* Browser version: Firefox 58

Anyway, let me know what you guys think. Thanks!

**Comment by dmarcelino** [comment] 2018-02-23 16:52
Hi @kaedroho, what do you think of increasing Embed's `url` max_length to 255?

Thanks

**Comment by thibaudcolas** [comment] 2018-03-06 14:14
Hey @dmarcelino, thank you for the detailed issue. This looks like a duplicate of of #1985 so I'll close this and we can discuss there.

**Closed by thibaudcolas** 2018-03-06 14:14 UTC

**Comment by dmarcelino** [comment] 2018-03-06 14:59
Thanks @thibaudcolas, I'll subscribe to that issue.
