### ISSUE TITLE
max_length not displaying character count or applying character limit to RichTextBlock

### ISSUE THREAD

**Issue by MichelleGreensted** [wagtail/wagtail#10640] opened 2023-07-05 15:59 UTC
### Issue Summary

Adding `max_length` to a `RichTextBlock` doesn't display a character count or limit the user from typing additional characters, even though the validator is still run on save. As the limit on typing additional characters functionality exists for a `CharBlock` but not for a `RichTextBlock` this seems like it might be a bug. The displaying character count functionality also exists for a `RichTextField` so again seems like it may be a bug that this doesn't exist for `RichTextBlock`.

<img width="997" alt="Screenshot 2023-07-05 at 14 00 32" src="https://github.com/wagtail/wagtail/assets/71762549/5897d516-c10a-4f60-89e0-3e7028cb5b94">

### Steps to Reproduce

1. Use the bakery demo site as an example
2. Add a `max_value` to the `RichTextBlock` of `paragraph_block` in `blocks.py`
3. Go the wagtail admin for the homepage and try to add more characters than the max length value to the paragraph block, and click publish. See that there is no character count displayed until after you click publish, and that there is no limit on how many characters you can add to the field even though a validator is run upon saving.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by YashTote** [comment] 2023-07-12 10:37
Hey, I am trying to fix this issue. I found the below piece of code in field_block.py that seems to be the definition of the validator. I tested the code and it seems to be working just fine. 
`class RichTextBlock(FieldBlock):
    def __init__(
        self,
        required=True,
        help_text=None,
        editor="default",
        features=None,
        max_length=None,
        validators=(),
        **kwargs,
    ):
        if max_length is not None:
            validators = list(validators) + [
                RichTextMaxLengthValidator(max_length),
            ]
`
Can anyone please suggest me what or where should I look for the origin of the bug?

**Comment by YashTote** [comment] 2023-07-12 17:56
@MichelleGreensted Use max_length instead of max_value.

**Comment by gasman** [comment] 2023-07-12 18:24
@YashTote You're right that `max_value` is a typo here - it should indeed be `max_length`. However, the bug report is still valid: rich text fields are expected to show a character counter whenever `max_length` is specified, as seen on the "promo text" field on the bakerydemo homepage:

![Screenshot 2023-07-12 at 19 19 35](https://github.com/wagtail/wagtail/assets/85097/4106f6d1-3db6-443c-b6ea-a7a04d3d6340)

However, this doesn't happen when adding a `max_length` attribute to RichTextBlock - tested by editing `paragraph_block` in bakerydemo/base/blocks.py to:

    paragraph_block = RichTextBlock(
        icon="pilcrow", template="blocks/paragraph_block.html", max_length=1000
    )

**Comment by YashTote** [comment] 2023-07-13 10:23
Okay, I will try to fix this and create a PR soon.

**Comment by YashTote** [comment] 2023-07-15 14:51
I am unable to locate the source code that is responsible for the rendering of RichTextBlock. Any suggestions?

**Comment by lb-** [comment] 2023-07-15 22:57
I've updated the title/description to use max length (not max value) and removed the unconfirmed label.

**Comment by danthedeckie** [comment] 2023-07-17 12:38
> I am unable to locate the source code that is responsible for the rendering of RichTextBlock. Any suggestions?

I'd start looking from

admin/rich_text/editors/draftail/__init__.py

?

I think most of it is actually rendered by draftail.js

**Comment by thibaudcolas** [comment] 2023-07-20 11:04
This seems like it might be the same issue as #10300. We don’t have those attributes present on the `input` element, so the initialisation of the corresponding editor feature fails.

If so, I suspect this could be fixed here by setting the attribute, hopefully from a value available in `initialState`: https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/telepath/widgets.js#L356.

**Comment by gasman** [comment] 2024-01-02 19:06
Fixed in #11395

**Closed by gasman** 2024-01-02 19:06 UTC
Labels: type:Bug, component:Rich text
