### ISSUE TITLE
Unwanted reset Media library page to first

### ISSUE THREAD

**Issue by andsimakov** [wagtail/wagtail#4216] opened 2018-01-26 09:22 UTC
### Issue Summary

The Media library resets to initial screen some time after choose a collection or switch to the next page.

### Steps to Reproduce

Open Media library with plenty of images to have a pagination or create a collection, put some images there then switch to it.

Possible reason is after going to another page/collection the Search input field at the top of a screen is focused. After transition (e.g. from 11) to next page URL looks like:

https://example.com/4dm1n/images/?p=12

and a bit later after jump:

https://example.com/4dm1n/images/?p=

It does not appear if to click any empty place on the admin page to take the focus off the Search input field.

### Technical details

* Python version: 3.6.2
* Django version: 1.11.7
* Wagtail version: 1.13.1
* Browser version: Chrome

**Comment by lb-** [comment] 2018-01-26 10:01
@andsimakov thank you for submitting this issue, it appears to be a duplicate of #3997 - which has since been resolved. The fix will be in the next release of Wagtail (2.0).

**Closed by lb-** 2018-01-26 10:01 UTC
