### ISSUE TITLE
Wagtail 4.1: AttributeError: 'GenericForeignKey' object has no attribute 'verbose_name'

### ISSUE THREAD

**Issue by yellowmonarch** [wagtail/wagtail#9616] opened 2022-11-05 12:21 UTC
### Issue Summary
An exception `AttributeError: object 'GenericForeignKey' has no attribute 'verbose_name'` occurs when trying to open the object usage report page. I did some experiments, and it turned out that the error only occurs if the object has a tag. Without tags, the page opens as expected.
> I ran `./manage.py reboot_references_index` but that had no effect.

![image](https://user-images.githubusercontent.com/75360541/200119559-0ac7d436-426d-4d84-a7bd-ef0a02c96974.png)

### Steps to Reproduce
1. Create any object (Document in my case)
2. Add a tag to that object
3. Click on Usage button

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

-   Python version: Python 3.11.0 (the same bug occured also in Python 3.9).
-   Django version: 4.1.3.
-   Wagtail version: 4.1.
-   Browser version: Chrome 107.

**Comment by gutogalego** [comment] 2022-11-05 14:58
Hey, can I take this issue? I'll have it fixed by today

**Comment by gutogalego** [comment] 2022-11-05 17:11
Can I try and fix this one? I think I know what's causing it.

**Comment by Scotchester** [comment] 2022-11-05 19:13
No need to ask permission @gutogalego :) Just try to confirm the bug with your own reproduction, then state that you are working on a fix.

**Comment by gasman** [comment] 2022-11-07 17:49
The root of this bug is that when you tag an document (using the default django-taggit model, as documents / images do), it creates a TaggedItem record that links back to the document via a GenericForeignKey. The references index then treats this as a reference to the document. However, GenericForeignKey does not have a verbose_name property, which the Usage page uses to indicate the field where the reference is found.

So, I think there are two aspects that need to be fixed here:

* `describe_source_field` should gracefully handle fields with no `verbose_name` property, probably by falling back on `name`
* TaggedItem records should not really be considered as object references in the first place, since tags are notionally just attaching information to the document, not forming a meaningful link between database objects. As such, the references index should skip them.

**Closed** 2022-11-08 18:01 UTC
Labels: type:Bug
