### ISSUE TITLE
'Image updated' success message doesn't show on mobile devices

### ISSUE THREAD

**Issue by kapito** [wagtail/wagtail#3795] opened 2017-08-25 08:37 UTC
The error persists on both Android and iOS devices, yet works perfectly fine on desktop (just using a smaller viewport). Interestingly it seems to be the only message which doesn't show properly. Every other message works fine -- even the 'image deleted' success message:

![image](https://user-images.githubusercontent.com/14837124/29705885-d01f8fe6-8977-11e7-8978-3f88d890041a.png)

So far tested on Galaxy S8+ and iPhone 6S, the error persists regardless of the browser used.

**Comment by heymonkeyriot** [comment] 2017-11-15 16:36
Trying to replicate and not able to. Admittedly only tested on Samsung S7 but all works as expected. That makes sense since the success message for 'image uploaded' and 'image deleted' use the same class name. Below a screenshot from my phone
![screenshot_20171115-162942](https://user-images.githubusercontent.com/11335309/32847830-f672bfe2-ca22-11e7-97f4-da92c7166227.png)

Is there any more info you can share to try and replicate?

**Comment by thibaudcolas** [comment] 2017-11-20 20:29
I can't reproduce either when trying to change an image's label or file (iOS 11, iPhone 8). Closing for now, we can reopen with more specific info.

**Closed by thibaudcolas** 2017-11-20 20:29 UTC
Labels: component:Frontend, size:Small, type:Bug
