### ISSUE TITLE
Field value in Customized Admin Views for Snippets does not Show properly

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#10765] opened 2023-08-08 02:47 UTC
I am converting ModelAdmin(Wagtail V5.0.2) class to SnippetViewSet(Wagtail V5.1.0).
I have a class, for example,

```py
class A(models.Model):
    name = models.CharField(max_length=255)
    weight = models.IntegerField(default=0)
    is_available = models.Boolean(default=False)

    class Meta:
        ordering = ('weight',)
```

I add the class to wagtail-admin

```py
class AViewSet(SnippetViewSet):
    model = A
    menu_label = 'A'
    list_display = ('name', ‘weight', 'is_avaialble')
```

But weight = 0 and is_available=False do not show properly in the view.

![image](https://github.com/wagtail/wagtail/assets/81170508/c3bc9920-4192-47d1-8bff-f2c0f3c173e9)

In previous Wagtail version, when I use ModelAdmin, 0 weight can be displayed and BooleanField can be displayed with icon (tick/cross)

![image](https://github.com/wagtail/wagtail/assets/81170508/7350e0ca-4e8b-4133-86ee-bb7be326610d)

Wagtail: 5.1.0
python: 3.10
Django: 4.2.4

**Comment by laymonage** [comment] 2023-08-08 08:38
Thanks for the report @aliceni81! I can confirm that the `0` values are not showing. Seems to be caused by the `if` check in the following template:

https://github.com/wagtail/wagtail/blob/db42d56beaa164e5b2c648f951281ebc10a9ddb7/wagtail/admin/templates/wagtailadmin/tables/cell.html#L2

For the `BooleanField` icon display, I don't think that's a built-in feature in ModelAdmin. Did you make any other customisations for displaying the field? Your screenshot shows the column is titled "Is gk filter", but your code refers to the `is_available` field.

**Comment by aliceni81** [comment] 2023-08-08 08:48
@laymonage Thanks for your confirmation. Besides 0, value equals "False" also could not be shown.
Sorry to make you confused, the field in my project is a Boolean Field called "is_gk_filter", but I give an example with "is_available".
I don't many any other customization for BooleanField using ModelAdmin in my project.

**Comment by laymonage** [comment] 2023-08-08 14:12
Thank you, you're right, I was trying with a custom property and not a `BooleanField`. Using a `BooleanField` does show the checkmark icons.

I'll work on a fix for the falsy values (`0`, `False`) issue, which should be in 5.1.1 later.

Not sure if the boolean icons will be in 5.1.1 too as it likely requires a new `Column` subclass, which might count as a new feature rather than a bugfix. In the mean time you can use something like:

```py
from django.contrib.admin.utils import display_for_value
from wagtail.admin.ui.tables import Column


class BooleanColumn(Column):
    """Represents a True/False/None value as a tick/cross/question icon"""

    def get_value(self, instance):
        value = super().get_value(instance)
        return display_for_value(value, lambda x: x, boolean=True)


# Then use it in your viewset's `list_display`, e.g.
class AViewSet(SnippetViewSet):
    model = A
    menu_label = "A"
    list_display = ("name", "weight", BooleanColumn("is_available"))
```

**Comment by aliceni81** [comment] 2023-08-09 01:23
@laymonage I understand. Thanks for your help!

**Closed** 2023-08-10 08:28 UTC
Labels: type:Bug
