### ISSUE TITLE
CSS Variables are repeated in core.css and sidebar.css files

### ISSUE THREAD

**Issue by zodiacfireworks** [wagtail/wagtail#7943] opened 2022-02-09 14:19 UTC
### Issue Summary

CSS variables are repeated in both core.css and sidebar.css files.

Extra info: I have some wagtail sites with customized admin colors, updating them to work with wagtail 2.16 I found that CSS variables for colors are repeated in both core.css and sidebar.css files

### Evidence

1. Start a new project with `wagtail start myproject`
2. Go to admin home
3. Open inspector in your browser and check styles panel

Styles in core.css file
![image](https://user-images.githubusercontent.com/4976355/153218902-965db796-af22-40b1-b12c-d09038120a38.png)

Styles in sidebar.css file
![image](https://user-images.githubusercontent.com/4976355/153218755-275a64d2-162b-44e7-986f-211937f7b89b.png)

### Technical details

* Python version: Python 3.10.1
* Django version: Django 3.2.15
* Wagtail version: Wagtail 2.16
* Browser version: Chrome 98

**Comment by lb-** [comment] 2022-02-10 20:05
@gasman that may be a fix for now but I am concerned there is a bigger problem here, it looks like the compiled sidebar.css contains a duplicate of a large portion of the exact same styles in core.css

See https://github.com/wagtail/wagtail/blob/main/client/scss/sidebar.scss

I think a longer term fix may need a bit of a rethink of how we are doing this. On or our goal is to make the sidebar styles and code something that can be used outside of Wagtail  (as per the file's comments) we have created a bit of complexity in when trying to use the sidebar in Wagtail (which is the more likely case).

Potential way forward
1. Re-order the admin_base for the fix in 2.16.1 - we still get heaps of duplicated css but it will be before we import any hooks provided css.
2. For 2.17 (main branch - next release) - get rid of sidebar.scss as an entry point and instead import the sidebar components into core so they are in the main bundle and find a different way to provide the sidebar styles standalone if that is still required.
3. Future - we could possibly remove the main_nav template tag once we drop support for the legacy sidebar and clean this up further.

Note: This is not a huge problem but probably just a side effect of us trying to do a few things at once; build a separate entirely new sidebar alongside supporting the existing one and also try provide a way to use the sidebar component/styles in isolation outside of Wagtail.

**Closed** 2022-04-08 15:51 UTC
Labels: type:Bug
