### ISSUE TITLE
ambiguous rendering on pages section on  firefox (windows)

### ISSUE THREAD

**Issue by salty-ivy** [wagtail/wagtail#9853] opened 2023-01-06 09:23 UTC
### Issue Summary

In the pages  section on firefox browser (windows) i encountered an ambiguous rendering when scrolled down to the bottom 
once it hits the bottom and if we scroll further it keeps on scrolling and keep on  generating an extra page grey in color,

expectedly it should stop once it hits the bottom 
i have confirmed it only happens at pages section and  further into it like editing

focus: at the bottom of the page

![image](https://user-images.githubusercontent.com/74553951/210970763-b8a4bab7-8989-4eb8-94e4-f017c2aae188.png)
![image](https://user-images.githubusercontent.com/74553951/210970943-a25550ff-f802-4694-b220-bdb183186d11.png)
![image](https://user-images.githubusercontent.com/74553951/210971152-9d95778e-bc1e-4b19-adc5-7e2a831a1a28.png)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. setup a basic project model 
3. go to the pages tab from the side panel / on the edit  page / form page for adding your new page
4. scroll to the bottom of the page, and keep scrolling after it hits the bottom

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Python version: 3.10.4
-   Django version: 4.1
-   Wagtail version: 4.0-4.0.1
-   Browser version: Firefox 108, https://www.whatsmybrowser.org/b/R69KU

**Comment by lb-** [comment] 2023-01-06 09:47
Looks like a duplicate of https://github.com/wagtail/wagtail/issues/8664

**Closed by lb-** 2023-01-06 09:47 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by salty-ivy** [comment] 2023-01-06 09:49
Alright 👍
