### ISSUE TITLE
Issue with column widths in document chooser when there are long filenames

### ISSUE THREAD

**Issue by davidjamesharris** [wagtail/wagtail#12357] opened 2024-09-25 15:14 UTC
### Issue Summary

When there are long filenames (without spaces) for documents, the column widths of the table in the document chooser are stretched (especially when the browser width is narrow) so it is difficult to read the document title.

### Steps to Reproduce

1. Upload a document with a long filename (with no spaces)
2. Edit a page with a document chooser
3. View the modal in a narrow browser window

See attached screengrab

![image](https://github.com/user-attachments/assets/8c24ccbe-5170-4aaa-a082-9f27e4356741)

### Technical details

-   Python version: unknown, I'm just raising this from an editorial perspective
-   Django version: unknown, I'm just raising this from an editorial perspective
-   Wagtail version: 6.1.3
-   Browser version: Chrome 128

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment] 2024-09-25 15:27
Thanks @davidjamesharris! Confirmed on current main branch - it's mitigated somewhat by the fix to the excessive right margin (which was caused by the sidebar styles from the main page leaking into the chooser) but still exists:

![Screenshot 2024-09-25 at 16 23 27](https://github.com/user-attachments/assets/d8a42531-a0b0-4f75-9b1c-45eb036dbf31)

**Comment by Sumitsh28** [comment] 2024-09-26 13:46
@davidjamesharris Can I work on this issue?

**Comment by gasman** [comment] 2024-09-26 18:07
@Sumitsh28 Thanks for your interest! Yes, anyone is welcome to work on any issue.

**Comment by aminechm** [comment] 2024-09-26 18:14
I will give this a go!

**Comment by Sambodhi-Roy** [comment] 2024-09-30 16:24
I will give it a try!!

**Comment by SayanDutta651** [comment] 2024-10-05 05:48
I will also trying to give a solution

**Comment by TejasSaraf** [comment] 2024-10-10 04:45
I want to work on this issue please assign me this issue.

**Comment by shauryapanchal** [comment] 2024-10-14 20:34
@davidjamesharris is this issue still open?

**Comment by gasman** [comment] 2024-10-14 20:50
@shauryapanchal Please see #12390 - a fix has been submitted already, but needs more work. You're welcome to pick this up if you're interested.

**Comment by shauryapanchal** [comment] 2024-10-15 04:35
@gasman understood.. i'll try to come up with a solution.. thanks for the update!

**Comment by frankyiu** [comment] 2024-10-20 04:36
@shauryapanchal Would you mind i pick this up real quick

**Closed** 2024-10-20 12:48 UTC
Labels: type:Bug, component:Frontend, good first issue
