### ISSUE TITLE
image.get_rendition(filter) returns incorrect rendition

### ISSUE THREAD

**Issue by funkhaus-phil** [wagtail/wagtail#12133] opened 2024-07-18 09:17 UTC
### Issue Summary

Uploading different Images with long and common filenames until basically the end of the filename is problematic when calling obj.get_rendition(filter). I expect to find the original image rendition but instead get the rendition of the image with the shortest common name.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. create a superuser
3. start the server
4. log into your backend
5. prepare some different images with filenames like that:
  093211_Kutter_Santa_Maria_Warnemunde.jpg
  093211_Kutter_Santa_Maria_Warnemunde_DCI5332.jpg
  093211_Kutter_Santa_Maria_Warnemunde_DCI5335.jpg
6. navigate to images in the backend and upload those images
7. come back to images to realise all your images use the same thumbnail, while pointing to the correct image on the detail page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
When giving the backend into client hands we can't make sure they are following special conventions to avoid problems. Also clients like to upload folders full of images at once without inspecting all filenames.
The Rendition should be the correct one for every image.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no
We also have a storage connected to the backend but i expect the problem inside of the get_rendition function from AbstractImage and expect the same behaviour on a fresh installation

### Technical details

-   Python version: 3.8.*
-   Django version: 3.1.*
-   Wagtail version: 2.15.6
-   Browser version: [https://www.whatsmybrowser.org/b/JPN6N](https://www.whatsmybrowser.org/b/JPN6N)

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by shubhammukati** [comment] 2024-07-19 06:55
@funkhaus-phil  please assign this to me....

**Comment by shubhammukati** [comment] 2024-07-19 07:17
@funkhaus-phil    I've started working on this issue and confirmed that it is working as expected. I have attached some screenshots for your reference. I uploaded three images with different filenames as per your instructions. When I checked the admin panel and the media directory, the image filenames were correct and as expected. It seems this is not a bug after all. Please review the attached screenshots.

![test1](https://github.com/user-attachments/assets/b738693d-2bfe-44f9-9fea-78977dfa5fbf)
![test2](https://github.com/user-attachments/assets/1d1d7306-cc0a-44e8-8fab-9b9ff4812397)

**Comment by funkhaus-phil** [comment] 2024-07-19 10:09
@shubhammukati Thank you for your time on this.
It looks like you are using a newer installation of Wagtail i will have another look into this next week. Your verification gives me hope that it might already been fixed in newer Versions.
More when i got the time to look further into the issue.

**Comment by shubhammukati** [comment] 2024-07-19 12:33
> @shubhammukati Thank you for your time on this. It looks like you are using a newer installation of Wagtail i will have another look into this next week. Your verification gives me hope that it might already been fixed in newer Versions. More when i got the time to look further into the issue.

@funkhaus-phil You're welcome!! Yes, it seems like the issue might be resolved in newer versions of Wagtail. I'm glad my verification was helpful. If there's anything specific you'd like to discuss further, just let me know. Have a great week!

**Comment by funkhaus-phil** [comment] 2024-07-29 11:14
We actually had another client come to us with the exact same problem today. 

In this project we are currently on wagtail 4.2.2
We also use a Minio Storage on both projects to store the images.

The Image filenames are coincidentially of common length:
093211_Kutter_Santa_Maria_Warnemunde_DCI5332.jpg
2406_@saskiaspethmann_valinor_greece_lowres-09091.jpg (the link comes automatically from the @ and does not work)

In case that it matters, we also use a serializer inside our API to have different rendition sizes ready to use and it looks like this and also return the incorrect download urls to the renditions of the same image over and over again:

```
class CustomImageSerializer(serializers.ModelSerializer):
	download_url_big = serializers.SerializerMethodField()
	download_url_medium = serializers.SerializerMethodField()
	download_url_small = serializers.SerializerMethodField()
	alt = serializers.SerializerMethodField()
	width = serializers.SerializerMethodField()
	height = serializers.SerializerMethodField()
	focal = serializers.SerializerMethodField()

	class Meta:
		model = WagtailImage
		fields = ['title','id','alt','download_url_big','download_url_medium','download_url_small','width','height','focal']

	def get_download_url_big(self, obj=None):
		if obj:
			try:
				if '.gif' in obj.file.name:
					return obj.file.url
				return obj.get_rendition('min-2100x2100|jpegquality-75').url
			except Exception as e:
				pass
		return None

	def get_download_url_medium(self, obj=None):
		if obj:
			try:
				if '.gif' in obj.file.name:
					return obj.file.url
				return obj.get_rendition('min-1450x1450|jpegquality-75').url
			except Exception as e:
				pass
		return None

	def get_download_url_small(self, obj=None):
		if obj:
			try:
				if '.gif' in obj.file.name:
					return obj.file.url
				return obj.get_rendition('min-1000x1000|jpegquality-75').url
			except Exception as e:
				pass
		return None

	def get_alt(self, obj=None):
		if obj:
			try:
				return obj.get_rendition('original|jpegquality-75').alt
			except Exception as e:
				pass
		return None

	def get_width(self, obj=None):
		if obj:
			try:
				return obj.get_rendition('original|jpegquality-75').width
			except Exception as e:
				pass
		return None

	def get_height(self, obj=None):
		if obj:
			try:
				return obj.get_rendition('original|jpegquality-75').height
			except Exception as e:
				pass
		return None

	def get_focal(self, obj=None):
		if obj:
			try:
				focal_point = obj.get_focal_point()
				if focal_point:
					fp_x, fp_y = focal_point.centroid
					fp_x_percentage = fp_x / obj.width * 100
					fp_y_percentage = fp_y / obj.height * 100
					return {
						"x": fp_x_percentage,
						"y": fp_y_percentage
					}
			except Exception as e:
				pass
		return None
```

sadly i can't provide a testenvironment to reproduce the issue, yet.
does anybody have an idea what could cause the renditions to be read incorrect? 

![WhatsApp Image 2024-07-29 at 12 38 30](https://github.com/user-attachments/assets/b2384d65-69e5-4d0b-8436-56921dbcc0a6)

**Comment by thibaudcolas** [comment] 2024-10-25 16:31
Perhaps this is specific to how the files are stored? Doesn’t Windows have trouble with long file names / paths? Note we stopped supporting Wagtail 2.15 / 4.2 since about a year ago, so I’m tempted to close this unless someone else can reproduce on the latest release, or the v5.2 LTS release.

**Closed** 2024-10-28 10:42 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed
