### ISSUE TITLE
Upgrading to 2.11 has exception when running migrations

### ISSUE THREAD

**Issue by picturedots** [wagtail/wagtail#6514] opened 2020-11-03 19:04 UTC
## Issue Summary

Received following error when running `manage.py migrate` after upgrading from 2.10.2 to 2.11:

```
Running migrations:
  Applying wagtailcore.0056_page_locale_fields_populate... OK
  Applying wagtailcore.0057_page_locale_fields_notnull... OK
  Applying wagtailcore.0058_page_alias_of...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "alias_of_id" of relation "wagtailcore_page" already exists


```

### Steps to Reproduce

1) Upgrade from 2.10.2 to 2.11
2) Run `manage.py migrate`

I received the exception as shown above.  However, if I do `manage.py showmigrations` Django indicates that the migrations were done...

```
 [X] 0056_page_locale_fields_populate
 [X] 0057_page_locale_fields_notnull
 [X] 0058_page_alias_of
 [X] 0059_apply_collection_ordering
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  no

### Technical details

* Python version: Python 3.9.0  (note, I was running python 3.9 with 2.10.2)
* Django version: Django==3.1.3
* psycopg2-binary==2.8.6
* Wagtail: 2.11
* postgres: 10 -- running in a docker container

**Comment by gasman** [comment] 2020-11-05 14:08
Hi @picturedots - thanks for the report.

Unfortunately I'm not able to replicate this issue as described. The fact that `manage.py migrate` is attempting to apply migration 58, but `manage.py showmigrations` reports that it's already applied, would suggest that there's a low-level inconsistency at the Django level. Can you confirm that running `manage.py migrate` again (with the same settings / environment variables as when you ran `showmigrations`) does indeed still fail when attempting to apply migration 58?

The only thing I can think of that _might_ account for this is that your project is [using multiple databases](https://docs.djangoproject.com/en/3.1/topics/db/multi-db/) - is this the case?

In the absence of any further information I'll close this as unreproducible for now, but happy to reopen if you're able to find a root cause that triggers this.

**Closed by gasman** 2020-11-05 14:08 UTC
Labels: type:Bug
