### ISSUE TITLE
Rich text field overlaps with sidebar

### ISSUE THREAD

**Issue by ghost** [wagtail/wagtail#6556] opened 2020-11-17 10:18 UTC
Whenever more than 113 characters are typed **without spaces** in RichTextField, the 'feature block' expands. And if the length of the sentence exceeds 199 the 'feature block' expands over the left navigation bar. 
NOTE: _this happens only when the sentence is typed WITHOUT SPACES after every word_(for a blog site "Scriptio continua" which requires typing without spaces between the words)

### Steps to Reproduce

1. Add a RichTextField on the homepage
2. type more than 113 characters without spaces (eg: thisisanexampleinputtype)

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) yes

watch : https://recordit.co/w4RMht0eul

**Comment by thibaudcolas** [comment] 2022-08-16 12:14
I’m unable to reproduce this in Wagtail 4 (tested with Firefox & Chrome). I’m not clear what would have changed in this release, so I would assume this has been fixed a few releases ago and we forgot this issue. Closing now – if anyone still experiences this please let us know.

**Closed by thibaudcolas** 2022-08-16 12:14 UTC
Labels: type:Bug, component:Rich text
