### ISSUE TITLE
Test fail if loading fixtures and models have search fields including related fields

### ISSUE THREAD

**Issue by haplo** [wagtail/wagtail#6399] opened 2020-09-23 15:22 UTC
### Issue Summary

I was upgrading Wagtail 2.9 to 2.10.1, and some tests broke because `wagtail.search` tries to index a related field before that data has been loaded from fixtures. I believe this is a regression because the same test passes with the same fixtures and models in Wagtail 2.9.

### Steps to Reproduce

Have a model with a `ForeignKey` field to another model in another app, and add that FK field to `search_fields`, e.g.:

```
class MyModel(models.Model):
    related_model = models.ForeignKey(OtherModel, on_delete=models.PROTECT)

    search_fields = [
        index.RelatedFields('related_model', [
            index.SearchField('title', boost=2),
        ]),
    ]
```

Then have a test that loads two separate fixtures: one with a MyModel instance and another with a `OtherModel` instance. The test should pass, but for me it fails because `index.insert_or_update_object(instance)` is called before the related `OtherModel` is loaded:

```
======================================================================
ERROR: setUpClass (app.tests.tests.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'related_model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/test/testcases.py", line 1131, in setUpClass
    call_command('loaddata', *cls.fixtures, **{'verbosity': 0, 'database': db_name})
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 788, in save_base
    post_save.send(
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/search/signal_handlers.py", line 13, in post_save_signal_handler
    index.insert_or_update_object(instance)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/search/index.py", line 155, in insert_or_update_object
    backend.add(indexed_instance)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 693, in add
    self.get_index_for_object(obj).add_item(obj)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 212, in add_item
    self.add_items(obj._meta.model, [obj])
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 303, in add_items
    update_method(content_type_pk, indexers)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 225, in add_items_upsert
    value = compiler.prepare_value(IndexEntry._meta.get_field('title'), indexer.title)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 111, in title
    for current_field, boost, value in self.prepare_field(self.obj, field):
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/contrib/postgres_search/backend.py", line 63, in prepare_field
    sub_obj = field.get_value(obj)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/wagtail/search/index.py", line 299, in get_value
    return getattr(obj, self.field_name)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = self.get_object(instance)
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 145, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/home/user/code/virtualenvs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
related.models.RelatedModel.DoesNotExist: Problem installing fixture '/home/user/code/project/app/fixtures/app_testdata.json': RelatedModel matching query does not exist.
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.2
* Django version: 2.2.13
* Wagtail version: 2.10.1

**Comment by haplo** [comment] 2020-09-23 15:23
If someone knowledgeable with the search code can point me towards the right approach to fix this I would be happy to develop and submit a patch.

**Comment by gasman** [comment] 2020-09-23 15:26
Hi @haplo - please can you try replicating this on a fresh Wagtail project, to confirm that this isn't caused by something specific to your project?

**Comment by haplo** [comment] 2020-09-23 15:43
> Hi @haplo - please can you try replicating this on a fresh Wagtail project, to confirm that this isn't caused by something specific to your project?

I will try, although I fear this bug can depend on the internal ordering of installed apps, or the order in which fixtures are defined.

**Comment by gasman** [comment] 2020-09-23 18:01
Indeed, and that's exactly why I'm asking :-) You're in a better position than us to find a reproducible test case, as you have a failing codebase to compare against, and we don't.

**Comment by gasman** [comment] 2020-10-19 08:42
Closing as unconfirmed for now - happy to reopen if you're able to find a reproducible test case.

**Closed by gasman** 2020-10-19 08:42 UTC
Labels: status:Needs Info, type:Bug
