### ISSUE TITLE
Superuser check is out of place when checking permissions on Snippets Views and does not respect ModelPermissionPolicy

### ISSUE THREAD

**Issue by LCMJ21** [wagtail/wagtail#11905] opened 2024-04-29 17:36 UTC
### Issue Summary

On the `SnippetViewSet` the `EditView` and `CreateView` use the `CreateEditViewOptionalFeaturesMixin`. This mixin redefines the `user_has_permission` defined in the `PermissionCheckedMixin`, and returns true if the user is a superuser:
```
def user_has_permission(self, permission):
    user = self.request.user
    if user.is_superuser:
        return True
    ...
```

This means this views will never go through the `permission_policy` set by that given view. Because I am trying to block a snippet from being editable, I changed my `permission_policy` to never give the “change” permission to any user. However, the check on the `CreateEditViewOptionalFeaturesMixin` is made before it ever arrives at the `permission_policy`, meaning any superuser is always given permission to edit the snippet.

I suggest removing this condition, and allowing the `permission_policy` to make this verification. In a normal case, a superuser will be given access to edit by the `permission_policy`. In a special case like mine, the `permission_policy` will block any edit attempt.

### Steps to Reproduce

1. Add a `wagtail_hooks.py` and register a `SnippetViewSet`
2. Create a custom `ModelPermissionPolicy` and make `user_has_permission` return false if `action==change`
3. Redefined the `permission_policy` property in your `SnippetViewSet` to use your `ModelPermissionPolicy`

### Technical details

-   Django version: 5.0.3
-   Wagtail version: 6.0.1
-   Browser version: You can use Chrome 123 to find this out.

**Comment by laymonage** [comment] 2024-04-30 02:08
Thanks for the report, this seems to be a duplicate of #11707.

**Closed by laymonage** 2024-04-30 02:08 UTC
Labels: type:Bug, status:Unconfirmed
