### ISSUE TITLE
Error messages on Pattern library (Storybook) stories

### ISSUE THREAD

**Issue by albinazs** [wagtail/wagtail#9306] opened 2022-10-11 10:14 UTC
### Issue Summary

There are errors on all Storybook stories:
- Error message on the story itself: `Error occurred while trying to proxy: localhost:6006/pattern-library/api/v1/sprite`
- Error message in console: `GET http://localhost:6006/pattern-library/api/v1/sprite 504 (Gateway Timeout)`
-
![image](https://user-images.githubusercontent.com/51043550/195063154-53e3f465-ff03-4209-8b04-679a538b3123.png)

On stories in Sidebar and Colors chapters you need to scroll down to see the message (+it is still in the console).

![image](https://user-images.githubusercontent.com/51043550/195063258-45daa047-04e7-42bf-9823-06d49b642aa2.png)

On stories in Icons, Breadcrumbs, Header and Tabs chapters there is an additional to the above error: `POST http://localhost:6006/pattern-library/api/v1/render-pattern 504 (Gateway Timeout)`

![image](https://user-images.githubusercontent.com/51043550/195062859-2f383339-327b-43b7-a36a-2d4c37132169.png)

### Steps to Reproduce

1. Runs Storybook with `npm run storybook`
2. Navigate to any story listed above

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Wagtail version: Latest main branch.
-   Browser version: Chrome 105

**Comment by lb-** [comment] 2022-10-11 10:35
Thanks, I think this is a duplicate of these two known issues, one which already has a PR up with a fix.

* https://github.com/wagtail/wagtail/issues/8031
* https://github.com/wagtail/wagtail/issues/9092 - fix PR https://github.com/wagtail/wagtail/pull/9097

The broken breadcrumbs one may be new though, but it could be that once the Storybook fails once it will show the error for other pages.

Could you maybe re-write this issue to be focused on the breadcrumbs issues only, but be sure also check that you have the local dev server running correctly.

https://docs.wagtail.org/en/latest/contributing/developing.html#using-the-pattern-library

Note that you need to run the local sever against the test database/app.

**Comment by lb-** [comment] 2022-10-12 20:36
Closing this as unable to confirm - Storybook is working fine for me locally aside from the two known issues above.

**Comment by albinazs** [comment] 2022-10-13 08:11
As briefly discussed with @thibaudcolas, this issue might be connected to the icons failing to load. So the different components will all work except they’d be missing their icon.

**Comment by lb-** [comment] 2022-10-13 08:12
Thanks. I'll re-open this for now.

**Comment by gasman** [comment] 2024-10-23 14:37
Closing due to lack of updates and independent confirmation - if this is still an issue, please provide more details and I'll be happy to reopen.

**Closed by gasman** 2024-10-23 14:37 UTC
Labels: type:Bug, status:Needs Info, component:Design system
