### ISSUE TITLE
Expose link dialog in a StreamBlock (LinkBlock)

### ISSUE THREAD

**Issue by danni** [wagtail/wagtail#3141] opened 2016-11-06 23:19 UTC
There are times when you want a link that can either be internal or external like the rich text link dialog, but embedded in a stream. Currently you have `PageChooserBlock` and `URLBlock` but nothing that combines the two.

**Comment by timheap** [comment] 2016-11-07 04:55
I agree, this would be very useful. I started working on PR #1645 that would make this a lot easier, by making the link chooser interface extensible and more generic. In that PR, the link chooser has tabs for pages, plain URLs, and emails like the current rich text editor, but also images and documents. Other apps could then register link choosers to appear in this modal. The modal would return a dict like `{"type": "page", "pk": 3}` or `{"type": "url", "href": "http://example.com/"}`, which could be passed to a function to generate a link.

Initially this was for the rich text editor, which is where that modal originates. Using it as a standalone widget would not be a huge amount of extra work once this PR was finished. 

Sadly the PR stalled because of a lack of time, and because I was unsure how to continue. The document chooser is used in the rich text editor and the DocumentChooserWidget, for example. I never got around to coming up with an interface that worked across both environments in a way that was nice, and allowed future extensions to tie in easily.

If you are interested in collaborating on #1645 to finish it up, adding a LinkChooserWidget would then be simple.

**Comment by rafaponieman** [comment] 2016-12-18 22:53
+1 for this, it seems like its already implemented on RichTextField

**Comment by timorieber** [comment] 2017-03-08 18:27
Also requested in http://stackoverflow.com/questions/42673465/wagtail-extending-pagechooserblock-to-support-external-urls.

**Comment by chrisbarry** [comment] 2017-10-31 22:23
I just used a streamblock to combine link & page (and could add document too) unless I'm missing something in the templating stage, doesn't this mean I can just build this feature like that? I admit having a single link dialog would be more robust, and should come out of the box.

**Comment by jimmywarting** [comment] 2020-02-14 11:12
bump, status?

**Comment by thibaudcolas** [comment] 2022-04-27 21:00
I believe this is a duplicate of #381? There is StreamField discussion on there, and even if this existed outside StreamField, I presume it would be simple to use within a block as well. Will close on that basis – if I got this wrong please let me know and we’ll reopen.

**Closed by thibaudcolas** 2022-04-27 21:00 UTC
Labels: type:Enhancement
