### ISSUE TITLE
Attribute Error when accessing admin site.

### ISSUE THREAD

**Issue by mvellasco** [wagtail/wagtail#10112] opened 2023-02-18 02:06 UTC
### Issue Summary

Using with an existing project, wagtail fails to render the admin login page(regular pages work, just the admin interface doesn't).

### Steps to Reproduce

1. Install wagtail into an existing project.
2. Try to access the admin url at `/cms/`(per tutorial on documentation, can be any url path for the admin)
3. The page will fail to render with a 500 error.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

```
AttributeError at /cms/login/
'NoneType' object has no attribute 'COOKIES'
Request Method:	GET
Request URL:	http://localhost:8002/cms/login/?next=/cms/
Django Version:	3.2.17
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'COOKIES'
Exception Location:	/usr/local/lib/python3.8/site-packages/wagtail/admin/templatetags/wagtailadmin_tags.py, line 909, in sidebar_collapsed
Python Executable:	/usr/local/bin/python
Python Version:	3.8.8
Python Path:	
['/app',
 '/app',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/usr/local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/site-packages/jaeger_client/thrift_gen']
Server time:	Fri, 17 Feb 2023 22:58:13 -0300
Error during template rendering
In template /usr/local/lib/python3.8/site-packages/wagtail/admin/templates/wagtailadmin/skeleton.html, error at line 17
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: 3.8.
-   Django version: 3.2.17.
-   Wagtail version: 4.2.
-   Browser version: Chrome 109.

**Comment by gasman** [comment] 2023-02-18 18:43
Hi @mvellasco - thanks for the report.

Please could you try reproducing this on a fresh project created with `django-admin.py startproject`? Wagtail is in use on thousands of sites, so it's highly unlikely that there's a bug of this sort that affects _all_ existing Django projects - more likely this is caused by some customisation in your project, such as a third-party middleware package. Without knowing the exact setup of the project where this occurs, we can't really investigate further.

**Comment by gasman** [comment] 2023-03-15 16:21
Closing for now, as there's not enough information here to replicate the issue independently.

**Closed by gasman** 2023-03-15 16:21 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed
