### ISSUE TITLE
Stimulus: Panel and Block should accept data attributes

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#10582] opened 2023-06-20 23:15 UTC
### Is your proposal related to a problem?

It is hard to implement general reusable Stimulus controllers without having the ability to easily pass data attributes into various FieldPanels and Blocks.

### Describe the solution you'd like

Ability to pass attributes in the constructor as static values or callable.

**Comment by lb-** [comment] 2023-06-21 01:40
Closing as duplicate of https://github.com/wagtail/wagtail/issues/10133

@pySilver feel free to add comments to that issue - I think it covers things. 

There is also a WIP PR up https://github.com/wagtail/wagtail/pull/10323

**Closed by lb-** 2023-06-21 01:40 UTC
Labels: type:Enhancement
