### ISSUE TITLE
Pages api call by "api/pages/find?html_path=some_path" keeps idle connection open on postgresql database. Returns too many connection error after a while.

### ISSUE THREAD

**Issue by xeroticikot** [wagtail/wagtail#12112] opened 2024-07-07 13:39 UTC
Pages api call to "api/pages/find?html_path=some_path" creates idle connections in postgresql database. When there's max connection limit reaches the postgresql server returns too many connection error.

All tech versions are latest used for the test.

**Comment by RealOrangeOne** [comment] 2024-07-07 17:07
There's no manual connection handling done in this view, so it's deferred entirely to Django. Do you have `CONN_MAX_AGE` set on your database? Is this the only view which causes the issue, or do other views do it too (either from the same pages viewset, other API requests, or other Wagtail requests).

**Comment by xeroticikot** [comment] 2024-07-08 08:42
These are the processes/queries list from the pgadmin panel - 

![postgresql-idle-connections](https://github.com/wagtail/wagtail/assets/11814742/df85745c-ca40-40fd-bfb6-ffd63990d455)

And below two are the queries that are getting idle - 

`SELECT "wagtailredirects_redirect"."id", "wagtailredirects_redirect"."old_path", "wagtailredirects_redirect"."site_id", "wagtailredirects_redirect"."is_permanent", "wagtailredirects_redirect"."redirect_page_id", "wagtailredirects_redirect"."redirect_page_route_path", "wagtailredirects_redirect"."redirect_link", "wagtailredirects_redirect"."automatically_created", "wagtailredirects_redirect"."created_at" FROM "wagtailredirects_redirect" WHERE (("wagtailredirects_redirect"."site_id" = 7 OR "wagtailredirects_redirect"."site_id" IS NULL) AND "wagtailredirects_redirect"."old_path" = '/api/reusable/19') LIMIT 21`

`SELECT "wagtailimages_image"."id", "wagtailimages_image"."collection_id", "wagtailimages_image"."title", "wagtailimages_image"."file", "wagtailimages_image"."width", "wagtailimages_image"."height", "wagtailimages_image"."created_at", "wagtailimages_image"."uploaded_by_user_id", "wagtailimages_image"."focal_point_x", "wagtailimages_image"."focal_point_y", "wagtailimages_image"."focal_point_width", "wagtailimages_image"."focal_point_height", "wagtailimages_image"."file_size", "wagtailimages_image"."file_hash" FROM "wagtailimages_image" WHERE "wagtailimages_image"."id" = 38 LIMIT 21`

**Comment by RealOrangeOne** [comment] 2024-07-08 08:56
Are you able to replicate this using on [bakerydemo](https://github.com/wagtail/bakerydemo), using its built-in postgres? I'm wondering whether there's something strange in your infrastructure or code causing this.

If you restart the Django process, do the connections disappear? If not, then it might be something in between, or a misconfiguration. Or, the connection limit being enforced incorrectly.

**Comment by xeroticikot** [comment] 2024-07-08 09:08
I'm using built-in postgres as well on ubuntu server. Not a single config was changed. For the page api call there's no custom code. But for the custom image rendition rendering, I've created a custom function. Below is my image render function -

in views.py -
```
from django.shortcuts import render, redirect, get_object_or_404
from wagtail.images.models import Image

def display_image(request, image_id, dimension, format):
    img = get_object_or_404(Image, id=image_id)
    format = f"format-{format}"
    rend = img.get_rendition(f"{dimension}|{format}").url
    return redirect(rend)
```
in urls.py - 

```
from wagtail.images.views.serve import ServeView


re_path(r'^images/([^/]*)/(\d*)/([^/]*)/[^/]*$', ServeView.as_view(), name='wagtailimages_serve'),
    path('image/<int:image_id>/<str:dimension>/<str:format>/', themes_api_views.display_image,
         name="display_image"),
```

**Comment by xeroticikot** [comment] 2024-07-08 09:11
Btw, I'm not using bakerydemo. I've worked on the basic wagtail installation & customized as required.

**Comment by RealOrangeOne** [comment] 2024-07-08 09:23
Does your `display_image` method leave connections open as you say? What do your database settings look like?

**Comment by xeroticikot** [comment] 2024-07-08 09:31
This is the database settings from the production.py file -

```
DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE', default='django.db.backends.mysql', cast=str),
        'CONN_MAX_AGE': 0,
        'NAME': config('DATABASE_NAME', default='devdb', cast=str),
        'USER': config('DATABASE_USER', default='root', cast=str),
        'PASSWORD': config('DATABASE_PASSWORD', default='', cast=str),
        'HOST': config('DATABASE_HOST', default='127.0.0.1', cast=str),
        'PORT': config('DATABASE_PORT', default=3306, cast=int),
        # 'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
    },
}
```

**Comment by RealOrangeOne** [comment] 2024-07-08 09:34
Interesting. `CONN_MAX_AGE` being set to 0 should be closing the connections. I'll see if I can reproduce and work out what's going on

**Comment by xeroticikot** [comment] 2024-07-08 09:43
Thank you so much for you precious time, really appreciate your concern. I have live test sites on test servers if you want to see for yourself. I have rather busy sites which consumes the default 100 connection limit in less than an hour, so I have to restart the database. Tried different workarounds like creating a middleware which closes the idle postgres connections on every requests, but due to some errors I've got to leave as it is and restart the database from server cli.

**Comment by xeroticikot** [comment] 2024-07-08 09:46
Btw, I'm using granian library for running the server. Previously I was using gunicorn. Can this be any problem?

**Comment by RealOrangeOne** [comment] 2024-07-08 09:59
There might be some issues with Granian not closing connections properly. Are you using version [1.4.1+](https://github.com/emmett-framework/granian/releases/tag/v1.4.1)? That fixed an issue which sounds very similar to yours: https://github.com/emmett-framework/granian/issues/306.

It's likely that's the cause of the issue, and that it sits in the Django / Postgres layer, as opposed to something which is Wagtail specific.

**Comment by xeroticikot** [comment] 2024-07-08 10:41
I'm using granian version 1.4.4 and planning to upgrade to v1.5.0. If the problem still persists, I have to mention the problem on granian issues right? 
Thank you so much for your insights. It may really solve the issues I've been facing.

**Closed** 2024-07-08 10:41 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed

**Comment by xeroticikot** [comment] 2024-07-08 13:33
I've soled the issue by providing the backlog settings in granian runtime call. This command is given below -

```
exec granian ${DJANGO_WSGI_MODULE}:application \
--interface wsgi \
--host 127.0.0.1 \
--port 8052 \
--workers $WORKERS \
--no-ws \
--no-reload \
--backlog 0
```

**Comment by gi0baro** [comment] 2024-07-15 16:39
> I've soled the issue by providing the backlog settings in granian runtime call. 

You should probably use `--backpressure` instead, as it is designed for that, and set it to the maximum amount of connections you want on the db. Mind that backpressure value is per worker.
