### ISSUE TITLE
MulitChooserPanel - chooserWidgetFactory openModal function is missing

### ISSUE THREAD

**Issue by SecretUnicorn** [wagtail/wagtail#10646] opened 2023-07-06 12:11 UTC
### Issue Summary
When trying to open a MutliChooserPanel it fails because the chooser modal openModal function is missing

### Steps to Reproduce

1. add
 ```
MultipleChooserPanel(
                  "project_features",
                  chooser_field_name="feature",
                  label="Feature",
                  max_num=8,
                  heading="Feature",
                  help_text="Min 1 feature

 Max 8"
              ),


class ProjectFeature(models.Model):
  project = ParentalKey(Project, on_delete=models.CASCADE,
                        related_name="project_features")
  feature = models.ForeignKey(
      Feature, on_delete=models.CASCADE, related_name="+")

```
3. Try to click add label button
4. Get this js error in the browser console
```

Uncaught TypeError: this.chooserWidgetFactory.openModal is not a function
    MultipleChooserPanel http://10.10.10.57:10000/api/static/wagtailadmin/js/page-editor.js?v=ce9bf046:1
    EventListener.handleEvent* http://10.10.10.57:10000/api/static/wagtailadmin/js/page-editor.js?v=ce9bf046:1
    <anonymous> http://10.10.10.57:10000/cms/app1/project/edit/1/:1617
    <anonymous> http://10.10.10.57:10000/cms/app1/project/edit/1/:1624
page-editor.js:1:4815

```

I searched the DOM for an element with the ID <field_name>-CHOOSER_WIDGET and found the script with the JSON you are parsing. I also parsed it in the console and there is indeed no openModal function in the unpacked object. Why is that though?

### Technical details
Python version: 3.10.8
Django: 4.2.3
Wagtail: 5.0.2
Browser: Firefox 114 & Chrome 114

**Comment by gasman** [comment] 2023-07-07 20:16
Hi @SecretUnicorn - thanks for the report. However, I'm unable to replicate this as described on a fresh installation of Wagtail 5.0.2 and Django 4.2.3. After running `wagtail start myproject`, I edited home/models.py to contain the following:

```python
from django.db import models

from wagtail.admin.panels import FieldPanel, MultipleChooserPanel
from wagtail.models import Page
from wagtail.snippets.models import register_snippet
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel


class HomePage(Page):
    pass


@register_snippet
class Feature(models.Model):
    name = models.CharField(max_length=255)

    panels = [
        FieldPanel("name"),
    ]

    def __str__(self):
        return self.name


@register_snippet
class Project(ClusterableModel):
    name = models.CharField(max_length=255)

    panels = [
        FieldPanel("name"),
        MultipleChooserPanel(
            "project_features",
            chooser_field_name="feature",
            label="Feature",
            max_num=8,
            heading="Feature",
            help_text="Min 1 feature Max 8"
        ),
    ]

    def __str__(self):
        return self.name


class ProjectFeature(models.Model):
    project = ParentalKey(Project, on_delete=models.CASCADE, related_name="project_features")
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE, related_name="+")

    panels = [
        FieldPanel("feature"),
    ]

```

and then ran `./manage.py makemigrations`, `./manage.py migrate`, `./manage.py createsuperuser`, `./manage.py runserver`.

After logging in to the admin, I was then able to go to the Snippets menu, create a Feature, and then create a Project with that feature associated, all with no errors.

Javascript errors can sometimes be an indication that you have some older Javascript files from a previous Wagtail release sticking around - if you've recently upgraded Wagtail, make sure you force-refresh the page in the browser, and if this is a production environment running on a 'real' webserver, remember to run `./manage.py collectstatic`.

Closing for now - if you can provide steps that replicate the issue starting from a fresh installation, I'll be happy to reopen and investigate further.

**Closed by gasman** 2023-07-07 20:16 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by SecretUnicorn** [comment] 2023-07-10 08:18
Yeah you are correct. This is indeed a freshly upgraded install (coming from 4.2) Sadly a clean install is not possible because this is only a small part. `collectstatic` and clearing the cache didnt help either. Tbh I have no clue what do do now as I pretty much did all of the upgrade steps...

**Comment by maribedran** [comment] 2023-11-22 19:45
The same thing just happened to me. I had an m2m relationship from `Article` to `Author` and added a thorough model in order to use the `MultipleChooserPanel`. I tried running collectstatic, restarting the server, and even rebuilding the container. Opening an image chooser modal didn't solve it for me.

**Comment by chosak** [comment] 2023-11-29 17:37
I ran into this same issue today and suspect I know what is happening here. This error happens if you try to use MultipleChooserPanel with a ForeignKey to a model that doesn't use ChooserViewSet, for example a plain Django model that isn't registered as a snippet but is still using ModelAdmin. This can be reproduced in Wagtail 5.2 using the code from @gasman [above](https://github.com/wagtail/wagtail/issues/10646#issuecomment-1626022504) but without the `@register_snippet` line.

Not registering the model as a snippet means it doesn't get registered with ChooserViewSet which I think means [it doesn't get](https://github.com/wagtail/wagtail/blob/15455013752a9ff3fe4b7698f527042d2e08a3a4/wagtail/admin/viewsets/chooser.py#L58) the BaseChooser widget; rather, the widget gets created with a plain select. Images, Documents, and Page types all have their own viewset classes that take care of this as well.

In our case, we ran into this problem because we are still using ModelAdmin to edit some of our models in Wagtail, and haven't yet migrated to snippets. Currently [the documentation says](https://docs.wagtail.org/en/latest/reference/pages/panels.html#multiplechooserpanel) that the ForeignKey must point to something that is "usually to an image, document, snippet or another page" - "usually" implies that it doesn't have to be one of these things.

I'm not sure how/if it would be possible to hook MA up to MCP, and maybe it's not worth it since MA is deprecated in 6.0+. But I wanted to share my theory in case others run into this in future on 4.2-5.2.

**Comment by gasman** [comment] 2023-11-29 18:03
@chosak Sounds like this is probably a documentation issue: MultipleChooserPanel is a specialised case of InlinePanel that can be used _when you have a ForeignKey field that uses a chooser interface_ - not a plain select. If you don't have a chooser, MultipleChooserPanel is not valid. Image, document, snippet and page are mentioned in the docs as examples of models that do always use choosers - you can also set up an arbitrary model to use one without making it a snippet by [registering a ChooserViewSet](https://docs.wagtail.org/en/latest/extending/generic_views.html#chooserviewset).
