### ISSUE TITLE
Userbar errors after refreshing script.

### ISSUE THREAD

**Issue by Nigel2392** [wagtail/wagtail#10904] opened 2023-09-16 18:17 UTC
### Issue Summary

An error occurs after reloading the page (No hard refresh!) and the userbar script gets evaluated a second time.
This causes the userbar to behave buggy in general, or even disappear!
It will also cause the accessibility tab to not be responsive, as in you click it - nothing happens.

### Steps to Reproduce

1. Setup SPA
2. Add userbar into template
3. re-execute the userbar script to update the current page's url. (am using htmx, userbar is included in template, script gets executed automatically)
4. error occurs

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
1. The error occurs in the userbar.js sourcecode.

### Technical details
```
userbar.js?v=7f96c3e7:2 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "wagtail-userbar" has already been used with this registry
    at 4917 (http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:499558)
    at n (http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:499700)
    at http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:501100
    at n.O (http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:499982)
    at http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:501114
    at http://127.0.0.1:8080/static/wagtailadmin/js/userbar.js?v=7f96c3e7:2:501120
```
`customElements.define("wagtail-userbar", s)` is the line which causes the error.

**Comment by lb-** [comment] 2023-09-16 19:59
Are you sure the script isn't being run twice in the same session?

Can you provide some of the template code in your bug report?

You say you're using an SPA and htmx, is htmx driving the SPA experience? Or is some other tech doing this (such as React).

It may be helpful to get some of the html from your main template, if you're using htmx swap with a region of the DOM that includes the Userbar script, maybe this is being patched in / swapped on a URL change.

Maybe you can try to ensure that the userbar script template tag is only included in a region of the DOM that won't change.

Either way, more information is going to be needed to reproduce this, 'setup SPA' as a step to reproduce is very ambiguous.

**Comment by gasman** [comment] 2023-11-08 13:14
Closing due to lack of info.

**Closed by gasman** 2023-11-08 13:14 UTC
Labels: type:Bug, status:Needs Info, component:Userbar
