### ISSUE TITLE
Adding external link in StreamField paragraph block minor bug

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#1915] opened 2015-11-10 13:45 UTC
This video shows the bug happening https://dl.dropboxusercontent.com/u/12756315/20151106_114218.mp4

It's when a URL with Query parameters is pasted in, though I'm unable to get the exact URL used in the video. Apparently it only happens occasionally. I've been personally unable to recreate it.

It looks like the link title it replaced with the link address.

**Comment by gasman** [comment] 2015-11-10 13:59
Possibly the same as (or related to) #1548.

**Comment by jossingram** [comment] 2015-11-10 14:05
Yes looks like, sorry.

**Comment by thibaudcolas** [comment] 2017-02-05 14:16
Closing as duplicate of #1548.

**Closed by thibaudcolas** 2017-02-05 14:16 UTC
