### ISSUE TITLE
Multiply images delete

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [wagtail/wagtail#3475] opened 2017-03-22 13:01 UTC
Not really an issue. But it is really annoying to delete images one by one if needed to delete more than 10.
Way to  represent : 
1) Upload 1000 - 2000 images 
2) Open admin page and start to delete them.
Sorry if i complain about something already implemented. 
May be exist something to delete in one click ?

**Comment by khink** [comment] 2017-03-24 09:54
I think this is a duplicate of https://github.com/wagtail/wagtail/issues/121.

**Comment by gasman** [comment] 2017-03-24 10:02
I think so too. Thanks for the report @jpVm5jYYRE1VIKL!

**Closed by gasman** 2017-03-24 10:02 UTC
