### ISSUE TITLE
docs search not working in versions

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#8815] opened 2022-07-07 13:16 UTC
I just noticed this problem: _(not very important)._

I was looking for something. For some reason the search did not work proper:
https://docs.wagtail.org/en/v3.0.1/search.html?q=ModelAdmin#

This due v3.0.1 in url. 

How to repeat. Select V3 and do a search.

**Comment by lb-** [comment] 2022-07-11 08:43
Duplicate of known issue. 

https://github.com/wagtail/wagtail/issues/8159

**Closed by lb-** 2022-07-11 08:43 UTC
Labels: Documentation
