### ISSUE TITLE
LOGIN_REDIRECT_URL required

### ISSUE THREAD

**Issue by jdavid** [wagtail/wagtail#3620] opened 2017-05-29 15:04 UTC
### Issue Summary

Since 1.0 LOGIN_REDIRECT_URL should not be required, but it is.
See http://docs.wagtail.io/en/v1.0/releases/1.0.html#you-no-longer-need-login-url-and-login-redirect-url-to-point-to-wagtail-admin

### Steps to Reproduce

    $ virtualenv venv
    $ cd venv/
    $ source bin/activate
    $ pip install wagtail
    $ wagtail start project
    $ cd project/
    $ python manage.py migrate
    $ python manage.py createsuperuser
    $ python manage.py runserver

Go to http://localhost:8000/admin/login/
Login => 404 Not found 

Expected: access to the admin. Instead you get a redirection to http://localhost:8000/accounts/profile/ and a Not Found error.

### Technical details

Django version: 1.11.1
Wagtail version: 1.10.1

**Comment by gasman** [comment] 2017-05-30 20:17
Thanks for the report! I can confirm I'm seeing the same thing. Normally there would be no reason to visit `/admin/login/` directly - you'd visit a URL like `/admin/`, which would redirect you to `/admin/login/?next=/admin/` where the `next` param overrides LOGIN_REDIRECT_URL. We should definitely make direct requests to `/admin/login/` work, though - it looks like the best way of doing that would be to insert a default value into `request.GET['next']` before [we call Django's auth.login view](https://github.com/wagtail/wagtail/blob/3f8052064ecd16e823143b4279585742e1aa22cf/wagtail/wagtailadmin/views/account.py#L139).

**Comment by jianshen92** [comment] 2017-06-02 20:11
Hi gasman, once you log out from the app, you will be at the `/admin/login`. So there are actually scenario where u will visit `/admin/login` directly.

**Comment by jianshen92** [comment] 2017-06-02 20:23
Kinda new to django, just wondering what is the temporary fix until the official fix for this bug.

**Comment by jdavid** [comment] 2017-06-02 21:01
@jianshen92 Add this to the settings file:

    LOGIN_REDIRECT_URL = 'wagtailadmin_home'

**Comment by kapito** [comment] 2017-07-10 12:07
I cannot successfuly reacreate this bug on Wagtail version 1.11.1 -- going to http://localhost:8000/admin/login/ redirects me to http://localhost:8000/admin/ as expected.

**Comment by gasman** [comment] 2017-07-10 12:15
@kapito It still happens here: if you visit http://localhost:8000/admin/login/ as a non-logged-in user and then log in, you're redirected to http://localhost:8000/accounts/profile/ .

**Comment by kapito** [comment] 2017-07-10 12:40
@gasman Perhaps I am doing something wrong -- for me after logging in from http://localhost:8000/admin/login/ I am simply taken to http://localhost:8000/admin/ .

**Comment by amwebste** [comment] 2017-08-17 18:33
I am unable to reproduce this issue in either wagtail version 1.10.1 or 1.13.0.  It looks like this issue has been closed from commit ad6805e2788e5176917fa7769306362a97cad761.  That commit sets the LOGIN_REDIRECT_URL='wagtailadmin_home' in the settings file.

**Comment by gasman** [comment] 2017-08-17 18:39
Hi @amwebste - commit ad6805e2788e5176917fa7769306362a97cad761 is part of the https://github.com/cca/libraries_wagtail/ repo, not Wagtail itself. (It only appears above because it references this ticket in the commit message)

**Comment by gasman** [comment] 2017-08-17 19:04
After further experimentation, I've now found that this was a Django bug introduced in 1.11 and fixed in 1.11.3:

https://code.djangoproject.com/ticket/28229
https://docs.djangoproject.com/en/1.11/releases/1.11.3/

Thanks for the investigation, all :-)

**Closed by gasman** 2017-08-17 19:04 UTC
Labels: difficulty:Easy, size:Small, type:Bug
