### ISSUE TITLE
Unable to horizontally scroll input fields in admin on safari mobile.

### ISSUE THREAD

**Issue by Wtyeomans** [wagtail/wagtail#3676] opened 2017-06-22 19:00 UTC
### Issue Summary

Inside the wagtail admin when editing a page, input fields are not able to scroll horizontally.  This is only happening in safari mobile, and seems to be not just an issue with wagtail based on apple forums.  

### Steps to Reproduce

Edit any page with an input field value that overflows past the input field width.  

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Others have used `overflow-x: scroll` and `-webkit-overflow-scrolling: touch` to some success, I wan't able to.  

### Technical details

* Python version: 3.5.2
* Django version: 1.10.5
* Wagtail version: 3.5.2
* Browser version: Safari 10 mobile

**Comment by thibaudcolas** [comment] 2022-08-16 12:33
I’m unable to reproduce this as of #8921, so will close this now.

**Closed by thibaudcolas** 2022-08-16 12:33 UTC
Labels: type:Bug, component:Frontend
