### ISSUE TITLE
Add question mark to boolean field -Is default site

### ISSUE THREAD

**Issue by Theresa-o** [wagtail/wagtail#9468] opened 2022-10-23 07:04 UTC
### Issue Summary
While adding/editing pages, there is an option to make a page the default/home page. This is a boolean question however there is no question mark to indicate this.

### Steps to Reproduce

1. Go to 'admin' site
2. Click on pages
3. Click on add/edit pages, you would see a boolean value 'Is default site'

While this may seem as an easy know-how for mid to experienced developers/users, a question mark indicating that this is a question and should be ticked should be added for fresh developers/users

![wagisdefaultsite](https://user-images.githubusercontent.com/62052443/197378648-0ca16b9b-7d50-4771-9d6e-4c1a53c4706c.PNG)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Proposal
Add a '?' to make the user experience easier as seen below

![wagisdefaultsiteedit](https://user-images.githubusercontent.com/62052443/197378772-416d6d08-9d47-4cbf-8b11-957eae8ff0e1.PNG)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by Theresa-o** [comment] 2022-10-23 07:04
@lb- please confirm if I can merge this

**Comment by lb-** [comment] 2022-10-23 08:27
@Theresa-o not sure to to be honest, this is the field label and not really a sentence. We don't make the page title field say 'what is the page title'. 

If anything, maybe the label could be just 'default site' without the 'is'. 

I'll flag this as an enhancement not a bug and that this needs a second or third opinion from the core team. 

Thanks for checking.

**Comment by lb-** [comment] 2022-10-23 08:28
We also have a very clear help text under the field.

**Comment by lb-** [comment] 2022-10-23 08:28
Thoughts @thibaudcolas

**Comment by Theresa-o** [comment] 2022-10-23 08:30
@lb- Ok, I understand, I await feedback.

I did not see an option for enhancement, that's why I created it as a bug

**Comment by AnishaSingh0118** [comment] 2022-11-03 10:17
Hello @Theresa-o I have resolved this issue. Let me know if I could do something else.

**Comment by Theresa-o** [comment] 2022-11-03 13:58
Hello @AnishaSingh0118 This is awaiting @thibaudcolas feedback.

There's no confirmation if this change should be made yet as discussed with @lb- above.

**Comment by AnishaSingh0118** [comment] 2022-11-03 14:23
> Hello @AnishaSingh0118 This is awaiting @thibaudcolas feedback.
> 
> There's no confirmation if this change should be made yet as discussed with @lb- above.

Oh! ok. Thanks for confirming.

**Comment by thibaudcolas** [comment] 2022-11-04 13:46
@Theresa-o this form is part of the fundamental website setup that will only ever be changed once or twice for a given site, and always by someone very familiar with Wagtail, most likely with developer-level awareness of what the form does.

As such I don’t think the current field label is hard to understand. It’s certainly not the most elegant wording but I don’t think changing it would necessarily be worth the effort for translator.

I’ll close this now – if anyone wants to see this considered more please re-open. If we proceed with a change, I’d prefer we avoid the question mark for the reasons LB mentions.

**Closed by thibaudcolas** 2022-11-04 13:46 UTC
Labels: type:Bug, type:Enhancement, status:Needs Design Decision, component:Site

**Comment by AnishaSingh0118** [comment] 2022-11-04 13:48
> @Theresa-o this form is part of the fundamental website setup that will only ever be changed once or twice for a given site, and always by someone very familiar with Wagtail, most likely with developer-level awareness of what the form does.
> 
> As such I don’t think the current field label is hard to understand. It’s certainly not the most elegant wording but I don’t think changing it would necessarily be worth the effort for translator.
> 
> I’ll close this now – if anyone wants to see this considered more please re-open. If we proceed with a change, I’d prefer we avoid the question mark for the reasons LB mentions.

Ok.

**Comment by Theresa-o** [comment] 2022-11-04 13:51
> @Theresa-o this form is part of the fundamental website setup that will only ever be changed once or twice for a given site, and always by someone very familiar with Wagtail, most likely with developer-level awareness of what the form does.
> 
> As such I don’t think the current field label is hard to understand. It’s certainly not the most elegant wording but I don’t think changing it would necessarily be worth the effort for translator.
> 
> I’ll close this now – if anyone wants to see this considered more please re-open. If we proceed with a change, I’d prefer we avoid the question mark for the reasons LB mentions.

Got it @thibaudcolas Thanks for the feedback
