### ISSUE TITLE
Fonts loaded from CSS break in private S3 bucket with django-storages

### ISSUE THREAD

**Issue by probabble** [wagtail/wagtail#4806] opened 2018-10-11 22:27 UTC
https://github.com/wagtail/wagtail/blob/7c82594c2911257710297ca9e4419e9ffbfbbf71/wagtail/admin/static_src/wagtailadmin/scss/_font-icons.scss#L4

Because these urls are generated outside Django's staticfiles app, they don't get the additional request parameters necessary to successfully authenticate with S3. These should be loaded in an alternate way, or at least with a backup that loads fonts with `{% static 'wagtailadmin/fonts/wagtail.woff' %}`

**Comment by gasman** [comment] 2018-10-12 11:40
Hi @probabble - thanks for the report.
Happy to hear other opinions on this, but my inclination is that this isn't Wagtail's problem to solve - the issue is not specific to fonts, but would affect any static file URLs that appear within CSS such as images, and I don't think it's feasible for us to avoid (or find workarounds for) static file references within CSS.

(As it happens our use of images in CSS is currently fairly minimal, since we do icons in fonts, but that may change soon: #4464)

Django's [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifeststaticfilesstorage) backend has a feature where it finds and rewrites URLs in CSS - I think that would be the appropriate level to implement a fix for this. (It may even turn out that switching to `ManifestStaticFilesStorage` will solve the problem entirely, if it pipes the path through `static` as part of the rewriting process...)

**Closed by gasman** 2018-10-12 11:40 UTC

**Comment by probabble** [comment] 2018-10-12 19:48
@gasman ok ... but https://docs.wagtail.io/en/v2.2.2/advanced_topics/deploying.html#cloud-storage recommends I set it up the way I had it when I encountered this problem, and I haven't found a clear path to enabling ManifestStaticFilesStorage and S3Boto3 storage at the same time. Currently trying 

```python
class ManifestS3Storage(S3Boto3Storage, ManifestFilesMixin):
    # hack to prevent boto3 from failing hard
    def _save_content(self, obj, content, parameters):
        """
        We create a clone of the content file as when this is passed to boto3 it wrongly closes
        the file upon upload where as the storage backend expects it to still be open
        """
        # Seek our content back to the start
        content.seek(0, os.SEEK_SET)

        # Create a temporary file that will write to disk after a specified size
        content_autoclose = SpooledTemporaryFile()

        # Write our original content into our copy that will be closed by boto3
        content_autoclose.write(content.read())

        # Upload the object which will auto close the content_autoclose instance
        super()._save_content(obj, content_autoclose, parameters)

        # Cleanup if this is fixed upstream our duplicate should always close
        if not content_autoclose.closed:
            content_autoclose.close()
```

Either the docs should warn users that this is currently unsupported ( due to a problem with django-storages ) or they should specify the correct combination of settings to get the CSS links formatting properly.
