### ISSUE TITLE
pass the page object to construct_wagtail_userbar hook

### ISSUE THREAD

**Issue by JanMalte** [wagtail/wagtail#11337] opened 2023-12-12 22:11 UTC
### Is your proposal related to a problem?

Sometime I have the case that a custom item in the userbar depends on the current page.

Currently only the request and the userbar items are passed to the hook. This makes it hard to access the current page.

### Describe the solution you'd like

The page object gathered in the userbar template tag should be passed as optional parameter to the registered hooks.

```python
# wagtail/admin/templatetags/wagtailuserbar.py:93
        for fn in hooks.get_hooks("construct_wagtail_userbar"):
            fn(request, items, page)
```

The included `ExplorePageItem` or `EditPageItem` userbar items get the `page` instance passed already.

Currently I have to use a workaround like this:

```python
BLOG_CURRENT_PAGE = "BLOG_CURRENT_PAGE"


class EditArticleItem(BaseItem):
    template = "wagtailadmin/userbar/item_edit_article.html"

    def __init__(self, page):
        self.page: ArticlePage = page

    def render(self, request):
        # Don't render if the page doesn't have an id
        if not self.page.id:
            return ""
        # Don't render if the page doesn't have an article or the article doesn't have an id
        if not self.page.article_obj or not self.page.article_obj.pk:
            return ""

        # Don't render if user doesn't have permission to access the admin area
        if not request.user.has_perm("wagtailadmin.access_admin"):
            return ""

        # Don't render if user doesn't have permission to change the article
        if not request.user.has_perm("blog.article_change", obj=self.page.article_obj):
            return ""

        return super().render(request)


@register("construct_wagtail_userbar")
def article_edit_link(request, items: list):
    page = request.META.get(BLOG_CURRENT_PAGE, None)
    if page and isinstance(page, ArticlePage):
        items.insert(0, EditArticleItem(page))


@hooks.register("before_serve_page")
def article_edit_link_request_helper(page, request, serve_args, serve_kwargs):
    request.META.update(
        {
            BLOG_CURRENT_PAGE: page,
        }
    )

```

**Comment by thibaudcolas** [comment] 2023-12-22 12:23
Hi @JanMalte, thanks for the request. This makes a lot of sense to me Looking at the [userbar hook implementation](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templatetags/wagtailuserbar.py#L56-L93), I think it might be a matter of doing this in a way that it’s clear whether the menu item is displayed with a page available, something else.

Let’s see what others think.

**Comment by lb-** [comment] 2024-01-04 03:19
@JanMalte do you think this could be a duplicate of https://github.com/wagtail/wagtail/issues/3847 ?

**Comment by JanMalte** [comment] 2024-01-04 06:18
@lb- yes, this is the same issue. Thanks for the hint.

**Comment by lb-** [comment] 2024-01-04 06:26
Closing as duplicate of https://github.com/wagtail/wagtail/issues/3847

**Closed by lb-** 2024-01-04 06:26 UTC
Labels: type:Enhancement, component:Page, component:Userbar
