### ISSUE TITLE
TableBlock editing UI fails to render fully when collapsed=True

### ISSUE THREAD

**Issue by stevejalim** [wagtail/wagtail#10943] opened 2023-09-25 10:25 UTC
### Issue Summary

If you have a StreamField containing a StructBlock which includes a TableBlock and the StreamField uses `collapsed=True`, the editing UI for the child TableBlock will not be shown when that block is expanded.

It's possible this is also present for direct use of a TableBlock in a StreamField, but I have not explored this.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add a custom block that uses TableBlock as a child - eg

```class HeadedTableBlock(StructBlock):
    
    title = wagtail_blocks.CharBlock(
        max_length=50,
        required=False,
    )
    intro = wagtail_blocks.RichTextBlock(
        required=False,
    )
    table = TableBlock()
```

and add it to a Streamfield on a new Page subclass, with `collapsed=True` set on the StreamField

4. Add some content to that table. Save Draft. Expand the collapsed section again and you'll see the table does not render

5. Adjust the width of the window, however, and the table DOES appear. See accompanying video 

https://github.com/wagtail/wagtail/assets/101457/cfe1a503-fa9e-4725-8ffd-66ce1d867b9f

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no, but it's not related to other code

### Technical details

-   Python version: 3.11.x
-   Django version: 4.2
-   Wagtail version: 5.11
-   Browser version: Firefox 118.0b8

**Comment by lb-** [comment] 2023-09-25 10:33
This looks like a duplicate of https://github.com/wagtail/wagtail/issues/8611

Please can you add your comments/recording to that issue. It was hoped this was fixed, obviously that's not the case.

**Closed by lb-** 2023-09-25 10:33 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by stevejalim** [comment] 2023-09-25 10:35
Sure thing @lb- Thanks for the rapid reply
