### ISSUE TITLE
Wagtail guide URL does not exist

### ISSUE THREAD

**Issue by rikva** [wagtail/wagtail#10105] opened 2023-02-17 09:18 UTC
After upgrading to Wagtail 4.2.0, the CMS home page shows a dialog which links to https://guide.wagtail.org/4.2.x/. This page does not exist.

**Comment by laymonage** [comment] 2023-02-17 09:20
Hi @rikva, the page redirects to https://guide.wagtail.org/latest/ as 4.2.x is currently the latest version. When 5.0 is released, we'll update the guide website so that https://guide.wagtail.org/4.2.x/ actually exists and https://guide.wagtail.org/latest/ represents the guide for Wagtail 5.0.

Can you confirm that the https://guide.wagtail.org/4.2.x/ redirects you to the latest version?

**Comment by rikva** [comment] 2023-02-17 09:25
Hi @laymonage, it appears that on my machine the redirect works like expected when using `curl`, but not in Firefox and Safari.

**Comment by RealOrangeOne** [comment] 2023-02-17 09:31
The redirect is handled using Wagtail redirects, and is working fine for me in Firefox.

When you say the redirect "isn't working", what's happening instead? Are you given a 404 page?

**Comment by rikva** [comment] 2023-02-17 09:32
> The redirect is handled using Wagtail redirects, and is working fine for me in Firefox.
> 
> When you say the redirect "isn't working", what's happening instead? Are you given a 404 page?

Yes:

<img width="299" alt="afbeelding" src="https://user-images.githubusercontent.com/1089611/219607047-b894de79-3600-411a-9f9a-e5aef64236b2.png">

**Comment by thibaudcolas** [comment] 2023-02-28 09:42
Thanks for the report @rikva, that’s an interesting one. I can’t see a reason why this would fail aside from caching _somewhere_.

Could you try accessing the page with a query parameter (`https://guide.wagtail.org/4.2.x/?w=1`) and see what happens?

**Comment by rikva** [comment] 2023-02-28 11:09
@thibaudcolas so this is weird:

Earlier this morning, there was no difference when using a query parameter. 404 in both cases.

I asked a few colleagues located in the same country. They reported no 404s.

I tried using my phone and its carrier network; 404.
I used a VPN; 404.

Now, coincidentally I tried again on my machine and now the redirect suddenly works.

I can't explain this (other than it is likely caching somewhere) but it seems like I'm the only one having this problem. So feel free to close this issue.

**Comment by ax-sc** [comment] 2023-03-01 17:33
I do experience the same issue (no matter with or without an additional query parameter). I will attach the header information, feel free to ping me if you want to investigate further and I should provide more information. 

**Request Header:**
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Pragma: no-cache
Cookie: _ga=GA1.2.956179053.1677265759; _gid=GA1.2.856901512.1677506656; _ga_965H37LBFX=GS1.1.1677668090.7.0.1677668093.0.0.0
Cache-Control: no-cache
Host: guide.wagtail.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Accept-Language: de-DE,de;q=0.9
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

**Response Header:**
```
Content-Type: text/html; charset=utf-8
Via: 1.1 vegur
Content-Language: en-latest
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=RMdLgMQinIR6pxx1aBWQSVGpbTs2L8GWBn3qVOeyHwRbVr6%2FuwlGhNE60NJpYX%2BTDnGLdi3leC01%2FIjcJ6aIfIHdQZXNLZwM5xS6aci2o1r8drViNQATTdguobb4okO46PzSm7R3p%2BDpnE%2FlXAjw"}],"group":"cf-nel","max_age":604800}
Content-Encoding: br
Referrer-Policy: same-origin
Date: Wed, 01 Mar 2023 17:27:07 GMT
Cross-Origin-Opener-Policy: same-origin
X-Content-Type-Options: nosniff
Vary: Accept-Language, Accept-Encoding
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
cf-cache-status: DYNAMIC
Strict-Transport-Security: max-age=15552000; includeSubDomains
cf-ray: 7a131bdd1febabc6-CPH
```

**Comment by thibaudcolas** [comment] 2023-03-07 15:29
Ah! Looks like this is language-related.

This is a 301:

```bash
curl -I -H 'Accept-Language: en' https://guide.wagtail.org/4.2.x/
```

And 404:

```bash
curl -I -H 'Accept-Language: nl' https://guide.wagtail.org/4.2.x/
```

I’m guessing one of the site’s [language-aware middleware](https://github.com/wagtail/guide/blob/main/apps/core/middleware.py#L7) isn’t implemented correctly.

This is technically not an issue with Wagtail itself but I’ll leave it here for the time being so other people experiencing this don’t open new issues.

**Comment by thibaudcolas** [comment] 2023-05-10 23:05
Looks like this is actually a dupe of https://github.com/wagtail/guide/issues/262 so will close this now.

**Closed by thibaudcolas** 2023-05-10 23:05 UTC
Labels: type:Bug
