### ISSUE TITLE
RichText field is losing line breaks in 2.0b1

### ISSUE THREAD

**Issue by paperreduction** [wagtail/wagtail#4266] opened 2018-02-10 05:56 UTC
Upgraded from wagtail 2.0 alpha (no issue) to 2.0b1 and now when loading a richtext field that previously had line breaks the line breaks are missing. The initial editing/saving seems to work fine, but a subsequent edit causes the lose of the line breaks.

0. Python 3.6 and Django 2.0, Chrome 64
1. git checkout v2.0b1
2. npm install
3. npm run build
4. Start with empty richtext field on a page and save sample text to field:

The quick brown fox**⇧ + ↵**
jumps over the lazy dog.

5. Edit page again and now the field looks like this:

The quick brown foxjumps over the lazy dog.

6. Saving the page persists the missing line break(s). 

I'm not sure if this is a bug with draftail or wagtail, but there are no js errors in the console.

**Comment by thibaudcolas** [comment] 2018-02-10 11:38
Hey @paperreduction, thanks for the report. I'm not aware of any alpha release of 2.0 – would you know the particular commit you were working from?

----

For the issue, there are two ways to troubleshoot its origin. We can look at the content before/after saving the page:

1. Edit the page and enter content in the editor
2. Note the value of the hidden input sitting next to the editor.
3. Save the page
4. Disable JavaScript in your browser
5. Edit the page, note the value of the hidden input (that hasn't been altered client-side since JS is disabled)

In this example, here's how saving the page transforms the content:

```diff
{
  "blocks": [
    {
-      "key": "3zrap",
+      "key": "qr7nk",
-      "text": "Line\nbreak",
+      "text": "Linebreak",
      "type": "unordered-list-item",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
-      "data": {}
    }
  ],
  "entityMap": {}
}
```

We can also just look at what's rendered on the site's front-end (same as what's stored in the DB for a simple example like this):

```html
<ul><li>Line<br>break</li></ul>
```

So the issue seems to be server-side, at the DB HTML -> Draft.js ContentState stage. 

Here's a test case that reproduces it:

```py
def test_br_element_in_paragraph(self):
        converter = ContentstateConverter(features=[])
        result = json.loads(converter.from_database_format(
            '''
            <p>before<br>after</p>
            '''
        ))
        self.assertContentStateEqual(result, {
            'entityMap': {},
            'blocks': [
                {'key': '00000', 'inlineStyleRanges': [], 'entityRanges': [], 'depth': 0, 'text': 'before\nafter', 'type': 'unstyled'}
            ],
        })
```

This produces the following warning `assert name == expected_name, "Unmatched tags: expected %s, got %s" % (expected_name, name)
AssertionError: Unmatched tags: expected br, got p`. Changing from `<br>` to `<br/>` doesn't seem to work either.

Line breaks aren't an explicit "rich text feature" at the moment, so they may be enabled inconsistently across the rich text processing pipeline.

**Comment by paperreduction** [comment] 2018-02-10 14:15
Awesome! Thanks for the details. I'll see if I can digest that and track down the issue.

Sorry for the confusion on the "alpha" release, I was using commit 4fe6104 (2017-12-22).

**Comment by paperreduction** [comment] 2018-02-10 23:07
Okay, so I haven't contributed to this project yet. And this was a lot more complex than I realized. This parsing code is no joke. So before I fork and submit a PR here's what I'm thinking a solution could be:

Update `html_to_contentstate.py` with a new line break handler that injects the line break character into `current_block.text`. Then the `HtmlToContentStateHandler` can be configured to use it, or we could require it to be turned on by passing a `br` feature-

```python
class LineBreakHandler(InlineEntityElementHandler):
    mutability = 'IMMUTABLE'

    def create_entity(self, name, attrs, state, contentstate):
        return Entity('LINE_BREAK', 'IMMUTABLE', {})

    def handle_starttag(self, name, attrs, state, contentstate):
        super().handle_starttag(name, attrs, state, contentstate)
        state.current_block.text += '\n'

class HtmlToContentStateHandler(HTMLParser):
    def __init__(self, features=()):
        self.paragraph_handler = BlockElementHandler('unstyled')
        self.element_handlers = HTMLRuleset({
            'p': self.paragraph_handler,
            'br': LineBreakHandler('unstyled')
        })

# wagtail_hooks.py
features.register_converter_rule('contentstate', 'br', {
        'from_database_format': {
            'br': LineBreakHandler('unstyled'),
        },
        'to_database_format': {
            'entity_decorators': {'LINE_BREAK': lambda props: DOM.create_element('br')}
        }
    })
```

Running that in the test case produces-

```python
{'blocks': [
  {'key': 'r41ry', 'type': 'unstyled', 'depth': 0, 'text': 'before\nafter', 'inlineStyleRanges': [], 'entityRanges': [{'key': 0, 'offset': 6, 'length': 1}]}
], 'entityMap': {'0': {'mutability': 'IMMUTABLE', 'type': 'unstyled', 'data': {}}}}
```

This seems to be working on the first save. The value goes all the way to the database as a `<br/>`. When reloading the admin for an edit, the text is also displayed correctly. I can see the input value includes `\n` in the html source:

```html
&quot;text&quot;: &quot;The quick brown fox\nJumps over the lazy dog.&quot;, 
```
And on the react side of things the `rawContentState` prop looks like:

```js
rawContentState: {
...
text: "The quick brown fox\nJumps over the lazy dog."
...
}
```

However, if I make no changes to the text and click save I lose the line break! Looking at the POST request between the first post and the second shows the line break is in the block text, but the entityMap on the second (broken) post has an extra object (looks like what `from_database_format` is producing):

```json
"1": {
  "mutability": "IMMUTABLE",
  "type": "unstyled",
  "data": {}
}
```

**Comment by geoandrew** [comment] 2018-02-11 02:46
Thanks for jumping on this @paperreduction, I just spent a couple of hours with this same issue on my own project and then thought to check the bug list. 

I have also found some other anomalies to do with the editor display which may or may not be related.

```
heading = RichTextField(features=['bold', 'italic', 'link'])
...
panels = [ FieldPanel('heading'),]
```

displays the following in the editor
![image](https://user-images.githubusercontent.com/11432770/36068762-d03ecb6e-0e91-11e8-8141-17c45cc00b01.png)

As you can see, the line break icon is in the toolbar, even though it's not in the `features` list. Now, I do actually want line breaks in my features, but could not find which key word should be used as it's not listed in the [documentation](http://docs.wagtail.io/en/latest/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field).

I spent some time digging through the source code but without much luck.

**Comment by paperreduction** [comment] 2018-02-11 02:51
I think I have it figured out. I'm prepping my pull request now. Same idea, but without using an Entity or Block on the state. This is similar to how the ul/ol tags work.

```python
class LineBreakHandler:
    def handle_starttag(self, name, attrs, state, contentstate):
        state.push()  # void tag
        state.current_block.text += '\n'

    def handle_endtag(self, name, state, contentstate):
        state.pop()  # void tag
```

**Comment by paperreduction** [comment] 2018-02-11 05:16
@geoandrew I did a little looking at the `features` list since you pointed out that it's not listed in the documentation as being defaulted on. I'm not sure if this is a bug (needs a fix), or by design (needs docs). And I don't want that holding up the patch since this is marked as release blocker. 

@thibaudcolas maybe you can speak to how you want to deal with the UI aspect.

**Comment by thibaudcolas** [comment] 2018-02-11 13:03
Yes, at the moment there are two rich text features that are [hard-coded at the editor level](https://github.com/wagtail/wagtail/blob/6825aab5f764cb9accfd6af47b126e8e0f12f0d2/client/src/components/Draftail/index.js#L78-L81) and do not have a corresponding configurable "rich text feature":

- Line breaks, set to "enabled"
- Maximum list nesting (for UL and OL), set to 4

I don't think this is by design, it was just an oversight. At the very least this should be documented, or we should have rich text features for those. We should also define these with the other rich text features (even if they kept the same default values as now).

For line breaks this should be straightforward, following what @paperreduction did in #4268 (thank you!). For max list nesting, I'm not sure what's the best way to make it configurable.

@gasman will know how to proceed.

**Comment by gasman** [comment] 2018-02-15 22:10
Fixed in #4268

**Closed by gasman** 2018-02-15 22:10 UTC
Labels: Release blocker, component:Rich text, type:Bug

**Comment by thibaudcolas** [comment] 2018-04-02 21:07
@Pomax see https://github.com/wagtail/wagtail/pull/4268#issuecomment-365994579

**Comment by thibaudcolas** [comment] 2018-04-04 09:36
@Pomax err, I completely forgot for a moment but we actually discussed this again in one of our team meetings, and there was a consensus that it should be configurable / removable. Just made #4445 so I don't forget again.

**Comment by Pomax** [comment] 2018-04-04 15:45
awesome, I'l comment there!
