### ISSUE TITLE
Document the register_rich_text_embed_handler / register_rich_text_link_handler hooks (#1093)

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#1094] opened 2015-03-23 20:10 UTC

**Comment by jimr** [comment] 2016-06-10 08:38
Any word on when this might happen? We're using this hook and upgrading to 1.5.2 has broken our custom link handlers and I'm not entirely sure why :)

**Comment by jimr** [comment] 2016-06-10 09:16
I think the issue is related to this line: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js#L80

I'm pretty sure that should reference `pageData.link_type` instead of being hard-coded to `page`.

**Comment by gasman** [comment] 2016-06-10 09:55
Hi @jimr,
The `register_rich_text_embed_handler` / `register_rich_text_link_handler` hooks are unrelated to the behaviour of the toolbar buttons / choosers - they only handle the conversion between the internal database representation of rich text (where links appear as e.g. `<a linktype="page" id="123">link text</a>`) and the real HTML as displayed on the front-end and within the editor.

The line of code you point to looks correct to me - that's been unchanged since the original release of Wagtail, and is dealing specifically with JSON responses that come back from the page chooser modal (see https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js#L37), so it's valid for it to treat any response containing an ID as a page ID.

**Comment by jimr** [comment] 2016-06-10 10:08
OK, fair enough. I think our issue is that we're hijacking this functionality and inserting our own link types using the default hallo link plugin. Once the above docs are in place, maybe we'll be able to implement in a more robust fashion.

**Comment by woegjiub** [comment] 2016-12-07 03:40
It's worth noting that the order of precedence is effectively reversed for these:

In INSTALLED_APPS, earlier entries should override later ones.
With this hook, later ones override earlier.

**Comment by thibaudcolas** [comment] 2019-04-05 11:24
Closing, as this doesn't seem relevant anymore now that those rewrite handlers are defined through the `register_rich_text_features` hook and the rich text features registry.

**Closed by thibaudcolas** 2019-04-05 11:24 UTC
Labels: Documentation, component:Rich text

**Comment by gasman** [comment] 2019-04-05 11:32
@thibaudcolas Good catch :-) The Wagtail 2.x equivalent functionality is now documented at https://docs.wagtail.io/en/stable/advanced_topics/customisation/rich_text_internals.html .
