### ISSUE TITLE
Internationalization for Wagtail content

### ISSUE THREAD

**Issue by shezi** [wagtail/wagtail#96] opened 2014-02-25 18:13 UTC
As noted in #23 and other places, it would be great if Wagtail could support content in and for different locales.
The main effort about this is probably specification, so I'd like to get the discussion going here about the direction i18n for content should move.

One important question about the issue is whether i18n should be enabled all the time or optional. Depending on this, the changes can either go into the models directly or into model subclasses.

**Comment by lemieux** [comment] 2015-05-19 16:33
Any update on this issue?

**Comment by rmartins90** [comment] 2015-05-19 17:02
https://github.com/infoportugal/wagtail-modeltranslation

2015-05-19 17:33 GMT+01:00 Marc-Antoine Lemieux <notifications@github.com>:

**Comment by rmartins90** [comment] 2015-05-19 17:03
Still in development. Maybe you can contribute.

Thanks in advance

2015-05-19 18:02 GMT+01:00 Rui Martins <rmartins16@gmail.com>:

**Comment by SalahAdDin** [comment] 2015-05-19 21:09
Have not you thought about doing it like they do in django cms? To create "copies" of the model fields for each language supported, and that the user fills these fields with the appropriate translations? I think it would be easier that way.

**Comment by SalahAdDin** [comment] 2015-06-09 03:08
wagtail-modeltranslation work like django-cms, i think that is a very good idea become a official wagtail feautre, and put each language in a content tab.

**Comment by merqurio** [comment] 2015-06-09 12:46
:+1: @SalahAdDin That would be awesome

**Comment by nek4life** [comment] 2015-07-23 11:03
:+1: Looking into using wagtail for a project and this is probably going to end up being a deal breaker. I looked at the [current suggested approach](http://docs.wagtail.io/en/latest/advanced_topics/multilingual_sites.html), but it seems like that would expect all pages to be translated and duplicated. There are also fields that do not need translating that would be duplicated.

**Comment by tomdyson** [comment] 2015-07-23 11:16
@nek4life we've built multi-language Wagtail sites that don't expect all pages to be translated, e.g. Global Witness:

https://www.globalwitness.org/ (see 'Languages' at the top)

and some that do, e.g.

http://www.coebank.org/

and one where every field is translated:

http://refugee-photo-project.unhcr.org/en/

Better i18n / multi-language support is a priority for upcoming Wagtail versions, but it's certainly possible now.

**Comment by tomdyson** [comment] 2015-07-23 11:22
P.S. @nek4life which model do you need? We want to make sure we can accommodate most of them :)

**Comment by rmartins90** [comment] 2015-07-23 11:23
We, at InfoPortugal, developed an isolated app that integrates django-modeltranslation with Wagtail CMS. It's pretty stable. We are using it on several projects and soon one of them will be available on production environment. It's been tested on pre-production environments.

https://github.com/infoportugal/wagtail-modeltranslation

**Comment by kaedroho** [comment] 2015-07-23 11:27
The docs for multilingual sites are a bit old (#612) and there's now better options available.

If I get time, I'll have a go at rewriting them over the weekend.

**Comment by tomdyson** [comment] 2015-07-23 11:28
@rmartins90 this is great to read! Is the production environment running on Wagtail 1.0?

**Comment by rmartins90** [comment] 2015-07-23 11:31
The pre-production environment is running on Wagtail 1.0 and Django 1.7.8. And is being used by clients as well. Until now it's working just fine.

**Comment by rmartins90** [comment] 2015-07-23 11:37
We intend to make some serious modifications on v1.0 as:
- drop django-modeltranslation dependency;
- use translated tabs instead of repeating fields along the tab. This should not contain non translatable fields;
- better documentation;

All help is welcome.

**Comment by tomdyson** [comment] 2015-07-23 11:42
Thanks, @rmartins90, that's a useful roadmap. We (Torchbox) can certainly help. Shall we have a Hangout or similar to discuss, early next week? Does anyone else want to be involved?

**Comment by J0hn5mith** [comment] 2015-07-23 11:45
Hi

My company is also figuring out how we can use wagtail with several languages. I already approached you but we could not find a date. 
I could help with some ideas for the concept. But I don't have much time for actual coding.

**Comment by nek4life** [comment] 2015-07-23 12:49
Hey @tomdyson, so I actually need to talk with the owner of this particular project to see what their exact needs are, but I do have some general thoughts on translation support.

Front end. I'd like the language in the path /en /fr-CA /fr . I would like the paths to remain the same to child pages even if they are not translated, i.e. the default language the content is generated is the fall back, but the url does not change only the fields that are translated. Half a page could potentially be translated for example.

Admin side: One page with translatable fields. No pages are duplicated just to translate them. All fields could be translated, but not necessarily think something like images. I would also like the translations to not be inline with the original text for content creators so it's not in the way of getting work done. A translation tab that shows the original content next to the selected translated language would be great way to handle this.

I've built a custom admin like this before using flask, but not using Django. It's the only site I've done i18n on so it may or may not be the best approach, but just some ideas of how I was thinking about the problem.

**Comment by SalahAdDin** [comment] 2015-07-23 18:11
@tomdyson please man, help he :D

**Comment by Alp-Phone** [comment] 2015-07-24 11:13
@nek4life @GabLeRoux  I'd just like to put in my 10 cents for what it's worth. 
I've done a lot of multilingual work in Django (though not in Wagtail) and in my experience there is no one-size-fits-all translation paradigm.  Different CMS have different approaches that serve certain use cases well and others less so.
A common way to translate pages in Magnolia CMS for instance is to duplicate each and every page for every language similar how you would do it now in Wagtail.  Wagtail's approach is by no means an oddball approach.
I would encourage you to think about your translation needs and how you can adapt Wagtail to fit your needs.  
I've written Django backends that deal with up to 8 languages.  One way of effectively handling that many languages (that also scales well for a REST API for instance) is to have the page contain the non-translatable content and add translations as inlines.
I guess what I'm trying to say is that there is usually no drop-in solution that makes all your problems go away.  In my experience you always have to accept some trade-offs with regards to multilingual content, be it usability or scalability or what have you.

**Comment by Alp-Phone** [comment] 2015-07-24 11:25
@rmartins90 @tomdyson Yes I'd like be in the loop. I'm going to start coding on a new wagtail project in August. I might be able to help out.

**Comment by nek4life** [comment] 2015-07-24 12:14
@tomdyson @Alp-Phone Some more about the use case I'm considering using Wagtail for and the needs for translations. I'm looking into using Wagtail as the backend to supply the content for an E-Commerce platform. The E-Com platform has terrible content handling, so I would like to provide a better experience for content authors. For this particular project I would not be designing a front-end using Wagtail at all. I would be doing either one of three things. Exporting content as an xml feed. Pushing content to the other system using API's provided from the E-Com platform or potentially developing a REST API with Wagtail that we could pull content from depending on how well Wagtail can scale up. The content in the E-Com system ends up as one entity with translated fields so if we were to do separate pages we'd have to merge them back down somehow, so that is a big reason I would rather not use separate pages, although I'm sure we could find a work around if we had to. Just wanted to give some more insight into my particular use case.

**Comment by Alp-Phone** [comment] 2015-07-24 12:32
@nek4life How many languages do you support? Are you using StreamField?  if not, you could duplicate model fields with a language postfix.  That's not very elegant, but it gets the job done, i.e.: product_name_en, product_name_fr, product_name_it.

**Comment by nek4life** [comment] 2015-07-24 13:10
@Alp-Phone We're currently supporting 9 languages. That is definitely one approach to consider, perhaps there's even a way to store those fields in a separate tab when editing. It's definitely not elegant as you say, but it also doesn't require any joins. I've also set it up before with two tables one with the standard fields with a locale_id field and also another table with post_id and locale_id as the foreign keys along with the translation fields although that wasn't using Django and I wrote a custom admin for that.

**Comment by SalahAdDin** [comment] 2015-07-24 23:26
:+1:

**Comment by jorge-marques** [comment] 2015-07-28 10:39
:+1: Although two tables would incur a join, I would rather have a separate table for translations, similar to how [django-parler](https://github.com/edoburu/django-parler) does it. I'd like to avoid migrations when adding a new language.

**Comment by helderco** [comment] 2015-07-28 10:44
How about having a field for the language code, and another for a translation group? Then you could just add another record for the translation. You would group by the translation group id (tid), and get all records from the same table for each language.

**Comment by jorge-marques** [comment] 2015-07-28 10:58
@helderco I may be misunderstanding but wouldn't you end up with duplicate image fields?

**Comment by helderco** [comment] 2015-07-28 11:02
@jorge-marques yes, in order to do this, you would have only translated fields in this table and common fields in another, tied to the translation group.

**Comment by Alp-Phone** [comment] 2015-07-28 11:04
The django-parler approach (even though it seems quite clever) wouldn't work on Streamfield content, would it?

**Comment by Alp-Phone** [comment] 2015-07-28 12:34
Actually, I take that back.  Django-parler appears to have an exquisite design.  I think it could work with StreamField.

**Comment by keimlink** [comment] 2015-07-29 17:18
@rmartins90 Your integration of django-modeltranslation with Wagtail CMS looks very promising. Thanks for publishing your work! Have you thought about adding some tests to your app to make the functionality better testable?

**Comment by rmartins90** [comment] 2015-08-06 16:52
Hey. We've been very busy, sorry for the late reply.
We've just released a new version with support for StreamFields.
Until the next month we'll have no time to work on tests or anything to this app, however we'll be watching for any contributions or reports.

**Comment by kaedroho** [comment] 2015-08-21 10:12
I've just pushed some updates to the i18n docs to this PR #1630.

**Comment by SalahAdDin** [comment] 2015-08-21 20:35
wagtail-modeltranslation have many problems with migrations :(

**Comment by agelinas** [comment] 2015-08-21 20:53
SalahAdDin,

Just curious, are the migrations problems encountered for new projects or one where migrations have been done before implementing wagtail-modeltranslation?

My limited experience is that I had no problems using wagtail-modeltranslation in new projects. I do like using wagtail-modeltranslation and hope that the community can wrinkle out any problems it may have.

**Comment by SalahAdDin** [comment] 2015-08-22 00:26
The problem is when you migrate a project that haven't implemented wagtail-modeltranslation before.
I'm working in this project since wagtail 0.8.4 and i had tried implement modeltranslation and i have these problems.

**Comment by ratson** [comment] 2015-10-21 12:17
I am looking for a way to integrate [django-parler](https://github.com/edoburu/django-parler)` TranslatedFields` to Wagtail.

Does anyone have a success story about it?

**Comment by akhayyat** [comment] 2016-04-02 14:29
It's been a while since there were any updates on this issue. Any progress? Is there a plan to tackle it?

It'd be great to have built-in support for model translations. For one thing, multilingual websites would be able to upgrade to new wagtail releases without having to wait for third-party translation apps to support them.  

Although wagtail-modeltranslation did work with wagtail 1.3.1, it still [does not work with the later wagtail releases][1], and we have to upgrade due to critical-for-us features and fixes in these newer releases.

[1]: https://github.com/infoportugal/wagtail-modeltranslation/issues/72

**Comment by benebun** [comment] 2016-04-03 08:17
@akhayyat: As far as I know the current plan is to use translatable page models, should arrive in Wagtail 1.5 in April. So far I think there is no documentation yet, but there are two blog posts about the sprints where Torchbox & Co tackled this topic:
https://wagtail.io/blog/cape-town-retrospective/
http://www.springload.co.nz/blog/wagtail-cape-town-sprint/

In the first post Tom linked to the Takeflight's fork for the translation work:
https://github.com/takeflight/wagtail/tree/feature/page-translations

Not sure what that means for wagtail-modeltranslations though…

**Comment by timheap** [comment] 2016-04-04 02:50
Sorry everyone, I have been very slack about getting this translation work finished. I'll try and get some more polish on this, as well as tests and documentation when I can, but life has been hectic ever since I did the initial work, and life will not become calm again any time soon. I'll make an effort to work on this when ever I get a chance to do some Wagtail work though.

**Comment by JoshBarr** [comment] 2016-04-04 02:56
@timheap is there an RFC or spec that the wider Wagtail community could follow to help get it finished?

**Comment by benebun** [comment] 2016-04-04 08:38
Yes that would be helpful. We're just starting the next Wagtail project here, so maybe we can help.

**Comment by rmartins90** [comment] 2016-04-05 21:46
While Wagtail team don't release a version with support for multiple languages site we've just released an alpha version of wagtail-modeltranslation (0.5.0a) supporting Wagtail 1.4: https://github.com/infoportugal/wagtail-modeltranslation

**Comment by SalahAdDin** [comment] 2016-04-05 23:20
@rmartins90 , i support you, but, i think that you documentation are incomplete.

**Comment by akhayyat** [comment] 2016-05-04 09:18
Any updates on when to expect built-in translation support?

The blog posts:
https://wagtail.io/blog/cape-town-retrospective/
http://www.springload.co.nz/blog/wagtail-cape-town-sprint/
suggested that this should be available sometime in April. On the other hand, the repository where this development is supposedly taking place has not received any updates since February!
https://github.com/takeflight/wagtail/tree/feature/page-translations

**Comment by gasman** [comment] 2016-05-04 09:40
@akhayyat No updates right now. Work on this feature is currently dependent on volunteered time, which (as per @timheap's message above) is in short supply at the moment.

**Comment by akhayyat** [comment] 2016-05-04 16:06
@gasman How can we volunteer? Are there any specs?

**Comment by fdemmer** [comment] 2016-05-05 07:23
adding to what @akhayyat wrote: i looked over that sprint branch and there were a few exceptions right from the start, so it is hard to see what is supposed to be finished and what is actually part of translation or just ui changes (like the new button/language selector widget).

**Comment by gasman** [comment] 2016-05-09 09:34
There's now a draft spec for this feature at https://github.com/torchbox/wagtail-rfcs/pull/9 - feedback welcome.

**Comment by robmoorman** [comment] 2016-12-14 20:49
Please see if https://github.com/LUKKIEN/wagtailtrans fits your requirements, this should be a pretty good implemetation of the [wagtail/wagtail-rfcs#9](https://github.com/wagtail/wagtail-rfcs/pull/9) purposal

**Comment by SalahAdDin** [comment] 2016-12-17 16:19
@robmoorman is better than wagtail-modeltranslation?

**Comment by mikedingjan** [comment] 2016-12-19 08:07
@SalahAdDin, some advantages of wagtailtrans over wagtail-modeltranslation..

- No database migrations, in model translation you’ll get a extra column in your DB for every language / translatable field. With wagtailtrans there is a relation with a Language object, it will create a new page for the language.
- Separate Page trees per language, allows you to have a translator (role) per language
- With settings, languages / tree structures can differ per language.

**Comment by SalahAdDin** [comment] 2016-12-19 08:50
Sounds good, but, how manage this package the urls routers? Are there any way to manage all translations of a page in the same page? Changing between translations using some button or combo box?

**Comment by mikedingjan** [comment] 2016-12-19 09:20
@SalahAdDin URL routing is done via your page structure, it creates trees per language, where you can handle your urls yourself.. The `TranslatableSiteRootPage` makes sure the user gets redirected to the right language.. 

Managing all translations on one page isn't possible, since they're actually different pages. We can't assume that content is the same for all languages. All pages do have a relation with their `canonical` page (language),  so creating a link to other pages (languages) isn't that hard to do..

**Comment by SalahAdDin** [comment] 2016-12-20 16:17
@mikedingjan I understand all, but you din't to me, i mean, in the interface, not in the background, in the interface, is possible change between languages in the page? I'm explain me: You have root page, instead to have in the HUD three different page, one for each language, have the single page, go into this page and with a botton change between languages. Had i explained me?

**Comment by mikedingjan** [comment] 2016-12-20 16:22
I understand what you mean.. Short answer: No

**Comment by SalahAdDin** [comment] 2016-12-20 17:06
@mikedingjan Ok, Is easy make this way? By other i think this is a better alternative to moderltranslation, that now have many problems, and is not usable.

**Comment by rristow** [comment] 2017-06-29 14:38
@ratson - some news about the wagtail-parler integration? For me also seems to be the best approach.

**Comment by SalahAdDin** [comment] 2017-06-29 15:36
Yes, `wagtail-modeltrandlation` is super useless.

**Comment by kaedroho** [comment] 2017-06-29 20:28
@SalahAdDin please keep it constructive.

**Comment by SalahAdDin** [comment] 2017-11-10 14:13
@nifel87 same question here.

**Comment by dmarcelino** [comment] 2017-12-23 15:40
Hi everyone,

Wagtail is a great project which I've started using earlier this year. Ease of use, clean integration with Django and support for internationalisation (according to the [docs I read back then](http://docs.wagtail.io/en/v1.6.3/advanced_topics/i18n/index.html#translating-content)) were among the reasons that convinced me.

Fast-forward some 10 months, with lots of content created using Wagtail it came the time to translate it and suddenly we started hitting some `wagtail-modeltranslation` bugs. I've raised and fixed some issues (as you can see in https://github.com/infoportugal/wagtail-modeltranslation/issues?utf8=%E2%9C%93&q=author%3Admarcelino+) and was invited as a project collaborator (thanks @DiogoMarques29!).

For the project I'm working on good i18n support is key and since we are committed to Wagtail I'm willing to spend more time until the end of the year looking to improve `wagtail-modeltranslation` as best as I can. After looking at the different alternatives for translating Django ([django-modeltranslation](https://github.com/deschler/django-modeltranslation), [django-hvad](https://github.com/KristianOellegaard/django-hvad) and [django-parler](https://github.com/django-parler/django-parler)) `django-modeltranslation` is still my favourite approach (mostly because the translation fields live in the same tables as the original ones) hence I believe `wagtail-modeltranslation` is the best bet for translating Wagtail.

Having said all this, I think `wagtail-modeltranslation` needs some breaking changes and I've created a POC outlining them on https://github.com/infoportugal/wagtail-modeltranslation/pull/150. I'd appreciate if @kaedroho and @gasman could look at the POC and give some feedback. I'll try to accommodate your opinions as best as I can since `wagtail-modeltranslation` should align with Wagtail.

If we combine our efforts I'm sure we can give Wagtail the i18n support it deserves.

Thanks and Merry Xmas!

**Comment by mikedingjan** [comment] 2017-12-25 11:02
Hi @dmarcelino ,

Did you ever take a look al [wagtailtrans](https://github.com/LUKKIEN/wagtailtrans), I personally like that approach better because, as you said, translations live in the same table as the original ones. But even better, adding a new language doesn't involve migrating you complete database. It also allows you to have different page structures per language (if you want)..

I'm not a big fan of monkeypatching Wagtail for adding translations, as you've done in your PR with adding the title_xx and slug_xx to the Page table. This because changes in for example wagtail can break the functionality. 

Having said all that, I don't think there is a holy grail for good i18n support, since there are a lot of different ways of doing that and everybody has their own preference.

One thing I would like for wagtail is a "easier" way of integrating i18n support, perhaps we can have a discussion about that after the holidays? Packages as ``wagtail-personalisation`` and ``wagtail-experiments`` could really benefit from this as well.

Happy Holidays!

**Comment by SalahAdDin** [comment] 2017-12-25 14:23
@mikedingjan Personally i did try to use these package and `wagtail-modeltranslation`, and both have a terrible performance with last versions. I tried with the other package, it was better but still it doesn't represent a ideal option.

**Comment by mikedingjan** [comment] 2017-12-25 18:48
Performance shouldn’t be less with wagtailtrans, since it doesn’t change anything to wagtails way of selecting / showing pages, etc. If you really encounter heavy performance issues I would rather think you’ve configured something wrong..

Can you provide a detailed report of the issues you encounter? Also include your configuration. If I can reproduce it I (we) can have a look at it and maybe resolve the issues..

**Comment by dmarcelino** [comment] 2017-12-25 23:23
Hi @mikedingjan, thanks for your feedback.

Yes, I looked at `wagtailtrans` and browsed through the docs, I did not install it though. Correct me if I'm wrong but my understanding is that `wagtailtrans` duplicates pages and all their fields without an option to translate specific fields only. For example, if there is an `Event` model with `date` and `body` it would be up to the translator to keep `date` in sync across languages if it were to change, right? In my project I have Wagtail models which only require partial translation.

The apps I've mentioned, including `django-modeltranslation`, allow the developer to choose which fields to translate and only those require any translator intervention. `django-modeltranslation` also has nice fallback settings where a missing language for a field can be replaced by another. For example, Brazilian Portuguese can fallback to European Portuguese and finally to English. This can be configured on a general basis or on field-by-field basis.

I confess I'm not a fan of monkey patching either, it was kind of *last resort*. If Wagtail supported [swappable models](https://github.com/wq/django-swappable-models) things would become much simpler. Having said this, I believe patching `Page` to be a calculated risk, it's not likely that Wagtail authors will add `slug_xx`, `title_xx`, `etc_xx` fields to `Page` unless they are adding their own i18n app (which would fix all our issues 🙂).

I wholly agree Wagtail should be easier to add i18n to, perhaps https://github.com/wagtail/wagtail/issues/3282 can be a way to reach that goal.

@SalahAdDin, https://github.com/infoportugal/wagtail-modeltranslation/pull/150 will enable the removal of most (perhaps all) calls to `Page.specific` and that should improve performance significantly.

Happy New Year!

**Comment by MechanisM** [comment] 2017-12-27 07:53
It is possible to add support for [django-nece](https://github.com/tatterdemalion/django-nece) and [django-modeltrans](https://github.com/zostera/django-modeltrans) as well? These apps for PostgreSQL only, but so awesome.

**Comment by mikedingjan** [comment] 2017-12-27 08:51
@dmarcelino Partial translation isn't something that's supported by ``wagtailtrans`` indeed, however it shouldn't be to hard to implement yourself. For example with syncing "some" fields upon save, each page keeps a relation to it's translations, which makes that easy.

I've looked at swappable models as well, will solve a lot of use cases but will also bring more risk of breaking things.


@MechanisM Wagtail supports more than only PostgreSQL so adding support for something that only woks with PostgreSQL isn't something that's likely going to happen. If you want to use those packages with Wagtail, you can create your own "Wagtail" add-on.

**Comment by dmarcelino** [comment] 2017-12-27 10:59
@mikedingjan, I would certainly do that if I had no alternative but I see 2 issues with that approach:

1. Not very DRY: fields like images, names, dates, addresses, etc will be repeated for each language;
2. I don't think the user of a translation app should have the burden to override Wagtail's `save` to achieve this. The translation app should handle this scenario seamlessly, requiring only the appropriate configuration (perhaps you can look at it as a feature suggestion for `wagtailtrans`).

**Comment by dmarcelino** [comment] 2018-02-05 15:38
Hi everyone,

Since my initial [comment from December](https://github.com/wagtail/wagtail/issues/96#issuecomment-353732699) my POC has been accepted into [wagtail-modeltranslation](https://github.com/infoportugal/wagtail-modeltranslation), merged to the main code and version `0.8` has been released. Besides the actual changes proposed by me, we also added more tests, squashed a few bugs and improved the documentation. All in all `wagtail-modeltranslation` looks better now. If you can try it out I'd love to hear some feedback!

@kaedroho, @gasman, the latest version of `wagtail-modeltranslation` patches Wagtail's `Page` model with translation fields `title_xx`, `slug_xx`, `seo_title_xx`, `search_description_xx` and `url_path_xx` where "xx" represents the language code for each translated language. Do you foresee this being a problem in the future? I mean, do you think Wagtail will create fields with conflicting names?

**Comment by nifel87** [comment] 2018-02-06 10:38
Hi, very good work. I think I will use it in my next work. 
I tried it in one of my test site and it's based on a good idea. But I found a little problem about the UI department. If I have a page with 4 languages and 10 fields the total amount of fields on the single page will be 40. It's a little bit hard to compile 40 fields in a single page, a normal user will freak out. I think I would be great grouping all fields by language in tabs. What do you think?

Something like this:
![schermata 2018-02-06 alle 11 40 55](https://user-images.githubusercontent.com/33495308/35854970-28349e38-0b32-11e8-917a-949e240f94d3.png)

**Comment by dmarcelino** [comment] 2018-02-06 14:41
Hey @nifel87,

Thanks.

I agree, `django-modeltranslation` itself implements a tabbed interface for Django's admin ([docs](http://django-modeltranslation.readthedocs.io/en/latest/admin.html#using-tabbed-translation-fields)). It would be a great feature to implement in `wagtail-modeltranslation`. All work I've done has been on the internals so I'm not sure how much work that would entail. It's not something I can work on at the moment but it's certainly has my thumbs up! I would be happy to review any PR for such functionality.

**Comment by SalahAdDin** [comment] 2018-02-06 16:06
@dmarcelino are there any way of group fields by a regex suffix work?

**Comment by dmarcelino** [comment] 2018-02-15 11:39
@SalahAdDin, not one that I'm aware of.

**Comment by onasipim** [comment] 2019-11-08 10:53
Any update on this? I like the proposition by dmarcelino to integrate the tabbed interface to wagtail-modeltranslation. This way we would come very close to a true, easy to use multilingual feature in Wagtail

**Comment by kaedroho** [comment] 2019-11-08 11:50
I've recently been working on a new library to add translation/localisation support into Wagtail, current progress is in https://github.com/kaedroho/wagtail-localize (this will be moved to wagtail org when I've finished the docs).

It uses a different approach to `wagtail-modeltranslation` in that you translate content using separate pages for each language instead of separate fields.

This has some benefits over the multi-field approach:

 - Translations can be published at different times and be in different states
 - Content can be authored in any language
 - It doesn't require any magic to insert fields into models
 - Page slugs can also be translated
 - The pages are all linked at the database level so language-switching works well in both the editor and the frontend

Wagtail localize also supports:
 - Integrating with external translation engines (Pontoon, Google translate) and translation using PO files
 - Localization (you can tailor content to target at a specific region without having to set up new languages)
 - Translation of non-page models such as images and snippets

I'm also planning on doing some changes to Wagtail itself to make URL building, search, and the API aware of languages.

**Comment by onasipim** [comment] 2019-11-08 12:17
Wow, exactly what I hopped for! Your approach seems indeed much better. Looking forward when all this gets directly integrated and/or supported with the rest of Wagtail so that we have one, golden standard for multilingual sites. Thanks for your work.

**Comment by MechanisM** [comment] 2019-11-08 18:25
For content translation, I think the best options are: https://github.com/tatterdemalion/django-nece and https://github.com/zostera/django-modeltrans - it utilizes PostgreSQL's JSONB field, but something like this can be done for other databases too.

**Comment by ceelian** [comment] 2020-05-12 05:25
@kaedroho what are the advantages/differences of watail-localize to wagtailtrans?

**Comment by kaedroho** [comment] 2020-05-18 10:50
They both follow the same general approach by separating different languages into different page trees so they both have the same advantages/disadvantages when compared against `wagtail-modeltranslation`.

`wagtailtrans` has been around longer than `wagtail-localize`, is used more widely and is currently much better documented. So if you're looking to add internationalisation to a site right now, I'd definitely use `wagtailtrans` over `wagtail-localize` unless you really need one of the extra features `wagtail-localize` provides.

The advantages of `wagtail-localize` over `wagtailtrans` are:

 - It uses mixins instead of a separate page class, this makes it much easier to implement it on an existing site and also allows translations of non-pages such as snippets and images
 - It doesn't have a "default" language so content can be authored in any language and translated into any other
 - It allows you to configure which fields should be translated and which fields should be kept in sync with the original page
 - It has an optional "translation" module that allows translation to be done with an external system. Currently Google Translate, .po files and Mozilla Pontoon are supported. This module also provides translation memory as well.
 - It has an optional "workflow" module that provides UI that allows Editors to submit pages to Translators within Wagtail for translation
 - Currently working on an "incremental translation" feature that allows a language tree to contain both translated and untranslated content

Even though `wagtail-localize` is newer than `wagtailtrans`, it's not a replacement and we plan to support both. `wagtail-localize` was created as a separate project because we couldn't find a way to easily migrate existing `wagtailtrans` sites to the new models.

**Comment by ceelian** [comment] 2020-05-19 13:58
Thx @kaedroho  a lot for that detailed comparison! So it looks like that wagtail-localize is the future. Really like the features and some of them I already miss in wagtailtrans.

**Comment by kaedroho** [comment] 2020-07-08 11:36
I've created an RFC for adding internationalisation features to Wagtail core:

 - [View the rendered document here](https://github.com/wagtail/rfcs/blob/internationalisation/text/054-internationalisation.md)
 - [Please add any feedback to the PR here](https://github.com/wagtail/rfcs/pull/54)

**Comment by gasman** [comment] 2020-11-04 22:39
With the [multi-language support in 2.11](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#multi-language-content) and the release of [wagtail-localize 0.9](https://github.com/wagtail/wagtail-localize), I think we can finally declare this done!

**Closed by gasman** 2020-11-04 22:39 UTC
Labels: component:i18n, type:Enhancement
