### ISSUE TITLE
Orderable CSS bug in admin

### ISSUE THREAD

**Issue by ladrua** [wagtail/wagtail#4886] opened 2018-11-05 22:24 UTC
![bilde](https://user-images.githubusercontent.com/1674550/48030520-9d275000-e151-11e8-9686-a438e6b8a905.png)
When `Orderable` model with `ParentalKey` and when there are non added It seems like there is a bug with the div height.

Wagtail 2.3 - Django 2.1.3

**Comment by ladrua** [comment] 2018-11-08 23:42
```
class Link(models.Model):
    link = models.ForeignKey(
    'wagtailcore.Page',
    null=True,
    blank=True,
    on_delete=models.SET_NULL,
    related_name='+',
    )
    title = models.CharField("Title", max_length=255, blank=True)

    panels = [
    PageChooserPanel('link'),
    FieldPanel('title', classname="col6"),
    ]

    class Meta:
        abstract = True

class Links(Orderable, Link):
    page = ParentalKey(SitePage, related_name='links')

class SitePage(Page):
    body = RichTextField(blank=True)
    content_panels = Page.content_panels + [
    FieldPanel('body', classname="full"),
    InlinePanel('links', label="Links"),
    ]
```
**OS:** macOS 
**Browser:** Firefox 63.0.1, Safari 11.0.2

**Comment by ladrua** [comment] 2018-11-09 00:10
If I put the `InlinePanel` inside a `MultiFieldPanel`
```
       MultiFieldPanel(
            [
                InlinePanel('links', label="Links"),
            ],heading="Links",
            classname=None
        ),
```
It looks like this:
<img width="341" alt="bilde" src="https://user-images.githubusercontent.com/1674550/48234923-f397c700-e3bb-11e8-80cd-07bb160c1b79.png">

Thats better in many ways I think, but unclear to me if that is a requirement for a `InlinePanel`

**Comment by gasman** [comment] 2018-11-09 16:36
Afraid I can't reproduce this as described - perhaps you have some custom CSS or a third-party add-on in your project that's causing this?

Here are the steps I tried:

    mkvirtualenv orderablecss
    pip install wagtail==2.3 Django==2.1.3
    wagtail start orderablecss
    cd orderablecss

Update home/models.py to include the Links / SitePage definition:

    from django.db import models

    from wagtail.core.models import Page, Orderable
    from wagtail.core.fields import RichTextField
    from wagtail.admin.edit_handlers import PageChooserPanel, FieldPanel, InlinePanel

    from modelcluster.fields import ParentalKey


    class HomePage(Page):
        pass


    class Link(models.Model):
        link = models.ForeignKey(
            'wagtailcore.Page',
            null=True,
            blank=True,
            on_delete=models.SET_NULL,
            related_name='+',
        )
        title = models.CharField("Title", max_length=255, blank=True)

        panels = [
            PageChooserPanel('link'),
            FieldPanel('title', classname="col6"),
        ]

        class Meta:
            abstract = True


    class SitePage(Page):
        body = RichTextField(blank=True)
        content_panels = Page.content_panels + [
            FieldPanel('body', classname="full"),
            InlinePanel('links', label="Links"),
        ]


    class Links(Orderable, Link):
        page = ParentalKey(SitePage, related_name='links')

Run:

    ./manage.py makemigrations
    ./manage.py migrate
    ./manage.py createsuperuser
    ./manage.py runserver 0:8000

Log in to http://localhost:8000/admin/ in Firefox 63.0.1 and add a Site page as a child of the homepage - the Links section renders as expected:

<img width="1272" alt="screen shot 2018-11-09 at 16 35 01" src="https://user-images.githubusercontent.com/85097/48275501-89276b00-e43d-11e8-9c4f-4bca6684f2f8.png">

Will close this for now, but happy to reopen if you can provide steps for reproducing this.

**Closed by gasman** 2018-11-09 16:36 UTC
Labels: component:Frontend, status:Needs info, type:Bug
