### ISSUE TITLE
Switching between admin pages flickering only in Chrome

### ISSUE THREAD

**Issue by robvdl** [wagtail/wagtail#2467] opened 2016-04-09 21:49 UTC
I am noticing that when I am using Chrome and switching between pages in the wagtail admin causes flicker while the new page is rendering, a blank white page is briefly visible, this gets quite distracting.

However, using Firefox on the same machine is fine and does not experience render flicker, I am only experiencing this issue in Chrome.

**Comment by maartenkling** [comment] 2017-03-22 18:46
Cannot reproduce in Version 57.0.2987.98 (64-bit).

**Comment by robvdl** [comment] 2017-03-22 19:02
@maartenkling This issue is almost a year old now, for all I know it may have been an issue with the version of Chrome a year ago and it may well be fixed now.  I haven't re-tested this because I haven't used wagtail for a while.

**Comment by robmoorman** [comment] 2017-03-22 19:15
Thanks for testing @maartenkling and @robvdl. Did some more testing myself on several Chrome versions, seems like I can't reproduce this flickering either. For now we close this ticket, may it appear again, please re-open and let us now!

**Closed by robmoorman** 2017-03-22 19:15 UTC
Labels: component:Frontend
