### ISSUE TITLE
AttributeError: 'BlockWidget' object has no attribute '_block_json'

### ISSUE THREAD

**Issue by robmoorman** [wagtail/wagtail#11702] opened 2024-02-28 08:44 UTC
### Issue Summary

After migrating StreamField data, rendering StreamField's in JS causing the error `AttributeError: 'BlockWidget' object has no attribute '_block_json'`.

What we had is a nested StreamField structure:
```
[
    ("content", StreamBlock([
        ("text", TextBlock()),
    ])),
]
```

We migrated all bock to a flat list of SteamFields, like:
```
[
    ("text", TextBlock()),
]
```

Rendering the templates on the frontend still ok. All good. Data seems legit. Only rendering the StreamFields in the CMS causes this error.

Very hard to point out what this issue is causing. Trying to reproduce this with same dependencies, architecture, database backup etc., but no luck so far.

Reading in our community platforms this issue seems quite rare.

### Full stack trace

```
AttributeError: 'BlockWidget' object has no attribute '_block_json'
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "wagtail/admin/auth.py", line 184, in overridden_render
    return render()
  File "django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 175, in render
    return self._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "django/template/base.py", line 914, in _resolve_lookup
    current = current()
  File "wagtail/admin/panels/base.py", line 317, in render_form_content
    return mark_safe(self.render_html() + self.render_missing_fields())
  File "wagtail/admin/ui/components.py", line 22, in render_html
    return template.render(context_data)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 175, in render
    return self._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "django/template/base.py", line 914, in _resolve_lookup
    current = current()
  File "wagtail/admin/ui/components.py", line 22, in render_html
    return template.render(context_data)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 175, in render
    return self._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "wagtail/admin/templatetags/wagtailadmin_tags.py", line 1185, in render
    children = self.nodelist.render(context) if self.nodelist else ""
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "wagtail/admin/templatetags/wagtailadmin_tags.py", line 1051, in render
    html = component.render_html(context)
  File "wagtail/admin/ui/components.py", line 17, in render_html
    context_data = self.get_context_data(parent_context)
  File "wagtail/admin/panels/field_panel.py", line 274, in get_context_data
    context.update(self.get_editable_context_data())
  File "wagtail/admin/panels/field_panel.py", line 317, in get_editable_context_data
    rendered_field = self.bound_field.as_widget(attrs=widget_attrs)
  File "django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
  File "wagtail/blocks/base.py", line 583, in render
    return self.render_with_errors(
  File "wagtail/blocks/base.py", line 577, in render_with_errors
    block_json=self.block_json,
  File "wagtail/blocks/base.py", line 552, in block_json
    return self._block_json
```

### Steps to Reproduce

- Until now this issue only applies on our production environment, unable to reproduce this with locally

### Technical details

-   Python version: 3.10.13 (did also apply on other python version)
-   Django version: django==4.2.7
-   Wagtail version: wagtail==5.2.3
-   Browser version: Chrome (applies on every browser)

### Working on this

- Running locally with a backup did not cause this issue strange enough (maybe the json structure of a streamfield was invalid after migration...)
- Enabling/flushing/disabling cache (redis) no impact

**Comment by gasman** [comment] 2024-02-28 10:39
When we've seen this in the past, it's been caused by people having custom block classes (possibly subclasses of ChooserBlock in particular) that hooked into Wagtail internal APIs that have now been changed. For example, it affected older versions of wagtail-streamforms:

https://github.com/labd/wagtailstreamforms/commit/10a599aaebde71293b999e83f4d96e06eaf5d931
https://github.com/labd/wagtailstreamforms/issues/200

Will close this for now, as there's not really much we can do on Wagtail's side without a reproducible test case.

**Closed by gasman** 2024-02-28 10:39 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by robmoorman** [comment] 2024-02-28 10:50
He @gasman ok thanks, we do have a custom streamfield in which blocks can be switched on/off based on settings. However this has been working for over the past versions. I'll dive into this and post my findings here.

**Comment by robmoorman** [comment] 2024-03-12 20:59
Found the issue. When a SnippetChooserBlock is in use but a Snippet viewset (new snippet features) is not enabled (in my case due a setting) you will get conflicts.

**Comment by lukasvonallmensmartfactory** [comment] 2024-06-12 11:26
We encountered the same exception `AttributeError: 'BlockWidget' object has no attribute '_block_json'` after removing some models and their related blocks. We had to run the following command: `python manage.py remove_stale_contenttypes`

IDK if it's related in any way but maybe it helps someone else enncountering this exception.

**Comment by gasman** [comment] 2024-06-12 12:22
When I last looked into this, `'BlockWidget' object has no attribute '_block_json'` happens because the code in BlockWidget assumes that [`_js_context` and `_block_json` are always defined together](https://github.com/wagtail/wagtail/blob/0bea099ab860128cfab8bebb7e0c40a35d0a377a/wagtail/blocks/base.py#L548-L550) - you never get one without the other. However, it seems that the code that calls this often has an unreasonably broad try/catch around it, so if an error occurs during the `self._js_context.pack` process, it gets swallowed up, resulting in a BlockWidget with broken internal state. As a result, there's probably a wide range of errors in the general category of "passing unexpected values as part of a StreamField definition when passing it off to front-end code" which is masked by this error.

**Comment by catilgan-nextension** [comment] 2024-06-20 11:58
@gasman Your last comment helped me to resolve my issue with same error message. 

Indeed, the `self._js_context.pack` process was throwing an error. In my case, the `snippet_viewset` of my snippet model was missing.

Registering a viewset in `wagtail_hooks.py` helped me to resolve the issue:

```python
class MyModelViewSet(SnippetViewSet):
    model = MyModel
    
model_viewset = MyModelViewSet()

@hooks.register("register_admin_viewset")
def register_viewset():
    return model_viewset
```

So, it's indeed not a framework error - but i would be nice, if the errors are caught and a sensible message is displayed to the user.
