### ISSUE TITLE
layout bug revisions screen admin

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#10066] opened 2023-02-13 12:22 UTC
### Issue Summary
On any screen size I go to the revisions. I notice that not everything fits on the screen (see screenshot). The filter column has not enough room to show the full select field.
On the body there is css has **overflow-x: hidden**. the screen is also not sideways scrollable. I'm not sure that is good practice. Better imho is this is not needed the containing elements are adapted to the width the containing elements.

![screen](https://user-images.githubusercontent.com/178425/218456610-c5584265-19bc-4b89-b19b-c516d41fc699.png)

**Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?**
I expect that the fields are adapted to the width of the container and don't enforce a width.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
-   Wagtail version: 4.2
-   Browser version: Chorme latests

**Comment by laymonage** [comment] 2023-02-13 12:25
Thanks for the report, this looks like a duplicate of #9480.

**Closed by laymonage** 2023-02-13 12:25 UTC
Labels: type:Bug, status:Unconfirmed
