### ISSUE TITLE
Comment Spanning Outside Container in Blog Page

### ISSUE THREAD

**Issue by codewithmide** [wagtail/wagtail#11048] opened 2023-10-14 18:05 UTC
### Pertinent section of the Wagtail blog:

![comment](https://github.com/wagtail/wagtail/assets/81376427/0e49187e-2e48-4436-b375-a022cfaaa3bb)

### Issue Summary

I've identified an issue in the comment section of the blog page, where users encounter a problem when entering a lengthy comment. When a user submits a comment with a significant amount of text, the comment extends beyond the confines of its container. As a result, only a portion of the comment is visible, and the rest is hidden from view.

This issue affects the user experience and readability of comments on the blog page, potentially leading to confusion and frustration among users. It's essential to address this problem to ensure that comments are fully accessible and legible for all users.

### Steps to Reproduce

1. Follow the [Your first Wagtail site](https://docs.wagtail.org/en/stable/getting_started/tutorial.html) tutorial
2. Go to the admin dashboard [http://127.0.0.1:8000/admin/](http://127.0.0.1:8000/admin/)
3. Create a blog
4. Edit a blog
5. Add a comment to the blog

## Proposed Solution:

To rectify this issue, I propose implementing a solution that adjusts the comment container's layout dynamically to accommodate longer comments. This would ensure that comments are fully visible and do not span outside their designated area.

- [x] I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Python 3.9.13
-   Django version: Django>=4.2,<4.3
-   Wagtail version: 5.1.2
-   Browser version: Brave.

**Comment by Chiemezuo** [comment] 2023-10-14 22:05
I tried following along with your steps to reproduce, but didn't see a section for putting in any comments in mine.
Could there be anything else you did that you may have forgotten to mention, so I could try it out and see if I can reproduce the bug?

This is what my own screen looks like:
![image](https://github.com/wagtail/wagtail/assets/29470516/679630f6-e0d6-40bd-8068-e02ded08a76d)

**Comment by codewithmide** [comment] 2023-10-14 22:14
Hover over any of the sections of the blog. A comment icon will pop up, click on it

**Comment by Chiemezuo** [comment] 2023-10-14 22:42
@codewithmide Thank you. Your suggestion worked like a charm. I also observed the bug.

**Comment by Chiemezuo** [comment] 2023-10-14 23:51
@lb- I've found a fix for this issue. In my browser, I inspected the comment box (more specifically, the `comment__text` class attributes) and discovered that the overflow needs to be set to hidden. I did this and the problem was solved. However, I don't know which scss file contains what needs to be edited.

**Comment by lb-** [comment] 2023-10-15 00:12
I think it's a bit of an edge case for a single comment to have a word longer than ~30 ish characters. 

Nonetheless we may want to consider `word-break; break-all;`. 

 https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#break-all

**Comment by Chiemezuo** [comment] 2023-10-15 00:15
That works. I'll give it a go and let you know.

**Comment by codewithmide** [comment] 2023-10-15 06:22
Oh great @Chiemezuo I intend on working on this before. But go for it😅

**Comment by Chiemezuo** [comment] 2023-10-15 06:29
Thanks a lot, man. 😅
Also, credit to your spotting the issue.

**Closed** 2023-10-17 10:16 UTC
Labels: type:Bug, component:Commenting
