### ISSUE TITLE
Scrolling beyond viewport in Firefox

### ISSUE THREAD

**Issue by RealOrangeOne** [wagtail/wagtail#10622] opened 2023-06-30 08:10 UTC
### Issue Summary

Potentially related to #8664, when scrolling in Firefox (all extensions disabled) on the page editor, when you reach the bottom of the page, if you keep scrolling the viewport keeps getting bigger, letting you scroll forever. If you scroll back up, the height is reset correctly.

![Peek 2023-06-30 09-07](https://github.com/wagtail/wagtail/assets/6527489/9523e6e0-3dbd-4d60-a788-4aa9c94bc640)

### Steps to Reproduce

1. Be in Firefox
2. Edit a page
3. Scroll down to the bottom, and then keep scrolling. Most noticeable when using an un-ratcheted scroll wheel.

### Technical details

-   Python version: N/A
-   Django version: N/A.
-   Wagtail version: Confirmed on 4.1, 4.2 and 5.0.
-   Browser version: Firefox 114 / 115 on Linux.

**Comment by lb-** [comment] 2023-06-30 09:42
I'd say this is a duplicate of https://github.com/wagtail/wagtail/issues/8664

**Comment by laymonage** [comment] 2023-06-30 09:48
Yeah I agree, the screenshot in the issue is from pre-4.0 but I think it's the same problem discussed further there. Closing as duplicate.

**Closed by laymonage** 2023-06-30 09:48 UTC
Labels: type:Bug, status:Unconfirmed
