### ISSUE TITLE
GroupApprovalTask email notifications go to inactive users

### ISSUE THREAD

**Issue by bwilliams3** [wagtail/wagtail#7506] opened 2021-09-08 20:05 UTC
Hello -- I'm not sure if this was by design, but our desired behavior would be that inactive users do not receive any email notifications from Wagtail. If the appropriate fix is as simple as updating the query below, I can submit a PR:

https://github.com/wagtail/wagtail/blob/cee245e7015b8462f2aa921e42803cd7d0962b8b/wagtail/admin/mail.py#L364

**Comment by gasman** [comment] 2021-09-09 15:42
Hi @bwilliams3 - thanks for the report. Yes, I think the intended behaviour would be to leave inactive users out of the notifications.

One thing to be careful of here is that we need to support [custom user models](https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_user_models.html), and in their most basic form (inheriting from Django's AbstractBaseUser rather than AbstractUser) `is_active` could just be a plain boolean attribute rather than a database field - in these cases, including it in a `filter` clause wouldn't work. I think the preferred fix would be to add a `recipient.is_active` check here:

https://github.com/wagtail/wagtail/blob/cee245e7015b8462f2aa921e42803cd7d0962b8b/wagtail/admin/mail.py#L87

The PR will also need a unit test to confirm that this is working as expected (and help us to spot it being inadvertently broken in any future development) - it would probably be [something like this one](https://github.com/wagtail/wagtail/blob/cee245e7015b8462f2aa921e42803cd7d0962b8b/wagtail/admin/tests/test_workflows.py#L1320-L1333), but rather than setting the user's `approved_notifications` field, set them to inactive and confirm that the email doesn't get sent.

**Comment by bwilliams3** [comment] 2021-09-10 17:52
@gasman Thanks for that context and direction. I realized that the `def send_notification` function is related to comment subscribers and the workflow/task notifications are generated from `class EmailNotificationMixin`, so I added that `is_active` check and created unit tests for each in #7510. If you'd prefer a different approach, let me know.

**Comment by lb-** [comment] 2021-09-11 04:18
Fixed via #7510 & fb4a5a6961c20ab9d0b2bdd0aa8374af9d61cb2d

**Closed** 2021-09-13 10:12 UTC
Labels: type:Bug
