### ISSUE TITLE
Image and Document summary items can't be removed

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6160] opened 2020-06-18 13:06 UTC
### Issue Summary

It is impossible to remove 'image' and 'document' summary items. Only 'pages' can be removed.

> Add or **remove** items from the ‘site summary’ bar on the admin homepage (which shows the number of pages and other object that exist on the site). 

https://docs.wagtail.io/en/stable/reference/hooks.html#construct-homepage-summary-items

This question https://stackoverflow.com/questions/62403914/wagtail-how-to-remove-summary-items-on-the-admin-homepage/62438671?noredirect=1#comment110440074_62438671 triggered me to look into this issue.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit wagtail_hooks.py

```
from wagtail.core import hooks

@hooks.register("construct_homepage_summary_items")
def remove_all_summary_items(request, items):
    items.clear()
```
This should remove all items. Yet image and document are still visible.

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project. Latest Python, Django and Wagtail.

### What goes wrong

The order that hooks are executed matters. Documents and images hooks are executed and therefore can't be removed as the are not in `items` yet.

A hack/workaround is to put `'wagtail.documents'` and  `'wagtail.images'` at the top of installed apps.

A possible solution is to move document and image register to `wagtail/admin/site_summary.py`

```
@hooks.register('construct_homepage_summary_items')
def add_pages_summary_item(request, items):
    items.append(PagesSummaryItem(request))


@hooks.register('construct_homepage_summary_items')
def add_documents_summary_item(request, items):
    from wagtail.documents.wagtail_hooks import DocumentsSummaryItem  # noqa
    items.append(DocumentsSummaryItem(request))


@hooks.register('construct_homepage_summary_items')
def add_images_summary_item(request, items):
    from wagtail.images.wagtail_hooks import ImagesSummaryItem  # noqa
    items.append(ImagesSummaryItem(request))
```
Note the imports are in the methods to prevent circular import.

**Comment by gasman** [comment] 2020-06-18 13:25
> A hack/workaround is to put 'wagtail.documents' and 'wagtail.images' at the top of installed apps.

This is intended behaviour, not a hack. The order of execution can be controlled by passing an `order` argument to `hooks.register`, as documented at https://docs.wagtail.io/en/stable/reference/hooks.html; if order is not specified then they proceed in the order given by INSTALLED_APPS. We should document this latter point (and mention the fact that hooks are used internally by Wagtail too, so you need to be aware of order when overriding built-in Wagtail functionality).

**Comment by allcaps** [comment] 2020-06-18 15:05
I don't get why page item is registered before and images and documents after my item. As my apps come before Wagtail. So you'd expect all Wagtail before.

If the hooks respect the order of installed apps, then they should begin at the bottom and work to the top. As you need your own packages at the top (or that is the default thing to do if you want to customise anything else).

In the SO answer I adviced to create a separate app for hooks and place that at the bottom of installed apps.

**Comment by gasman** [comment] 2020-06-18 15:36
> I don't get why page item is registered before and images and documents after my item. As my apps come before Wagtail. So you'd expect all Wagtail before.

I suspect that's because the relevant `hooks.register` block is in site_summary.py:
https://github.com/wagtail/wagtail/blob/ce6b2fe97b6fada507741c6221493c6d4759afe8/wagtail/admin/site_summary.py#L62-L64

This means it's being registered while the server is starting up, rather than the point where wagtail.core.hooks loops over the apps (which would place it in the correct INSTALLED_APPS ordering). I'd be happy to accept a PR that moves it into wagtail/admin/wagtail_hooks.py.

> If the hooks respect the order of installed apps, then they should begin at the bottom and work to the top. As you need your own packages at the top (or that is the default thing to do if you want to customise anything else).

I don't think you can make a general statement like that. Placing customisations at the top is appropriate when the code being customised works by the logic "use the first matching rule that you find", like URL patterns, template overrides, or hooks like `before_create_page` that have the ability to cancel the subsequent processing. Placing customisations at the bottom is appropriate when the code being customised works by the logic "apply all matching rules in turn", like this hook, inserting JS includes, and registering rich text features.

**Comment by gasman** [comment] 2020-06-25 14:29
Closing as this is working as designed, and the points arising from this are now covered by #6161 and #6179.

**Closed by gasman** 2020-06-25 14:29 UTC
Labels: Documentation
