### ISSUE TITLE
Filter sidebar overlaps content table in Admin UI

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#10627] opened 2023-07-03 19:06 UTC
The Wagtail Admin filter sidebar overlaps the content table when managing content types with many fields on medium display width.

<img width="1260" alt="Screenshot 2023-07-03 at 22 02 32" src="https://github.com/wagtail/wagtail/assets/17307/742c447e-94b0-4cb8-a322-cbb0c3468e6d">

### Steps to Reproduce

1. Start a project and define a content model with 5-10 fields
2. Register that content type with the Wagtail Admin
3. Include one or more filter definitions when registering the content type
4. View the Wagtail Admin on a medium-width display, such as a tablet

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.x
-   Wagtail version: 5.x
-   Browser version: various browsers

**Comment by YashTote** [comment] 2023-07-08 12:49
@brylie Is there any part of Wagtail Docs where it is defined how to add Filter definitions? It would be a great help.

**Comment by brylie** [comment] 2023-07-08 13:29
The ModelAdmin docs describe many customization options, including the `list_filter` property:

https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/indexview.html#id3

**Comment by YashTote** [comment] 2023-07-10 11:38
As is reproduced the issue, I found out that this error surfaces when the number of field columns are increased or width of screen is changed.What is the solution that you would like to implement?  These are the possible solutions:
1. Change the position of the filter entirely so that it will never overlap the Field Columns.
2. Change the responsive behavior of SCSS with '@media'.
3. Something different.

**Comment by gasman** [comment] 2023-07-10 11:56
On #10446 you can find designs for an updated version of Wagtail's listing views, which we're planning to implement over the next couple of releases. These designs address this issue by placing the filters above the listing.

The new designs will be in place for the page and snippet listings - as per https://github.com/wagtail/rfcs/pull/85, the plan is for snippets to entirely take over the role of modeladmin. So, while it's unlikely that we'll be revisiting the modeladmin template layout at this point, the move towards snippets along with the universal listings redesign will fully address this.

As such, I'll close this as a duplicate of those existing tickets. Thanks for the feedback!

**Closed by gasman** 2023-07-10 11:56 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by YashTote** [comment] 2023-07-11 09:55
Are the contributions for the new design open? If yes, how can I contribute?

**Comment by gasman** [comment] 2023-07-11 11:27
@YashTote You're welcome to provide feedback on #10446. I don't think we're looking for people to contribute to the designs directly - to avoid a "design by committee" situation - but we'll be happy to take your input into account.
