### ISSUE TITLE
Internationalisation, admin and live button

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail#6837] opened 2021-02-26 08:53 UTC
- Got setting configured in two languages. nl-Be and fr-Be. So my i18n url are .../nl-be/... and ../fr-be/...
- I change the language in the admin to Nederlands (Dutch)
- I go to a page in the admin and want to see the page live by clicking the LIVE button
- I get redirected to page not found .../nl-nl/...

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

If I put the admin en English I don't have this problem.
If I put the admin in French it redirect me to .../fr/... while in dutch to .../nl-nl/...

### Technical details
* Python version: 3.8
* Django version: 3.1
* Wagtail version: 2.11.4
* Browser version: Chrome latest

**Comment by gasman** [comment] 2021-02-26 09:57
Hi @onno-timmerman,
This sounds like a duplicate of #6531. What you're describing is the expected behaviour when you have `i18n_patterns` in your URL config but don't have Wagtail's i18n features enabled (`WAGTAIL_I18N_ENABLED = True`) - in this setup, you've indicated that you don't want Wagtail to handle setting an appropriate language in the URL and so you're responsible for handling this yourself.

**Closed by gasman** 2021-02-26 09:57 UTC
Labels: type:Bug
