### ISSUE TITLE
Screen Shaking and Rapid Style Top Changes When Entering Long Comment 

### ISSUE THREAD

**Issue by rohitsrma** [wagtail/wagtail#11320] opened 2023-12-07 20:27 UTC
### Issue Summary
Upon entering a long comment and scrolling down, the screen exhibits noticeable shaking, accompanied by rapid and unexpected changes in the style's top property, resulting in an undesirable user experience.

https://github.com/wagtail/wagtail/assets/111359305/6e1a88ea-dc85-4019-90f1-86e20099806c

### Steps to Reproduce

1. Navigate to any page having only 1-2 fields with a comment section.
2. Enter a comment with a substantial length.
3. Scroll down the comment.
4. Observe the screen shaking

This issue happens when there are only a few fields on a page. If there are many fields, and you try to write a really long comment that's larger than the visible area of the fields, it becomes impossible to scroll down to see the entire comment and submit button.

![image](https://github.com/wagtail/wagtail/assets/111359305/9442fe65-5eaa-4a54-bad0-9393d092989c)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Proposed Solution

In my exploration, adjusting the position to relative seems to resolve both issues. I would greatly appreciate your feedback and any alternative suggestions before proceeding with a potential pull request.

### Technical details

-   Python version: Python 3.11.4
-   Django version: 4.2.6
-   Wagtail version: 5.2.2

**Comment by lb-** [comment] 2023-12-07 20:41
Duplicate of https://github.com/wagtail/wagtail/issues/10984 - please can you move your recordings/comments there and we can make that one confirmed.

**Closed by lb-** 2023-12-07 20:41 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by rohitsrma** [comment] 2023-12-08 10:54
Oh Apologies @lb- , I was not aware of this. I have confirmed the issue and moved my recordings & additional info.

**Comment by lb-** [comment] 2023-12-08 10:55
No need to apologise - there's lots of issues and sometimes things get lost. Thanks for your amazing details and suggestion for a fix. @rohitsrma
