### ISSUE TITLE
Remove Notifications tab from Account settings admin page

### ISSUE THREAD

**Issue by murty2** [wagtail/wagtail#10315] opened 2023-04-05 17:01 UTC
register_account_settings_panel in documentation only shows how to add a tab.

How can I remove Notifications tab for a certain user or group from the Account settings admin page?

**Comment by lb-** [comment] 2023-04-05 20:45
Hi @murty2  it does not look like this is supported as is, and the Accounts view is a function view so this will not be easy to customise.

I looks like in the code that the NotificationsPanel will not show if the user does not have page editing or publishing permissions.

However, GitHub issues are not the correct way to request support - please see the preferred options here https://github.com/wagtail/wagtail#-community-support

As this is not a bug I will close it, if you would like to raise a new issue as a feature request, please do so and please use the template provided when creating issues as it helps the team triage and understand the context.

**Closed by lb-** 2023-04-05 20:45 UTC
Labels: type:Bug, status:Unconfirmed

**Comment by zerolab** [comment] 2023-04-06 08:04
Note that we have an existing issue that relates to this #9712

**Comment by lb-** [comment] 2023-04-06 08:37
Thanks Dan. I thought I had seen this but my issue search came up blank.
