### ISSUE TITLE
Editing ClusterTaggableManager field in Wagtail admin interrupted when pressing key with code 188

### ISSUE THREAD

**Issue by evgenymarkov** [wagtail/wagtail#3815] opened 2017-08-30 13:12 UTC
Steps to Reproduce:
- Open any admin editor page with ClusterTaggableManager field.
- Write some symbols to field and press key with , (comma) symbol in US layout. That key has 188 keycode.
- See how your input is interrupted

![Bug](http://i.imgur.com/iWZQLuz.png)

Technical details:
- Wagtail version: 1.12
- Browser version: Chromium 60.0.3112.113 
- OS: Arch Linux with Gnome 3.24
- **In Firefox 55.0.3 it works correctly.**

**Comment by AlexeyMis** [comment] 2017-08-30 13:14
same issue

**Comment by NickVernal** [comment] 2017-09-14 07:53
I have the same issue

**Comment by gasman** [comment] 2017-09-14 08:12
Thanks for the report! I believe this is a duplicate of #2056.

**Closed by gasman** 2017-09-14 08:12 UTC
