### ISSUE TITLE
Preview fails in 2.7 when SECURE_SSL_REDIRECT is set to True

### ISSUE THREAD

**Issue by ianastewart** [wagtail/wagtail#5737] opened 2019-12-19 11:36 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When SECURE_SSL_REDIRECT is set to True in Django settings, previewing a draft page results in a 404 error.
This appears to be a regression due to the reworking of preview mode so middleware processing is implemented. Related issue is #3048.

### Steps to Reproduce
The error can only be reproduced in a production environment that supports SSL. The error cannot be reproduced using the Django development server .
Set SECURE_SSL_REDIRECT = True in Settings.
Create a new page.
Select preview.
Wagtail attempts to show the new page at its live URL, resulting in a 404 error

The issue can be worked around by removing the SECURE_SSL_REDIRECT setting and doing the redirect to SSL in e.g. nginx instead of Django.

### Technical details

* Python version: 3.7.3
* Django version: 2.2.8
* Wagtail version: 2.7

**Comment by gasman** [comment] 2019-12-19 11:41
Hi @ianastewart - do you have the port set to 443 under Settings -> Sites? (If not, you've encountered #5303.)

**Comment by gasman** [comment] 2020-01-07 19:55
Closing due to lack of update - I assume the port setting was indeed the issue.

**Closed by gasman** 2020-01-07 19:55 UTC
Labels: status:Needs Info, type:Bug

**Comment by ianastewart** [comment] 2020-01-07 20:47
Sorry. Missed your reply over the Christmas break. I did not have 443 in site settings. I had already solved the problem by changing the settings and doing the redirect in nginx. But I do think that this should be covered somewhere in the docs.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vbudovski-alliance** [comment] 2021-05-20 01:31
@gasman This issue is still not resolved. Setting `SECURE_SSL_REDIRECT` to `True` still causes the preview to fail with a redirect to the home page instead.

**Comment by gasman** [comment] 2021-05-20 09:44
@vbudovski-alliance As per the discussion above, the fix is to set the port number to 443 in Settings -> Sites. If this does not fix it, please open a new issue with full details, including steps to reproduce.

**Comment by rodydavis** [comment] 2022-12-07 20:57
> Hi @ianastewart - do you have the port set to 443 under Settings -> Sites? (If not, you've encountered #5303.)

This worked for me!

**Comment by PetrDlouhy** [comment] 2023-03-23 10:57
I have lived without preview for a few years and now I finally got myself into investigating why it doesn't work.
It took me another half of day until I found this issue which finally helped.

Would it be possible to somehow fix this, so more people doesn't bump into this issue? E.g. raising error in case access to preview page with `SECURE_SSL_REDIRECT=True`, port 80 in settings and HTTPS?

**Comment by lb-** [comment] 2023-03-23 20:58
@PetrDlouhy sorry it took a long time for you to find this issue, may I suggest you raise a new issue requesting either a docs update or a Django check warning to help others in the future.

**Comment by PetrDlouhy** [comment] 2023-03-24 09:14
@lb- Thank you for your work on Wagtail which helps me otherwise very much.
I hope my struggle will result into improvements for others.
I have made new issue at #10259.
