### ISSUE TITLE
Table block content can not be edited after it has been saved

### ISSUE THREAD

**Issue by bobby-didcoding** [wagtail/wagtail#11301] opened 2023-12-02 11:29 UTC
### Issue Summary

When using Wagtail 5.2.0 I am unable to edit content in a Table block when content has been saved

### Steps to Reproduce

1. In a Wagtail project, create a Page with a StreamField that contains TableBlock in its block_types.
2. In the Wagtail admin, create an instance of this page and save it.
3. Add a table to your stream field, editing it as you like. This works fine.
4. Save the page.
5. Try to edit the table again.

This issue was previously raised by @nathanielwarner in Wagtail version 4.1.4

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: 3.9.2.
-   Django version: 4.1.13
-   Wagtail version: 5.2.0
-   Browser version: Chrome

**Comment by gasman** [comment] 2023-12-02 11:32
Original issue: #10335

**Comment by laymonage** [comment] 2023-12-06 13:54
I cannot replicate this yet, tried making some changes that might address it in #11312 but I don't know for sure. Bumping this to 6.0 for now so it doesn't block the 5.2.2 release, but if we can replicate this or if you can confirm that the issue is fixed with #11312, then we can backport it for a 5.2.3 release at some point in the future.

**Comment by gasman** [comment] 2024-04-24 16:47
Also unable to replicate on the given Wagtail / Django versions. I suspect this may have been happening due to outdated javascript files (e.g. this was happening on a production site, and `./manage.py collectstatic` hadn't been run after upgrading).

**Closed by gasman** 2024-04-24 16:47 UTC
Labels: type:Bug, status:Needs Info, status:Unconfirmed
